/**
 * Biology extra units — appended to the core BIOLOGY bank.
 */

import type { SeedUnit } from '../seed-bank';
import { mcq, fill, match, makeExercise } from '../seed-bank';

export const BIOLOGY_EXTRA: Record<1 | 2 | 3, SeedUnit[]> = {
  1: [
    {
      title: 'Diversity of Life',
      description: 'Five kingdom classification, viruses, biodiversity.',
      exercises: [
        makeExercise('Classification', [
          mcq('Father of taxonomy:', ['Aristotle', 'Linnaeus', 'Darwin', 'Mendel'], 1),
          mcq('Number of kingdoms (Whittaker):', ['3', '4', '5', '7'], 2),
          mcq('Bacteria belong to:', ['Animalia', 'Plantae', 'Monera', 'Fungi'], 2),
          mcq('Mushrooms belong to:', ['Plantae', 'Fungi', 'Animalia', 'Protista'], 1),
          mcq('Algae belong to:', ['Monera', 'Protista', 'Plantae', 'Fungi'], 1),
          mcq('Binomial nomenclature uses:', ['One name', 'Two names (genus + species)', 'Three', 'Latin number'], 1),
          fill('Scientific name of human is Homo ___.', ['sapiens']),
          fill('Genus name is written with first letter ___.', ['capitalised']),
          mcq('Mosses and ferns belong to:', ['Bryophytes/Pteridophytes', 'Gymnosperms', 'Angiosperms', 'Algae'], 0, 'medium'),
          mcq('Most diverse group of animals:', ['Mammals', 'Insects', 'Birds', 'Reptiles'], 1, 'medium'),
        ]),
        makeExercise('Viruses', [
          mcq('Viruses are:', ['Cellular', 'Non-cellular', 'Multicellular', 'Plant-like'], 1),
          mcq('Genetic material in HIV:', ['DNA', 'RNA', 'Both', 'None'], 1),
          mcq('Bacteriophages infect:', ['Animals', 'Plants', 'Bacteria', 'Fungi'], 2),
          mcq('Virus discovered by:', ['Pasteur', 'Iwanowski/Beijerinck', 'Watson', 'Hooke'], 1),
          mcq('Virus capsid is made of:', ['DNA', 'Protein', 'Lipid', 'Sugar'], 1),
          mcq('TMV affects:', ['Tobacco plant', 'Humans', 'Bacteria', 'Cattle'], 0),
          fill('Viruses replicate only inside ___ cells.', ['host']),
          fill('Influenza virus has ___ RNA.', ['segmented']),
          mcq('Retroviruses synthesise DNA from RNA via:', ['DNA polymerase', 'Reverse transcriptase', 'RNA pol II', 'Ribosome'], 1, 'medium'),
          mcq('Smallpox is caused by:', ['Variola virus', 'HIV', 'Influenza', 'TMV'], 0, 'medium'),
        ]),
        makeExercise('Biodiversity', [
          mcq('Hottest hotspot of biodiversity in India:', ['Western Ghats', 'Thar Desert', 'Indo-Gangetic Plain', 'Andaman shore desert'], 0),
          mcq('Endemic species are:', ['Globally common', 'Restricted to a region', 'Extinct', 'Imported'], 1),
          mcq('IUCN classifies species into:', ['Categories like CR/EN/VU', 'Ages', 'Sizes', 'Colours'], 0),
          mcq('In situ conservation:', ['Sanctuaries/National parks', 'Zoos only', 'Botanical gardens only', 'Seed banks only'], 0),
          mcq('Ex situ conservation example:', ['National Park', 'Zoo / Seed bank', 'Wildlife corridor', 'Forest reserve'], 1),
          mcq('Project Tiger started in:', ['1973', '1947', '2001', '1990'], 0),
          fill('Hotspots have high endemism and high ___.', ['threat']),
          fill('Biosphere reserve is a UNESCO ___.', ['MAB']),
          mcq('Red Data Book lists:', ['Common species', 'Threatened species', 'Extinct only', 'Domestic'], 1, 'medium'),
          mcq('Biggest threat to biodiversity:', ['Habitat loss', 'Predators', 'Sunlight', 'Cold'], 0, 'medium'),
        ]),
        makeExercise('Ecosystems Intro', [
          mcq('Producers in food chain are:', ['Carnivores', 'Plants', 'Decomposers', 'Herbivores'], 1),
          mcq('Decomposers are:', ['Plants', 'Bacteria/Fungi', 'Reptiles', 'Birds'], 1),
          mcq('Energy pyramid is:', ['Always upright', 'Inverted in oceans', 'Always inverted', 'Random'], 0),
          mcq('Trophic level 2 is:', ['Producer', 'Primary consumer', 'Secondary consumer', 'Decomposer'], 1),
          mcq('10% law refers to:', ['Energy transfer between trophic levels', 'Mass loss', 'Volume', 'Sound'], 0),
          mcq('Nitrogen fixation is done mainly by:', ['Plants directly', 'Bacteria like Rhizobium', 'Fungi only', 'Viruses'], 1),
          fill('Photosynthesis converts solar energy to ___.', ['chemical']),
          fill('Carbon cycle involves CO₂ exchange via ___ and respiration.', ['photosynthesis']),
          mcq('Eutrophication is caused by:', ['Excess nutrients in water', 'Cold currents', 'Earthquakes', 'Volcanoes'], 0, 'medium'),
          mcq('Most productive ecosystem:', ['Desert', 'Tropical rainforest', 'Tundra', 'Cultivated field'], 1, 'medium'),
        ]),
        makeExercise('Five Kingdom Examples', [
          mcq('Amoeba belongs to:', ['Monera', 'Protista', 'Fungi', 'Plantae'], 1),
          mcq('Yeast belongs to:', ['Plantae', 'Fungi', 'Monera', 'Animalia'], 1),
          mcq('Cyanobacteria belong to:', ['Monera', 'Protista', 'Plantae', 'Fungi'], 0),
          mcq('Sponges belong to:', ['Porifera', 'Cnidaria', 'Mollusca', 'Arthropoda'], 0),
          mcq('Earthworm belongs to:', ['Annelida', 'Mollusca', 'Echinodermata', 'Chordata'], 0),
          mcq('Insects belong to:', ['Arthropoda', 'Annelida', 'Mollusca', 'Cnidaria'], 0),
          fill('Snails belong to phylum ___.', ['Mollusca']),
          fill('Starfish belong to phylum ___.', ['Echinodermata']),
          mcq('Animals with notochord belong to:', ['Chordata', 'Annelida', 'Cnidaria', 'Porifera'], 0, 'medium'),
          mcq('Five-kingdom system was proposed by:', ['Linnaeus', 'Whittaker', 'Darwin', 'Mendel'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Nutrition & Health',
      description: 'Nutrients, deficiency diseases, balanced diet.',
      exercises: [
        makeExercise('Nutrients', [
          mcq('Energy macro-nutrient with most kcal/g:', ['Carbs', 'Proteins', 'Fats', 'Water'], 2),
          mcq('Carb 1 g energy ≈', ['4 kcal', '7 kcal', '9 kcal', '0'], 0),
          mcq('Protein 1 g energy ≈', ['4 kcal', '7 kcal', '9 kcal', '0'], 0),
          mcq('Fat 1 g energy ≈', ['4 kcal', '7 kcal', '9 kcal', '0'], 2),
          mcq('Vitamin C source:', ['Citrus', 'Liver only', 'Eggs only', 'Sand'], 0),
          mcq('Iron source:', ['Spinach/meat', 'Sugar only', 'Salt only', 'Water'], 0),
          fill('Building blocks of proteins are ___.', ['amino acids']),
          fill('Vitamin D is synthesised in skin via ___ light.', ['UV']),
          mcq('Essential amino acids cannot be:', ['Eaten', 'Synthesised by body', 'Digested', 'Stored'], 1, 'medium'),
          mcq('Glycogen stored mainly in:', ['Liver and muscle', 'Bones', 'Skin', 'Eyes'], 0, 'medium'),
        ]),
        makeExercise('Deficiency Diseases', [
          mcq('Vitamin A deficiency:', ['Night blindness', 'Scurvy', 'Rickets', 'Beri-beri'], 0),
          mcq('Vitamin C deficiency:', ['Scurvy', 'Pellagra', 'Beri-beri', 'Goitre'], 0),
          mcq('Vitamin D deficiency:', ['Rickets', 'Scurvy', 'Anemia', 'Goitre'], 0),
          mcq('B1 deficiency:', ['Beri-beri', 'Pellagra', 'Anemia', 'Scurvy'], 0),
          mcq('Iron deficiency:', ['Anemia', 'Goitre', 'Rickets', 'Scurvy'], 0),
          mcq('Iodine deficiency:', ['Goitre', 'Rickets', 'Scurvy', 'Pellagra'], 0),
          fill('Calcium deficiency may cause weak ___.', ['bones']),
          fill('Vitamin K is required for blood ___.', ['clotting']),
          mcq('B12 deficiency causes:', ['Anemia (pernicious)', 'Scurvy', 'Goitre', 'Rickets'], 0, 'medium'),
          mcq('Pellagra is caused by deficiency of:', ['Niacin (B3)', 'Riboflavin', 'Vitamin C', 'Iron'], 0, 'medium'),
        ]),
        makeExercise('Digestion', [
          mcq('Digestion of starch begins in:', ['Mouth', 'Stomach', 'Intestine', 'Liver'], 0),
          mcq('Stomach acid is:', ['HCl', 'H₂SO₄', 'NaOH', 'Lactic'], 0),
          mcq('Bile is produced by:', ['Liver', 'Pancreas', 'Stomach', 'Spleen'], 0),
          mcq('Bile is stored in:', ['Liver', 'Gall bladder', 'Pancreas', 'Spleen'], 1),
          mcq('Most absorption occurs in:', ['Stomach', 'Small intestine', 'Large intestine', 'Mouth'], 1),
          mcq('Protein digestion enzyme in stomach:', ['Pepsin', 'Trypsin', 'Lipase', 'Amylase'], 0),
          fill('Pancreatic juice is ___.', ['alkaline']),
          fill('Lipase digests ___.', ['fats']),
          mcq('Villi increase:', ['Surface area', 'Volume only', 'Mass', 'Heat'], 0, 'medium'),
          mcq('Mechanical churning in stomach is by:', ['Peristalsis', 'Muscle contraction', 'Bile', 'Diffusion'], 1, 'medium'),
        ]),
        makeExercise('Diseases & Immunity', [
          mcq('Malaria is caused by:', ['Plasmodium', 'Bacteria', 'Virus', 'Worm'], 0),
          mcq('TB is caused by:', ['Mycobacterium tuberculosis', 'Plasmodium', 'HIV', 'Worm'], 0),
          mcq('Vector of dengue:', ['Aedes aegypti', 'Anopheles', 'Culex', 'Tsetse'], 0),
          mcq('Vaccines induce:', ['Active immunity', 'Passive immunity only', 'No immunity', 'Heat'], 0),
          mcq('Antibodies are produced by:', ['T cells', 'B cells', 'Red cells', 'Platelets'], 1),
          mcq('AIDS attacks:', ['Helper T cells', 'B cells only', 'RBC', 'Platelets'], 0),
          fill('Antibodies are also called ___.', ['immunoglobulins']),
          fill('Polio is prevented by ___ vaccine.', ['oral']),
          mcq('Innate immunity includes:', ['Skin barrier', 'Memory cells only', 'Antibodies only', 'Vaccines'], 0, 'medium'),
          mcq('Adaptive immunity has ___ response.', ['Faster always', 'Memory & specificity', 'Random', 'No response'], 1, 'medium'),
        ]),
        makeExercise('Balanced Diet & Lifestyle', [
          mcq('Balanced diet should contain:', ['Only carbs', 'All food groups in proportion', 'Only fats', 'Only proteins'], 1),
          mcq('BMI = weight (kg) / height (m)__:', ['1', '2', '3', '0'], 1),
          mcq('Healthy adult BMI range:', ['10–15', '18.5–24.9', '30–35', '40+'], 1),
          mcq('Fiber comes mainly from:', ['Meat', 'Plant foods', 'Sugar', 'Oil'], 1),
          mcq('Excess saturated fat raises:', ['HDL only', 'LDL cholesterol', 'Vitamin C', 'Iron'], 1),
          mcq('Type 2 diabetes is linked to:', ['Insulin resistance', 'No insulin produced', 'Vitamin lack', 'Iron lack'], 0),
          fill('Hypertension means high blood ___.', ['pressure']),
          fill('Trans fats should be ___.', ['avoided']),
          mcq('Recommended daily water intake (approx):', ['200 mL', '2 L', '10 L', '20 L'], 1, 'medium'),
          mcq('Regular exercise reduces risk of:', ['Cardiovascular disease', 'Allergies only', 'Eye colour', 'Hair loss'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Reproduction Basics',
      description: 'Asexual, sexual, plant and animal reproduction overview.',
      exercises: [
        makeExercise('Modes of Reproduction', [
          mcq('Binary fission occurs in:', ['Bacteria/amoeba', 'Mammals', 'Birds', 'Plants only'], 0),
          mcq('Budding example:', ['Hydra/Yeast', 'Cat', 'Bee', 'Frog'], 0),
          mcq('Fragmentation occurs in:', ['Spirogyra', 'Mammal', 'Bird', 'Insect'], 0),
          mcq('Spore formation in:', ['Fungi like Rhizopus', 'Mammals', 'Birds', 'Reptiles'], 0),
          mcq('Vegetative propagation example:', ['Potato tuber', 'Egg', 'Seed only', 'Spore'], 0),
          mcq('Sexual reproduction involves:', ['One parent', 'Two gametes/parents', 'No parent', 'Many parents'], 1),
          fill('Gamete fusion is called ___.', ['fertilisation']),
          fill('Zygote is the first ___ cell.', ['diploid']),
          mcq('Hydra reproduces sexually as well as by:', ['Budding', 'Fission', 'Spores', 'Fragmentation only'], 0, 'medium'),
          mcq('Asexual reproduction produces:', ['Genetically identical offspring', 'Diverse offspring always', 'No offspring', 'Mutants only'], 0, 'medium'),
        ]),
        makeExercise('Plant Reproduction', [
          mcq('Male reproductive part of flower:', ['Stamen', 'Pistil', 'Sepal', 'Petal'], 0),
          mcq('Female reproductive part:', ['Stamen', 'Pistil/carpel', 'Sepal', 'Petal'], 1),
          mcq('Pollen carries:', ['Male gamete', 'Female gamete', 'Both', 'Neither'], 0),
          mcq('Ovule develops into:', ['Fruit', 'Seed', 'Petal', 'Sepal'], 1),
          mcq('Ovary develops into:', ['Seed', 'Fruit', 'Petal', 'Stamen'], 1),
          mcq('Pollination by wind is called:', ['Anemophily', 'Hydrophily', 'Zoophily', 'Entomophily'], 0),
          fill('Pollination by insects is ___.', ['entomophily']),
          fill('Self-pollination occurs within the same ___.', ['flower']),
          mcq('Double fertilisation is unique to:', ['Gymnosperms', 'Angiosperms', 'Ferns', 'Mosses'], 1, 'medium'),
          mcq('Endosperm in angiosperms is:', ['Haploid', 'Diploid', 'Triploid', 'Random'], 2, 'medium'),
        ]),
        makeExercise('Human Reproduction Overview', [
          mcq('Male gamete:', ['Egg', 'Sperm', 'Pollen', 'Zygote'], 1),
          mcq('Female gamete:', ['Egg', 'Sperm', 'Pollen', 'Zygote'], 0),
          mcq('Fertilisation occurs in:', ['Uterus', 'Oviduct (Fallopian tube)', 'Ovary', 'Cervix'], 1),
          mcq('Implantation site:', ['Ovary', 'Uterus', 'Cervix', 'Tube'], 1),
          mcq('Gestation period in humans ≈', ['6 months', '9 months', '12 months', '3 months'], 1),
          mcq('Twins from one egg:', ['Identical', 'Fraternal', 'Random', 'No twins'], 0),
          fill('XY chromosomes determine ___ sex.', ['male']),
          fill('Hormone of pregnancy maintenance is ___.', ['progesterone']),
          mcq('Menstrual cycle average ≈', ['7 days', '14 days', '28 days', '60 days'], 2, 'medium'),
          mcq('Menopause is end of:', ['Pregnancy', 'Ovulation cycles', 'Lactation', 'Growth'], 1, 'medium'),
        ]),
      ],
    },
  ],

  2: [
    {
      title: 'Cell Division & Inheritance',
      description: 'Mitosis, meiosis, Mendelian genetics, sex determination.',
      exercises: [
        makeExercise('Mitosis', [
          mcq('Mitosis produces:', ['Two genetically identical cells', 'Four gametes', 'No daughter', 'Many cells'], 0),
          mcq('Number of phases:', ['Two', 'Four', 'Six', 'One'], 1),
          mcq('Chromatids separate in:', ['Anaphase', 'Telophase', 'Prophase', 'Metaphase'], 0),
          mcq('Nuclear membrane reforms in:', ['Prophase', 'Telophase', 'Anaphase', 'Metaphase'], 1),
          mcq('Cytokinesis follows:', ['Mitosis', 'Interphase', 'S phase', 'Prophase'], 0),
          mcq('Spindle fibres are made of:', ['Actin', 'Microtubules', 'DNA', 'Lipids'], 1),
          fill('DNA replication occurs in ___ phase.', ['S']),
          fill('Sister chromatids are joined at the ___.', ['centromere']),
          mcq('Mitosis preserves chromosome number:', ['False', 'True (diploid → diploid)', 'Sometimes', 'No'], 1, 'medium'),
          mcq('Cancer often involves loss of:', ['Cell-cycle control', 'Energy', 'Calcium only', 'Sound'], 0, 'medium'),
        ]),
        makeExercise('Meiosis', [
          mcq('Meiosis produces:', ['2 diploid', '4 haploid gametes', '8 cells', 'No cells'], 1),
          mcq('Crossing over occurs in:', ['Prophase I', 'Telophase II', 'Metaphase II', 'Anaphase II'], 0),
          mcq('Independent assortment occurs in:', ['Metaphase I', 'Prophase II', 'Telophase II', 'Anaphase II'], 0),
          mcq('Reduction division refers to:', ['Mitosis', 'Meiosis I', 'Meiosis II', 'S phase'], 1),
          mcq('Homologous pair separates in:', ['Anaphase I', 'Anaphase II', 'Prophase I', 'Telophase II'], 0),
          mcq('Synapsis means:', ['Random union', 'Homolog pairing', 'Spindle formation', 'Replication'], 1),
          fill('Tetrad has ___ chromatids.', ['four']),
          fill('Chiasmata indicate sites of ___ over.', ['crossing']),
          mcq('Genetic variation arises mainly from crossing over and:', ['Random fertilisation', 'Mitosis', 'Replication', 'Translation'], 0, 'medium'),
          mcq('Non-disjunction in meiosis can lead to:', ['Aneuploidy', 'Cancer only', 'Mitosis', 'Replication'], 0, 'medium'),
        ]),
        makeExercise('Mendelian Genetics', [
          mcq('Mendel\u2019s plant of choice:', ['Pea', 'Maize', 'Rice', 'Bean'], 0),
          mcq('Ratio in monohybrid cross F2:', ['3:1', '1:1', '9:3:3:1', '2:1'], 0),
          mcq('Ratio in dihybrid cross F2:', ['3:1', '1:1', '9:3:3:1', '5:3'], 2),
          mcq('Test cross uses:', ['Heterozygous parent', 'Homozygous recessive parent', 'Random', 'Same gene'], 1),
          mcq('Phenotype is:', ['Genetic makeup', 'Observable trait', 'Karyotype', 'Allele'], 1),
          mcq('Genotype is:', ['Observable', 'Genetic makeup', 'Karyotype', 'Phenotype'], 1),
          fill('Dominant allele masks ___ allele.', ['recessive']),
          fill('Pure-breeding parents are ___.', ['homozygous']),
          mcq('Tall × short heterozygous F1 cross gives ratio:', ['1:1', '3:1', '9:3:3:1', '1:2:1'], 1, 'medium'),
          mcq('Codominance example:', ['ABO blood group', 'Tall vs short', 'Red vs white pea', 'None'], 0, 'medium'),
        ]),
        makeExercise('Sex Determination & Linkage', [
          mcq('Human sex chromosomes:', ['XX/XY', 'ZZ/ZW', 'XO/XX', 'WX/YY'], 0),
          mcq('Birds use:', ['XX/XY', 'ZZ/ZW', 'XO', 'YY'], 1),
          mcq('Sex of offspring is determined by:', ['Egg', 'Sperm chromosome', 'Random', 'Both equally'], 1),
          mcq('Linked genes are on:', ['Different chromosomes', 'Same chromosome', 'No chromosome', 'Plasmid'], 1),
          mcq('Recombination frequency relates to:', ['Distance between genes', 'Mass', 'Charge', 'No relation'], 0),
          mcq('Y chromosome is generally:', ['Longer than X', 'Shorter than X', 'Equal', 'Absent in mammals'], 1),
          fill('Haemophilia is X-linked ___.', ['recessive']),
          fill('Color blindness is X-linked ___.', ['recessive']),
          mcq('Father with X-linked recessive trait will pass it to:', ['All sons', 'All daughters as carriers', 'Only sons', 'No children'], 1, 'medium'),
          mcq('Klinefelter syndrome chromosome composition:', ['XXY', 'XYY', 'XO', 'XXX'], 0, 'medium'),
        ]),
        makeExercise('Chromosomal Disorders & Pedigree', [
          mcq('Down syndrome involves:', ['Trisomy 21', 'Monosomy X', 'XYY', 'Trisomy 18'], 0),
          mcq('Turner syndrome:', ['XO', 'XYY', 'XXY', 'XXX'], 0),
          mcq('Edwards syndrome:', ['Trisomy 18', 'Trisomy 21', 'Trisomy 13', 'XYY'], 0),
          mcq('Pedigree squares represent:', ['Females', 'Males', 'Both', 'Random'], 1),
          mcq('Pedigree circles represent:', ['Males', 'Females', 'Both', 'Random'], 1),
          mcq('Autosomal recessive trait often skips:', ['Generations', 'No generations', 'All generations', 'Sex'], 0),
          fill('Sickle-cell anemia is autosomal ___.', ['recessive']),
          fill('Cystic fibrosis is autosomal ___.', ['recessive']),
          mcq('Huntington disease is:', ['Autosomal dominant', 'X-linked recessive', 'Mitochondrial', 'Y-linked'], 0, 'medium'),
          mcq('Carrier individual is:', ['Homozygous dominant', 'Heterozygous (often unaffected)', 'Homozygous recessive', 'Sterile'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Plant Physiology',
      description: 'Photosynthesis, respiration, transpiration, plant hormones.',
      exercises: [
        makeExercise('Photosynthesis', [
          mcq('Photosynthesis occurs in:', ['Mitochondria', 'Chloroplast', 'Nucleus', 'Ribosome'], 1),
          mcq('Pigment for light absorption:', ['Chlorophyll', 'Haemoglobin', 'Melanin', 'Cytochrome'], 0),
          mcq('Light reaction occurs at:', ['Stroma', 'Thylakoid membrane', 'Cytosol', 'Mitochondria'], 1),
          mcq('Dark reaction (Calvin cycle) occurs at:', ['Stroma', 'Thylakoid', 'Cytosol', 'Mito'], 0),
          mcq('Final electron acceptor in light reaction:', ['NAD⁺', 'NADP⁺', 'O₂', 'CO₂'], 1),
          mcq('Source of O₂ released:', ['CO₂', 'H₂O', 'Glucose', 'NADPH'], 1),
          fill('CO₂ + H₂O →(light) glucose + ___.', ['O₂']),
          fill('C₃ pathway fixes CO₂ via the enzyme ___.', ['Rubisco']),
          mcq('C₄ plants have additional CO₂ fixation by:', ['Rubisco only', 'PEP carboxylase', 'NAD reductase', 'No fix'], 1, 'medium'),
          mcq('Photorespiration is wasteful in:', ['C₃ plants', 'C₄ plants', 'CAM plants', 'No plants'], 0, 'medium'),
        ]),
        makeExercise('Respiration in Plants', [
          mcq('Glycolysis occurs in:', ['Cytosol', 'Mito matrix', 'Inner mito membrane', 'Nucleus'], 0),
          mcq('Krebs cycle occurs in:', ['Cytosol', 'Matrix', 'Outer membrane', 'Lysosome'], 1),
          mcq('ETC is located in:', ['Inner mito membrane', 'Cytosol', 'ER', 'Nucleus'], 0),
          mcq('Net ATP from aerobic respiration of one glucose ≈', ['2', '8', '32-38', '50'], 2),
          mcq('Anaerobic respiration in plants gives:', ['Lactic acid', 'Ethanol + CO₂', 'O₂', 'Glucose'], 1),
          mcq('Mitochondria DNA is:', ['Linear', 'Circular', 'Random', 'Absent'], 1),
          fill('Final electron acceptor in aerobic respiration is ___.', ['O₂']),
          fill('Glycolysis converts glucose to ___.', ['pyruvate']),
          mcq('Fermentation in yeast produces:', ['Ethanol', 'Lactic acid', 'Glycogen', 'Glucose'], 0, 'medium'),
          mcq('Respiratory quotient (CO₂/O₂) for carbohydrate:', ['1.0', '0.7', '0.8', '0.5'], 0, 'medium'),
        ]),
        makeExercise('Transport in Plants', [
          mcq('Water moves up through:', ['Phloem', 'Xylem', 'Cortex', 'Pith'], 1),
          mcq('Sugars move through:', ['Xylem', 'Phloem', 'Epidermis', 'Cuticle'], 1),
          mcq('Root hairs absorb water by:', ['Active transport only', 'Osmosis', 'Endocytosis only', 'Diffusion of gas'], 1),
          mcq('Transpiration occurs through:', ['Stomata', 'Leaves only via cuticle', 'Roots only', 'Stem only'], 0),
          mcq('Cohesion-tension theory explains:', ['Phloem flow', 'Xylem ascent of sap', 'Photosynthesis', 'Respiration'], 1),
          mcq('Source-sink hypothesis explains:', ['Phloem transport', 'Xylem transport', 'Photosynthesis', 'Translation'], 0),
          fill('Stomata are guarded by ___ cells.', ['guard']),
          fill('Plasmolysis occurs in ___ solution.', ['hypertonic']),
          mcq('Wilting in plants is caused by:', ['Excess water', 'Loss of turgor', 'High respiration only', 'Sun stop'], 1, 'medium'),
          mcq('Active transport across membrane uses:', ['Diffusion', 'ATP energy', 'Heat', 'Sound'], 1, 'medium'),
        ]),
        makeExercise('Plant Hormones', [
          mcq('Auxin promotes:', ['Cell elongation', 'Senescence', 'Dormancy', 'Cell wall destruction'], 0),
          mcq('Gibberellin promotes:', ['Stem elongation', 'Sleep', 'Hypoglycemia', 'Closing stomata'], 0),
          mcq('Cytokinin promotes:', ['Cell division', 'Senescence', 'Aging', 'Wilting'], 0),
          mcq('ABA induces:', ['Growth', 'Dormancy/closing stomata', 'Senescence inhibition', 'Photosynthesis'], 1),
          mcq('Ethylene promotes:', ['Fruit ripening', 'Cell division', 'Photosynthesis', 'Stem elongation'], 0),
          mcq('Phototropism is a response to:', ['Gravity', 'Light', 'Touch', 'Water'], 1),
          fill('Geotropism (gravitropism) is response to ___.', ['gravity']),
          fill('Thigmotropism is response to ___.', ['touch']),
          mcq('Auxin moves polarly mainly:', ['Basipetally', 'Acropetally only', 'Random', 'No movement'], 0, 'medium'),
          mcq('Gibberellin promotes seed:', ['Germination', 'Decay', 'Sleep', 'Death'], 0, 'medium'),
        ]),
        makeExercise('Tropisms & Photoperiodism', [
          mcq('Phototropism is response to:', ['Gravity', 'Light', 'Touch', 'Water'], 1),
          mcq('Hydrotropism in roots is towards:', ['Light', 'Water', 'Air', 'Heat'], 1),
          mcq('Thigmotropism in tendrils is towards:', ['Touch', 'Sound', 'Light', 'Heat'], 0),
          mcq('Long-day plants flower when day length:', ['Exceeds critical length', 'Is below critical', 'Zero', 'Always'], 0),
          mcq('Short-day plants flower when day length:', ['Below critical', 'Always', 'Zero', 'Above critical'], 0),
          mcq('Vernalization is induction of flowering by:', ['Cold', 'Heat', 'Light only', 'Dark only'], 0),
          fill('Photoperiod is duration of ___ in 24 h.', ['light']),
          fill('Phytochrome detects ___ light.', ['red']),
          mcq('Day-neutral plants flower:', ['Regardless of day length', 'Only in long days', 'Only in short days', 'Never'], 0, 'medium'),
          mcq('Phytochrome Pr converts to Pfr under:', ['Red light', 'Far-red light', 'Dark', 'Heat'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Human Physiology',
      description: 'Circulation, respiration, excretion, nervous system.',
      exercises: [
        makeExercise('Circulation', [
          mcq('Human heart chambers:', ['2', '3', '4', '5'], 2),
          mcq('Pulmonary artery carries:', ['Oxygenated', 'Deoxygenated blood', 'Lymph', 'Plasma only'], 1),
          mcq('Aorta carries:', ['Deoxygenated', 'Oxygenated blood', 'Lymph', 'CO₂ only'], 1),
          mcq('SA node generates:', ['Hormone', 'Electrical impulse for heartbeat', 'Bile', 'Mucus'], 1),
          mcq('Normal resting heart rate (adult):', ['~30', '~60-100', '~150', '~200'], 1),
          mcq('Diastole is:', ['Heart contraction', 'Heart relaxation', 'Stroke', 'Beat'], 1),
          fill('Liquid component of blood is ___.', ['plasma']),
          fill('Universal donor blood group is ___.', ['O-']),
          mcq('Hemoglobin carries primarily:', ['CO₂ only', 'O₂ (and some CO₂)', 'Glucose', 'Salt'], 1, 'medium'),
          mcq('Lymph drains into:', ['Heart directly', 'Veins via thoracic duct', 'Stomach', 'Skin'], 1, 'medium'),
        ]),
        makeExercise('Respiration', [
          mcq('Air enters lungs through:', ['Pharynx → trachea → bronchi', 'Esophagus', 'Heart', 'Liver'], 0),
          mcq('Exchange of gases occurs in:', ['Alveoli', 'Bronchi', 'Trachea', 'Pleura'], 0),
          mcq('Diaphragm contracts during:', ['Inhalation', 'Exhalation', 'Both', 'Neither'], 0),
          mcq('Hemoglobin loads O₂ in:', ['Tissues', 'Lungs', 'Veins', 'Brain'], 1),
          mcq('CO₂ transported as bicarbonate in:', ['Plasma mostly', 'RBCs only', 'Hb only', 'Lymph'], 0),
          mcq('Tidal volume ≈', ['100 mL', '500 mL', '1500 mL', '5000 mL'], 1),
          fill('Vital capacity = TV + IRV + ___.', ['ERV']),
          fill('Asthma involves narrowing of ___.', ['bronchioles']),
          mcq('Bohr effect refers to:', ['CO₂/pH lowering Hb O₂ affinity', 'High O₂ affinity', 'No effect', 'Lung volume'], 0, 'medium'),
          mcq('Smoking damages cilia and increases:', ['Risk of bronchitis/cancer', 'Lung capacity', 'Hb', 'BP only'], 0, 'medium'),
        ]),
        makeExercise('Excretion', [
          mcq('Functional unit of kidney:', ['Neuron', 'Nephron', 'Hepatocyte', 'Alveolus'], 1),
          mcq('Glomerular filtration rate ≈', ['1 mL/min', '125 mL/min', '500 mL/min', '5000 mL/min'], 1),
          mcq('Urea is formed in:', ['Liver', 'Kidney', 'Spleen', 'Lung'], 0),
          mcq('Urine is stored in:', ['Kidney', 'Bladder', 'Ureter', 'Urethra'], 1),
          mcq('Loop of Henle creates:', ['Hormones', 'Counter-current concentration', 'Bile', 'Mucus'], 1),
          mcq('ADH increases water:', ['Loss', 'Reabsorption', 'Filtration', 'Mineral'], 1),
          fill('Aldosterone reabsorbs ___.', ['Na+']),
          fill('Healthy urine is mostly ___ in colour.', ['yellow']),
          mcq('Dialysis is used in:', ['Mild dehydration', 'Renal failure', 'Mild allergy', 'Skin care'], 1, 'medium'),
          mcq('Diabetes insipidus involves:', ['Insulin lack', 'ADH lack', 'Glucose excess', 'Salt excess'], 1, 'medium'),
        ]),
        makeExercise('Nervous System', [
          mcq('Functional unit of nervous system:', ['Cell', 'Neuron', 'Synapse', 'Axon'], 1),
          mcq('Neurotransmitter at neuromuscular junction:', ['Acetylcholine', 'Adrenaline', 'GABA', 'Serotonin'], 0),
          mcq('Resting membrane potential ≈', ['-70 mV', '+30 mV', '0 mV', '+70 mV'], 0),
          mcq('Action potential is:', ['Continuous DC', 'All-or-none spike', 'Random noise', 'No event'], 1),
          mcq('Brain part for balance:', ['Cerebellum', 'Cerebrum', 'Medulla', 'Thalamus'], 0),
          mcq('Reflex arc minimal includes:', ['Sensor → motor only', 'Sensor → spinal cord → motor', 'Brain → motor', 'Sensor → brain → effector'], 1),
          fill('Myelin sheath increases conduction ___.', ['speed']),
          fill('Synapse uses chemical messengers called ___.', ['neurotransmitters']),
          mcq('Multiple sclerosis affects:', ['Myelin', 'Bone', 'Skin', 'Eyes only'], 0, 'medium'),
          mcq('Sympathetic vs parasympathetic in fight-or-flight:', ['Sympathetic', 'Parasympathetic', 'Both equal', 'Neither'], 0, 'medium'),
        ]),
      ],
    },
  ],

  3: [
    {
      title: 'Molecular Biology (Advanced)',
      description: 'DNA replication, transcription, translation, regulation.',
      exercises: [
        makeExercise('DNA Replication', [
          mcq('DNA replication is:', ['Conservative', 'Semi-conservative', 'Dispersive', 'No copy'], 1),
          mcq('Enzyme that synthesises new DNA:', ['DNA polymerase', 'Ligase only', 'Helicase only', 'Primase only'], 0),
          mcq('Helicase function:', ['Joins fragments', 'Unwinds DNA', 'Adds primer only', 'Cuts DNA'], 1),
          mcq('Primase synthesises:', ['DNA primer', 'RNA primer', 'Protein', 'Nothing'], 1),
          mcq('Okazaki fragments are on:', ['Leading strand', 'Lagging strand', 'Both', 'None'], 1),
          mcq('Direction of synthesis:', ['5\u2032→3\u2032', '3\u2032→5\u2032', 'Random', 'Both directions'], 0),
          fill('Telomeres are extended by ___.', ['telomerase']),
          fill('Replication origin is called ___.', ['ori']),
          mcq('Meselson-Stahl experiment proved:', ['Conservative', 'Semi-conservative', 'Dispersive', 'No replication'], 1, 'medium'),
          mcq('Proofreading is by 3\u2032\u21925\u2032 ___ activity of DNA pol.', ['polymerase', 'exonuclease', 'helicase', 'ligase'], 1, 'medium'),
        ]),
        makeExercise('Transcription', [
          mcq('Transcription produces:', ['DNA', 'RNA', 'Protein', 'Lipid'], 1),
          mcq('Enzyme:', ['DNA pol', 'RNA pol', 'Ligase', 'Reverse transcriptase'], 1),
          mcq('Promoter is bound by:', ['Ribosome', 'RNA pol with TFs', 'mRNA', 'tRNA'], 1),
          mcq('In eukaryotes, mRNA is processed by:', ['5′ cap, splicing, polyA tail', 'Translation only', 'Replication', 'No processing'], 0),
          mcq('Introns are:', ['Coding regions', 'Non-coding, removed', 'Promoters', 'tRNA'], 1),
          mcq('Exons are:', ['Removed', 'Joined to form mature mRNA', 'Random', 'Promoters'], 1),
          fill('TATA box is part of the ___.', ['promoter']),
          fill('Polyadenylation adds ___ tail.', ['polyA']),
          mcq('Alternative splicing increases:', ['Protein diversity', 'DNA stability', 'Lipid count', 'No effect'], 0, 'medium'),
          mcq('In bacteria, transcription and translation are:', ['Separated by membrane', 'Coupled', 'Slower', 'Inverse'], 1, 'medium'),
        ]),
        makeExercise('Translation', [
          mcq('Translation occurs at:', ['Nucleus', 'Ribosome', 'Lysosome', 'Golgi'], 1),
          mcq('Genetic code is:', ['Triplet', 'Doublet', 'Quadruplet', 'Singlet'], 0),
          mcq('Start codon:', ['UAA', 'AUG', 'UGA', 'UAG'], 1),
          mcq('Stop codons:', ['UAA, UAG, UGA', 'AUG only', 'UAA only', 'CCG only'], 0),
          mcq('tRNA carries:', ['mRNA', 'Amino acid', 'rRNA', 'Lipid'], 1),
          mcq('Wobble hypothesis explains:', ['Codon-anticodon flexibility', 'Replication', 'Transcription', 'Translation start'], 0),
          fill('Genetic code is nearly ___ across life.', ['universal']),
          fill('Sites in ribosome are A, P, ___.', ['E']),
          mcq('Frameshift mutation causes:', ['Single substitution', 'Reading frame shift', 'No effect', 'Replication only'], 1, 'medium'),
          mcq('Antibiotic streptomycin targets:', ['Ribosome', 'DNA pol', 'RNA pol', 'Cell wall'], 0, 'medium'),
        ]),
        makeExercise('Gene Regulation', [
          mcq('Lac operon is:', ['Inducible', 'Constitutive', 'Repressible always', 'Eukaryotic only'], 0),
          mcq('Trp operon is:', ['Inducible', 'Repressible', 'Constitutive', 'Random'], 1),
          mcq('Operon concept proposed by:', ['Watson', 'Jacob & Monod', 'Crick', 'Mendel'], 1),
          mcq('Eukaryotic enhancers can act:', ['Only nearby', 'At long distances', 'Never', 'On RNA'], 1),
          mcq('Methylation of DNA usually:', ['Activates expression', 'Silences expression', 'No effect', 'Replicates'], 1),
          mcq('Histone acetylation tends to:', ['Activate', 'Repress', 'No effect', 'Methylate'], 0),
          fill('CRISPR-Cas9 uses guide ___.', ['RNA']),
          fill('Repressor binds to ___ region.', ['operator']),
          mcq('siRNA / miRNA mainly regulates:', ['Translation/mRNA stability', 'DNA replication only', 'Lipids', 'Cell wall'], 0, 'medium'),
          mcq('Epigenetic changes affect expression without altering:', ['DNA sequence', 'Protein', 'RNA', 'Cell shape'], 0, 'medium'),
        ]),
        makeExercise('Mutations & Repair', [
          mcq('Point mutation changes:', ['One base pair', 'Whole chromosome', 'Many genes', 'No DNA'], 0),
          mcq('Silent mutation has:', ['Same amino acid encoded', 'New amino acid', 'Stop codon', 'No protein'], 0),
          mcq('Missense mutation results in:', ['Stop codon', 'Different amino acid', 'No change', 'Frame shift'], 1),
          mcq('Nonsense mutation introduces:', ['Stop codon', 'Same aa', 'Splice site', 'Promoter'], 0),
          mcq('Frameshift comes from:', ['Insertion or deletion not multiple of 3', 'Substitution', 'Translocation only', 'No change'], 0),
          mcq('UV light typically causes:', ['Pyrimidine dimers', 'Triple helices', 'No damage', 'Aneuploidy'], 0),
          fill('Mismatch repair fixes errors after ___.', ['replication']),
          fill('Base excision repair removes damaged ___.', ['bases']),
          mcq('Xeroderma pigmentosum is defective in:', ['Nucleotide excision repair', 'Mitosis only', 'Translation', 'Replication helicase only'], 0, 'medium'),
          mcq('Double-strand breaks are repaired by:', ['NHEJ or HR', 'Mismatch only', 'BER only', 'No repair'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Evolution & Ecology',
      description: 'Natural selection, speciation, populations, community.',
      exercises: [
        makeExercise('Evolutionary Theory', [
          mcq('Origin of Species author:', ['Darwin', 'Mendel', 'Lamarck', 'Wallace'], 0),
          mcq('Natural selection acts on:', ['Phenotypes leading to fitness differences', 'Random DNA', 'Cells only', 'Eggs only'], 0),
          mcq('Lamarck proposed:', ['Inheritance of acquired characters', 'Natural selection', 'Punctuated equilibrium', 'Genetic drift'], 0),
          mcq('Genetic drift is significant in:', ['Small populations', 'Large populations only', 'No populations', 'Sterile only'], 0),
          mcq('Gene flow is:', ['Migration', 'Mutation', 'Selection', 'Drift'], 0),
          mcq('Hardy-Weinberg requires:', ['No selection, no migration, large pop', 'Strong selection', 'Drift', 'Mutation rate high'], 0),
          fill('Mutation provides raw material of ___.', ['evolution']),
          fill('Speciation is formation of new ___.', ['species']),
          mcq('Allopatric speciation requires:', ['Geographic isolation', 'No isolation', 'Selfing only', 'No mutation'], 0, 'medium'),
          mcq('Sympatric speciation occurs:', ['Without geographic isolation', 'Always with isolation', 'In sterile org', 'Never'], 0, 'medium'),
        ]),
        makeExercise('Population Ecology', [
          mcq('Carrying capacity K is:', ['Max sustainable population', 'Min population', 'Mean population', 'No meaning'], 0),
          mcq('Logistic growth gives:', ['J-curve', 'S-curve', 'Linear', 'Random'], 1),
          mcq('Exponential growth gives:', ['S-curve', 'J-curve', 'Linear', 'Decay'], 1),
          mcq('Birth rate − death rate =', ['Carrying capacity', 'Per capita rate of increase r', 'Density', 'Constant'], 1),
          mcq('Population density is:', ['Number / area', 'Biomass / volume only', 'Total biomass', 'Maximum'], 0),
          mcq('Age pyramids show:', ['Population structure', 'Random', 'Habitat', 'Energy flow'], 0),
          fill('r-strategy involves many ___ offspring.', ['short-lived']),
          fill('K-strategy: few, ___ offspring.', ['long-lived']),
          mcq('Density-dependent factor example:', ['Disease', 'Earthquake', 'Lightning', 'Cold spell'], 0, 'medium'),
          mcq('Logistic dN/dt = rN((K−N)/___).', ['K', 'N', 'r', 't'], 0, 'medium'),
        ]),
        makeExercise('Community & Biosphere', [
          mcq('Niche is:', ['Same as habitat', 'Functional role + habitat', 'Latitude', 'Altitude'], 1),
          mcq('Competitive exclusion principle:', ['Two species in same niche cannot coexist long-term', 'Co-existence forever', 'No effect', 'Random'], 0),
          mcq('Keystone species:', ['Disproportionately impactful species', 'Common species', 'Random species', 'Decomposer'], 0),
          mcq('Succession ends in:', ['Climax community', 'Pioneer stage', 'Random', 'No end'], 0),
          mcq('Primary succession starts on:', ['Bare rock/sand', 'Existing soil', 'Forest', 'Pond ecosystem'], 0),
          mcq('Biomes are large-scale:', ['Communities', 'Climatic regions with characteristic biota', 'Cells', 'Niches'], 1),
          fill('Mutualism benefits ___ species.', ['both']),
          fill('Parasitism benefits one and harms the ___.', ['host']),
          mcq('Coral reef and zooxanthellae interaction:', ['Mutualism', 'Parasitism', 'Predation', 'Competition'], 0, 'medium'),
          mcq('Rainforest biome characterised by:', ['High rainfall, high diversity', 'Low rainfall', 'Cold', 'Low diversity'], 0, 'medium'),
        ]),
        makeExercise('Phylogenetics & Speciation', [
          mcq('Phylogenetic tree shows:', ['Evolutionary relationships', 'Random groups', 'Sizes', 'Colours'], 0),
          mcq('Common ancestor is the:', ['Most recent shared lineage', 'First cell', 'First organism only', 'Random'], 0),
          mcq('Homologous structures share:', ['Common ancestry', 'Common function only', 'Random origin', 'No origin'], 0),
          mcq('Analogous structures share:', ['Common ancestry', 'Common function from convergence', 'No similarity', 'Random'], 1),
          mcq('Vestigial organs example:', ['Whale pelvis', 'Heart', 'Lungs', 'Brain'], 0),
          mcq('Adaptive radiation example:', ['Galapagos finches', 'Identical species', 'Random', 'No example'], 0),
          fill('Cladogram does not show ___ length usually.', ['branch']),
          fill('Polyploidy can drive ___ speciation in plants.', ['sympatric']),
          mcq('Reproductive isolation is the hallmark of:', ['Speciation', 'Mutation only', 'Drift only', 'No process'], 0, 'medium'),
          mcq('Punctuated equilibrium proposes:', ['Rapid speciation between long stasis', 'Gradual change always', 'No change', 'Linear progress'], 0, 'medium'),
        ]),
        makeExercise('Conservation & Climate', [
          mcq('Greenhouse effect is caused mainly by:', ['CO₂, CH₄, H₂O vapour', 'O₂ only', 'N₂ only', 'Argon'], 0),
          mcq('Ozone layer protects from:', ['IR', 'UV', 'Microwave', 'Visible light'], 1),
          mcq('Acid rain is caused by:', ['SO₂ and NOₓ emissions', 'CO₂ only', 'CH₄ only', 'O₂ only'], 0),
          mcq('Eutrophication is caused by:', ['Excess nutrients', 'Drought', 'Cold', 'Salinity only'], 0),
          mcq('CFCs damage:', ['Ozone layer', 'Ground crops', 'Buildings only', 'Soil only'], 0),
          mcq('IUCN Red List categorises:', ['Conservation status of species', 'Habitats only', 'Climates', 'Cells'], 0),
          fill('Global warming raises sea ___.', ['levels']),
          fill('Sustainable development meets present needs without harming ___ generations.', ['future']),
          mcq('Carbon footprint refers to:', ['Total CO₂-eq emissions of activity', 'Foot size only', 'Land area', 'Calorie intake'], 0, 'medium'),
          mcq('Renewable energy example:', ['Coal', 'Solar', 'Crude oil', 'Natural gas'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Biotechnology & Health',
      description: 'rDNA, PCR, vaccines, cancer biology.',
      exercises: [
        makeExercise('Recombinant DNA', [
          mcq('Restriction enzymes cut DNA at:', ['Random sites', 'Specific palindromic sequences', 'Telomeres', 'Centromeres'], 1),
          mcq('Vector example:', ['Plasmid', 'Mitochondrion only', 'Lysosome', 'Cytoskeleton'], 0),
          mcq('Ligase joins:', ['DNA strands', 'Lipids', 'Proteins', 'RNA only'], 0),
          mcq('Cloning vector must have:', ['Origin of replication', 'No selectable marker', 'No restriction site', 'No promoter'], 0),
          mcq('Selection often uses:', ['Antibiotic resistance', 'Heat', 'Pressure', 'Light'], 0),
          mcq('Insulin can be produced in:', ['Goat hair', 'E. coli with human insulin gene', 'Stones', 'Air'], 1),
          fill('Plasmid is a small circular ___.', ['DNA']),
          fill('Sticky ends are produced by ___ enzymes.', ['restriction']),
          mcq('Blue-white screening uses:', ['lacZ disruption', 'Antibiotic only', 'Heat shock only', 'No marker'], 0, 'medium'),
          mcq('GM crops may have:', ['Pest resistance via Bt gene', 'No effect', 'Random genes', 'No marker'], 0, 'medium'),
        ]),
        makeExercise('PCR & Sequencing', [
          mcq('PCR amplifies:', ['DNA exponentially', 'Protein', 'RNA only', 'Lipids'], 0),
          mcq('PCR steps:', ['Denature, anneal, extend', 'Translate, replicate, splice', 'Random', 'Cool, heat, mix'], 0),
          mcq('Taq polymerase is heat-:', ['Sensitive', 'Stable', 'Unstable', 'Inactive'], 1),
          mcq('Sanger sequencing uses:', ['ddNTPs to terminate', 'Restriction enzymes', 'Heat shock', 'Light only'], 0),
          mcq('Next-generation sequencing increases:', ['Throughput', 'Cost', 'Time', 'Errors only'], 0),
          mcq('Reverse transcription needs:', ['DNA template', 'RNA template', 'Protein template', 'No template'], 1),
          fill('Primers anneal to template at ___ temperature.', ['lower']),
          fill('Cycles in PCR roughly double DNA each ___.', ['cycle']),
          mcq('qPCR measures DNA quantity in:', ['Real-time', 'After end-point only', 'Random', 'Never'], 0, 'medium'),
          mcq('CRISPR can be programmed by changing the:', ['Cas9 protein', 'Guide RNA', 'Restriction enzyme', 'Vector backbone'], 1, 'medium'),
        ]),
        makeExercise('Vaccines & Cancer', [
          mcq('Vaccines induce:', ['Active immunity', 'Passive immunity only', 'No immunity', 'Allergy only'], 0),
          mcq('mRNA vaccines deliver:', ['Whole virus', 'mRNA encoding antigen', 'DNA only', 'Antibodies'], 1),
          mcq('Cancer is uncontrolled:', ['Cell death', 'Cell division', 'Apoptosis', 'Aging'], 1),
          mcq('Oncogenes are:', ['Tumor-suppressors', 'Mutated proto-oncogenes', 'Random', 'Inactive'], 1),
          mcq('p53 is a:', ['Tumor suppressor', 'Oncogene', 'Cytokine', 'Hormone'], 0),
          mcq('Metastasis is:', ['Spread of cancer to other tissues', 'Local growth only', 'Apoptosis', 'Healing'], 0),
          fill('BRCA1 mutations increase risk of ___ cancer.', ['breast']),
          fill('Carcinogens are agents that cause ___.', ['cancer']),
          mcq('Chemotherapy primarily targets:', ['Rapidly dividing cells', 'Static cells', 'Bone density', 'Hair only'], 0, 'medium'),
          mcq('Immunotherapy works by:', ['Boosting immune attack on tumour', 'Cooling tumour', 'Diet', 'Hormone replacement'], 0, 'medium'),
        ]),
      ],
    },
  ],
};
