/**
 * Chemistry extra units — appended to the core CHEMISTRY bank.
 */

import type { SeedUnit } from '../seed-bank';
import { mcq, fill, match, makeExercise } from '../seed-bank';

export const CHEMISTRY_EXTRA: Record<1 | 2 | 3, SeedUnit[]> = {
  1: [
    {
      title: 'States of Matter',
      description: 'Solids, liquids, gases, gas laws, kinetic theory.',
      exercises: [
        makeExercise('Phases & Properties', [
          mcq('Definite shape and volume:', ['Solid', 'Liquid', 'Gas', 'Plasma'], 0),
          mcq('Definite volume, no fixed shape:', ['Solid', 'Liquid', 'Gas', 'Plasma'], 1),
          mcq('Most compressible:', ['Solid', 'Liquid', 'Gas', 'Crystal'], 2),
          mcq('Particles in gas move:', ['Slowly fixed', 'Vibrate only', 'Rapidly random', 'Don\u2019t move'], 2),
          mcq('Sublimation goes from:', ['Liquid → gas', 'Solid → gas', 'Gas → solid', 'Solid → liquid'], 1),
          mcq('Evaporation occurs at:', ['Boiling only', 'All temperatures', '0 K', 'Critical point'], 1),
          fill('Melting is solid → ___.', ['liquid']),
          fill('Condensation is gas → ___.', ['liquid']),
          mcq('Diffusion fastest in:', ['Solids', 'Liquids', 'Gases', 'Plasma'], 2, 'medium'),
          mcq('Plasma is ionised gas at:', ['Low temperatures', 'Very high temperatures', '0 K', '273 K'], 1, 'medium'),
        ]),
        makeExercise('Gas Laws', [
          mcq('Boyle\u2019s law: PV =', ['constant (T fixed)', 'T', 'nR', 'V/T'], 0),
          mcq('Charles\u2019 law: V/T =', ['const (P fixed)', 'nP', 'PR', 'P/T'], 0),
          mcq('Avogadro: V ∝', ['n', 'P', '1/T', '1/n'], 0),
          mcq('Ideal gas equation:', ['PV=nRT', 'PV=nT', 'P/V=nRT', 'V=PnRT'], 0),
          mcq('R in J/(mol·K):', ['0.08', '8.314', '22.4', '273'], 1),
          mcq('Molar volume at STP (0 °C, 1 atm) ≈', ['11.2 L', '22.4 L', '24.5 L', '44.8 L'], 1),
          fill('STP: 273.15 K and 1 ___.', ['atm']),
          fill('Real gases deviate at high P and low ___.', ['T']),
          mcq('1 mol gas at 273 K, 1 atm has V:', ['11.2 L', '22.4 L', '44.8 L', '101 L'], 1, 'medium'),
          mcq('At constant T, doubling P:', ['Doubles V', 'Halves V', 'Same V', 'Zero V'], 1, 'medium'),
        ]),
        makeExercise('Kinetic Theory', [
          mcq('PV = ⅓ N m ___².', ['v_rms', 'v_avg', 'v_max', 'v'], 0),
          mcq('Average KE per molecule = ___ kT.', ['1/2', '3/2', '5/2', '7/2'], 1),
          mcq('Real gas correction (van der Waals) involves:', ['a, b only', 'Volume + intermolecular forces', 'Charge', 'Mass only'], 1),
          mcq('Diffusion rate ∝ 1/√(M):', ['Boyle', 'Graham', 'Charles', 'Avogadro'], 1),
          mcq('Compressibility factor Z = PV/nRT:', ['= 1 ideal', '= 0', '< 0', '> 100'], 0),
          mcq('Ideal gas assumes molecules have:', ['Volume', 'No volume', 'Strong attraction', 'Charge'], 1),
          fill('Maxwell speed distribution depends on T and ___.', ['mass']),
          fill('Mean free path increases with decreasing ___.', ['pressure']),
          mcq('Helium effuses faster than argon because:', ['Lighter', 'Heavier', 'Bigger', 'Charged'], 0, 'medium'),
          mcq('Z < 1 indicates predominance of:', ['Repulsion', 'Attraction', 'No effects', 'Solid'], 1, 'medium'),
        ]),
        makeExercise('Liquids & Solids', [
          mcq('Surface tension acts on:', ['Bulk', 'Surface molecules', 'Interior only', 'No molecules'], 1),
          mcq('Capillary rise depends on:', ['Tube diameter', 'Surface tension', 'Both', 'Mass only'], 2),
          mcq('Viscosity of water vs honey:', ['Higher', 'Lower', 'Equal', 'Zero'], 1),
          mcq('Vapor pressure increases with:', ['Cooling', 'Heating', 'Compression', 'Solidifying'], 1),
          mcq('Crystalline solids have:', ['Random structure', 'Ordered structure', 'No melting point', 'Liquid behaviour'], 1),
          mcq('Amorphous example:', ['Quartz', 'Glass', 'Diamond', 'Salt'], 1),
          fill('Boiling occurs when vapor pressure equals ___ pressure.', ['external']),
          fill('Hydrogen bonds give water its high ___ point.', ['boiling']),
          mcq('Boiling point of water at higher altitude is:', ['Higher', 'Lower', 'Same', 'Zero'], 1, 'medium'),
          mcq('Allotropes of carbon include:', ['Iron, gold', 'Diamond, graphite, fullerene', 'O₂, O₃ only', 'Steam'], 1, 'medium'),
        ]),
        makeExercise('Phase Diagrams', [
          mcq('Triple point shows coexistence of:', ['Two phases', 'Three phases', 'One phase', 'No phase'], 1),
          mcq('Critical point separates:', ['Solid/liquid', 'Gas/supercritical', 'Liquid/gas distinction lost', 'Solid/gas'], 2),
          mcq('Phase diagram axes typically:', ['T vs V', 'P vs T', 'P vs n', 'V vs n'], 1),
          mcq('Above critical T a substance is:', ['Solid', 'Liquid', 'Supercritical fluid', 'Gas only'], 2),
          mcq('Sublimation line lies between:', ['Solid-Liquid', 'Solid-Gas', 'Liquid-Gas', 'None'], 1),
          mcq('Water’s solid-liquid line slope is:', ['Positive', 'Negative', 'Vertical', 'Zero'], 1),
          fill('Triple point of water at ~273.16 K and ~611 ___.', ['Pa']),
          fill('Supercritical CO₂ is used as a green ___.', ['solvent']),
          mcq('Increasing P on water near 0 °C tends to:', ['Freeze', 'Melt', 'No effect', 'Sublime'], 1, 'medium'),
          mcq('Phase rule F = C − P + ___.', ['1', '2', '3', '0'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Acids, Bases & Salts',
      description: 'Indicators, pH, neutralisation, common salts.',
      exercises: [
        makeExercise('Acids & Bases Basics', [
          mcq('Acids turn litmus:', ['Blue', 'Red', 'Green', 'Yellow'], 1),
          mcq('Bases turn litmus:', ['Red', 'Blue', 'Green', 'Yellow'], 1),
          mcq('pH of pure water at 25 °C:', ['0', '1', '7', '14'], 2),
          mcq('Acid + Base →', ['Salt only', 'Water only', 'Salt + Water', 'Gas + heat'], 2),
          mcq('Common strong acid:', ['HCl', 'CH₃COOH', 'NH₃', 'NaOH'], 0),
          mcq('Common strong base:', ['NaOH', 'NH₃', 'HCl', 'CO₂'], 0),
          fill('pH < 7 means ___.', ['acidic']),
          fill('pH > 7 means ___.', ['basic']),
          mcq('Antacid neutralises:', ['Body base', 'Stomach acid', 'Sweat', 'Air'], 1, 'medium'),
          mcq('Soap solution is:', ['Neutral', 'Basic', 'Acidic', 'Salt only'], 1, 'medium'),
        ]),
        makeExercise('Indicators', [
          mcq('Phenolphthalein in base:', ['Colourless', 'Pink', 'Blue', 'Yellow'], 1),
          mcq('Phenolphthalein in acid:', ['Pink', 'Colourless', 'Blue', 'Red'], 1),
          mcq('Methyl orange in acid:', ['Yellow', 'Red/orange', 'Blue', 'Green'], 1),
          mcq('Universal indicator gives:', ['pH range colour', 'Mass', 'Volume', 'Density'], 0),
          mcq('Turmeric in base:', ['Yellow', 'Red', 'Blue', 'Green'], 1),
          mcq('Olfactory indicator example:', ['Vanilla extract', 'Litmus', 'Phenolphthalein', 'Methyl orange'], 0),
          fill('Indicators give ___ change with pH.', ['colour']),
          fill('Universal indicator approximates ___.', ['pH']),
          mcq('Phenolphthalein\u2019s transition near pH:', ['1', '4', '8.5', '12'], 2, 'medium'),
          mcq('Methyl orange\u2019s transition near pH:', ['1', '3.5', '7', '10'], 1, 'medium'),
        ]),
        makeExercise('Salts & Their Uses', [
          mcq('NaCl is:', ['Soap', 'Common salt', 'Soda', 'Lime'], 1),
          mcq('Baking soda formula:', ['Na₂CO₃', 'NaHCO₃', 'NaOH', 'NaCl'], 1),
          mcq('Washing soda:', ['NaCl', 'Na₂CO₃·10H₂O', 'NaOH', 'CaSO₄'], 1),
          mcq('Plaster of Paris formula:', ['CaSO₄·½H₂O', 'CaSO₄·2H₂O', 'CaCO₃', 'CaCl₂'], 0),
          mcq('Bleaching powder:', ['CaOCl₂', 'CaCO₃', 'CaCl₂', 'NaOCl'], 0),
          mcq('CaSO₄·2H₂O is:', ['Plaster of Paris', 'Gypsum', 'Marble', 'Limestone'], 1),
          fill('Salt of strong acid + weak base is ___.', ['acidic']),
          fill('Salt of weak acid + strong base is ___.', ['basic']),
          mcq('Heating gypsum gives:', ['Lime', 'Plaster of Paris', 'Salt', 'Marble'], 1, 'medium'),
          mcq('Bleaching powder oxidises by releasing:', ['Cl₂', 'O₂', 'H₂', 'N₂'], 0, 'medium'),
        ]),
        makeExercise('pH in Daily Life', [
          mcq('Tooth decay starts below pH:', ['7', '5.5', '3', '2'], 1),
          mcq('Bee sting is:', ['Acidic', 'Basic', 'Neutral', 'Salt'], 0),
          mcq('Wasp sting is:', ['Acidic', 'Basic', 'Neutral', 'Salt'], 1),
          mcq('Soil for many plants prefers pH near:', ['1', '4', '6.5–7.5', '12'], 2),
          mcq('Acid rain has pH usually:', ['Above 7', 'Below 5.6', 'Around 7', 'Above 8'], 1),
          mcq('Baking powder works because of release of:', ['CO₂', 'O₂', 'H₂', 'N₂'], 0),
          fill('Toothpaste is mildly ___.', ['basic']),
          fill('Hydrochloric acid in stomach helps in ___.', ['digestion']),
          mcq('Treat bee sting with mild ___.', ['acid', 'base', 'salt', 'water'], 1, 'medium'),
          mcq('Treat wasp sting with mild ___.', ['acid', 'base', 'salt', 'oil'], 0, 'medium'),
        ]),
        makeExercise('Neutralisation & Titration', [
          mcq('Equivalence point is when moles acid = moles ___.', ['salt', 'base', 'water', 'gas'], 1),
          mcq('Titration uses a graduated:', ['Beaker', 'Burette', 'Test tube', 'Funnel'], 1),
          mcq('Strong acid + strong base end pH:', ['<7', '7', '>7', '0'], 1),
          mcq('Strong acid + weak base end pH:', ['<7', '7', '>7', '14'], 0),
          mcq('Weak acid + strong base end pH:', ['<7', '7', '>7', '0'], 2),
          mcq('Indicator for strong acid-strong base:', ['Phenolphthalein or methyl orange', 'Only litmus', 'Universal only', 'No indicator'], 0),
          fill('Acid + Carbonate → Salt + Water + ___.', ['CO₂']),
          fill('Neutralisation is generally an ___ reaction.', ['exothermic']),
          mcq('25 mL of 0.1 M HCl needs ___ mL of 0.1 M NaOH.', ['12.5', '25', '50', '100'], 1, 'medium'),
          mcq('Back titration is used when:', ['Reaction is fast & visible', 'Direct titration impractical', 'Always', 'Never'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Metals & Non-Metals',
      description: 'Properties, reactivity series, extraction, alloys.',
      exercises: [
        makeExercise('Metallic Properties', [
          mcq('Metals are generally:', ['Brittle', 'Malleable', 'Insulators', 'Gaseous'], 1),
          mcq('Most metals are good conductors of:', ['Heat only', 'Heat & electricity', 'Light only', 'Sound only'], 1),
          mcq('Mercury is metal that is:', ['Solid', 'Liquid at RT', 'Gas', 'Plasma'], 1),
          mcq('Sodium is stored under:', ['Water', 'Kerosene', 'Air', 'Acid'], 1),
          mcq('Most ductile metal:', ['Iron', 'Gold', 'Aluminium', 'Copper'], 1),
          mcq('Best conductor of electricity:', ['Iron', 'Silver', 'Copper', 'Gold'], 1),
          fill('Metals lose electrons to form ___.', ['cations']),
          fill('Non-metals gain electrons to form ___.', ['anions']),
          mcq('Carbon, sulfur, phosphorus are:', ['Metals', 'Non-metals', 'Metalloids', 'Salts'], 1, 'medium'),
          mcq('Graphite conducts electricity because of:', ['Mobile electrons', 'Ionic bonds', 'Magnetism', 'Hydrogen bonds'], 0, 'medium'),
        ]),
        makeExercise('Reactivity Series', [
          mcq('Most reactive metal in series:', ['Cu', 'K', 'Au', 'Ag'], 1),
          mcq('Least reactive in series:', ['K', 'Na', 'Au', 'Mg'], 2),
          mcq('Iron displaces:', ['Cu from CuSO₄', 'Mg from MgSO₄', 'Na from NaCl', 'Al from Al₂O₃'], 0),
          mcq('Hydrogen sits between:', ['Cu and Ag', 'Pb and Cu', 'Na and Mg', 'Au and Pt'], 1),
          mcq('Reaction with cold water (very reactive):', ['Sodium', 'Iron', 'Copper', 'Gold'], 0),
          mcq('Reaction with steam only:', ['Magnesium', 'Iron', 'Copper', 'Gold'], 1),
          fill('Cu + dilute HCl: ___.', ['no reaction']),
          fill('Zn + dilute HCl gives ZnCl₂ + ___.', ['H₂']),
          mcq('Order of reactivity (high → low):', ['K, Na, Ca, Mg', 'Mg, Ca, Na, K', 'Cu, Fe, Mg, Na', 'Fe, Mg, K, Na'], 0, 'medium'),
          mcq('Aluminium does not corrode visibly because of:', ['Inertness', 'Self-passivating Al₂O₃ layer', 'Magnetism', 'Lustre only'], 1, 'medium'),
        ]),
        makeExercise('Extraction & Refining', [
          mcq('Ore of iron:', ['Bauxite', 'Hematite', 'Cinnabar', 'Galena'], 1),
          mcq('Ore of aluminium:', ['Bauxite', 'Hematite', 'Cinnabar', 'Galena'], 0),
          mcq('Ore of mercury:', ['Bauxite', 'Cinnabar', 'Hematite', 'Galena'], 1),
          mcq('Ore of lead:', ['Galena', 'Hematite', 'Bauxite', 'Cinnabar'], 0),
          mcq('Reduction of ore uses:', ['Carbon/CO usually', 'Magnetism', 'Light', 'Sound'], 0),
          mcq('Aluminium is extracted by:', ['Roasting only', 'Electrolysis (Hall-Héroult)', 'Reduction with C', 'Calcination only'], 1),
          fill('Roasting heats ore in ___.', ['air']),
          fill('Calcination heats ore in absence of ___.', ['air']),
          mcq('Blast furnace uses ___ as reducing agent.', ['CO', 'O₂', 'N₂', 'H₂O'], 0, 'medium'),
          mcq('Refining of copper uses:', ['Distillation', 'Electrolytic refining', 'Crystallisation', 'Filtration'], 1, 'medium'),
        ]),
        makeExercise('Alloys & Corrosion', [
          mcq('Alloy of Cu and Sn:', ['Brass', 'Bronze', 'Steel', 'Solder'], 1),
          mcq('Alloy of Cu and Zn:', ['Brass', 'Bronze', 'Steel', 'Solder'], 0),
          mcq('Steel is iron + ___.', ['Tin', 'Carbon', 'Lead', 'Zinc'], 1),
          mcq('Stainless steel contains:', ['Cr, Ni', 'Cu, Sn', 'Pb, Sb', 'Au, Ag'], 0),
          mcq('Galvanisation prevents corrosion using coat of:', ['Zinc', 'Copper', 'Silver', 'Lead'], 0),
          mcq('Rust is hydrated:', ['Iron oxide', 'Iron sulfide', 'Copper carbonate', 'Aluminium oxide'], 0),
          fill('Solder is alloy of Pb and ___.', ['Sn']),
          fill('Coating with paint protects metal from ___.', ['corrosion']),
          mcq('Tarnishing of silver gives black ___.', ['Ag₂S', 'AgCl', 'AgBr', 'Ag₂O'], 0, 'medium'),
          mcq('Sacrificial anode for ship hull is typically:', ['Zinc', 'Copper', 'Iron', 'Lead'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Carbon & Its Compounds',
      description: 'Tetravalency, hydrocarbons, isomerism, functional groups.',
      exercises: [
        makeExercise('Bonding & Allotropes', [
          mcq('Carbon\u2019s valency is:', ['1', '2', '3', '4'], 3),
          mcq('Diamond is:', ['Soft', 'Hardest natural mineral', 'Conductor', 'Liquid'], 1),
          mcq('Graphite conducts electricity because of:', ['Mobile electrons in layers', 'Ions', 'Magnetism', 'Hydrogen bonds'], 0),
          mcq('Fullerene C₆₀ shape:', ['Cube', 'Soccer ball', 'Sheet', 'Diamond'], 1),
          mcq('Methane formula:', ['CH₃', 'CH₄', 'C₂H₆', 'C₃H₈'], 1),
          mcq('Ethane formula:', ['CH₄', 'C₂H₆', 'C₂H₄', 'C₂H₂'], 1),
          fill('Carbon forms strong ___ bonds with itself.', ['covalent']),
          fill('Two carbons share ___ pairs in a double bond.', ['two']),
          mcq('Number of σ bonds in CH₄:', ['1', '2', '3', '4'], 3, 'medium'),
          mcq('Catenation is property of forming ___ chains.', ['short', 'long', 'no', 'one-atom'], 1, 'medium'),
        ]),
        makeExercise('Hydrocarbons', [
          mcq('Saturated hydrocarbon = ___.', ['Alkane', 'Alkene', 'Alkyne', 'Aromatic'], 0),
          mcq('Alkene contains:', ['Single bonds', 'C=C double bond', 'Triple bond', 'No carbon'], 1),
          mcq('Alkyne contains:', ['C–C', 'C=C', 'C≡C', 'C–H only'], 2),
          mcq('Ethyne is:', ['C₂H₂', 'C₂H₄', 'C₂H₆', 'C₃H₆'], 0),
          mcq('General formula alkane:', ['C_nH_{2n}', 'C_nH_{2n+2}', 'C_nH_{2n-2}', 'C_nH_n'], 1),
          mcq('General formula alkene:', ['C_nH_{2n}', 'C_nH_{2n+2}', 'C_nH_{2n-2}', 'C_nH_n'], 0),
          fill('LPG mainly consists of ___.', ['butane']),
          fill('CNG mainly consists of ___.', ['methane']),
          mcq('Combustion of CH₄ gives:', ['CO₂ + H₂O', 'CO + H₂', 'C + H₂', 'C₂H₆'], 0, 'medium'),
          mcq('Cyclohexane formula:', ['C₆H₆', 'C₆H₁₂', 'C₆H₁₀', 'C₆H₈'], 1, 'medium'),
        ]),
        makeExercise('Functional Groups', [
          mcq('-OH is:', ['Alcohol', 'Aldehyde', 'Ketone', 'Acid'], 0),
          mcq('-COOH is:', ['Alcohol', 'Aldehyde', 'Ketone', 'Carboxylic acid'], 3),
          mcq('-CHO is:', ['Aldehyde', 'Alcohol', 'Ester', 'Amine'], 0),
          mcq('-CO- (between Cs) is:', ['Aldehyde', 'Ketone', 'Acid', 'Alcohol'], 1),
          mcq('-NH₂ is:', ['Amide', 'Amine', 'Acid', 'Alcohol'], 1),
          mcq('-COOR is:', ['Ester', 'Amine', 'Acid', 'Aldehyde'], 0),
          fill('Ethanol functional group is ___.', ['hydroxyl']),
          fill('Acetic acid contains the ___ group.', ['carboxyl']),
          mcq('Esters are formed by acid + ___.', ['acid', 'alcohol', 'water', 'salt'], 1, 'medium'),
          mcq('Soap is sodium salt of long-chain ___.', ['alcohol', 'fatty acid', 'amine', 'ester'], 1, 'medium'),
        ]),
        makeExercise('Soaps & Detergents', [
          mcq('Soap molecule has:', ['Polar head + non-polar tail', 'Two heads', 'Two tails', 'No structure'], 0),
          mcq('Hard water + soap → ___.', ['Lather easily', 'Scum', 'Salt', 'Acid'], 1),
          mcq('Detergents work in:', ['Hard water poorly', 'Hard water well', 'Only soft water', 'Vacuum'], 1),
          mcq('Cleansing action involves forming ___.', ['emulsion/micelles', 'precipitate', 'gas', 'crystal'], 0),
          mcq('Sodium stearate is a:', ['Soap', 'Detergent', 'Acid', 'Salt only'], 0),
          mcq('Saponification produces:', ['Soap + glycerol', 'Soap + acid', 'Acid + base', 'Salt + gas'], 0),
          fill('Tail of soap is ___ (water-fearing).', ['hydrophobic']),
          fill('Head of soap is ___ (water-loving).', ['hydrophilic']),
          mcq('Synthetic detergents are usually salts of:', ['Acetic acid', 'Sulfonic acids', 'Carbonic acid', 'Nitric acid'], 1, 'medium'),
          mcq('Soap fails in hard water because of:', ['Ca²⁺/Mg²⁺ ions', 'High pH', 'Low T', 'Air'], 0, 'medium'),
        ]),
      ],
    },
  ],

  2: [
    {
      title: 'Chemical Bonding (Advanced)',
      description: 'VSEPR, hybridisation, MO theory basics.',
      exercises: [
        makeExercise('VSEPR Geometry', [
          mcq('CH₄ shape:', ['Linear', 'Bent', 'Tetrahedral', 'Trigonal planar'], 2),
          mcq('NH₃ shape:', ['Tetrahedral', 'Trigonal pyramidal', 'Trigonal planar', 'Linear'], 1),
          mcq('H₂O shape:', ['Linear', 'Bent', 'Tetrahedral', 'Trigonal'], 1),
          mcq('CO₂ shape:', ['Linear', 'Bent', 'Trigonal', 'Tetrahedral'], 0),
          mcq('SF₆ shape:', ['Octahedral', 'Tetrahedral', 'Square planar', 'Trigonal'], 0),
          mcq('PCl₅ shape:', ['Trigonal bipyramidal', 'Tetrahedral', 'Octahedral', 'Linear'], 0),
          fill('Lone pairs ___ bond angle (vs ideal).', ['decrease']),
          fill('CH₄ bond angle is ___°.', ['109.5']),
          mcq('XeF₄ shape:', ['Tetrahedral', 'Square planar', 'Octahedral', 'Linear'], 1, 'medium'),
          mcq('NH₃ angle vs CH₄:', ['Larger', 'Smaller (107)', 'Same', 'Zero'], 1, 'medium'),
        ]),
        makeExercise('Hybridisation', [
          mcq('sp³ in:', ['CH₄', 'C₂H₄', 'C₂H₂', 'CO₂'], 0),
          mcq('sp² in:', ['CH₄', 'C₂H₄', 'C₂H₂', 'NH₃'], 1),
          mcq('sp in:', ['CH₄', 'C₂H₄', 'C₂H₂', 'NH₃'], 2),
          mcq('Carbon in benzene:', ['sp', 'sp²', 'sp³', 'sp³d'], 1),
          mcq('PCl₅ central atom hybridisation:', ['sp³', 'sp³d', 'sp³d²', 'sp²'], 1),
          mcq('SF₆ central atom hybridisation:', ['sp³', 'sp³d', 'sp³d²', 'sp²'], 2),
          fill('Triple bond contains 1 σ and 2 ___.', ['π']),
          fill('Double bond contains 1 σ and 1 ___.', ['π']),
          mcq('Allene CH₂=C=CH₂ central C:', ['sp', 'sp²', 'sp³', 'sp³d'], 0, 'medium'),
          mcq('Benzene π-electrons number:', ['4', '6', '8', '12'], 1, 'medium'),
        ]),
        makeExercise('Molecular Orbitals', [
          mcq('Bond order = (Nb − Na)/___.', ['1', '2', 'Na', 'Nb'], 1),
          mcq('Bond order of O₂:', ['1', '2', '2.5', '3'], 1),
          mcq('Bond order of N₂:', ['1', '2', '2.5', '3'], 3),
          mcq('Paramagnetic diatomic among:', ['N₂', 'F₂', 'O₂', 'Ne'], 2),
          mcq('Bond order 0 means:', ['Strong bond', 'No molecule', 'Triple bond', 'Single bond'], 1),
          mcq('σ bonds have density along:', ['Internuclear axis', 'Above/below axis', 'Random', 'No direction'], 0),
          fill('π bonds form by ___ overlap of p orbitals.', ['side-on']),
          fill('Antibonding MO is denoted with ___.', ['*']),
          mcq('He₂ stability: bond order:', ['0', '0.5', '1', '2'], 0, 'medium'),
          mcq('O₂⁻ vs O₂: bond order:', ['Higher', 'Lower (1.5)', 'Same', 'Zero'], 1, 'medium'),
        ]),
        makeExercise('Intermolecular Forces', [
          mcq('Strongest intermolecular force:', ['London', 'Dipole-dipole', 'Hydrogen bond', 'Ion-dipole'], 3),
          mcq('Hydrogen bond requires H bonded to:', ['C', 'F/O/N', 'I', 'Cl mostly'], 1),
          mcq('Dispersion forces increase with:', ['Smaller mass', 'Bigger polarisability', 'Charge', 'Heat'], 1),
          mcq('Dipole-dipole acts between:', ['Non-polar', 'Polar molecules', 'Ions only', 'Atoms only'], 1),
          mcq('Boiling point of H₂O > H₂S because of:', ['H-bonding', 'Mass', 'Charge', 'Density'], 0),
          mcq('Iodine sublimes due to:', ['Strong H-bond', 'Weak London forces', 'Ionic bonds', 'Metal bonds'], 1),
          fill('Dipole moment unit is ___.', ['Debye']),
          fill('Ion-dipole forces matter in ___ solutions.', ['aqueous']),
          mcq('Surface tension of water is high due to:', ['Mass', 'H-bonding', 'Density', 'Pressure'], 1, 'medium'),
          mcq('CO₂ is non-polar despite polar bonds because:', ['Bent', 'Linear cancellation', 'Ionic', 'Empty orbitals'], 1, 'medium'),
        ]),
        makeExercise('Bond Energy & Polarity', [
          mcq('Electronegativity trend across a period:', ['Decreases', 'Increases', 'Constant', 'Random'], 1),
          mcq('Most electronegative element:', ['O', 'F', 'Cl', 'N'], 1),
          mcq('Polar covalent bond has ΔEN:', ['= 0', '~0.5–1.7', '> 3', '< 0'], 1),
          mcq('Ionic bond ΔEN typically:', ['< 0.5', '0.5–1.7', '> 1.7', '0'], 2),
          mcq('Bond enthalpy measures energy to:', ['Form bond', 'Break bond', 'Polarise bond', 'Ionise atom'], 1),
          mcq('Bond length and bond order:', ['Direct', 'Inverse', 'Independent', 'Always equal'], 1),
          fill('Resonance ___ stability of a molecule.', ['increases']),
          fill('Formal charge sums to total ___ of molecule.', ['charge']),
          mcq('NaCl bond is best described as:', ['Pure covalent', 'Polar covalent', 'Predominantly ionic', 'Metallic'], 2, 'medium'),
          mcq('Greater bond order means:', ['Longer & weaker bond', 'Shorter & stronger bond', 'No effect', 'Same length'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Equilibria & Solutions',
      description: 'Le Chatelier, Ka/Kb, buffers, colligative properties.',
      exercises: [
        makeExercise('Equilibrium Basics', [
          mcq('At equilibrium, rates of forward & reverse:', ['Zero', 'Equal', 'Forward larger', 'Reverse larger'], 1),
          mcq('K_eq for aA + bB ⇌ cC + dD = ', ['[C]^c[D]^d/[A]^a[B]^b', 'Sum of conc.', 'Product of all', 'Difference'], 0),
          mcq('Le Chatelier: add reactant →', ['Shift right', 'Shift left', 'No shift', 'Stops'], 0),
          mcq('Increase pressure favours side with:', ['More moles of gas', 'Fewer moles of gas', 'Same', 'No effect'], 1),
          mcq('Catalyst affects:', ['K_eq', 'Rate but not K', 'Equilibrium position', 'Temperature'], 1),
          mcq('K_p vs K_c relation:', ['K_p = K_c (RT)^Δn', 'K_p = K_c', 'K_p = K_c/T', 'K_p = K_c²'], 0),
          fill('Le Chatelier: heating endo shifts ___.', ['forward']),
          fill('Q < K means reaction proceeds ___.', ['forward']),
          mcq('Increasing temperature for exothermic reaction:', ['Increases K', 'Decreases K', 'No change', 'Doubles K'], 1, 'medium'),
          mcq('Adding inert gas at constant V on equilibrium:', ['Shifts right', 'No shift', 'Shifts left', 'Stops'], 1, 'medium'),
        ]),
        makeExercise('Acid-Base Equilibria', [
          mcq('pH = -log[___]', ['H⁺', 'OH⁻', 'H₂O', 'pOH'], 0),
          mcq('Pure water at 25 °C: [H⁺]:', ['10⁻⁷ M', '10⁻¹⁴', '1 M', '7 M'], 0),
          mcq('Strong acid like HCl in water has Ka:', ['Very small', 'Very large', 'Zero', 'Negative'], 1),
          mcq('Buffer maintains pH near:', ['pKa', '7 always', '0', '14'], 0),
          mcq('Henderson-Hasselbalch: pH = pKa + log([___]/[HA]).', ['A⁻', 'H₂O', 'OH', 'HCl'], 0),
          mcq('Common ion effect ___ ionisation.', ['Increases', 'Suppresses', 'Doubles', 'Stops'], 1),
          fill('At 25 °C, K_w = ___.', ['10^-14']),
          fill('pH + pOH = ___.', ['14']),
          mcq('Buffer of equal CH₃COOH/CH₃COO⁻ has pH ≈', ['1', '4.74', '7', '14'], 1, 'medium'),
          mcq('Adding NaCl to HCl-water:', ['Lowers pH a lot', 'Almost no change', 'Raises pH a lot', 'Neutralises'], 1, 'medium'),
        ]),
        makeExercise('Solubility & Ksp', [
          mcq('K_sp is product of:', ['Reactant conc.', 'Ions of saturated salt', 'Water concs', 'Heat'], 1),
          mcq('Adding common ion ___ solubility.', ['Increases', 'Decreases', 'Doubles', 'Stops'], 1),
          mcq('AgCl K_sp ≈', ['10⁻⁵', '10⁻¹⁰', '10⁻²', '10²'], 1),
          mcq('Q > K_sp means:', ['Unsaturated', 'Saturated', 'Supersaturated → ppt', 'Empty'], 2),
          mcq('Solubility of gas in liquid increases with:', ['Higher T', 'Lower T', 'No effect', 'Higher V'], 1),
          mcq('Henry\u2019s law: P = k_H ___.', ['x', 'V', 'T', 'M'], 0),
          fill('Adding NaCl to AgCl saturated soln decreases ___ of AgCl.', ['solubility']),
          fill('CO₂ solubility decreases as T ___.', ['rises']),
          mcq('Solubility (mol/L) of AB-type salt with K_sp = 10⁻¹⁰:', ['10⁻⁵', '10⁻¹⁰', '10⁻⁷', '10⁻²'], 0, 'medium'),
          mcq('Salt AB₂ with K_sp = 4×10⁻¹², solubility:', ['10⁻⁴', '10⁻⁶', '10⁻⁸', '10⁻³'], 0, 'medium'),
        ]),
        makeExercise('Colligative Properties', [
          mcq('ΔT_b = K_b m i (ebullioscopic):', ['Boiling point elevation', 'Freezing point depression', 'Osmosis', 'Diffusion'], 0),
          mcq('Freezing point depression ΔT_f = K_f m ___.', ['i', 'V', 'P', 'T'], 0),
          mcq('Osmotic pressure π = ___.', ['MRT', 'M/RT', 'RT/M', 'PV'], 0),
          mcq('Van\u2019t Hoff factor i for NaCl ideally:', ['1', '2', '3', '4'], 1),
          mcq('Salt-spreading on icy roads relies on:', ['ΔT_b', 'ΔT_f', 'Osmosis', 'Sublimation'], 1),
          mcq('Sea water boils at:', ['Same as pure water', 'Higher (elevation)', 'Lower', 'Doesn\u2019t boil'], 1),
          fill('Colligative properties depend on ___ of solute.', ['number']),
          fill('Solvent vapour pressure ___ on adding non-volatile solute.', ['decreases']),
          mcq('1 m glucose vs 1 m NaCl: bigger ΔT_f for:', ['Glucose', 'NaCl', 'Same', 'Neither'], 1, 'medium'),
          mcq('Reverse osmosis is used in:', ['Sound', 'Water purification', 'Magnetism', 'Heat engines'], 1, 'medium'),
        ]),
        makeExercise('Buffers & Titration Curves', [
          mcq('Buffer best resists pH change near:', ['pKa', '0', '14', '7 always'], 0),
          mcq('Acidic buffer example:', ['CH₃COOH/CH₃COONa', 'NH₃/NH₄Cl', 'HCl/NaCl', 'NaOH/NaCl'], 0),
          mcq('Basic buffer example:', ['NH₃/NH₄Cl', 'CH₃COOH/CH₃COONa', 'HCl/NaCl', 'KCl/H₂O'], 0),
          mcq('Equivalence point of weak acid + strong base pH is:', ['<7', '7', '>7', '0'], 2),
          mcq('Half-equivalence point pH equals:', ['pKa', '7', 'pKw', 'pH+pOH'], 0),
          mcq('Buffer capacity is highest when [HA] ≈ [___].', ['A⁻', 'H₂O', 'OH', 'H⁺'], 0),
          fill('At equivalence, moles acid = moles ___.', ['base']),
          fill('Beyond equivalence, pH is governed by ___ excess.', ['titrant']),
          mcq('Polyprotic acids show ___ equivalence points.', ['One', 'Multiple', 'Zero', 'Negative'], 1, 'medium'),
          mcq('Choosing indicator: ideally pKa close to ___ of equivalence.', ['pH', 'pOH', 'pK_w', 'p_iso'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Electrochemistry',
      description: 'Cells, electrode potentials, electrolysis, batteries.',
      exercises: [
        makeExercise('Galvanic Cells', [
          mcq('Daniell cell electrodes:', ['Zn/Cu', 'Ag/Cu', 'Fe/Pt', 'C/H'], 0),
          mcq('Anode in galvanic cell is:', ['+', '-', 'Neutral', 'Salt bridge'], 1),
          mcq('Cathode in galvanic cell is:', ['+', '-', 'Salt', 'Neutral'], 0),
          mcq('SHE potential is:', ['1 V', '0 V', '-1 V', '0.5 V'], 1),
          mcq('E°cell = E°cath − E°___.', ['anode', 'salt', 'oxd', 'red'], 0),
          mcq('Salt bridge maintains:', ['Voltage', 'Charge balance', 'Heat', 'Mass'], 1),
          fill('Oxidation occurs at the ___.', ['anode']),
          fill('Reduction occurs at the ___.', ['cathode']),
          mcq('Zn|Zn²⁺||Cu²⁺|Cu cell EMF:', ['~0', '~1.1 V', '~2 V', '~5 V'], 1, 'medium'),
          mcq('Nernst equation reduces to E° at:', ['Standard concs', 'Zero V', 'Equilibrium', 'Discharge'], 0, 'medium'),
        ]),
        makeExercise('Electrolysis', [
          mcq('Electrolytic cell: anode is:', ['+', '-', 'Salt', 'Neutral'], 0),
          mcq('Faraday\u2019s 1st law: m ∝ ___.', ['Q', 'V', 'R', 'T'], 0),
          mcq('1 Faraday ≈', ['96,500 C', '6.02×10²³', '9.81', '8.314'], 0),
          mcq('Electrolysis of brine produces:', ['NaOH, Cl₂, H₂', 'Na, O₂', 'NaCl + H₂O', 'No change'], 0),
          mcq('Electroplating cathode is:', ['Object to be plated', 'Pure metal block', 'Anode', 'Salt bridge'], 0),
          mcq('Hall-Héroult process for:', ['Iron', 'Aluminium', 'Copper', 'Sodium'], 1),
          fill('m = (E I t)/F where E is ___ weight.', ['equivalent']),
          fill('Cation moves to ___ during electrolysis.', ['cathode']),
          mcq('Charge to deposit 1 mol Cu²⁺:', ['96,500 C', '193,000 C', '48,250 C', '0'], 1, 'medium'),
          mcq('1 A for 965 s deposits Ag (E=108):', ['1.08 g', '0.108 g', '10.8 g', '108 g'], 0, 'medium'),
        ]),
        makeExercise('Batteries & Conductivity', [
          mcq('Dry cell EMF:', ['1.5 V', '12 V', '5 V', '0.7 V'], 0),
          mcq('Lead-acid battery EMF:', ['~2 V', '~12 V (6 cells)', '~1 V', '~6 V'], 1),
          mcq('Li-ion battery anode commonly:', ['Graphite', 'LiCoO₂', 'Pb', 'Zn'], 0),
          mcq('Fuel cell uses:', ['Coal', 'H₂/O₂ continuous supply', 'Closed reservoir', 'Air only'], 1),
          mcq('Conductance unit:', ['Ω', 'S (Siemens)', 'F', 'H'], 1),
          mcq('Specific conductivity κ unit:', ['S/m', 'S', 'Ω·m', 'V/A'], 0),
          fill('Molar conductivity Λ_m increases as conc ___.', ['decreases']),
          fill('Strong electrolytes follow ___ law (Kohlrausch).', ['independent migration']),
          mcq('Limiting molar conductivity is reached at:', ['Infinite dilution', 'Saturation', 'Boiling', 'Freezing'], 0, 'medium'),
          mcq('Internal resistance increases when battery is:', ['New', 'Aged/discharged', 'Recharged', 'Idle'], 1, 'medium'),
        ]),
      ],
    },
  ],

  3: [
    {
      title: 'Coordination Chemistry',
      description: 'Werner theory, ligands, isomerism, CFT.',
      exercises: [
        makeExercise('Coordination Compounds', [
          mcq('Coordination number of [Co(NH₃)₆]³⁺:', ['4', '6', '8', '2'], 1),
          mcq('Geometry of [Ni(CN)₄]²⁻:', ['Tetrahedral', 'Square planar', 'Octahedral', 'Linear'], 1),
          mcq('Bidentate ligand example:', ['NH₃', 'en (ethylenediamine)', 'Cl⁻', 'H₂O'], 1),
          mcq('EDTA donates ___ pairs.', ['1', '2', '4', '6'], 3),
          mcq('Werner\u2019s primary valency = ___.', ['Ionic charge', 'Coordination', 'Atomic number', 'Mass'], 0),
          mcq('Crystal field theory considers:', ['Covalent overlap only', 'Electrostatic field of ligands', 'Magnetism only', 'Mass'], 1),
          fill('Ligands act as ___ donors.', ['lone-pair']),
          fill('Strong field ligands cause ___ spin.', ['low']),
          mcq('Spectrochemical series order (high → low Δ):', ['CO > CN⁻ > NH₃ > F⁻ > I⁻', 'I⁻ > F⁻ > NH₃ > CN⁻ > CO', 'F⁻ > CN⁻ > NH₃ > I⁻', 'NH₃ > Cl⁻ > CN⁻ > CO'], 0, 'medium'),
          mcq('Octahedral d⁶ low-spin has unpaired e⁻:', ['0', '2', '4', '6'], 0, 'medium'),
        ]),
        makeExercise('Isomerism in Complexes', [
          mcq('Geometrical isomerism in [MA₂B₂] square planar:', ['cis-trans', 'fac-mer', 'optical only', 'none'], 0),
          mcq('Optical isomerism requires:', ['Chirality', 'High symmetry', 'Inversion centre', 'σh plane'], 0),
          mcq('Linkage isomers differ in:', ['Atom that bonds (e.g., NO₂ vs ONO)', 'Geometry', 'Charge', 'Mass'], 0),
          mcq('Ionisation isomers exchange ions between:', ['Inner & outer sphere', 'Two cations', 'Solvents', 'Phases'], 0),
          mcq('fac/mer isomerism in:', ['MA₂B₂ Td', 'MA₃B₃ Oh', 'MA₂ Td', 'MA Oh'], 1),
          mcq('Coordination isomerism appears in:', ['Salts of two complex ions', 'Single complex', 'Solid only', 'Liquid only'], 0),
          fill('cis-Pt(NH₃)₂Cl₂ is the anticancer drug ___.', ['cisplatin']),
          fill('Optical isomers rotate plane-polarised ___.', ['light']),
          mcq('[Co(en)₃]³⁺ optical isomers count:', ['0', '2', '3', '4'], 1, 'medium'),
          mcq('Hydrate isomerism example:', ['CrCl₃·6H₂O variants', 'NaCl', 'KMnO₄', 'CO₂'], 0, 'medium'),
        ]),
        makeExercise('CFT & Colour', [
          mcq('Octahedral splitting parameter:', ['Δ_o', 'Δ_t', '10Dq²', 'g_J'], 0),
          mcq('Tetrahedral splitting Δ_t ≈', ['(4/9) Δ_o', 'Δ_o', '2 Δ_o', 'Δ_o²'], 0),
          mcq('Colour arises from:', ['d-d transitions absorbing visible light', 'Magnetism', 'Mass', 'Density'], 0),
          mcq('d⁰ and d¹⁰ complexes are usually:', ['Coloured', 'Colourless', 'Black', 'Magnetic'], 1),
          mcq('Hund\u2019s rule favours:', ['Pairing', 'Parallel spins in degenerate orbitals', 'Empty orbitals only', 'No spin'], 1),
          mcq('Strong-field ligand → ___ splitting.', ['Small', 'Large', 'No', 'Negative'], 1),
          fill('Complementary colour observed = colour of light ___.', ['absorbed']),
          fill('Δ_t < Δ_o because of fewer ligands and orientation effects, hence Td is mostly ___ spin.', ['high']),
          mcq('CFSE for d³ Oh = ___ Δ_o.', ['-0.4', '-0.8', '-1.2', '0'], 2, 'medium'),
          mcq('[Fe(CN)₆]³⁻ is:', ['High spin', 'Low spin', 'Diamagnetic only', 'Paramagnetic with 5 unpaired'], 1, 'medium'),
        ]),
        makeExercise('Organometallics', [
          mcq('Grignard reagent general formula:', ['RMgX', 'RLi only', 'RZnR', 'RNa'], 0),
          mcq('Grignard reacts with carbonyl to give:', ['Alkene', 'Alcohol', 'Halide', 'Acid'], 1),
          mcq('Ferrocene is an example of:', ['Sandwich complex', 'Ionic salt', 'Polymer', 'Metallic alloy'], 0),
          mcq('CO is a ___ ligand (donates and accepts).', ['Sigma-only', 'Pi-acceptor', 'Pure ionic', 'Spectator'], 1),
          mcq('18-electron rule applies to:', ['Main group only', 'Many transition metal complexes', 'Lanthanides only', 'Salts'], 1),
          mcq('Wilkinson catalyst is used for:', ['Cross coupling', 'Hydrogenation of alkenes', 'Halogenation', 'Sulfonation'], 1),
          fill('Catalyst that couples aryl halides with boronic acids: ___ coupling.', ['Suzuki']),
          fill('Pi-acid ligands stabilise low oxidation states of ___ metals.', ['transition']),
          mcq('Hapticity η⁵ means ligand donates via ___ atoms.', ['1', '3', '5', '6'], 2, 'medium'),
          mcq('Electron count of [Fe(CO)₅] is:', ['16', '18', '20', '22'], 1, 'medium'),
        ]),
        makeExercise('Bioinorganic Highlights', [
          mcq('Hemoglobin contains the metal:', ['Mg', 'Fe', 'Cu', 'Zn'], 1),
          mcq('Chlorophyll contains:', ['Fe', 'Mg', 'Cu', 'Zn'], 1),
          mcq('Vitamin B12 contains:', ['Co', 'Fe', 'Mg', 'Mn'], 0),
          mcq('Carbonic anhydrase metal cofactor:', ['Zn', 'Fe', 'Cu', 'Mg'], 0),
          mcq('Cytochromes contain:', ['Fe heme', 'Cu only', 'Mg', 'Mn'], 0),
          mcq('Cisplatin targets:', ['DNA', 'RNA only', 'Lipids', 'Sugars'], 0),
          fill('Iron in hemoglobin binds reversibly to ___.', ['O₂']),
          fill('CO is toxic because it binds heme much stronger than ___.', ['O₂']),
          mcq('MRI contrast agents commonly use:', ['Gd(III) chelates', 'Au(I)', 'Fe(III) salts only', 'Salt water'], 0, 'medium'),
          mcq('Nitrogenase enzyme contains the cluster:', ['FeMoCo', 'CuZn', 'MnFe', 'NiFe only'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Organic Reaction Mechanisms',
      description: 'Sn1/Sn2, E1/E2, addition, aromatic substitution.',
      exercises: [
        makeExercise('Substitution', [
          mcq('SN2 occurs in one step with:', ['Carbocation', 'Backside attack & inversion', 'Free radical', 'Carbanion'], 1),
          mcq('SN1 has rate dependent on:', ['Substrate only', 'Substrate + nucleophile', 'Solvent only', 'Temperature only'], 0),
          mcq('Best substrate for SN2:', ['3°', '2°', '1° / methyl', 'Aryl'], 2),
          mcq('Best substrate for SN1:', ['Methyl', '1°', '2°', '3°'], 3),
          mcq('SN2 prefers solvent:', ['Polar protic', 'Polar aprotic', 'Non-polar only', 'Vacuum'], 1),
          mcq('SN1 prefers solvent:', ['Polar protic', 'Non-polar', 'Aprotic', 'No solvent'], 0),
          fill('SN1 rate-limiting step forms a ___.', ['carbocation']),
          fill('SN2 has ___ stereochemistry.', ['inversion']),
          mcq('Tertiary alkyl halide + weak nucleophile (water) likely gives:', ['SN2', 'SN1', 'E2', 'No reaction'], 1, 'medium'),
          mcq('Methyl bromide + OH⁻ is mainly:', ['SN1', 'SN2', 'E1', 'E2'], 1, 'medium'),
        ]),
        makeExercise('Elimination', [
          mcq('E2 needs:', ['Strong base, anti-periplanar', 'Heat only', 'Light only', 'Acid'], 0),
          mcq('Zaitsev\u2019s rule favours:', ['Least substituted alkene', 'Most substituted alkene', 'No alkene', 'Random'], 1),
          mcq('Hofmann product is favoured with:', ['Small bases', 'Bulky bases', 'No base', 'Acid'], 1),
          mcq('E1 has:', ['One step', 'Two steps via carbocation', 'Concerted', 'Free radical'], 1),
          mcq('E2 stereochemistry:', ['syn only', 'anti-periplanar', 'Random', 'cis only'], 1),
          mcq('E1 vs E2 rate effect of base concentration:', ['E1 independent, E2 first order in base', 'Both same', 'E1 first order in base', 'No effect'], 0),
          fill('Tertiary alkyl halides favor ___ over SN under strong base.', ['E2']),
          fill('Hofmann uses bulky base like ___.', ['t-BuO-']),
          mcq('Dehydration of alcohol gives more substituted alkene because:', ['Hofmann', 'Zaitsev', 'Markovnikov', 'No rule'], 1, 'medium'),
          mcq('Bicyclic constraints can override Zaitsev to give:', ['Hofmann/Bredt', 'Same', 'No alkene', 'Carbocation only'], 0, 'medium'),
        ]),
        makeExercise('Addition Reactions', [
          mcq('Markovnikov for HX + alkene: H goes to:', ['More-substituted C', 'Less-substituted C', 'Random', 'Neither'], 1),
          mcq('Anti-Markovnikov occurs with:', ['HBr + peroxide (radical)', 'HCl alone', 'HI alone', 'H₂O'], 0),
          mcq('Hydroboration-oxidation gives:', ['Markovnikov OH', 'Anti-Markovnikov OH', 'Halide', 'Alkane'], 1),
          mcq('Halogenation of alkene gives:', ['1,2-dihalide', '1,1-dihalide', 'Alkane', 'Aromatic'], 0),
          mcq('Hydrogenation of alkene gives:', ['Alkene', 'Alkane', 'Alkyne', 'Aromatic'], 1),
          mcq('Ozonolysis of alkene gives:', ['Carbonyls', 'Alkanes', 'Halides', 'Esters'], 0),
          fill('Bromination across C=C is ___ addition.', ['anti']),
          fill('Catalysts for hydrogenation are ___ metals.', ['Pd/Pt/Ni']),
          mcq('Symmetry of carbocation intermediate explains:', ['No regioselectivity', 'Markovnikov rule', 'Hofmann', 'No effect'], 1, 'medium'),
          mcq('Acid-catalysed hydration of alkene gives:', ['Anti-Markovnikov', 'Markovnikov alcohol', 'Halide', 'Alkane'], 1, 'medium'),
        ]),
        makeExercise('Aromatic Reactions', [
          mcq('Benzene undergoes:', ['Electrophilic addition mainly', 'Electrophilic aromatic substitution', 'Free radical only', 'No reaction'], 1),
          mcq('Activating groups direct to:', ['ortho/para', 'meta', 'No direction', 'Random'], 0),
          mcq('Deactivating groups (e.g., -NO₂) direct to:', ['ortho/para', 'meta', 'No direction', 'Random'], 1),
          mcq('Friedel-Crafts uses catalyst:', ['NaOH', 'AlCl₃', 'KMnO₄', 'H₂O'], 1),
          mcq('Nitration uses:', ['HNO₃ + H₂SO₄', 'Cl₂', 'AlCl₃', 'KMnO₄'], 0),
          mcq('Halogenation of benzene needs catalyst like:', ['AlCl₃ / FeBr₃', 'NaOH', 'H₂O', 'Heat alone'], 0),
          fill('-OH on benzene is strongly ___.', ['activating']),
          fill('-NO₂ on benzene is ___.', ['deactivating']),
          mcq('Strong activator + small base gives mostly:', ['ortho/para', 'meta', 'No reaction', 'mix only'], 0, 'medium'),
          mcq('-NH₂ in EAS direction is:', ['ortho/para', 'meta', 'Mixture only', 'Inert'], 0, 'medium'),
        ]),
        makeExercise('Carbonyl Chemistry', [
          mcq('Aldehydes are oxidised to:', ['Alcohols', 'Carboxylic acids', 'Esters only', 'Alkanes'], 1),
          mcq('Ketones resist oxidation by mild oxidants:', ['False', 'True', 'Sometimes', 'Always oxidise'], 1),
          mcq('Tollens reagent gives positive test for:', ['Ketones', 'Aldehydes', 'Alkanes', 'Esters'], 1),
          mcq('Nucleophilic addition to C=O gives:', ['Alkene', 'Alcohol after workup', 'Halide', 'Aromatic'], 1),
          mcq('Aldol condensation forms a:', ['α,β-unsaturated carbonyl', 'Halide', 'Ester only', 'Aromatic ring'], 0),
          mcq('Claisen condensation involves:', ['Two esters', 'Two alkanes', 'Acid + alcohol', 'Two amines'], 0),
          fill('Hemiacetals come from carbonyl + ___.', ['alcohol']),
          fill('Imines form from carbonyl + ___.', ['amine']),
          mcq('Wittig reaction uses an ylide to make:', ['Alkene from carbonyl', 'Alcohol', 'Acid', 'Halide'], 0, 'medium'),
          mcq('Cannizzaro reaction occurs with aldehydes lacking:', ['α-H', 'β-H', 'O', 'C'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Spectroscopy',
      description: 'UV-Vis, IR, NMR, MS basics.',
      exercises: [
        makeExercise('IR Spectroscopy', [
          mcq('IR detects:', ['Electronic transitions', 'Vibrational modes', 'Nuclear spin', 'Mass'], 1),
          mcq('Carbonyl C=O stretch ≈', ['1700 cm⁻¹', '3300 cm⁻¹', '1000 cm⁻¹', '500 cm⁻¹'], 0),
          mcq('O-H broad stretch ≈', ['3200–3600 cm⁻¹', '1700', '500', '2200'], 0),
          mcq('C-H stretches are typically:', ['~1500', '~2900', '~700', '~3600'], 1),
          mcq('Triple bond C≡C stretch ≈', ['~2200 cm⁻¹', '~1700', '~3300', '~1000'], 0),
          mcq('Fingerprint region:', ['<1500 cm⁻¹', '>4000', '~2900', '>10000'], 0),
          fill('Number of normal modes for nonlinear N-atom: 3N − ___.', ['6']),
          fill('Linear molecule modes: 3N − ___.', ['5']),
          mcq('Strong dipole change yields stronger IR:', ['False', 'True', 'Sometimes', 'No relation'], 1, 'medium'),
          mcq('Hydrogen-bonded O-H is broader and at:', ['Higher cm⁻¹', 'Lower cm⁻¹', 'Same', 'No shift'], 1, 'medium'),
        ]),
        makeExercise('NMR', [
          mcq('Most common NMR nucleus:', ['¹H', '¹²C', '¹⁶O', '³⁵Cl'], 0),
          mcq('Chemical shift δ unit:', ['ppm', 'Hz', 'cm⁻¹', 'eV'], 0),
          mcq('Aromatic H typically ≈', ['0–1 ppm', '1–2 ppm', '7 ppm', '12 ppm'], 2),
          mcq('TMS reference shift:', ['0 ppm', '7 ppm', '10 ppm', '12 ppm'], 0),
          mcq('Coupling constant J unit:', ['Hz', 'ppm', 'cm⁻¹', 'eV'], 0),
          mcq('n+1 rule splits H signal into:', ['n peaks', 'n+1 peaks', 'n−1 peaks', '1 peak only'], 1),
          fill('OH of alcohol is variable; often broad ___ peak.', ['singlet']),
          fill('¹³C NMR is decoupled to give ___ peaks per C.', ['single']),
          mcq('CH₃ next to CH₂ shows splitting pattern:', ['Singlet', 'Doublet', 'Triplet', 'Quartet'], 2, 'medium'),
          mcq('Equivalent protons give:', ['One signal', 'Many signals', 'No signal', 'Doublet always'], 0, 'medium'),
        ]),
        makeExercise('UV-Vis & MS', [
          mcq('UV-Vis probes:', ['Vibration', 'Electronic transitions', 'Nuclear spin', 'Mass'], 1),
          mcq('λ_max increases with:', ['Less conjugation', 'More conjugation', 'Heat only', 'Mass only'], 1),
          mcq('Beer\u2019s law: A = ε c ___.', ['l', 'V', 'T', 'P'], 0),
          mcq('Mass spectrometer ionises and measures:', ['m/z ratio', 'wavelength', 'Spin', 'IR shift'], 0),
          mcq('Molecular ion peak gives:', ['Mass of fragment', 'Molecular mass', 'Empirical formula only', 'Charge'], 1),
          mcq('Isotope pattern of Cl shows:', ['No isotopes', 'M and M+2 (3:1)', 'M and M+1 only', 'Random'], 1),
          fill('Conjugation lowers HOMO-LUMO ___.', ['gap']),
          fill('M+ peak is the ___ ion peak.', ['molecular']),
          mcq('Br shows isotope pattern roughly:', ['1:1 M and M+2', '3:1', '5:1', 'No isotopes'], 0, 'medium'),
          mcq('McLafferty rearrangement is seen in:', ['Aromatics', 'Carbonyls with γ-H', 'Alkanes', 'Salts'], 1, 'medium'),
        ]),
      ],
    },
  ],
};
