/**
 * C++ question bank.
 * Levels: 1 = beginner, 2 = intermediate (OOP/STL), 3 = advanced (modern C++).
 */

import type { SeedUnit } from '../seed-bank';
import { mcq, fill, match, makeExercise } from '../seed-bank';

export const CPP: Record<1 | 2 | 3, SeedUnit[]> = {
  1: [
    {
      title: 'Syntax & I/O',
      description: 'Compilation model, headers, std::cout / std::cin.',
      exercises: [
        makeExercise('Hello, C++', [
          mcq('Entry point of a C++ program:', ['start()', 'main()', 'init()', 'begin()'], 1),
          mcq('Header for cout:', ['<stdio.h>', '<iostream>', '<string>', '<cstdio>'], 1),
          mcq('Standard namespace:', ['sys', 'std', 'cpp', 'system'], 1),
          mcq('Statement terminator:', [':', ';', '.', 'newline'], 1),
          mcq('Single-line comment:', ['#', '//', '--', '%'], 1),
          mcq('Compile typical command:', ['gcc a.c', 'g++ a.cpp', 'cpp a', 'make a.cpp'], 1),
          fill('C++ is a ___ typed language.', ['statically']),
          fill('A program file must include exactly one ___ function.', ['main']),
          mcq('Result of `cout << 5 << \" \" << 6;`:', ['56', '5 6', '5,6', '11'], 1, 'medium'),
          mcq('std::endl differs from \"\\n\" because it also:', ['Adds tab', 'Flushes the stream', 'Crashes', 'Does nothing'], 1, 'medium'),
        ]),        makeExercise('Compilation Model', [
          mcq('Phase that resolves #include:', ['Linking', 'Preprocessing', 'Parsing', 'Codegen'], 1),
          mcq('Producer of object files:', ['Linker', 'Compiler', 'Loader', 'Assembler only'], 1),
          mcq('Linker job:', ['Combine objects to executable', 'Generate AST', 'Run program', 'Format code'], 0),
          mcq('ODR stands for:', ['One Definition Rule', 'Object Dispatch Routine', 'Order of Decl. Resolution', 'Out-of-Date Reference'], 0),
          mcq('Header guard alternative:', ['#once', '#pragma once', '#guard', '#protect'], 1),
          mcq('Translation unit is:', ['One .cpp + included headers', 'One .h only', 'Whole project', 'One function'], 0),
          fill('Common C++ extensions are .cpp, .cc, .___.', ['cxx']),
          fill('Static library archives end in .___ on Linux.', ['a']),
          mcq('Link error "undefined reference":', ['Missing definition', 'Bad syntax', 'Out of memory', 'Wrong charset'], 0, 'medium'),
          mcq('-O2 vs -O0 mainly differs in:', ['Linking', 'Optimisation level', 'Warnings only', 'Debug info'], 1, 'medium'),
        ]),
        makeExercise('std::cin / std::cout', [
          mcq('Read int from cin:', ['cin >> x;', 'cin << x;', 'cin.read(x);', 'scanf cin x;'], 0),
          mcq('Print int with newline:', ['cout << x << endl;', 'cout >> x;', 'print(x);', 'cout.print(x);'], 0),
          mcq('Read full line:', ['getline(cin, s)', 'cin >> s', 'cin.getline only', 'fgets'], 0),
          mcq('Sync C++ streams off:', ['ios::sync_with_stdio(false)', 'cin.fast()', 'cout.fast()', 'sync(0)'], 0),
          mcq('Untie streams:', ['cin.tie(nullptr)', 'cout.untie()', 'tie(0)', 'cin.detach()'], 0),
          mcq('Format hex output:', ['cout << hex << x', 'cout.hex(x)', 'printHex(x)', 'cout << x.hex'], 0),
          fill('Set field width with std::___.', ['setw']),
          fill('Boolean prints as 1/0 unless ___ flag set.', ['boolalpha']),
          mcq('cin >> on bad input:', ['Sets failbit', 'Crashes', 'Silently zeros', 'Loops'], 0, 'medium'),
          mcq('Recover after fail:', ['cin.clear()', 'cin.reset()', 'cin.flush()', 'cin.discard()'], 0, 'medium'),
        ]),
        makeExercise('Operators & Precedence', [
          mcq('Modulo for ints:', ['%', 'mod', 'rem', '//'], 0),
          mcq('Logical AND:', ['&', '&&', 'and only', '|'], 1),
          mcq('Bitwise XOR:', ['^', '|', '&', '~'], 0),
          mcq('Left shift:', ['<<', '>>', '<-', '>-'], 0),
          mcq('Pre- vs post-increment yields:', ['Same value', 'Different temporary', 'Always equal', 'Crash'], 1),
          mcq('?: is the:', ['Comma op', 'Conditional op', 'Sizeof', 'Ternary plus'], 1),
          fill('a==b ? x : y is the ___ operator.', ['conditional']),
          fill('sizeof returns size in ___.', ['bytes']),
          mcq('5 / 2 in C++ ints =', ['2', '2.5', '3', 'Error'], 0, 'medium'),
          mcq('-3 % 2 (impl-defined pre-C++11, defined now):', ['-1', '1', '0', 'Error'], 0, 'medium'),
        ]),
        makeExercise('Strings', [
          mcq('Modern C++ string type:', ['char*', 'std::string', 'CString', 'std::str'], 1),
          mcq('Concatenate strings:', ['+', '.', '..', 'concat()'], 0),
          mcq('Length of std::string:', ['size()', 'len()', 'count()', 'length only'], 0),
          mcq('Access char by index:', ['s[i]', 's.at(i)', 'Both safe variants', 'None'], 2),
          mcq('Convert int to string:', ['std::to_string', 'str(int)', 'cast<string>', '(string)i'], 0),
          mcq('std::string_view (C++17) is:', ['Owning', 'Non-owning view', 'Pointer alias', 'Hash table'], 1),
          fill('Find substring with s.___.', ['find']),
          fill('Compare with operator==, returns ___.', ['bool']),
          mcq('std::string + char* yields:', ['Pointer', 'Concatenated string', 'Compile error', 'View'], 1, 'medium'),
          mcq('std::stoi parses:', ['Float', 'Int from string', 'Hash', 'Char'], 1, 'medium'),
        ]),      ],
    },
    {
      title: 'Variables & Types',
      description: 'Primitive types, sizes, casts, const.',
      exercises: [
        makeExercise('Types', [
          mcq('Typical size of int (most platforms):', ['2 bytes', '4 bytes', '8 bytes', '1 byte'], 1),
          mcq('Floating-point types:', ['int / long', 'float / double', 'char / bool', 'string / int'], 1),
          mcq('const variable means:', ['Compile error', 'Cannot be reassigned', 'Globally shared', 'Random'], 1),
          mcq('auto x = 3.14; deduces:', ['int', 'double', 'float', 'long'], 1),
          mcq('Boolean type:', ['boolean', 'bool', 'Bool', 'flag'], 1),
          mcq('Character type:', ['chr', 'char', 'character', 'byte'], 1),
          fill('Use ___ to print to standard output.', ['cout']),
          fill('Read input with ___.', ['cin']),
          mcq('static_cast<int>(3.7) is:', ['3', '4', '3.7', 'Error'], 0, 'medium'),
          mcq('size_t is typically:', ['Signed', 'Unsigned integer for sizes', 'Floating-point', 'Pointer'], 1, 'medium'),
        ]),
        makeExercise('Integer Types', [
          mcq('Min guaranteed bits for int:', ['8', '16', '32', '64'], 1),
          mcq('Fixed-width int 32-bit:', ['int32_t', 'int_fast32_t', 'long32', 'i32'], 0),
          mcq('Header for fixed-width ints:', ['<cstdint>', '<stdint.h> only', '<inttypes>', '<types>'], 0),
          mcq('Unsigned overflow is:', ['UB', 'Defined modular wrap', 'Implementation defined', 'Trap'], 1),
          mcq('Signed overflow is:', ['Defined wrap', 'Undefined behaviour', 'Saturating', 'Trap'], 1),
          mcq('long long is at least:', ['16 bits', '32 bits', '64 bits', '128 bits'], 2),
          fill('char may be signed or unsigned ___-defined.', ['implementation']),
          fill('Promotion to int happens for small ___ types.', ['integer']),
          mcq('uint8_t printed via cout prints as:', ['Number', 'Character (since alias of unsigned char)', 'Bits', 'Error'], 1, 'medium'),
          mcq('std::numeric_limits<int>::max() lives in:', ['<limits>', '<cmath>', '<cstdint>', '<bits>'], 0, 'medium'),
        ]),
        makeExercise('Floating Point', [
          mcq('Default float literal type:', ['float', 'double', 'long double', 'half'], 1),
          mcq('Float literal suffix:', ['f', 'd', 'l', 'g'], 0),
          mcq('IEEE 754 has:', ['One zero', 'Two zeros (+0/-0)', 'Three zeros', 'No zero'], 1),
          mcq('Compare doubles for equality:', ['==', '<= and >=', 'Within epsilon', 'Bitwise'], 2),
          mcq('NaN compared with itself:', ['true', 'false', 'crashes', 'undefined'], 1),
          mcq('std::isnan in:', ['<cmath>', '<float>', '<limits>', '<cstdint>'], 0),
          fill('long double precision is at least double ___.', ['precision']),
          fill('Round to int with ___().', ['std::round']),
          mcq('0.1 + 0.2 == 0.3 in IEEE doubles:', ['true', 'false', 'depends', 'NaN'], 1, 'medium'),
          mcq('std::numeric_limits<double>::infinity() requires:', ['has_infinity true', 'always exists', 'never exists', 'compile flag'], 0, 'medium'),
        ]),
        makeExercise('const & constexpr', [
          mcq('const int x = 5; allows:', ['Reassign', 'Read only', 'Mutate via ptr', 'Crash'], 1),
          mcq('constexpr requires value:', ['Runtime', 'Compile-time constant', 'Both', 'None'], 1),
          mcq('const member function promises:', ['No mutation of *this', 'Static dispatch', 'Inline', 'Throws'], 0),
          mcq('const int* p means:', ['Const pointer', 'Pointer to const int', 'Const ref', 'Both'], 1),
          mcq('int* const p means:', ['Pointer to const int', 'Const pointer to int', 'Const both', 'Reference'], 1),
          mcq('consteval (C++20) ensures:', ['Maybe runtime', 'Always compile-time eval', 'Inline only', 'Threads'], 1),
          fill('constinit ensures static ___ initialisation.', ['constant']),
          fill('A constexpr function may be called at compile or ___ time.', ['runtime']),
          mcq('mutable allows mutation in:', ['const member function', 'Globals', 'Macros', 'Loops'], 0, 'medium'),
          mcq('constexpr if is for:', ['Runtime branch', 'Templates branch elimination', 'Macros', 'Loops'], 1, 'medium'),
        ]),
        makeExercise('References', [
          mcq('Reference declaration:', ['int& r = x', 'int *r = x', 'int r&', 'ref<int>'], 0),
          mcq('References must be:', ['Optional', 'Initialised', 'Heap', 'Static'], 1),
          mcq('Re-binding references:', ['Allowed', 'Forbidden', 'With const', 'With move'], 1),
          mcq('const T& binds to temporary:', ['No', 'Yes (extends lifetime)', 'Crashes', 'UB'], 1),
          mcq('rvalue reference syntax:', ['T&', 'T&&', 'T*', '&&T'], 1),
          mcq('Pass-by-ref avoids:', ['Inheritance', 'Copies', 'Templates', 'Macros'], 1),
          fill('A reference is essentially an ___ for an object.', ['alias']),
          fill('Returning reference to local is ___.', ['UB']),
          mcq('std::ref creates a:', ['Pointer', 'reference_wrapper', 'Copy', 'Move'], 1, 'medium'),
          mcq('Forwarding reference T&& in template is:', ['Always rvalue ref', 'Universal ref', 'Const ref', 'Move only'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Control Flow & Functions',
      description: 'if/else, loops, function basics.',
      exercises: [
        makeExercise('Control & Functions', [
          mcq('Loop that runs at least once:', ['for', 'while', 'do-while', 'foreach'], 2),
          mcq('Range-based for needs:', ['Pointer', 'Container with begin/end', 'Macros', 'Globals'], 1),
          mcq('Pass by reference:', ['void f(int x)', 'void f(int& x)', 'void f(int* x) only', 'void f(const int)'], 1),
          mcq('Default arg in function:', ['void f(int x=0)', 'void f(int x:0)', 'void f(int x default 0)', 'void f(int x ?? 0)'], 0),
          mcq('Function overloading allows:', ['Same name, different signatures', 'Same signature, different return', 'Templates only', 'Globals only'], 0),
          mcq('inline keyword hints:', ['Threading', 'Compiler may inline', 'Recursion', 'Static'], 1),
          fill('Pass-by-value copies the ___.', ['argument']),
          fill('A function with no return type uses ___.', ['void']),
          mcq('Const reference avoids copy and forbids:', ['Reading', 'Writing', 'Both', 'Neither'], 1, 'medium'),
          mcq('Recursion base case must:', ['Recurse', 'Return without recursing', 'Throw', 'Loop'], 1, 'medium'),
        ]),
        makeExercise('Loops', [
          mcq('for(int i=0; i<n; ++i) prints n times where n=5:', ['4', '5', '6', '0'], 1),
          mcq('while(false) body runs:', ['1', '0', 'Inf', 'Error'], 1),
          mcq('do { } while(false) body runs:', ['0', '1', 'Inf', 'Error'], 1),
          mcq('break exits:', ['Whole function', 'Innermost loop/switch', 'All loops', 'Nothing'], 1),
          mcq('continue jumps to:', ['Loop end exit', 'Next iteration', 'Loop start exit', 'Function exit'], 1),
          mcq('Range-based for over vector v:', ['for(auto x : v)', 'foreach v', 'for x in v', 'iterate(v)'], 0),
          fill('Use for-each by const ref to avoid ___.', ['copy']),
          fill('Infinite loop pattern: for(;;) or while(___).', ['true']),
          mcq('Nested break needs:', ['One break', 'Goto / flag for outer', 'Throw', 'Return only'], 1, 'medium'),
          mcq('Loop unrolling improves:', ['Memory', 'Branch overhead', 'Linker speed', 'Threads'], 1, 'medium'),
        ]),
        makeExercise('Conditionals & switch', [
          mcq('switch works on:', ['Strings only', 'Integral / enum', 'Doubles', 'Vectors'], 1),
          mcq('Missing break causes:', ['Compile error', 'Fall-through', 'Crash', 'Loop'], 1),
          mcq('default label:', ['Optional, runs when no match', 'Mandatory', 'Forbidden', 'First'], 0),
          mcq('if constexpr is for:', ['Runtime branch', 'Compile-time branch in templates', 'Macros', 'Loops'], 1),
          mcq('Ternary operator:', ['?:', '::?', '<?>', '?if'], 0),
          mcq('[[fallthrough]] attribute (C++17):', ['Forces fall-through', 'Suppresses warnings about fall-through', 'Disables case', 'Forces break'], 1),
          fill('Compare floats with care due to ___ error.', ['rounding']),
          fill('Pattern: if (auto p = make(); p) limits scope to ___ block.', ['if']),
          mcq('Nested if-else can often be replaced by:', ['Macro', 'switch / map / polymorphism', 'goto', 'Lambda only'], 1, 'medium'),
          mcq('Short-circuit evaluation evaluates rhs:', ['Always', 'Only when needed', 'Never', 'Random'], 1, 'medium'),
        ]),
        makeExercise('Functions Deep Dive', [
          mcq('Function declaration vs definition:', ['Same thing', 'Decl announces; def implements', 'Def first only', 'Decl has body'], 1),
          mcq('Default arg location:', ['First arg only', 'From right to left consecutively', 'Anywhere', 'Forbidden'], 1),
          mcq('Function pointer type:', ['int (*fp)(int)', 'fp<int(int)>', 'fp = int->int', 'func<int>'], 0),
          mcq('Lambdas (C++11) capture by:', ['[=] / [&] / mixed', 'Globals only', 'Threads only', 'Macros'], 0),
          mcq('Recursion vs iteration:', ['Same always', 'Recursion uses call stack', 'Iteration uses heap', 'Both forbidden'], 1),
          mcq('std::function holds:', ['Any callable', 'Only fn ptrs', 'Only lambdas', 'Only methods'], 0),
          fill('inline + header lets a function avoid ___ violations.', ['ODR']),
          fill('A function template generates code at ___ time.', ['compile']),
          mcq('Returning a reference to a local variable is:', ['Safe', 'Undefined behaviour', 'Slow', 'Defined null'], 1, 'medium'),
          mcq('noexcept on a function:', ['Promises no throw', 'Forces throw', 'Disables exceptions globally', 'Inlines'], 0, 'medium'),
        ]),
        makeExercise('Scope & Lifetime', [
          mcq('Stack object lifetime ends at:', ['Program end', 'End of enclosing scope', 'Throw only', 'Never'], 1),
          mcq('Heap object freed by:', ['delete/delete[]', 'GC', 'OS only', 'free()'], 0),
          mcq('Static local initialised:', ['Each call', 'Once, thread-safe (C++11)', 'Never', 'Twice'], 1),
          mcq('Globals lifetime:', ['Per call', 'Whole program', 'Per scope', 'Per thread'], 1),
          mcq('Local variable shadowing:', ['Compile error', 'Allowed; warns', 'Linker error', 'Forbidden'], 1),
          mcq('thread_local lifetime:', ['Whole program', 'One per thread', 'Per call', 'Per object'], 1),
          fill('A dangling pointer points to ___ memory.', ['freed']),
          fill('A dangling reference is similarly ___.', ['UB']),
          mcq('Most-vexing-parse declares:', ['A variable', 'A function', 'A typedef', 'A namespace'], 1, 'medium'),
          mcq('Brace-init T x{} is preferred to T x() because:', ['No diff', 'Avoids most-vexing-parse', 'Faster', 'Allocates'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Arrays & Pointers',
      description: 'C-style arrays, pointers, references.',
      exercises: [
        makeExercise('Pointers', [
          mcq('Pointer declaration:', ['int p*;', 'int *p;', 'int& p;', 'pointer<int> p;'], 1),
          mcq('Address-of operator:', ['*', '&', '->', '@'], 1),
          mcq('Dereference operator:', ['*', '&', '->', '$'], 0),
          mcq('Null pointer (modern):', ['NULL', 'nullptr', '0', 'void'], 1),
          mcq('Array decays to:', ['Reference', 'Pointer to first element', 'Vector', 'Span'], 1),
          mcq('Reference must be:', ['Optionally bound', 'Bound at creation', 'Re-bindable', 'Heap-allocated'], 1),
          fill('sizeof yields a ___-time constant for arrays.', ['compile']),
          fill('new allocates on the ___.', ['heap']),
          mcq('delete[] is required for memory allocated with:', ['new T', 'new T[n]', 'malloc', 'stack'], 1, 'medium'),
          mcq('Reference vs pointer: a reference cannot:', ['Be reassigned', 'Be const', 'Refer to objects', 'Exist'], 0, 'medium'),
        ]),
        makeExercise('Arrays', [
          mcq('C-array of 5 ints:', ['int a[5];', 'int[5] a;', 'array<int>5 a;', 'int a(5);'], 0),
          mcq('Modern fixed-size array:', ['std::array<int,5>', 'std::vector<int>', 'std::list<int>', 'int*'], 0),
          mcq('Array index starts at:', ['0', '1', '-1', 'Custom'], 0),
          mcq('Bounds checking on a[i]:', ['Always', 'Never', 'Only with .at()', 'Only with debug'], 2),
          mcq('2D array int a[3][4] elements:', ['7', '12', '34', '4'], 1),
          mcq('std::array vs std::vector main diff:', ['Heap vs stack', 'Stack/static size vs heap dynamic', 'No diff', 'Vector is faster always'], 1),
          fill('std::vector grows on demand at the ___.', ['heap']),
          fill('Range loop preserves ___ of elements.', ['order']),
          mcq('Decay: passing int a[5] to function makes it:', ['int[5]', 'int*', 'std::array', 'reference'], 1, 'medium'),
          mcq('std::span (C++20) is:', ['Owning array', 'Non-owning view', 'Pointer pair only', 'String'], 1, 'medium'),
        ]),
        makeExercise('Pointer Arithmetic', [
          mcq('p + 1 advances by:', ['1 byte', 'sizeof(*p) bytes', '4 bytes always', '0'], 1),
          mcq('p - q for same array yields:', ['Pointer', 'ptrdiff_t (signed)', 'size_t', 'void'], 1),
          mcq('Comparing pointers from different arrays:', ['Defined', 'UB (except equality)', 'Always equal', 'Crashes'], 1),
          mcq('Past-the-end pointer is:', ['Invalid to dereference', 'Valid to dereference', 'Always nullptr', 'Random'], 0),
          mcq('void* arithmetic:', ['Allowed', 'Not allowed in standard C++', 'Same as char*', 'Same as int*'], 1),
          mcq('Array name inside expression decays to:', ['nullptr', 'Pointer to first', 'Reference', 'Size'], 1),
          fill('std::distance gives ptrdiff_t between two ___.', ['iterators']),
          fill('std::advance moves an iterator by ___ steps.', ['n']),
          mcq('a[i] is equivalent to:', ['*(a+i)', 'a.at(i)', 'a.get(i)', 'a->i'], 0, 'medium'),
          mcq('1[a] is:', ['Compile error', 'Same as a[1]', 'UB', 'Type mismatch'], 1, 'medium'),
        ]),
        makeExercise('new / delete & RAII', [
          mcq('Allocate single int on heap:', ['new int', 'malloc(int)', 'alloc<int>', 'std::heap<int>'], 0),
          mcq('Free with new[]:', ['delete', 'delete[]', 'free', 'destroy'], 1),
          mcq('Mismatched delete is:', ['Defined', 'UB', 'Logged', 'Throws'], 1),
          mcq('Smart pointer for unique ownership:', ['unique_ptr', 'shared_ptr', 'weak_ptr', 'auto_ptr'], 0),
          mcq('make_unique<T>(args...) replaces:', ['new T(args)', 'malloc(T)', 'shared_ptr', 'static_cast'], 0),
          mcq('RAII binds resources to:', ['Globals', 'Object lifetime', 'Threads', 'Files only'], 1),
          fill('Smart pointers live in <___>.', ['memory']),
          fill('shared_ptr uses ___ counting.', ['reference']),
          mcq('Calling delete on already-deleted ptr:', ['Safe', 'UB', 'Throws', 'No-op'], 1, 'medium'),
          mcq('Storing ints in vector vs new int[]:', ['Same', 'Vector handles RAII automatically', 'Vector slower always', 'Vector limited to small'], 1, 'medium'),
        ]),
        makeExercise('References vs Pointers', [
          mcq('Reference syntax:', ['int& r = x', 'int *r = &x', 'ref<int>', 'int@ r = x'], 0),
          mcq('Null reference:', ['Allowed', 'Not allowed (must bind)', 'Sometimes', 'Yes via cast'], 1),
          mcq('Pointer can be null:', ['Yes', 'No', 'Only if const', 'Only if static'], 0),
          mcq('Reference re-binding:', ['Allowed', 'Forbidden', 'With move', 'With const'], 1),
          mcq('Use reference when:', ['Optionality needed', 'Always-bound non-null aliasing', 'Polymorphism only', 'Threads only'], 1),
          mcq('Use pointer when:', ['Optional / re-bind / arrays', 'Aliasing only', 'Const only', 'Stack only'], 0),
          fill('& on a function param means pass-by-___.', ['reference']),
          fill('* in a declaration vs expression has different ___.', ['meaning']),
          mcq('Reference to a temporary lifetime:', ['Lasts forever', 'Extended to ref lifetime if const lvalue ref', 'Crashes', 'UB always'], 1, 'medium'),
          mcq('std::reference_wrapper allows:', ['Storing references in containers', 'Casting', 'Threads', 'Move only'], 0, 'medium'),
        ]),
      ],
    },
  ],

  2: [
    {
      title: 'OOP Basics',
      description: 'Classes, members, constructors and access.',
      exercises: [
        makeExercise('Classes', [
          mcq('Default access in class:', ['public', 'private', 'protected', 'internal'], 1),
          mcq('Default access in struct:', ['public', 'private', 'protected', 'package'], 0),
          mcq('Constructor with no args:', ['Copy constructor', 'Default constructor', 'Move constructor', 'Destructor'], 1),
          mcq('~ClassName() is:', ['Constructor', 'Destructor', 'Operator', 'Friend'], 1),
          mcq('Member init list precedes:', ['Body', 'Class', 'Header', 'Destructor'], 0),
          mcq('this is:', ['Pointer to current object', 'Reference to class', 'Macro', 'Reserved future'], 0),
          fill('Encapsulation hides ___ details.', ['implementation']),
          fill('A class can declare a ___ to grant access.', ['friend']),
          mcq('Copy constructor signature:', ['T(T)', 'T(const T&)', 'T(T&&)', 'T(T*)'], 1, 'medium'),
          mcq('Rule of three concerns:', ['Loops', 'Copy ctor / copy assign / dtor', 'Templates', 'Threads'], 1, 'medium'),
        ]),
        makeExercise('Constructors', [
          mcq('Default constructor:', ['T()', 'T(T&)', 'T(T&&)', '~T()'], 0),
          mcq('Member init list runs:', ['Before body', 'After body', 'Never', 'Twice'], 0),
          mcq('Delegating constructor:', ['T(): T(0) {}', 'T() => T(0)', 'T() : default', 'T() ext T(0)'], 0),
          mcq('=default forces:', ['Compiler-generated version', 'Pure virtual', 'Inline', 'Static'], 0),
          mcq('=delete forbids:', ['Calls', 'Compile time use of that overload', 'Virtual dispatch', 'Inheritance'], 1),
          mcq('explicit prevents:', ['Inheritance', 'Implicit conversions via ctor', 'Move', 'Copy'], 1),
          fill('Constructor with one non-explicit arg can be used for ___ conversion.', ['implicit']),
          fill('A class with no user-declared ctors gets a synthesised ___.', ['default']),
          mcq('Throwing in a constructor:', ['Object considered constructed', 'Object never fully constructed', 'Always crashes', 'Lost'], 1, 'medium'),
          mcq('In-class member initialiser (C++11) sets default for:', ['Static only', 'Non-static data members', 'Globals', 'Locals'], 1, 'medium'),
        ]),
        makeExercise('Access & Encapsulation', [
          mcq('private members visible to:', ['Anyone', 'Class itself + friends', 'Subclass', 'Globals'], 1),
          mcq('protected members visible to:', ['Class only', 'Class + derived', 'Anyone', 'Friends only'], 1),
          mcq('public:', ['Anyone', 'Class only', 'Friends only', 'Same package'], 0),
          mcq('Friend declaration:', ['friend class X', 'extern class X', 'open class X', 'export X'], 0),
          mcq('Getters/setters provide:', ['Direct access', 'Controlled access', 'Inheritance', 'Threads'], 1),
          mcq('Encapsulation goal:', ['Performance', 'Hide invariants', 'Save memory', 'Improve syntax'], 1),
          fill('Class members default to ___ access.', ['private']),
          fill('Struct members default to ___ access.', ['public']),
          mcq('Friendship is:', ['Inherited', 'Not inherited', 'Transitive', 'Reciprocal'], 1, 'medium'),
          mcq('protected inheritance changes public base members to:', ['Public', 'Protected', 'Private', 'Hidden'], 1, 'medium'),
        ]),
        makeExercise('Operator Overloading', [
          mcq('Overload + as member:', ['T operator+(const T&) const', 'T add(T)', '+(T,T)', 'op+(T)'], 0),
          mcq('Free-function operator+ benefits from:', ['Symmetry of operands', 'Threading', 'Inheritance', 'Macros'], 0),
          mcq('operator<< for streams typically:', ['Member', 'Free function', 'Friend free function often', 'Static member'], 2),
          mcq('operator= must:', ['Be member', 'Be virtual', 'Be friend', 'Be free'], 0),
          mcq('Spaceship operator (C++20):', ['<=>', '=>', '<>', '?='], 0),
          mcq('Returning *this from operator= enables:', ['Chaining', 'Inheritance', 'Move', 'Threads'], 0),
          fill('User-defined literal operator: operator___.', ['""']),
          fill('Conversion operator: operator T() const returns ___.', ['T']),
          mcq('++pre vs post: post-increment usually returns:', ['Reference', 'Old value by value', 'Pointer', 'Void'], 1, 'medium'),
          mcq('operator[] in const context returns:', ['T&', 'const T&', 'T*', 'void'], 1, 'medium'),
        ]),
        makeExercise('Static & Friend', [
          mcq('Static data member is:', ['Per instance', 'Shared by class', 'Per thread', 'Per call'], 1),
          mcq('Define static data member outside class:', ['Required (pre-C++17)', 'Forbidden', 'Optional', 'Auto generated always'], 0),
          mcq('inline static data member (C++17):', ['Forbidden', 'Allowed; defines in class', 'Threads only', 'Local only'], 1),
          mcq('Static member function:', ['Has this', 'No this', 'Virtual only', 'Friend only'], 1),
          mcq('friend can be:', ['class or function', 'macro', 'namespace', 'template only'], 0),
          mcq('Granting friend gives access to:', ['public only', 'private/protected too', 'protected only', 'nothing'], 1),
          fill('A static member can access ___ members directly.', ['static']),
          fill('A friend declaration is part of the class ___.', ['interface']),
          mcq('Static const integral member can be initialised in-class:', ['Always', 'Yes (with constexpr/static const)', 'Never', 'Only externally'], 1, 'medium'),
          mcq('friend functions defined inside class are:', ['Members', 'Free functions found by ADL', 'Virtual', 'Templates only'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Inheritance & Polymorphism',
      description: 'Virtual functions, vtables and overriding.',
      exercises: [
        makeExercise('Polymorphism', [
          mcq('Virtual function dispatch is:', ['Static', 'Dynamic', 'Compile-time', 'Hashed'], 1),
          mcq('Mark override safety with:', ['final', 'override', 'sealed', 'virtualOnly'], 1),
          mcq('Abstract method declared with:', ['= delete', '= 0', '= abstract', 'abstract'], 1),
          mcq('Without virtual destructor in base, deleting derived via base ptr is:', ['Safe', 'Undefined behaviour', 'Same', 'Forbidden by compiler'], 1),
          mcq('Multiple inheritance is:', ['Forbidden', 'Allowed', 'Only single', 'Only with interfaces'], 1),
          mcq('Diamond problem solved with:', ['final', 'virtual inheritance', 'private', 'mutex'], 1),
          fill('A pure virtual class is ___.', ['abstract']),
          fill('Slicing happens when assigning derived to base by ___.', ['value']),
          mcq('dynamic_cast on a non-polymorphic class is:', ['Allowed', 'Compile error', 'Undefined', 'Same as static_cast'], 1, 'medium'),
          mcq('Final class cannot be:', ['Constructed', 'Inherited from', 'Used', 'Linked'], 1, 'medium'),
        ]),
        makeExercise('Virtual Functions', [
          mcq('Virtual dispatch uses:', ['Macros', 'vtable / vptr', 'Templates', 'Hash'], 1),
          mcq('Mark abstract method:', ['= 0', '= delete', 'abstract', 'pure'], 0),
          mcq('override keyword:', ['Optional but recommended', 'Mandatory', 'Forbidden', 'Compile-time only on templates'], 0),
          mcq('final on virtual function:', ['Allows override', 'Forbids further override', 'Inherits', 'Inlines'], 1),
          mcq('Calling virtual in constructor calls:', ['Most-derived', 'Static (current class)', 'Pure', 'UB'], 1),
          mcq('Default arg on virtual fn:', ['Looks up dynamically', 'Statically (base type)', 'Both', 'Forbidden'], 1),
          fill('Virtual dispatch costs an extra ___ lookup.', ['vtable']),
          fill('Non-virtual interface idiom uses public non-virtual + private ___.', ['virtual']),
          mcq('Virtual destructor in base lets you delete derived via base ptr:', ['Always UB', 'Safely', 'Crashes', 'Same as non-virtual'], 1, 'medium'),
          mcq('Devirtualization optimisation requires:', ['Final hint or known dynamic type', 'Macros', 'Templates only', 'Threads'], 0, 'medium'),
        ]),
        makeExercise('Abstract & Interfaces', [
          mcq('Abstract class has:', ['No virtual', 'At least one pure virtual', 'No methods', 'No data'], 1),
          mcq('Cannot instantiate:', ['Final class', 'Abstract class', 'Empty class', 'Concrete class'], 1),
          mcq('Pure virtual + body allowed:', ['No', 'Yes (call via Base::fn)', 'Compile error', 'Linker error only'], 1),
          mcq('Interface in C++ commonly:', ['Class with all =0 methods + virtual dtor', 'Struct only', 'Macro', 'Concept only'], 0),
          mcq('Multiple inheritance for interfaces is:', ['Forbidden', 'Common idiom', 'Slow always', 'Templates only'], 1),
          mcq('Marker interfaces in C++ usually use:', ['Empty class', 'Tag types', 'Both', 'Macros'], 2),
          fill('virtual + =0 declares a ___ method.', ['pure']),
          fill('Implementing interfaces requires overriding all ___ functions.', ['pure']),
          mcq('Diamond w/ virtual base ensures:', ['Two base copies', 'Single shared base subobject', 'Crash', 'Slicing'], 1, 'medium'),
          mcq('CRTP achieves:', ['Static polymorphism', 'Dynamic dispatch', 'Templates of macros', 'Threads'], 0, 'medium'),
        ]),
        makeExercise('Slicing & Casts', [
          mcq('Object slicing happens when:', ['Cast pointer', 'Assign derived to base by value', 'Move', 'Throw'], 1),
          mcq('Avoid slicing by:', ['Pass by ref/ptr', 'Always copy', 'Inline', 'Macros'], 0),
          mcq('dynamic_cast checks at:', ['Compile time', 'Runtime', 'Link time', 'Never'], 1),
          mcq('static_cast performs:', ['Runtime check', 'Compile-time cast (no rtti)', 'Both', 'Bit copy only'], 1),
          mcq('reinterpret_cast is for:', ['Reinterpreting bits', 'Type-safe conversions', 'Up-casts', 'Polymorphism'], 0),
          mcq('const_cast removes:', ['Type', 'const/volatile', 'Inheritance', 'References'], 1),
          fill('dynamic_cast with reference fails by ___.', ['throwing']),
          fill('typeid lives in <___>.', ['typeinfo']),
          mcq('dynamic_cast<Derived*>(basePtr) returns nullptr if:', ['Always', 'Type mismatch', 'Always succeeds', 'Compile error'], 1, 'medium'),
          mcq('Down-casting without RTTI is best done via:', ['static_cast (when type known)', 'reinterpret_cast', 'C-style cast only', 'malloc'], 0, 'medium'),
        ]),
        makeExercise('Multiple Inheritance', [
          mcq('Syntax:', ['class C: public A, public B', 'class C ext A,B', 'class C : A & B', 'class C(A,B)'], 0),
          mcq('Diamond inheritance solved with:', ['final', 'virtual base', 'private', 'mutex'], 1),
          mcq('Ambiguous member access fixed by:', ['Renaming', 'Qualified scope (Base::x)', 'Macros', 'Templates'], 1),
          mcq('vptr per:', ['Class', 'Polymorphic base subobject', 'Function', 'Translation unit'], 1),
          mcq('Mixins typically inherit:', ['Privately', 'Publicly', 'Virtually', 'Friend'], 1),
          mcq('CRTP requires inheritance from:', ['Self template instantiation', 'Concrete base', 'Macro', 'Friend'], 0),
          fill('Layout of multi-inherited objects is ___-dependent.', ['ABI']),
          fill('Empty base optimisation reduces size of empty ___.', ['bases']),
          mcq('Casting between siblings via base:', ['static_cast directly', 'dynamic_cast on polymorphic', 'C cast', 'reinterpret'], 1, 'medium'),
          mcq('Virtual inheritance imposes:', ['Lower cost', 'Extra indirection', 'No cost', 'Compile error'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Templates & STL',
      description: 'Generic programming and standard containers.',
      exercises: [
        makeExercise('STL Containers', [
          mcq('Dynamic array:', ['array', 'vector', 'list', 'deque'], 1),
          mcq('Doubly-linked list:', ['list', 'vector', 'forward_list', 'array'], 0),
          mcq('Hash map:', ['map', 'unordered_map', 'set', 'multimap'], 1),
          mcq('Sorted map (RB tree):', ['unordered_map', 'map', 'list', 'array'], 1),
          mcq('FIFO container adapter:', ['stack', 'queue', 'priority_queue', 'list'], 1),
          mcq('LIFO container adapter:', ['queue', 'stack', 'deque', 'vector'], 1),
          fill('std::vector grows by reallocating with amortised ___.', ['O(1)']),
          fill('std::array has size known at ___ time.', ['compile']),
          mcq('Average lookup of unordered_map:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 0, 'medium'),
          mcq('Iterator invalidation on vector push_back may occur on:', ['Every call', 'Reallocation', 'Never', 'Only erase'], 1, 'medium'),
        ]),
        makeExercise('Templates', [
          mcq('Template function header:', ['template<typename T>', 'generic<T>', 'using T', 'def<T>'], 0),
          mcq('Template specialisation lets you:', ['Disable templates', 'Customise for a specific type', 'Force inheritance', 'Use macros'], 1),
          mcq('SFINAE means:', ['Static fail not error', 'Substitution Failure Is Not An Error', 'Stack Frame Inline Auto Expand', 'Standard Function Init'], 1),
          mcq('Variadic templates use:', ['template<T...>', 'template<typename... Ts>', 'template<list T>', 'template<va_list>'], 1),
          mcq('Type deduction for `auto x = {1,2,3};`:', ['vector<int>', 'std::initializer_list<int>', 'array<int,3>', 'int[3]'], 1),
          mcq('Concepts (C++20) constrain:', ['Macros', 'Templates', 'Pointers', 'Threads'], 1),
          fill('decltype(expr) yields the ___ of expr.', ['type']),
          fill('Templates are instantiated at ___ time.', ['compile']),
          mcq('Function template overloading vs class template specialisation: function templates support:', ['Partial specialisation', 'Only full specialisation (use overloads)', 'Neither', 'Both unconditionally'], 1, 'medium'),
          mcq('std::enable_if is used for:', ['Threading', 'Conditional template instantiation', 'I/O', 'Hashing'], 1, 'medium'),
        ]),
        makeExercise('STL Algorithms', [
          mcq('Sort range:', ['std::sort(b,e)', 'sort_range(b,e)', 'sortAll(b,e)', 'std::order(b,e)'], 0),
          mcq('Find first match:', ['std::find', 'std::search_first', 'std::contains', 'std::indexOf'], 0),
          mcq('Count matches:', ['std::count / count_if', 'std::find_if', 'std::tally', 'std::sum'], 0),
          mcq('Transform a range:', ['std::transform', 'std::map_range', 'std::apply_each', 'std::for_each only'], 0),
          mcq('Accumulate sums values in:', ['<numeric>', '<algorithm>', '<vector>', '<utility>'], 0),
          mcq('Stable sort:', ['std::stable_sort', 'std::sort with flag', 'std::nth_sort', 'std::ordered_sort'], 0),
          fill('std::for_each iterates with a ___.', ['callback']),
          fill('std::ranges::sort comes from C++___.', ['20']),
          mcq('std::sort complexity:', ['O(n)', 'O(n log n) average/worst', 'O(n²)', 'O(log n)'], 1, 'medium'),
          mcq('std::partition partitions in:', ['Stable', 'Linear, no stability guarantee', 'Quadratic', 'Logarithmic'], 1, 'medium'),
        ]),
        makeExercise('Iterators', [
          mcq('Random-access iterator example:', ['std::list', 'std::vector', 'std::map', 'std::forward_list'], 1),
          mcq('begin/end yield iterators forming a ___ range.', ['Empty', 'Half-open [begin,end)', 'Closed', 'Reverse'], 1),
          mcq('cbegin returns:', ['Mutable iterator', 'const_iterator', 'reverse_iterator', 'pointer'], 1),
          mcq('Reverse iteration:', ['rbegin/rend', 'reverse(begin,end)', 'rev(b,e)', 'iterator-1'], 0),
          mcq('Iterator categories include:', ['Input/Output/Forward/Bidirectional/RandomAccess', 'Just one', 'Const/Mutable only', 'Lazy/Eager'], 0),
          mcq('Iterator invalidation rules differ per:', ['Container', 'Algorithm', 'Compiler', 'Optimization'], 0),
          fill('std::distance counts iterator ___.', ['steps']),
          fill('std::next advances iterator by ___ steps.', ['n']),
          mcq('Inserting into a vector may invalidate iterators when:', ['Always', 'Reallocation due to capacity', 'Never', 'Only with reserve'], 1, 'medium'),
          mcq('Stream iterators (istream_iterator) are:', ['Random access', 'Input iterators', 'Bidirectional', 'Forward'], 1, 'medium'),
        ]),
        makeExercise('Smart Containers', [
          mcq('Hash set:', ['std::set', 'std::unordered_set', 'std::list', 'std::multiset'], 1),
          mcq('Multimap allows:', ['Unique keys', 'Duplicate keys', 'No keys', 'Sorted by value'], 1),
          mcq('Container for fixed-size compile-time array:', ['std::vector', 'std::array', 'std::deque', 'std::list'], 1),
          mcq('std::deque supports:', ['Random access push_front/back O(1)', 'Only push_back', 'Linked nodes', 'Tree'], 0),
          mcq('std::priority_queue is a ___ heap by default.', ['Min', 'Max', 'Sorted', 'Random'], 1),
          mcq('std::span (C++20):', ['Owns memory', 'Non-owning view of contiguous range', 'Linked list', 'Tree'], 1),
          fill('Sorted containers use ___ tree typically.', ['red-black']),
          fill('Hash containers store buckets indexed by ___ value.', ['hash']),
          mcq('emplace vs insert:', ['Same', 'emplace constructs in place', 'insert constructs in place', 'emplace copies always'], 1, 'medium'),
          mcq('std::flat_map (C++23):', ['Sorted vector-backed map', 'Hash map', 'Tree map', 'Linked list'], 0, 'medium'),
        ]),
      ],
    },
  ],

  3: [
    {
      title: 'Modern Memory Model',
      description: 'RAII, smart pointers, move semantics.',
      exercises: [
        makeExercise('Smart Pointers & RAII', [
          mcq('RAII ties resource lifetime to:', ['Heap', 'Object lifetime', 'Threads', 'Files'], 1),
          mcq('Owning unique resource:', ['shared_ptr', 'unique_ptr', 'weak_ptr', 'auto_ptr'], 1),
          mcq('Reference-counted ownership:', ['shared_ptr', 'unique_ptr', 'weak_ptr', 'raw ptr'], 0),
          mcq('weak_ptr is used to break:', ['Recursion', 'Reference cycles', 'Threads', 'Inheritance'], 1),
          mcq('std::move converts to:', ['lvalue', 'rvalue (xvalue)', 'reference', 'pointer'], 1),
          mcq('Move constructor signature:', ['T(T)', 'T(const T&)', 'T(T&&)', 'T(T*)'], 2),
          fill('Rule of five adds move ctor and move ___.', ['assignment']),
          fill('make_unique avoids manual ___.', ['new']),
          mcq('After std::move(x), x is:', ['Destroyed', 'Valid but unspecified', 'Same as before', 'nullptr'], 1, 'medium'),
          mcq('shared_ptr control block holds:', ['Strong + weak counts', 'Hash', 'Mutex only', 'Type info only'], 0, 'medium'),
        ]),
        makeExercise('Move Semantics', [
          mcq('rvalue reference syntax:', ['T&', 'T&&', 'T*', '&T'], 1),
          mcq('std::move actually:', ['Moves data', 'Casts to xvalue', 'Copies', 'Destroys'], 1),
          mcq('Move ctor signature:', ['T(const T&)', 'T(T&&) noexcept', 'T(T*)', 'T(T)'], 1),
          mcq('After move, source object is in:', ['Original state', 'Valid but unspecified', 'Destroyed', 'nullptr'], 1),
          mcq('std::forward preserves:', ['Const', 'Value category in templates', 'References only', 'Pointers'], 1),
          mcq('Universal/forwarding reference is:', ['T&', 'T&& in deduced template context', 'const T&', 'auto'], 1),
          fill('Move assignment usually returns *___.', ['this']),
          fill('noexcept on move enables vector to use moves on ___.', ['reallocation']),
          mcq('Returning by value of local enables:', ['Always copy', 'NRVO/move elision', 'UB', 'Slicing'], 1, 'medium'),
          mcq('std::move on a const T:', ['Moves', 'Becomes a copy (const lvalue ref)', 'Crashes', 'Throws'], 1, 'medium'),
        ]),
        makeExercise('unique_ptr', [
          mcq('unique_ptr ownership is:', ['Shared', 'Exclusive', 'None', 'Reference counted'], 1),
          mcq('Copy unique_ptr:', ['Allowed', 'Forbidden', 'Deep copy', 'Reference'], 1),
          mcq('Transfer ownership:', ['= other', 'std::move(other)', 'copy(other)', 'share(other)'], 1),
          mcq('Custom deleter:', ['unique_ptr<T, D>', 'unique_ptr<T>::deleter', 'D(unique_ptr<T>)', 'Forbidden'], 0),
          mcq('release() does:', ['Frees memory', 'Returns raw ptr & gives up ownership', 'Locks', 'Resets'], 1),
          mcq('reset(p) does:', ['Frees old & owns new', 'Frees only', 'Owns only', 'Steals'], 0),
          fill('make_unique avoids the use of ___.', ['new']),
          fill('unique_ptr is ___ in size like a raw pointer (default deleter).', ['same']),
          mcq('Pass unique_ptr by value transfers ownership; by ref:', ['Borrows without ownership change', 'Crashes', 'Always copies', 'UB'], 0, 'medium'),
          mcq('Array unique_ptr:', ['unique_ptr<T[]>', 'unique_ptr<T,arr>', 'unique_array<T>', 'arr_ptr<T>'], 0, 'medium'),
        ]),
        makeExercise('shared_ptr & weak_ptr', [
          mcq('shared_ptr increments count on:', ['Move', 'Copy', 'Both', 'Neither'], 1),
          mcq('shared_ptr decrements on:', ['Destroy/reset', 'Copy', 'Move only', 'Never'], 0),
          mcq('Atomic ref count makes copy:', ['Free', 'Have synchronisation cost', 'UB', 'Same as raw'], 1),
          mcq('Cycle of shared_ptrs causes:', ['Crash', 'Memory leak', 'Faster', 'No effect'], 1),
          mcq('Break cycles with:', ['weak_ptr', 'unique_ptr', 'raw ptr', 'auto'], 0),
          mcq('weak_ptr.lock() returns:', ['shared_ptr (maybe empty)', 'unique_ptr', 'raw ptr', 'optional<T>'], 0),
          fill('make_shared allocates control block + object in ___ allocation.', ['one']),
          fill('enable_shared_from_this lets methods get a ___ to themselves.', ['shared_ptr']),
          mcq('Storing shared_ptr in container vs unique_ptr:', ['shared has overhead but copyable', 'No diff', 'unique copyable too', 'shared faster'], 0, 'medium'),
          mcq('weak_ptr alone cannot:', ['Lock to shared', 'Dereference directly', 'Expire check', 'Construct'], 1, 'medium'),
        ]),
        makeExercise('Allocators & Memory Layout', [
          mcq('Default allocator:', ['std::allocator<T>', 'malloc only', 'std::heap', 'sbrk'], 0),
          mcq('Pimpl idiom hides:', ['Inheritance', 'Implementation in .cpp', 'Templates', 'Threads'], 1),
          mcq('Polymorphic allocator (C++17):', ['<memory_resource>', '<allocator>', '<new>', '<thread>'], 0),
          mcq('Placement new constructs:', ['On heap', 'At given address', 'On stack', 'Random'], 1),
          mcq('Aligned allocation (C++17):', ['std::aligned_alloc', 'aligned_new', 'malloc_aligned', 'new(align,T)'], 0),
          mcq('Empty Base Optimisation reduces size when:', ['Base has no data', 'Always', 'Virtual base', 'Final base'], 0),
          fill('std::pmr provides ___ memory resources.', ['polymorphic']),
          fill('Trivial destructor lets the compiler skip ___ on exit.', ['cleanup']),
          mcq('Object lifetime starts after constructor returns and ends:', ['At delete', 'When destructor begins', 'Never', 'On move'], 1, 'medium'),
          mcq('Strict aliasing rule prohibits:', ['Aliasing same-type', 'Aliasing through unrelated types', 'Pointer arith', 'Move'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Concurrency',
      description: 'Threads, mutexes, atomics, async.',
      exercises: [
        makeExercise('Threads', [
          mcq('Standard thread type:', ['std::thread', 'std::task', 'std::pthread', 'std::process'], 0),
          mcq('Mutual exclusion lock:', ['std::lock', 'std::mutex', 'std::sync', 'std::guard'], 1),
          mcq('RAII mutex helper:', ['lock_guard', 'mutex_lock', 'sync', 'auto_lock'], 0),
          mcq('Atomic types live in:', ['<atomic>', '<thread>', '<mutex>', '<future>'], 0),
          mcq('std::async returns a:', ['thread', 'future', 'promise', 'mutex'], 1),
          mcq('A data race is:', ['Two reads', 'Concurrent unsynchronised read & write', 'Single thread bug', 'Compile error'], 1),
          fill('std::condition_variable needs an associated ___.', ['mutex']),
          fill('memory_order_relaxed gives no ___ guarantees.', ['ordering']),
          mcq('std::jthread differs from std::thread by:', ['Faster', 'Auto-joins on destruction & supports stop_token', 'Detached', 'Single core'], 1, 'medium'),
          mcq('Spurious wakeup is handled by:', ['Single if', 'A loop that re-checks the predicate', 'Ignoring it', 'Locking twice'], 1, 'medium'),
        ]),
        makeExercise('Mutexes & Locks', [
          mcq('Recursive lock:', ['std::mutex', 'std::recursive_mutex', 'std::shared_mutex', 'std::lock_guard'], 1),
          mcq('Reader-writer lock:', ['std::shared_mutex (C++17)', 'std::mutex', 'std::recursive_mutex', 'std::semaphore'], 0),
          mcq('RAII helper that allows manual unlock:', ['lock_guard', 'unique_lock', 'shared_lock only', 'scoped_lock'], 1),
          mcq('Lock multiple mutexes deadlock-free:', ['std::lock(a,b)', 'a.lock(); b.lock();', 'mutex.lock_all', 'sync_lock'], 0),
          mcq('scoped_lock (C++17) is:', ['Single mutex only', 'Variadic deadlock-free', 'Recursive only', 'Reader-writer'], 1),
          mcq('Try-lock returns:', ['void', 'bool indicating success', 'mutex', 'thread'], 1),
          fill('Unlock count must equal lock count for ___ mutex.', ['recursive']),
          fill('Holding a lock across user callbacks is generally a ___ idea.', ['bad']),
          mcq('Deadlock requires ≥ how many resources?', ['1', '2', '3', '4'], 1, 'medium'),
          mcq('Priority inversion happens when:', ['Higher prio waits on lower prio holder', 'Threads same prio', 'No locks held', 'GC running'], 0, 'medium'),
        ]),
        makeExercise('Atomics & Memory Order', [
          mcq('std::atomic<int> guarantees:', ['Compare-and-swap', 'Atomic load/store', 'Both', 'Neither'], 2),
          mcq('Default memory order:', ['relaxed', 'seq_cst', 'acquire', 'release'], 1),
          mcq('Acquire/release pair establishes:', ['Total order', 'Happens-before across threads', 'Nothing', 'Crash'], 1),
          mcq('relaxed gives:', ['No ordering, only atomicity', 'Full ordering', 'Acquire only', 'Release only'], 0),
          mcq('Compare-exchange returns:', ['void', 'bool indicating success', 'old value', 'new value'], 1),
          mcq('std::atomic_flag is:', ['General atomic', 'Lock-free spin primitive', 'Mutex alias', 'Counter'], 1),
          fill('std::memory_order has values relaxed, consume, acquire, release, acq_rel, ___.', ['seq_cst']),
          fill('Lock-free does not necessarily mean ___-free.', ['wait']),
          mcq('atomic<T> for non-trivial T may use:', ['Always lock-free', 'Internal lock', 'CAS only', 'Mutex always'], 1, 'medium'),
          mcq('Memory fences are:', ['std::atomic_thread_fence', 'memory.barrier', 'fence_t', '__sync_barrier only'], 0, 'medium'),
        ]),
        makeExercise('Async & Futures', [
          mcq('std::async returns:', ['std::future<T>', 'std::promise<T>', 'std::packaged_task', 'std::thread'], 0),
          mcq('future.get() blocks until:', ['Thread starts', 'Result ready', 'Lock free', 'Timeout always'], 1),
          mcq('shared_future allows:', ['Multiple gets', 'Single get', 'No get', 'Move only'], 0),
          mcq('std::promise.set_value broadcasts to:', ['Future', 'Mutex', 'Lock', 'Atomic'], 0),
          mcq('packaged_task wraps:', ['Function as future-yielding task', 'Mutex', 'Future', 'Thread'], 0),
          mcq('Launch policy std::launch::async forces:', ['New thread', 'Deferred lazy', 'Same thread', 'Random'], 0),
          fill('When future is destroyed, std::async with default policy may ___ in destructor.', ['block']),
          fill('std::future<void> represents an async ___ result.', ['void']),
          mcq('promise.set_exception stores:', ['Result', 'Exception to be re-thrown on get', 'Mutex', 'Thread'], 1, 'medium'),
          mcq('std::when_all / when_any are in proposals as part of:', ['Concurrency TS', 'Network TS', 'Ranges TS', 'Modules'], 0, 'medium'),
        ]),
        makeExercise('Parallel Algorithms', [
          mcq('Parallel STL execution policy header:', ['<execution>', '<parallel>', '<thread>', '<atomic>'], 0),
          mcq('Sequential policy:', ['std::execution::seq', 'std::execution::par', 'std::execution::par_unseq', 'std::execution::unseq'], 0),
          mcq('Parallel:', ['par', 'seq', 'unseq', 'all'], 0),
          mcq('Parallel + vectorised:', ['par_unseq', 'par', 'seq', 'unseq'], 0),
          mcq('Race in user predicate:', ['Allowed', 'Programmer responsibility to avoid', 'Auto serialised', 'Crashes'], 1),
          mcq('std::reduce vs std::accumulate:', ['Same', 'reduce may run unordered/parallel', 'reduce sequential only', 'reduce only floats'], 1),
          fill('std::for_each with par may run callbacks in any ___.', ['order']),
          fill('Parallel algorithms first added in C++___.', ['17']),
          mcq('Throwing inside parallel algorithm:', ['Behaves like sequential', 'Calls std::terminate', 'Catches automatically', 'Logs'], 1, 'medium'),
          mcq('Implementation backend may be:', ['TBB', 'OpenMP', 'Vendor-specific', 'Any of these'], 3, 'medium'),
        ]),
      ],
    },
    {
      title: 'Modern C++ Features',
      description: 'Lambdas, ranges, constexpr, modules.',
      exercises: [
        makeExercise('C++17/20', [
          mcq('Lambda expression syntax starts with:', ['[]', '<>', '{}', '()'], 0),
          mcq('Lambda capture by value:', ['[&]', '[=]', '[*]', '[+]'], 1),
          mcq('constexpr function is evaluated at:', ['Runtime only', 'Compile time when possible', 'Link time', 'Never'], 1),
          mcq('Structured bindings (C++17) destructure:', ['Pointers', 'Tuples / pairs / structs', 'Functions', 'Macros'], 1),
          mcq('std::optional represents:', ['Definitely has value', 'Maybe-has-value', 'Reference', 'Pointer'], 1),
          mcq('std::variant is a:', ['Type-safe union', 'Tuple', 'List', 'Pointer'], 0),
          fill('Ranges (C++20) compose with the ___ operator.', ['|']),
          fill('Modules replace many uses of header ___.', ['files']),
          mcq('consteval enforces evaluation at:', ['Runtime', 'Compile time mandatorily', 'Both', 'Never'], 1, 'medium'),
          mcq('constexpr if is used to:', ['Branch at runtime', 'Conditionally compile template branches', 'Replace if', 'Replace switch'], 1, 'medium'),
        ]),
        makeExercise('Performance & Idioms', [
          mcq('Pass large object as:', ['By value', 'const T&', 'T**', 'T&& always'], 1),
          mcq('Return value optimisation (RVO) avoids:', ['Allocation', 'Unnecessary copies/moves of return values', 'Exceptions', 'Threads'], 1),
          mcq('Avoid premature optimisation by first:', ['Inline assembly', 'Profiling', 'Manual SIMD', 'Removing tests'], 1),
          mcq('Branch prediction misses cost:', ['Nothing', 'Many CPU cycles (pipeline flush)', 'Memory only', 'Disk I/O'], 1),
          mcq('Cache-friendly layout prefers:', ['Linked nodes scattered', 'Contiguous arrays', 'Random allocations', 'Pointer chasing'], 1),
          mcq('std::string Small String Optimisation stores small strings:', ['On heap', 'Inline in the object', 'Mmap', 'Compressed'], 1),
          fill('noexcept lets compiler avoid extra ___ handling.', ['exception']),
          fill('std::move on a const object becomes a ___.', ['copy']),
          mcq('reserve() on a vector:', ['Resizes', 'Reserves capacity to avoid reallocations', 'Shrinks', 'Sorts'], 1, 'medium'),
          mcq('Empty-base optimisation reduces size when:', ['No base', 'Base is empty', 'Base is virtual', 'Always'], 1, 'medium'),
        ]),
        makeExercise('Ranges (C++20)', [
          mcq('Header:', ['<ranges>', '<range>', '<algo>', '<iter>'], 0),
          mcq('Pipe operator chains:', ['Views', 'Mutexes', 'Threads', 'Containers'], 0),
          mcq('Lazy evaluation means:', ['Compute eagerly', 'Compute on iteration', 'Compile time only', 'Runtime random'], 1),
          mcq('std::views::filter takes:', ['Predicate', 'Container', 'Iterator', 'Number'], 0),
          mcq('std::views::transform takes:', ['Function', 'Container', 'Pair', 'Atom'], 0),
          mcq('Range adaptor closures live in:', ['std::ranges', 'std::range', 'std::adapt', 'std::view'], 0),
          fill('Views are typically ___-cost copies.', ['cheap']),
          fill('std::ranges::sort works on ___-iterator ranges.', ['random']),
          mcq('Materialise a view to vector via:', ['ranges::to (C++23)', 'static_cast', 'collect()', 'auto only'], 0, 'medium'),
          mcq('Dangling iterators from temp ranges are flagged via:', ['std::dangling sentinel', 'crash', 'optional', 'monostate'], 0, 'medium'),
        ]),
        makeExercise('Concepts (C++20)', [
          mcq('Concept declares:', ['Compile-time named requirements', 'Runtime checks', 'Threads', 'Macros'], 0),
          mcq('Apply concept on template:', ['template<Integral T>', 'concept T', 'using T = concept', 'requires<T>'], 0),
          mcq('requires-clause example:', ['requires (T a, T b) { a+b; }', 'rule { a+b; }', 'spec { a+b; }', 'check { a+b; }'], 0),
          mcq('Standard concept Integral checks:', ['Floating', 'Integer types', 'Pointer', 'Reference'], 1),
          mcq('Concepts replace many uses of:', ['SFINAE', 'Templates', 'Macros', 'Ranges'], 0),
          mcq('Subsumption rules order concepts by:', ['Generality', 'Compile time', 'Memory', 'Threads'], 0),
          fill('Concepts produce better ___ messages than SFINAE.', ['error']),
          fill('A concept is essentially a named ___ predicate.', ['compile-time']),
          mcq('Abbreviated function templates use:', ['auto parameters with concepts', 'Macros', 'Modules', 'Threads'], 0, 'medium'),
          mcq('Concept conjunction uses:', ['&&', 'and', 'concat', '+'], 0, 'medium'),
        ]),
        makeExercise('Coroutines (C++20)', [
          mcq('Coroutine keywords:', ['co_await / co_yield / co_return', 'await / yield / return', 'async / await', 'spawn / yield'], 0),
          mcq('Promise type names:', ['promise_type', 'CoroutinePromise', 'task::promise', 'co_promise'], 0),
          mcq('Coroutine handle type:', ['std::coroutine_handle<P>', 'co::handle<P>', 'co_handle<P>', 'task<P>'], 0),
          mcq('co_yield expression in generator:', ['Yields a value', 'Returns final', 'Awaits', 'Crashes'], 0),
          mcq('co_return ends:', ['The coroutine', 'Whole program', 'Loop', 'Throw'], 0),
          mcq('Awaitable requires:', ['await_ready/suspend/resume', 'await/yield/return', 'co_run only', 'queue/run'], 0),
          fill('Coroutines are stackless and store state in a ___ object.', ['frame']),
          fill('Symmetric transfer optimises tail-call between ___.', ['coroutines']),
          mcq('std::generator (C++23) yields:', ['Single value', 'Range of values', 'Future', 'Pair'], 1, 'medium'),
          mcq('Heap allocation for coroutine state can be elided by:', ['HALO optimisation', 'Macros', 'Threads', 'Compiler flag only'], 0, 'medium'),
        ]),
        makeExercise('Modules (C++20)', [
          mcq('Module declaration:', ['export module M;', 'module M;', 'export M;', 'pkg M;'], 0),
          mcq('Importing:', ['import M;', 'include M;', 'use M;', 'require M;'], 0),
          mcq('Modules replace many uses of:', ['Headers', 'Templates', 'Macros', 'Threads'], 0),
          mcq('Module interface unit declares:', ['Exported names', 'Locals only', 'Macros', 'Globals only'], 0),
          mcq('Compared to headers, modules are:', ['Slower to compile', 'Faster (compiled once)', 'Same', 'Identical'], 1),
          mcq('Header units allow:', ['Importing existing headers as modules', 'Macros only', 'Threads', 'Crashes'], 0),
          fill('Module partition uses module M:___ syntax.', ['part']),
          fill('Standard library module is import std (C++___).', ['23']),
          mcq('export keyword on declaration makes it:', ['Hidden', 'Visible to importers', 'Inline', 'Static'], 1, 'medium'),
          mcq('Macros are ___ exported by modules.', ['Always', 'Not (must use header units)', 'Sometimes', 'Forbidden'], 1, 'medium'),
        ]),
      ],
    },
  ],
};
