/**
 * Computer Science extra units — appended to the core CS bank.
 */

import type { SeedUnit } from '../seed-bank';
import { mcq, fill, match, makeExercise } from '../seed-bank';

export const CS_EXTRA: Record<1 | 2 | 3, SeedUnit[]> = {
  1: [
    {
      title: 'Number Systems & Logic',
      description: 'Binary, octal, hex, Boolean logic, gates.',
      exercises: [
        makeExercise('Binary Basics', [
          mcq('Binary digits are:', ['0,1', '0-9', '0-7', '0-F'], 0),
          mcq('1010 binary equals decimal:', ['8', '10', '12', '5'], 1),
          mcq('1 byte =', ['4 bits', '8 bits', '16 bits', '32 bits'], 1),
          mcq('Maximum value of 8-bit unsigned:', ['127', '128', '255', '256'], 2),
          mcq('Hex letters represent:', ['10-15', '0-9', '16-25', '0-7'], 0),
          mcq('Octal uses:', ['0-7', '0-9', '0-F', '0-1'], 0),
          fill('Decimal 255 in hex is ___.', ['FF']),
          fill('Decimal 16 in binary is ___.', ['10000']),
          mcq('Two\u2019s complement of 8-bit -1 is:', ['00000001', '11111111', '10000001', '01111111'], 1, 'medium'),
          mcq('Hex 0x1F equals decimal:', ['15', '31', '63', '255'], 1, 'medium'),
        ]),
        makeExercise('Boolean Logic', [
          mcq('AND of 1,0:', ['0', '1', 'X', 'Z'], 0),
          mcq('OR of 1,0:', ['0', '1', 'X', 'Z'], 1),
          mcq('XOR of 1,1:', ['0', '1', 'X', 'Z'], 0),
          mcq('NOT 0:', ['0', '1', 'X', 'Z'], 1),
          mcq('NAND is universal? ', ['Yes', 'No', 'Sometimes', 'Only with NOR'], 0),
          mcq('De Morgan\u2019s: NOT (A AND B) =', ['NOT A AND NOT B', 'NOT A OR NOT B', 'A OR B', 'A AND B'], 1),
          fill('A AND A = ___.', ['A']),
          fill('A OR 1 = ___.', ['1']),
          mcq('Truth table rows for n inputs:', ['n', '2n', '2^n', 'n!'], 2, 'medium'),
          mcq('XOR detects:', ['Equal inputs', 'Different inputs', 'All ones', 'No event'], 1, 'medium'),
        ]),
        makeExercise('Gates & Circuits', [
          mcq('Half adder produces:', ['Sum and carry', 'Sum only', 'Carry only', 'Subtract'], 0),
          mcq('Full adder has:', ['2 inputs', '3 inputs (a,b,carry-in)', '4 inputs', '5 inputs'], 1),
          mcq('Multiplexer selects:', ['One of many inputs', 'All inputs', 'No input', 'Random'], 0),
          mcq('Decoder output:', ['Activates one of many', 'Random', 'Always all', 'None'], 0),
          mcq('Flip-flop stores:', ['1 bit', '8 bits', '16 bits', '0 bits'], 0),
          mcq('SRAM is ___ than DRAM:', ['Slower', 'Faster but costlier', 'Same speed', 'Volatile only'], 1),
          fill('A latch is level-triggered; a flip-flop is ___-triggered.', ['edge']),
          fill('Combinational logic has no ___ state.', ['memory']),
          mcq('K-map is used to:', ['Simplify Boolean expressions', 'Sort numbers', 'Encrypt data', 'Run programs'], 0, 'medium'),
          mcq('Sequential circuits include:', ['Memory & state', 'Pure logic only', 'Just gates', 'Wires'], 0, 'medium'),
        ]),
        makeExercise('Computer Organisation', [
          mcq('CPU consists of:', ['ALU + CU + registers', 'RAM only', 'Disk only', 'GPU only'], 0),
          mcq('Volatile memory:', ['ROM', 'RAM', 'Hard disk', 'CD'], 1),
          mcq('Fastest memory closest to CPU:', ['Cache', 'RAM', 'SSD', 'HDD'], 0),
          mcq('Cache mapping types include:', ['Direct, set, full assoc', 'Linked', 'Hashed only', 'Sorted'], 0),
          mcq('Bus types:', ['Address, data, control', 'Data only', 'Control only', 'Single'], 0),
          mcq('Pipeline improves:', ['Throughput', 'Latency for one inst', 'Power', 'Cost'], 0),
          fill('GPU is good for ___ computations.', ['parallel']),
          fill('Operating system manages ___ resources.', ['hardware']),
          mcq('RISC vs CISC: RISC has:', ['Few simple instructions', 'Many complex', 'No instructions', 'Variable bits only'], 0, 'medium'),
          mcq('Cache hit ratio improves with:', ['Locality of reference', 'Random access', 'No locality', 'Page faults'], 0, 'medium'),
        ]),
        makeExercise('Number Conversions', [
          mcq('Binary 110 in decimal:', ['4', '5', '6', '7'], 2),
          mcq('Decimal 7 in binary:', ['101', '110', '111', '100'], 2),
          mcq('Binary 1101 in decimal:', ['11', '13', '15', '17'], 1),
          mcq('Decimal 12 in hex:', ['B', 'C', 'D', 'E'], 1),
          mcq('Hex 1A in decimal:', ['16', '20', '26', '36'], 2),
          mcq('Octal 17 in decimal:', ['7', '15', '17', '23'], 1),
          fill('Decimal 100 in binary is ___.', ['1100100']),
          fill('Decimal 100 in hex is ___.', ['64']),
          mcq('Binary 11111111 in decimal:', ['127', '128', '255', '256'], 2, 'medium'),
          mcq('Decimal -5 in 8-bit two\'s complement:', ['11111011', '00000101', '10000101', '11110101'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Programming Concepts',
      description: 'Variables, control flow, functions, error handling.',
      exercises: [
        makeExercise('Variables & Types', [
          mcq('Static typing:', ['Types checked at compile-time', 'No types', 'Runtime only', 'Random'], 0),
          mcq('Dynamic typing:', ['Compile-time check', 'Runtime types', 'No types', 'Same'], 1),
          mcq('Mutable example:', ['Python list', 'Tuple', 'Frozen set', 'String'], 0),
          mcq('Immutable example:', ['List', 'String/Tuple', 'Dict', 'Set'], 1),
          mcq('Constant declared in JS:', ['var', 'let', 'const', 'final'], 2),
          mcq('Garbage collection frees:', ['Unreachable memory', 'All memory', 'Disk', 'Files'], 0),
          fill('Strongly typed: no implicit ___ between types.', ['conversion']),
          fill('Reference type stores ___ to value.', ['address']),
          mcq('Pass-by-value vs pass-by-reference: Java passes objects by:', ['Value of reference', 'True reference', 'Pure copy', 'No pass'], 0, 'medium'),
          mcq('Type inference example:', ['var in C# / let in Rust', 'static int x', 'dim x', 'Lisp only'], 0, 'medium'),
        ]),
        makeExercise('Control Flow', [
          mcq('for vs while:', ['for has init/cond/step', 'while has init', 'Same', 'No diff'], 0),
          mcq('break exits:', ['Loop', 'Function', 'Program', 'Class'], 0),
          mcq('continue:', ['Skips to next iteration', 'Exits loop', 'Stops program', 'Calls function'], 0),
          mcq('switch in C is on:', ['Integral types', 'Floats', 'Objects', 'Files'], 0),
          mcq('Recursion needs:', ['Base case', 'No base', 'Loop', 'Random'], 0),
          mcq('Tail recursion can be optimized to:', ['Loop', 'Object', 'No optim', 'Stack growth'], 0),
          fill('Early return reduces ___.', ['nesting']),
          fill('Infinite loop with no break causes ___.', ['hang']),
          mcq('Short-circuit && stops evaluating when:', ['First false', 'Last true', 'Random', 'Never'], 0, 'medium'),
          mcq('Pattern matching is in:', ['Rust/Scala/Haskell', 'C only', 'Assembly', 'HTML'], 0, 'medium'),
        ]),
        makeExercise('Functions', [
          mcq('Pure function:', ['Same input → same output, no side effects', 'Random', 'IO heavy', 'Mutates state'], 0),
          mcq('First-class functions can be:', ['Passed as values', 'Stored only', 'Not used', 'Inline only'], 0),
          mcq('Closure captures:', ['Surrounding scope', 'Nothing', 'Globals only', 'Heap only'], 0),
          mcq('Higher-order function:', ['Takes/returns functions', 'Has > params', 'Recursive only', 'Async only'], 0),
          mcq('map applies fn to:', ['Each element', 'First only', 'Last only', 'Random'], 0),
          mcq('reduce combines elements to:', ['Single value', 'Array', 'Map', 'Set'], 0),
          fill('filter keeps elements where predicate is ___.', ['true']),
          fill('Lambda is an anonymous ___.', ['function']),
          mcq('Currying transforms f(a,b,c) into:', ['f(a)(b)(c)', 'f(a,b,c) same', 'fn array', 'No effect'], 0, 'medium'),
          mcq('Memoisation caches:', ['Function results', 'Disk files', 'Hardware', 'Network'], 0, 'medium'),
        ]),
        makeExercise('Errors & Testing', [
          mcq('try/catch handles:', ['Exceptions', 'Loops', 'Loops only', 'Threads'], 0),
          mcq('Compile-time error:', ['Syntax error', 'Out-of-memory', 'Race condition', 'Logic'], 0),
          mcq('Runtime error example:', ['Divide by zero', 'Missing semicolon', 'Type mismatch (static)', 'Indent'], 0),
          mcq('Unit test tests:', ['Smallest unit/function', 'System', 'UI only', 'DB only'], 0),
          mcq('Integration test:', ['Multiple modules together', 'Single function', 'No code', 'Compiler'], 0),
          mcq('Mock objects are used to:', ['Replace real dependencies in tests', 'Replace user', 'Render UI', 'Compile'], 0),
          fill('TDD = ___ Driven Development.', ['Test']),
          fill('Assert checks a ___ condition.', ['expected']),
          mcq('Code coverage measures:', ['Lines/branches executed by tests', 'Lines of code', 'Bugs found', 'Random'], 0, 'medium'),
          mcq('Flaky test:', ['Intermittently failing', 'Always passing', 'Always failing', 'Compile error'], 0, 'medium'),
        ]),
        makeExercise('Debugging & Tooling', [
          mcq('A debugger lets you:', ['Step through code', 'Compile only', 'Lint only', 'Format only'], 0),
          mcq('A breakpoint pauses at a:', ['Specific line', 'Random line', 'End only', 'Start only'], 0),
          mcq('Linter checks for:', ['Style/possible bugs', 'Runtime errors only', 'Hardware', 'Network'], 0),
          mcq('Version control example:', ['Git', 'Make', 'Docker', 'Linux'], 0),
          mcq('git commit records:', ['Snapshot of changes', 'Files only', 'Branches only', 'Nothing'], 0),
          mcq('git pull = git fetch + git ___.', ['merge', 'reset', 'log', 'init'], 0),
          fill('Stack trace shows the call ___.', ['stack']),
          fill('Continuous integration runs tests on every ___.', ['commit']),
          mcq('A profiler measures:', ['Runtime performance hot spots', 'Style', 'Disk usage only', 'Cables'], 0, 'medium'),
          mcq('Rubber-duck debugging means:', ['Explaining code aloud to find bugs', 'Throwing duck', 'Random', 'No method'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Networks & Web Basics',
      description: 'Internet, HTTP, DNS, cybersecurity hygiene.',
      exercises: [
        makeExercise('Internet Basics', [
          mcq('IP stands for:', ['Internet Protocol', 'Internal Path', 'Inter Procedural', 'Index Pointer'], 0),
          mcq('IPv4 is ___ bits.', ['16', '32', '64', '128'], 1),
          mcq('IPv6 is ___ bits.', ['32', '64', '128', '256'], 2),
          mcq('TCP is:', ['Connectionless', 'Reliable, connection-oriented', 'Random', 'No order'], 1),
          mcq('UDP is:', ['Reliable', 'Unreliable, fast', 'Connection oriented', 'Encrypted'], 1),
          mcq('Port for HTTP:', ['21', '22', '80', '443'], 2),
          fill('Port for HTTPS is ___.', ['443']),
          fill('DNS resolves names to ___.', ['IP']),
          mcq('Three-way handshake (TCP):', ['SYN, SYN-ACK, ACK', 'GET, POST, ACK', 'PING, PONG, ACK', 'A, B, C'], 0, 'medium'),
          mcq('CDN improves:', ['Global content delivery latency', 'CPU speed', 'Battery life', 'Disk size'], 0, 'medium'),
        ]),
        makeExercise('HTTP & Web', [
          mcq('GET is:', ['Idempotent, safe', 'Always changes state', 'Encrypted only', 'Slow only'], 0),
          mcq('POST typically:', ['Creates resource', 'Read only', 'Always idempotent', 'Random'], 0),
          mcq('Status 200:', ['Success', 'Redirect', 'Error', 'Server error'], 0),
          mcq('Status 404:', ['Not Found', 'Server Error', 'Forbidden', 'Created'], 0),
          mcq('Status 500:', ['Server Error', 'Not Found', 'Forbidden', 'OK'], 0),
          mcq('REST is:', ['Stateless API style', 'Stateful protocol', 'Database', 'Encryption'], 0),
          fill('JSON stands for JavaScript Object ___.', ['Notation']),
          fill('HTTPS uses ___ for encryption.', ['TLS']),
          mcq('CORS controls:', ['Cross-origin browser requests', 'CPU', 'Disk', 'Memory'], 0, 'medium'),
          mcq('Cookie attribute HttpOnly prevents:', ['JS access', 'Cookies entirely', 'CSRF', 'CORS'], 0, 'medium'),
        ]),
        makeExercise('Cybersecurity Hygiene', [
          mcq('Phishing is:', ['Tricking users to reveal info', 'Hardware attack', 'Compiler bug', 'Random'], 0),
          mcq('Strong password:', ['Long, mixed, unique', 'Short, simple', 'Reused', 'Empty'], 0),
          mcq('2FA adds:', ['Second factor (code/key)', 'Compiler', 'CPU', 'Disk'], 0),
          mcq('Public WiFi is risky because:', ['Sniffing/MITM possible', 'Slow', 'Cold', 'Random'], 0),
          mcq('Software updates fix:', ['Bugs and vulnerabilities', 'Hardware', 'Disks', 'Wires'], 0),
          mcq('Malware includes:', ['Viruses, trojans, ransomware', 'Compilers', 'Drivers only', 'Hardware'], 0),
          fill('VPN encrypts your ___ traffic.', ['network']),
          fill('Backups protect against ___ attacks.', ['ransomware']),
          mcq('Social engineering targets:', ['Humans, not just systems', 'CPU only', 'Cables', 'Disks'], 0, 'medium'),
          mcq('Zero-day vulnerability:', ['Unknown to vendor when exploited', 'Old patched bug', 'Hardware fault', 'Compiler bug'], 0, 'medium'),
        ]),
      ],
    },
  ],

  2: [
    {
      title: 'Advanced Data Structures',
      description: 'Heaps, balanced trees, graphs, hash tables.',
      exercises: [
        makeExercise('Heaps', [
          mcq('Heap is:', ['Complete binary tree', 'BST', 'Array sorted', 'Random tree'], 0),
          mcq('Min-heap root has:', ['Min element', 'Max element', 'Random', 'No element'], 0),
          mcq('Insert in heap is:', ['O(log n)', 'O(n)', 'O(1)', 'O(n log n)'], 0),
          mcq('Extract min/max is:', ['O(log n)', 'O(1)', 'O(n)', 'O(n^2)'], 0),
          mcq('Heap is used in:', ['Priority queue', 'Stack', 'Queue', 'Hash'], 0),
          mcq('Heapify of array is:', ['O(n)', 'O(n log n)', 'O(log n)', 'O(1)'], 0),
          fill('Heap sort time complexity is O(___).', ['n log n']),
          fill('Parent index of i in array heap is (i-1)/___.', ['2']),
          mcq('Build-heap (bottom-up) is:', ['O(n)', 'O(n^2)', 'O(n log n)', 'O(1)'], 0, 'medium'),
          mcq('Fibonacci heap improves:', ['Decrease key amortised cost', 'Insert worst case', 'Compile time', 'Disk'], 0, 'medium'),
        ]),
        makeExercise('Balanced Trees', [
          mcq('AVL tree balance factor:', ['{-1,0,1}', '{-2..2}', 'Any', 'No balance'], 0),
          mcq('Rotation in AVL:', ['LL, RR, LR, RL', 'Just LL', 'No rotation', 'Random'], 0),
          mcq('Red-Black tree height:', ['O(log n)', 'O(n)', 'O(1)', 'O(n log n)'], 0),
          mcq('B-Tree is used in:', ['Disk indexes/databases', 'Stack', 'Heap', 'Hash'], 0),
          mcq('Skip list is:', ['Probabilistic alternative to balanced trees', 'BST', 'Heap', 'Hash'], 0),
          mcq('Trie is good for:', ['Prefix queries', 'Random keys', 'No keys', 'Sorting'], 0),
          fill('B+ tree stores all data in ___.', ['leaves']),
          fill('Red-Black property: root is ___.', ['black']),
          mcq('Splay tree moves accessed node to:', ['Root via rotations', 'Leaves', 'Random', 'Removed'], 0, 'medium'),
          mcq('Treap combines BST with:', ['Random heap priorities', 'Hashing', 'Stack', 'Trie'], 0, 'medium'),
        ]),
        makeExercise('Graphs', [
          mcq('BFS uses:', ['Queue', 'Stack', 'Heap', 'Set'], 0),
          mcq('DFS uses:', ['Queue', 'Stack/recursion', 'Heap', 'Set'], 1),
          mcq('Dijkstra requires:', ['Non-negative weights', 'Negative weights ok', 'No weights', 'Cycles only'], 0),
          mcq('Bellman-Ford handles:', ['Negative edges', 'Only positive', 'No edges', 'Disjoint'], 0),
          mcq('MST algorithms:', ['Kruskal/Prim', 'Dijkstra only', 'BFS only', 'DFS only'], 0),
          mcq('Topological sort exists for:', ['DAG', 'Any graph', 'Cyclic only', 'Tree only'], 0),
          fill('Adjacency list memory is O(V+___).', ['E']),
          fill('Dense graphs prefer adjacency ___.', ['matrix']),
          mcq('Floyd-Warshall is:', ['All-pairs shortest path O(V^3)', 'Single-source O(V)', 'Sort', 'Search'], 0, 'medium'),
          mcq('Strongly connected components found by:', ['Tarjan / Kosaraju', 'BFS only', 'Dijkstra', 'Prim'], 0, 'medium'),
        ]),
        makeExercise('Hashing', [
          mcq('Hash table average lookup:', ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'], 0),
          mcq('Worst-case lookup with chaining:', ['O(1)', 'O(n)', 'O(log n)', 'O(n^2)'], 1),
          mcq('Open addressing example:', ['Linear probing', 'Chaining', 'Tree', 'Heap'], 0),
          mcq('Good hash function:', ['Uniform distribution', 'Always same', 'Random crash', 'Returns 0'], 0),
          mcq('Load factor =', ['n / table_size', 'table_size / n', 'n^2', 'log n'], 0),
          mcq('Rehashing happens at:', ['High load factor', 'Low load factor only', 'Never', 'Random'], 0),
          fill('Two keys mapped to same bucket = ___.', ['collision']),
          fill('Cryptographic hashes are ___-resistant to collisions.', ['highly']),
          mcq('Bloom filter gives:', ['No false negatives, possible false positives', 'No errors', 'Always wrong', 'Stores values'], 0, 'medium'),
          mcq('Consistent hashing is used in:', ['Distributed caches', 'Single-host arrays', 'Compiler', 'Disks only'], 0, 'medium'),
        ]),
        makeExercise('Disjoint Set Union & Tries', [
          mcq('DSU supports:', ['union & find', 'sort', 'hash', 'sum'], 0),
          mcq('Path compression in DSU brings amortised cost near:', ['O(α(n))', 'O(n)', 'O(log n)', 'O(n^2)'], 0),
          mcq('Union by rank reduces:', ['Tree height', 'Tree size', 'Time to insert only', 'No effect'], 0),
          mcq('Trie node typically stores:', ['Children pointers per character', 'Single value only', 'No children', 'Hash only'], 0),
          mcq('Trie supports prefix lookups in:', ['O(L) where L is prefix length', 'O(n)', 'O(n^2)', 'O(1) regardless'], 0),
          mcq('DSU is widely used in:', ['Kruskal MST', 'Dijkstra', 'BFS only', 'Hash table only'], 0),
          fill('Suffix tree solves substring queries in ___ time.', ['linear']),
          fill('Aho-Corasick combines trie + ___.', ['BFS']),
          mcq('DSU initial parents are:', ['Self for each node', 'Zero', 'Random', 'Sorted'], 0, 'medium'),
          mcq('Compressed trie is also called:', ['Radix tree', 'BST', 'Heap', 'Skip list'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Operating Systems',
      description: 'Processes, scheduling, memory, file systems.',
      exercises: [
        makeExercise('Processes & Threads', [
          mcq('Process is:', ['Program in execution', 'A file', 'A function', 'A class'], 0),
          mcq('Thread is:', ['Lightweight unit inside process', 'Process', 'Disk', 'Driver'], 0),
          mcq('Context switch saves:', ['CPU state', 'Disk', 'GPU only', 'Battery'], 0),
          mcq('PCB stores:', ['Process metadata', 'Code only', 'Disk only', 'Random'], 0),
          mcq('IPC examples:', ['Pipes/sockets/shared memory', 'Disk', 'GPU', 'CPU only'], 0),
          mcq('Race condition occurs when:', ['Concurrent unsynchronized access', 'Single thread', 'No memory', 'Compile time'], 0),
          fill('Mutex provides ___ exclusion.', ['mutual']),
          fill('Deadlock requires hold-and-___.', ['wait']),
          mcq('Banker\u2019s algorithm prevents:', ['Deadlock', 'Starvation', 'Cache miss', 'Page fault'], 0, 'medium'),
          mcq('User vs kernel thread mapping:', ['1:1, M:N, M:1', 'Only 1:1', 'Only M:N', 'No mapping'], 0, 'medium'),
        ]),
        makeExercise('Scheduling', [
          mcq('FCFS is:', ['First-come first-served', 'Round-robin', 'SJF', 'Priority'], 0),
          mcq('SJF stands for:', ['Shortest Job First', 'Single Job First', 'Slow Job', 'Strict Job'], 0),
          mcq('Round-robin uses:', ['Time quantum', 'No quantum', 'Priority only', 'FCFS'], 0),
          mcq('Priority scheduling can cause:', ['Starvation', 'No issues', 'Cache miss', 'Page fault'], 0),
          mcq('Aging combats:', ['Starvation', 'Deadlock', 'Race', 'Page fault'], 0),
          mcq('Multilevel queue:', ['Multiple ready queues', 'Single queue', 'No queue', 'Stack'], 0),
          fill('Preemptive scheduling can ___ a running process.', ['interrupt']),
          fill('Throughput = jobs completed per ___.', ['unit time']),
          mcq('CFS is in:', ['Linux', 'Windows', 'macOS', 'iOS only'], 0, 'medium'),
          mcq('Real-time scheduling guarantees:', ['Deadlines', 'Throughput only', 'No guarantees', 'Random'], 0, 'medium'),
        ]),
        makeExercise('Memory Management', [
          mcq('Paging divides memory into:', ['Fixed-size pages', 'Variable segments', 'No division', 'Random'], 0),
          mcq('Page fault handled by:', ['OS bringing page from disk', 'Compiler', 'CPU only', 'GPU'], 0),
          mcq('Virtual memory enables:', ['Larger logical address space', 'No memory', 'Stack only', 'Cache'], 0),
          mcq('TLB caches:', ['Page table entries', 'Disk blocks', 'Files', 'Code'], 0),
          mcq('Thrashing occurs when:', ['Too much paging activity', 'No pages', 'Too few processes', 'No memory'], 0),
          mcq('Working set is:', ['Pages used recently', 'All pages', 'Disk pages only', 'Code only'], 0),
          fill('Page replacement algorithm LRU = least recently ___.', ['used']),
          fill('Belady\u2019s anomaly affects ___ replacement.', ['FIFO']),
          mcq('Demand paging brings pages:', ['On reference', 'Always all', 'Never', 'Random'], 0, 'medium'),
          mcq('Segmentation differs from paging by:', ['Variable size logical units', 'Fixed size only', 'No size', 'Same'], 0, 'medium'),
        ]),
        makeExercise('File Systems', [
          mcq('Inode contains:', ['File metadata', 'Whole file', 'Username', 'Disk number only'], 0),
          mcq('Journaling helps:', ['Crash recovery', 'Speed only', 'Compression', 'Encryption'], 0),
          mcq('FAT32 max file size:', ['2 GB', '4 GB - 1', '8 GB', 'No limit'], 1),
          mcq('NTFS supports:', ['Permissions/journaling', 'No journaling', 'No permissions', 'Read only'], 0),
          mcq('Block size affects:', ['Internal fragmentation', 'No effect', 'CPU only', 'Network'], 0),
          mcq('Hard link creates:', ['Another name to same inode', 'Copy of file', 'Symbolic link', 'New file'], 0),
          fill('Soft link breaks if target is ___.', ['deleted']),
          fill('Directory itself is a special ___.', ['file']),
          mcq('Copy-on-write fs example:', ['ZFS / Btrfs', 'FAT32', 'NTFS only', 'ext2'], 0, 'medium'),
          mcq('RAID 1 provides:', ['Mirroring', 'Striping only', 'No redundancy', 'Compression'], 0, 'medium'),
        ]),
        makeExercise('I/O & Device Management', [
          mcq('Polling means CPU:', ['Continuously checks device', 'Sleeps until interrupt', 'Switches off', 'No check'], 0),
          mcq('Interrupt-driven I/O lets CPU:', ['Do other work until interrupted', 'Always wait', 'Crash', 'No I/O'], 0),
          mcq('DMA allows transfer:', ['Without CPU per byte', 'Only via CPU', 'No transfer', 'Random'], 0),
          mcq('Device driver is part of:', ['OS', 'CPU only', 'GPU only', 'Disk only'], 0),
          mcq('Spooling buffers requests for:', ['Slow devices like printers', 'CPU only', 'Cache', 'Disk only'], 0),
          mcq('Block devices include:', ['Disks', 'Keyboards', 'Speakers', 'Network packets only'], 0),
          fill('Character devices transfer data ___ at a time.', ['one byte']),
          fill('Disk scheduling algorithm SCAN moves head in ___ direction.', ['one']),
          mcq('SSDs eliminate:', ['Mechanical seek time', 'All latency', 'Power use', 'Caching'], 0, 'medium'),
          mcq('Buffer cache stores recent:', ['Disk blocks in RAM', 'Network packets', 'CPU instructions', 'GPU data'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Databases & SQL',
      description: 'Relational model, normalisation, SQL, transactions.',
      exercises: [
        makeExercise('Relational Model', [
          mcq('Primary key is:', ['Unique identifier', 'Random column', 'Foreign reference', 'No constraint'], 0),
          mcq('Foreign key references:', ['PK in another table', 'No table', 'Same column', 'Index only'], 0),
          mcq('Normalisation reduces:', ['Redundancy', 'Speed', 'Indexes', 'Tables only'], 0),
          mcq('1NF removes:', ['Repeating groups', 'Partial dependency', 'Transitive dep', 'Multi-valued'], 0),
          mcq('2NF removes:', ['Partial dependency on composite key', 'Repeating', 'Transitive', '3NF'], 0),
          mcq('3NF removes:', ['Transitive dependency', 'Repeating', 'Partial', 'BCNF'], 0),
          fill('BCNF is stricter than ___.', ['3NF']),
          fill('A candidate key is a minimal ___ key.', ['super']),
          mcq('Index speeds up reads but slows:', ['Writes', 'Reads', 'Compile', 'No effect'], 0, 'medium'),
          mcq('A relation is denormalised to:', ['Improve read performance', 'Save space', 'Avoid PK', 'Rare cases'], 0, 'medium'),
        ]),
        makeExercise('SQL Queries', [
          mcq('SELECT * FROM t WHERE id = 1 returns:', ['Matching rows', 'All', 'Schema', 'Errors'], 0),
          mcq('JOIN combines:', ['Rows of two tables', 'Columns of one', 'Schemas', 'No effect'], 0),
          mcq('LEFT JOIN keeps:', ['All left rows', 'Matching only', 'All right', 'No rows'], 0),
          mcq('GROUP BY used with:', ['Aggregates like COUNT', 'WHERE', 'JOIN', 'ORDER'], 0),
          mcq('HAVING filters:', ['Aggregated groups', 'Rows', 'Columns', 'Tables'], 0),
          mcq('UPDATE without WHERE:', ['Updates all rows', 'Errors', 'No effect', 'Drops table'], 0),
          fill('DELETE FROM t WHERE id=1 removes ___ row(s).', ['matching']),
          fill('LIMIT N restricts result to ___ rows.', ['N']),
          mcq('Subquery in WHERE:', ['Inner query result used by outer', 'No use', 'Errors', 'Same as join'], 0, 'medium'),
          mcq('CTE syntax: WITH name AS ___', ['(query)', '{}', 'fn()', '[]'], 0, 'medium'),
        ]),
        makeExercise('Transactions & ACID', [
          mcq('ACID stands for:', ['Atomic, Consistent, Isolated, Durable', 'Active, Critical, ID, Disk', 'Atom, Cycle, ID, Drive', 'No'], 0),
          mcq('Atomicity means:', ['All or nothing', 'Random', 'Always commit', 'No rollback'], 0),
          mcq('Isolation level affecting dirty reads:', ['READ UNCOMMITTED allows them', 'SERIALIZABLE allows', 'Random', 'No level'], 0),
          mcq('Two-phase locking ensures:', ['Serializability', 'Speed', 'No locks', 'Random'], 0),
          mcq('Deadlock in DB resolved by:', ['Detect & abort one tx', 'Wait forever', 'Compile time', 'Disk'], 0),
          mcq('Phantom read prevented by:', ['SERIALIZABLE / range locks', 'READ UNCOMMITTED', 'Dirty read', 'No way'], 0),
          fill('COMMIT makes changes ___.', ['durable']),
          fill('ROLLBACK reverts to last ___.', ['savepoint']),
          mcq('Optimistic concurrency uses:', ['Version checks at commit', 'Locks always', 'No checks', 'Random'], 0, 'medium'),
          mcq('CAP theorem: pick at most ___ of 3.', ['2', '1', '3', '0'], 0, 'medium'),
        ]),
      ],
    },
  ],

  3: [
    {
      title: 'Algorithm Design',
      description: 'Divide & conquer, DP, greedy, NP-completeness.',
      exercises: [
        makeExercise('Divide & Conquer', [
          mcq('Merge sort time:', ['O(n log n)', 'O(n^2)', 'O(n)', 'O(log n)'], 0),
          mcq('Quick sort average:', ['O(n log n)', 'O(n^2)', 'O(n)', 'O(log n)'], 0),
          mcq('Quick sort worst:', ['O(n^2)', 'O(n)', 'O(n log n)', 'O(log n)'], 0),
          mcq('Binary search requires:', ['Sorted input', 'Random', 'Linked list', 'No structure'], 0),
          mcq('Master theorem analyses:', ['Divide-and-conquer recurrences', 'DP', 'Greedy', 'Networks'], 0),
          mcq('Strassen multiplies matrices in:', ['O(n^2.81)', 'O(n^3)', 'O(n)', 'O(n log n)'], 0),
          fill('Closest pair of points solved in O(n ___ n).', ['log']),
          fill('Karatsuba multiplies n-digit numbers in O(n^___).', ['log2 3']),
          mcq('Tail recursion is when recursive call is:', ['Last operation', 'First operation', 'Inside loop', 'Random'], 0, 'medium'),
          mcq('FFT runs in:', ['O(n log n)', 'O(n)', 'O(n^2)', 'O(log n)'], 0, 'medium'),
        ]),
        makeExercise('Dynamic Programming', [
          mcq('DP requires:', ['Optimal substructure & overlapping subproblems', 'Random', 'No structure', 'Greedy'], 0),
          mcq('Memoisation is:', ['Top-down DP', 'Bottom-up DP', 'No DP', 'Greedy'], 0),
          mcq('Tabulation is:', ['Bottom-up DP', 'Top-down', 'Greedy', 'BFS'], 0),
          mcq('LIS in O(n log n) uses:', ['Patience / BIT', 'BFS', 'DFS', 'Sort only'], 0),
          mcq('Knapsack 0/1 is:', ['DP O(nW)', 'Greedy', 'Brute O(2^n) only', 'Linear'], 0),
          mcq('Edit distance is:', ['DP problem', 'Greedy', 'BFS', 'Hash'], 0),
          fill('Bellman equation underlies ___-based RL.', ['DP']),
          fill('Coin change minimum coins solved by ___.', ['DP']),
          mcq('Bitmask DP commonly handles:', ['Subset state', 'Trees', 'Greedy', 'Hashing'], 0, 'medium'),
          mcq('Matrix chain multiplication DP runs in:', ['O(n^3)', 'O(n^2)', 'O(n log n)', 'O(n)'], 0, 'medium'),
        ]),
        makeExercise('Greedy & Approx', [
          mcq('Greedy chooses:', ['Local optimum', 'Random', 'All options', 'Recursion'], 0),
          mcq('Greedy works when problem has:', ['Greedy choice property + optimal substructure', 'Random structure', 'No structure', 'NP-hard'], 0),
          mcq('Activity selection by:', ['Earliest finish first greedy', 'Latest finish', 'Random', 'DP only'], 0),
          mcq('Huffman coding is:', ['Greedy', 'DP', 'Brute force', 'Backtracking'], 0),
          mcq('Set cover greedy ratio:', ['ln n approx', 'Optimal', 'No approx', 'Constant 2'], 0),
          mcq('Vertex cover 2-approx by:', ['Pick both endpoints of uncovered edge', 'Random vertex', 'Color', 'BFS'], 0),
          fill('TSP can be approximated to 1.5 in metric case via ___.', ['Christofides']),
          fill('Greedy for fractional knapsack is ___.', ['optimal']),
          mcq('Greedy for 0/1 knapsack is:', ['Suboptimal', 'Optimal', 'No solution', 'Random'], 0, 'medium'),
          mcq('PTAS provides:', ['(1+ε) approximation in poly time per ε', 'Exact answer', 'Random', 'No approx'], 0, 'medium'),
        ]),
        makeExercise('Complexity Theory', [
          mcq('P vs NP asks:', ['Is P = NP?', 'Is P empty?', 'Is NP empty?', 'No question'], 0),
          mcq('NP-complete examples:', ['SAT, TSP, Hamiltonian', 'Sorting', 'Search', 'Hashing'], 0),
          mcq('Cook-Levin theorem:', ['SAT is NP-complete', 'P=NP', 'TSP is in P', 'No theorem'], 0),
          mcq('Reduction A→B means:', ['Solve A using B', 'Same problem', 'No relation', 'Random'], 0),
          mcq('Class co-NP:', ['Complements of NP problems', 'Subset of P', 'Same as P', 'Outside'], 0),
          mcq('PSPACE includes:', ['Problems solvable with poly space', 'Constant space only', 'No space', 'Linear time only'], 0),
          fill('Halting problem is ___.', ['undecidable']),
          fill('Turing machine has an ___ tape.', ['infinite']),
          mcq('NP-hard means:', ['At least as hard as any NP problem', 'Easy', 'P only', 'Decidable always'], 0, 'medium'),
          mcq('Approximation hardness shown by:', ['PCP theorem', 'Greedy', 'DP', 'BFS'], 0, 'medium'),
        ]),
        makeExercise('Backtracking & Branch and Bound', [
          mcq('Backtracking explores:', ['Search tree pruning invalid paths', 'Random', 'No tree', 'Greedy only'], 0),
          mcq('N-Queens is solved by:', ['Backtracking', 'Greedy', 'BFS only', 'Hash'], 0),
          mcq('Sudoku solver typically uses:', ['Backtracking', 'DP', 'Greedy', 'BFS only'], 0),
          mcq('Branch and bound prunes using:', ['Bounds on objective', 'Random', 'No bounds', 'Greedy only'], 0),
          mcq('Best-first search uses:', ['Priority queue', 'Stack', 'Queue', 'No structure'], 0),
          mcq('A* combines:', ['g(n)+h(n)', 'g(n) only', 'h(n) only', 'Random'], 0),
          fill('Backtracking abandons a path when constraint is ___.', ['violated']),
          fill('Admissible heuristic never ___ true cost.', ['overestimates']),
          mcq('IDA* is iterative deepening of:', ['A*', 'BFS', 'DFS', 'Dijkstra'], 0, 'medium'),
          mcq('Constraint satisfaction problems are often solved by:', ['Backtracking + propagation', 'Brute force only', 'Greedy only', 'DP only'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Distributed & Cloud Systems',
      description: 'Consistency, replication, microservices, scaling.',
      exercises: [
        makeExercise('Distributed Foundations', [
          mcq('CAP theorem:', ['Consistency, Availability, Partition tolerance — at most 2', 'Always all 3', 'Only C', 'Only A'], 0),
          mcq('Eventual consistency:', ['Replicas converge eventually', 'Always strong', 'No consistency', 'Random'], 0),
          mcq('Strong consistency means:', ['Linearisable reads', 'Stale reads ok', 'No reads', 'Random'], 0),
          mcq('Two-phase commit:', ['Atomic commit across nodes', 'Single node only', 'No commit', 'Random'], 0),
          mcq('Paxos / Raft solve:', ['Consensus', 'Sorting', 'Hashing', 'Compile'], 0),
          mcq('Sharding partitions:', ['Data across nodes', 'Code', 'Cache', 'Network'], 0),
          fill('Replication improves availability and ___.', ['durability']),
          fill('A leader election ensures one ___.', ['primary']),
          mcq('Quorum reads with R+W>N gives:', ['Strong consistency', 'Eventual', 'No reads', 'Always availability'], 0, 'medium'),
          mcq('Vector clocks track:', ['Causal order', 'Wall time only', 'Memory', 'Disk'], 0, 'medium'),
        ]),
        makeExercise('Microservices', [
          mcq('Microservices vs monolith:', ['Smaller, independent services', 'Single binary', 'No services', 'Random'], 0),
          mcq('Communication style:', ['HTTP/REST or messaging', 'Shared memory', 'Disk only', 'Sockets only'], 0),
          mcq('Service discovery resolves:', ['Service endpoints', 'DNS only', 'Disk', 'Cache'], 0),
          mcq('Circuit breaker prevents:', ['Cascading failures', 'Compile errors', 'Disk failure', 'Network bandwidth'], 0),
          mcq('Sidecar pattern uses:', ['Auxiliary helper container', 'Big container', 'No container', 'Single binary'], 0),
          mcq('Event-driven systems use:', ['Brokers like Kafka', 'Direct DB only', 'Files only', 'No comm'], 0),
          fill('Bulkhead pattern isolates ___.', ['failures']),
          fill('Saga pattern manages ___ transactions.', ['distributed']),
          mcq('API gateway often handles:', ['Auth, rate limit, routing', 'DB writes', 'Compile', 'GC'], 0, 'medium'),
          mcq('CQRS separates:', ['Commands and queries', 'Cache and disk', 'Compile and link', 'Layer 4 and 7'], 0, 'medium'),
        ]),
        makeExercise('Cloud & Scaling', [
          mcq('Horizontal scaling:', ['Add more nodes', 'Bigger node only', 'Smaller node', 'No scaling'], 0),
          mcq('Vertical scaling:', ['Bigger node', 'More nodes', 'No scaling', 'Random'], 0),
          mcq('Load balancer distributes:', ['Traffic across servers', 'Code', 'Cache', 'Disk'], 0),
          mcq('CDN caches:', ['Edge content', 'DB rows', 'Compile output', 'GPU'], 0),
          mcq('Serverless example:', ['AWS Lambda', 'EC2 reserved', 'Bare metal', 'On-prem only'], 0),
          mcq('IaC stands for:', ['Infrastructure as Code', 'Internet as Cloud', 'Instance Cluster', 'Inverse Cache'], 0),
          fill('Containers isolate processes via Linux ___.', ['namespaces']),
          fill('Kubernetes orchestrates ___ containers.', ['many']),
          mcq('Blue-green deployment:', ['Two prod environments switched', 'Single env', 'Random', 'No deploy'], 0, 'medium'),
          mcq('Canary release routes:', ['Small % to new version', 'All to new', 'None', 'Random'], 0, 'medium'),
        ]),
        makeExercise('Messaging & Streaming', [
          mcq('Message queue example:', ['RabbitMQ', 'Postgres', 'Redis CLI only', 'gcc'], 0),
          mcq('Pub/sub allows:', ['Many subscribers per message', 'Single consumer only', 'No comms', 'Disk only'], 0),
          mcq('Kafka stores messages in:', ['Append-only log partitions', 'Random files', 'Single file', 'No storage'], 0),
          mcq('At-least-once delivery may cause:', ['Duplicates', 'Message loss', 'No delivery', 'Random'], 0),
          mcq('Exactly-once requires:', ['Idempotency or transactions', 'No design', 'Random', 'No delivery'], 0),
          mcq('Backpressure prevents:', ['Producer overwhelming consumer', 'Disk fill', 'CPU idle', 'No effect'], 0),
          fill('A consumer group balances partitions among ___.', ['consumers']),
          fill('Dead-letter queue collects ___ messages.', ['failed']),
          mcq('Stream processing engine example:', ['Apache Flink', 'Make', 'Docker', 'Vim'], 0, 'medium'),
          mcq('Event sourcing stores state as:', ['Sequence of events', 'Single snapshot only', 'No state', 'Random rows'], 0, 'medium'),
        ]),
        makeExercise('Observability & Reliability', [
          mcq('SLO is:', ['Target service-level objective', 'Code module', 'Library', 'Hardware'], 0),
          mcq('SLI is:', ['Indicator measured against SLO', 'Library', 'Compiler', 'Disk'], 0),
          mcq('SLA is:', ['Contractual commitment', 'Internal target only', 'Code style', 'Random'], 0),
          mcq('Three pillars of observability:', ['Logs, metrics, traces', 'CPU, RAM, disk', 'C, C++, Rust', 'Random'], 0),
          mcq('Distributed tracing uses:', ['Trace IDs spanning services', 'Single log only', 'No IDs', 'Random'], 0),
          mcq('Chaos engineering aims to:', ['Find failure modes by injecting faults', 'Crash systems for fun', 'No purpose', 'Compile'], 0),
          fill('Error budget = 1 − ___.', ['SLO']),
          fill('Postmortems should be ___-free.', ['blame']),
          mcq('SRE term coined at:', ['Google', 'Microsoft only', 'Apple', 'IBM only'], 0, 'medium'),
          mcq('Mean time to recovery (MTTR) measures:', ['Time to restore service', 'Time between failures', 'Compile time', 'Disk life'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Security & Cryptography',
      description: 'Symmetric/asymmetric, hashing, web security, attacks.',
      exercises: [
        makeExercise('Cryptography', [
          mcq('Symmetric uses:', ['Same key for enc/dec', 'Public/private', 'No key', 'One-way'], 0),
          mcq('Asymmetric uses:', ['Public/private key pair', 'One key only', 'No key', 'Random'], 0),
          mcq('AES is:', ['Symmetric block cipher', 'Asymmetric', 'Hash', 'MAC only'], 0),
          mcq('RSA security relies on:', ['Integer factorisation', 'Discrete log only', 'Hashing', 'Sorting'], 0),
          mcq('Diffie-Hellman provides:', ['Key exchange', 'Encryption itself', 'Hashing', 'Sign'], 0),
          mcq('Digital signatures use:', ['Private key sign, public verify', 'Public sign', 'Symmetric only', 'Hash only'], 0),
          fill('SHA-256 outputs ___ bits.', ['256']),
          fill('HMAC provides authenticity using a ___ key.', ['shared']),
          mcq('TLS handshake combines:', ['Asymmetric KEX + symmetric session', 'Asymmetric only', 'Symmetric only', 'No crypto'], 0, 'medium'),
          mcq('Forward secrecy ensures:', ['Past sessions safe if long-term key leaks', 'No confidentiality', 'Same key forever', 'No effect'], 0, 'medium'),
        ]),
        makeExercise('Web Security', [
          mcq('SQL injection caused by:', ['Unsanitised input concatenated to SQL', 'TLS', 'CORS', 'GC'], 0),
          mcq('Defence against SQLi:', ['Parametrised queries', 'String concat', 'Plain text logs', 'No defence'], 0),
          mcq('XSS injects:', ['Malicious JS in page', 'SQL', 'CSS only', 'CSV'], 0),
          mcq('CSRF tricks user into:', ['Sending authenticated request unintentionally', 'Logging out', 'No effect', 'Compile'], 0),
          mcq('Defence for CSRF:', ['Anti-CSRF tokens / SameSite cookies', 'Plain auth', 'No defence', 'CORS only'], 0),
          mcq('Content Security Policy controls:', ['Allowed sources of scripts/styles', 'TLS', 'GC', 'Compile'], 0),
          fill('Storing passwords requires ___ hashing (bcrypt, Argon2).', ['salted']),
          fill('TLS uses certificates issued by ___.', ['CAs']),
          mcq('JWT tampering detected by:', ['Signature verification', 'No detection', 'Random', 'Encryption only'], 0, 'medium'),
          mcq('OAuth 2.0 is for:', ['Delegated authorisation', 'Encryption', 'Hashing', 'Storage'], 0, 'medium'),
        ]),
        makeExercise('Threat Modelling', [
          mcq('STRIDE includes:', ['Spoofing, Tampering, Repudiation, Info disclosure, DoS, Elev. priv.', 'Sort, Trust, Random', 'No model', 'OWASP only'], 0),
          mcq('Defence in depth:', ['Multiple layered defences', 'Single layer', 'No defence', 'Hardware only'], 0),
          mcq('Principle of least privilege:', ['Minimum necessary rights', 'All admin', 'No rights', 'Random'], 0),
          mcq('Zero-trust assumes:', ['No implicit trust by network', 'Trust internal', 'Trust everyone', 'No security'], 0),
          mcq('OWASP Top 10 covers:', ['Common web app risks', 'Hardware bugs', 'Compiler bugs', 'OS only'], 0),
          mcq('SBOM is:', ['Software Bill of Materials', 'Hardware bill', 'Compile bom', 'Random'], 0),
          fill('Pen testing simulates ___.', ['attack']),
          fill('Logging and monitoring help detect ___.', ['intrusions']),
          mcq('Side-channel attack uses:', ['Timing/power leakage', 'Direct memory only', 'Compile', 'No leak'], 0, 'medium'),
          mcq('Supply-chain attack targets:', ['Dependencies/build pipeline', 'End user UI only', 'GC', 'No code'], 0, 'medium'),
        ]),
      ],
    },
  ],
};
