/**
 * DSA (Data Structures & Algorithms) question bank.
 * Levels: 1 = beginner, 2 = intermediate, 3 = advanced.
 * Each Exercise = 8 easy + 2 medium = 10 questions.
 */

import type { SeedUnit } from '../seed-bank';
import { mcq, fill, match, makeExercise } from '../seed-bank';

export const DSA: Record<1 | 2 | 3, SeedUnit[]> = {
  1: [
    {
      title: 'Arrays & Big-O Basics',
      description: 'Array memory layout, indexing, and asymptotic notation.',
      exercises: [
        makeExercise('Arrays 101', [
          mcq('Array index in C/C++/Java starts at:', ['-1', '0', '1', 'depends'], 1),
          mcq('Time to access an element by index in an array:', ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'], 2),
          mcq('Arrays store elements in:', ['Linked nodes', 'Contiguous memory', 'Tree nodes', 'Hash buckets'], 1),
          mcq('Inserting at the front of an array of n elements:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 2),
          mcq('Searching an unsorted array of size n in the worst case:', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 2),
          mcq('Best case of binary search:', ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'], 2),
          fill('Big-O describes ___ growth.', ['asymptotic']),
          fill('Binary search requires the array to be ___.', ['sorted']),
          mcq('A 2D array of size m×n stored row-major needs how many memory cells:', ['m+n', 'm·n', 'max(m,n)', 'm² + n²'], 1, 'medium'),
          mcq('Which is faster asymptotically: O(n log n) or O(n²) for large n?', ['O(n²)', 'O(n log n)', 'Same', 'Depends on constants'], 1, 'medium'),
        ]),
        makeExercise('Big-O Practice', [
          mcq('Two nested loops over n elements give:', ['O(n)', 'O(n²)', 'O(log n)', 'O(2ⁿ)'], 1),
          mcq('Recursion that halves input each call:', ['O(n)', 'O(n²)', 'O(log n)', 'O(2ⁿ)'], 2),
          mcq('Constant time operation:', ['Loop n times', 'Hash lookup average', 'Sort array', 'BFS'], 1),
          mcq('O(1) space means:', ['No memory used', 'Memory does not grow with n', 'Always 1 byte', 'Memory grows linearly'], 1),
          mcq('Which sort is O(n²) average:', ['Merge sort', 'Quick sort', 'Bubble sort', 'Heap sort'], 2),
          mcq('Drop lower-order terms in Big-O because:', ['They\u2019re wrong', 'Constants dominate', 'Asymptotic behavior is dominated by highest order', 'Compilers remove them'], 2),
          fill('O(2n + 5) simplifies to O(___).', ['n']),
          match('Match algorithm with time:', ['Binary search', 'Linear search', 'Bubble sort'], ['O(log n)', 'O(n)', 'O(n²)'], { 'Binary search': 'O(log n)', 'Linear search': 'O(n)', 'Bubble sort': 'O(n²)' }),
          mcq('A loop runs n + n/2 + n/4 + ... times. Total ≈', ['O(log n)', 'O(n)', 'O(n²)', 'O(2ⁿ)'], 1, 'medium'),
          mcq('Recurrence T(n) = 2T(n/2) + n solves to:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(2ⁿ)'], 1, 'medium'),
        ]),
        makeExercise('Array Manipulation', [
          mcq('Reverse an array of size n in-place:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 2),
          mcq('Rotate array by k via reversal:', ['O(n²)', 'O(n)', 'O(log n)', 'O(k)'], 1),
          mcq('Find max in unsorted array:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 2),
          mcq('Move zeros to end stable in-place:', ['O(n²)', 'O(n)', 'O(log n)', 'O(n log n)'], 1),
          mcq('Two-pointer technique often reduces time from O(n²) to:', ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], 0),
          mcq('Sliding window suits problems on:', ['Trees', 'Contiguous subarrays', 'Hash buckets only', 'Graphs'], 1),
          fill('Prefix sum allows range sum queries in O(___).', ['1']),
          fill('Kadane’s algorithm finds max ___ subarray.', ['contiguous']),
          mcq('Maximum subarray sum (Kadane):', ['O(n²)', 'O(n log n)', 'O(n)', 'O(1)'], 2, 'medium'),
          mcq('Trapping rain water in O(n) uses:', ['Two pointers', 'BFS', 'Heap', 'Greedy sort'], 0, 'medium'),
        ]),
        makeExercise('Sorting Basics', [
          mcq('Bubble sort worst case:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(2ⁿ)'], 2),
          mcq('Merge sort time:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], 1),
          mcq('Quick sort average:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], 1),
          mcq('Quick sort worst case:', ['O(n log n)', 'O(n²)', 'O(n)', 'O(log n)'], 1),
          mcq('Stable sort preserves order of:', ['All elements', 'Equal-key elements', 'Smallest only', 'Random'], 1),
          mcq('Counting sort suits when:', ['Range is small', 'Range is huge', 'Floats', 'Strings'], 0),
          fill('Merge sort uses O(___) extra space.', ['n']),
          fill('Heap sort is in-place but not ___.', ['stable']),
          mcq('Lower bound for comparison sort:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], 1, 'medium'),
          mcq('Radix sort time for n numbers up to k digits:', ['O(n)', 'O(n·k)', 'O(n log n)', 'O(n²)'], 1, 'medium'),
        ]),
        makeExercise('Searching', [
          mcq('Linear search worst case:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 2),
          mcq('Binary search needs:', ['Hash', 'Sorted array', 'Heap', 'Tree'], 1),
          mcq('Binary search complexity:', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 1),
          mcq('Ternary search splits into:', ['2', '3', '4', 'log n'], 1),
          mcq('Exponential search useful for:', ['Unbounded arrays', 'Trees', 'Hash', 'Strings'], 0),
          mcq('Interpolation search assumes:', ['Random data', 'Uniform distribution', 'Sorted only', 'Hashing'], 1),
          fill('Binary search divides search space in ___.', ['half']),
          fill('Search for first occurrence uses lower ___.', ['bound']),
          mcq('Find peak element in unsorted array (any peak):', ['O(n²)', 'O(log n)', 'O(n)', 'O(1)'], 1, 'medium'),
          mcq('Search in rotated sorted array:', ['O(n)', 'O(log n)', 'O(n²)', 'O(n log n)'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Strings',
      description: 'String storage, traversal, and basic problems.',
      exercises: [
        makeExercise('Strings Basics', [
          mcq('In C, strings end with:', ['\\\\0', '\\\\n', '\\\\t', 'space'], 0),
          mcq('Length of \"Hello\" (no null):', ['4', '5', '6', '7'], 1),
          mcq('Are Python strings mutable?', ['Yes', 'No', 'Sometimes', 'Only if list'], 1),
          mcq('Reversing a string of length n is:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 2),
          mcq('Concatenating two strings of length n in Python builds a new string of length:', ['n', '2n', 'n²', 'log n'], 1),
          mcq('A palindrome reads the same:', ['Forwards only', 'Backwards only', 'Both ways', 'Never'], 2),
          fill('A substring is a ___ contiguous sequence of characters.', ['']),
          fill('Comparing two strings character-by-character is O(___).', ['n']),
          mcq('Naive substring search is O(?):', ['n', 'n log n', 'n + m', 'n·m'], 3, 'medium'),
          mcq('KMP improves naive search to O(?):', ['n', 'n + m', 'n·m', 'n²'], 1, 'medium'),
        ]),
        makeExercise('Pattern Matching', [
          mcq('KMP preprocesses pattern of length m in:', ['O(1)', 'O(m)', 'O(m²)', 'O(m log m)'], 1),
          mcq('Rabin-Karp uses:', ['Hashing', 'Trie', 'BFS', 'DP'], 0),
          mcq('Z-algorithm computes:', ['Suffix array', 'Z array of matches', 'Hash', 'BFS order'], 1),
          mcq('Boyer-Moore best case:', ['O(n/m)', 'O(n)', 'O(n·m)', 'O(n²)'], 0),
          mcq('Aho-Corasick searches multiple patterns in:', ['O(n²)', 'O(n + matches + sum_m)', 'O(n·m)', 'O(2ⁿ)'], 1),
          mcq('Naive matching worst time:', ['O(n)', 'O(n + m)', 'O(n·m)', 'O(log n)'], 2),
          fill('KMP failure function avoids re-checking ___ characters.', ['matched']),
          fill('Rabin-Karp can use ___ hashing for sliding windows.', ['rolling']),
          mcq('Suffix array construction (efficient):', ['O(n²)', 'O(n log n)', 'O(n²·log n)', 'O(n!)'], 1, 'medium'),
          mcq('Longest palindromic substring (Manacher):', ['O(n²)', 'O(n log n)', 'O(n)', 'O(n³)'], 2, 'medium'),
        ]),
        makeExercise('String Manipulation', [
          mcq('Anagram check via sorting:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(1)'], 1),
          mcq('Anagram check via counts:', ['O(1)', 'O(n)', 'O(n log n)', 'O(n²)'], 1),
          mcq('Reverse words in a string in-place:', ['O(1)', 'O(n)', 'O(n²)', 'O(n log n)'], 1),
          mcq('Check palindrome of length n:', ['O(1)', 'O(n)', 'O(n²)', 'O(log n)'], 1),
          mcq('String concatenation in immutable strings creates:', ['Same string', 'New string', 'Pointer', 'Hash'], 1),
          mcq('Replace all occurrences scanning once:', ['O(1)', 'O(n)', 'O(n²)', 'O(n log n)'], 1),
          fill('StringBuilder/StringBuffer is mutable to avoid ___ copies.', ['repeated']),
          fill('Tokenizing splits a string by ___.', ['delimiter']),
          mcq('Find longest common prefix of n strings (length L):', ['O(n L)', 'O(n²)', 'O(L)', 'O(n²·L)'], 0, 'medium'),
          mcq('Group anagrams of n strings of average length L:', ['O(n² L)', 'O(n L log L)', 'O(n L)', 'O(n³)'], 1, 'medium'),
        ]),
        makeExercise('Substring Problems', [
          mcq('Longest substring without repeating chars (sliding window):', ['O(n²)', 'O(n)', 'O(n log n)', 'O(1)'], 1),
          mcq('Number of substrings of length n:', ['n', 'n²', 'n(n+1)/2', '2ⁿ'], 2),
          mcq('Substring search needs to scan up to:', ['n', 'n - m + 1', 'n²', 'log n'], 1),
          mcq('Longest repeating character replacement uses:', ['Sliding window', 'DP only', 'BFS', 'Trie only'], 0),
          mcq('Min window substring containing chars of pattern:', ['O(n²)', 'O(n)', 'O(n log n)', 'O(n!)'], 1),
          mcq('Counting palindromic substrings naively:', ['O(n)', 'O(n²)', 'O(n³)', 'O(n log n)'], 2),
          fill('Manacher gives all palindromic substrings in O(___).', ['n']),
          fill('Sliding window uses two ___ pointers.', ['index']),
          mcq('Substring with concatenation of all words length n, k words length L:', ['O(n²)', 'O(n·k·L)', 'O(n·L)', 'O(n³)'], 2, 'medium'),
          mcq('Distinct substrings of string of length n via suffix array + LCP:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(n³)'], 1, 'medium'),
        ]),
        makeExercise('Tries (Intro)', [
          mcq('Trie node typically stores:', ['Single char + children', 'Full word', 'Hash', 'Vector'], 0),
          mcq('Insert word of length L:', ['O(1)', 'O(L)', 'O(n)', 'O(L²)'], 1),
          mcq('Search word of length L:', ['O(1)', 'O(L)', 'O(n)', 'O(L²)'], 1),
          mcq('Trie is ideal for ___ queries:', ['range sum', 'prefix', 'hash', 'BFS'], 1),
          mcq('Memory grows with sum of:', ['Word counts', 'Word lengths', 'Constants', 'Log n'], 1),
          mcq('Autocomplete uses:', ['Heap', 'Trie', 'BFS', 'DP only'], 1),
          fill('Trie root represents the empty ___.', ['prefix']),
          fill('Compressed trie is also called a ___ tree.', ['radix']),
          mcq('Search prefix and list all words below: time:', ['O(L)', 'O(L + outputs)', 'O(n)', 'O(n²)'], 1, 'medium'),
          mcq('Trie insertion of n words of avg length L:', ['O(n L)', 'O(L log n)', 'O(n²)', 'O(L²)'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Linked Lists',
      description: 'Single & doubly linked lists, basic operations.',
      exercises: [
        makeExercise('Singly Linked List', [
          mcq('Each node holds at minimum:', ['Data only', 'Pointer only', 'Data and a next pointer', 'Two pointers'], 2),
          mcq('Insert at head of singly linked list:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 0),
          mcq('Search in singly linked list:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 2),
          mcq('Linked lists allow random access:', ['Always', 'Never (O(n) traversal)', 'Sometimes', 'Only sorted'], 1),
          mcq('A circular linked list:', ['Has no end', 'Has only one node', 'Cannot be traversed', 'Has 2 heads'], 0),
          mcq('Doubly linked node has:', ['Data + next', 'Data + prev + next', 'Data + 3 pointers', 'Just data'], 1),
          fill('To delete a non-head node by reference in O(1) you can copy the ___ node\u2019s data.', ['next']),
          fill('Linked lists are useful when ___ insertions are frequent.', ['middle']),
          mcq('Detect cycle in linked list with O(1) space using:', ['Hash set', 'Floyd\u2019s tortoise & hare', 'Sorting', 'Stack'], 1, 'medium'),
          mcq('Reverse a linked list iteratively in time/space:', ['O(n)/O(n)', 'O(n)/O(1)', 'O(n²)/O(1)', 'O(log n)/O(1)'], 1, 'medium'),
        ]),
        makeExercise('Doubly Linked List', [
          mcq('Doubly linked node has pointers to:', ['Next only', 'Previous only', 'Previous and next', 'Random'], 2),
          mcq('Delete node given pointer (DLL):', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 0),
          mcq('DLL needs more memory because:', ['Two pointers per node', 'Fewer nodes', 'No data', 'No reason'], 0),
          mcq('LRU cache typically uses:', ['SLL only', 'DLL + hash map', 'Heap', 'Trie'], 1),
          mcq('Insertion before a known node in DLL:', ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], 0),
          mcq('Traversing DLL from tail backward needs:', ['Hash', 'Stack', 'Prev pointers', 'BFS'], 2),
          fill('A circular DLL has tail.next = ___.', ['head']),
          fill('LRU eviction removes the ___-recently used node.', ['least']),
          mcq('Time for LRU get/put with DLL+Hash:', ['O(log n)', 'O(1)', 'O(n)', 'O(n log n)'], 1, 'medium'),
          mcq('Deletion of head in DLL:', ['O(n)', 'O(1)', 'O(log n)', 'O(n²)'], 1, 'medium'),
        ]),
        makeExercise('Reversal Patterns', [
          mcq('Reverse SLL recursively uses stack space:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 2),
          mcq('Reverse k-group needs:', ['Multiple pointers', 'Hash', 'Heap', 'BFS'], 0),
          mcq('Palindrome check on linked list with O(1) extra space uses:', ['Reverse half', 'Stack of all', 'Hash all', 'Sort'], 0),
          mcq('Swap pairs in linked list:', ['O(n²)', 'O(n)', 'O(log n)', 'O(1)'], 1),
          mcq('Rotate list right by k:', ['O(n²)', 'O(n + k mod n)', 'O(log n)', 'O(k²)'], 1),
          mcq('Reorder list (L0→Ln→L1→Ln-1...) needs:', ['Find mid + reverse + merge', 'Sort', 'Heap', 'Hash only'], 0),
          fill('To reverse a list, you typically use three pointers: prev, curr, ___.', ['next']),
          fill('Reversing a circular list breaks the ___.', ['cycle']),
          mcq('Reverse k-group when n%k != 0, leave the last group:', ['Reversed', 'As-is', 'Skipped', 'Removed'], 1, 'medium'),
          mcq('Recursive reverse SLL space complexity:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 2, 'medium'),
        ]),
        makeExercise('Cycle Detection', [
          mcq('Floyd’s algorithm uses:', ['One pointer', 'Two pointers (slow & fast)', 'Hash', 'Stack'], 1),
          mcq('Floyd time:', ['O(log n)', 'O(n)', 'O(n²)', 'O(1)'], 1),
          mcq('Floyd extra space:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 0),
          mcq('Hash-set cycle detection space:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 2),
          mcq('Cycle start can be found by:', ['Reset slow to head', 'Sort', 'Hash all', 'BFS'], 0),
          mcq('Brent’s algorithm is alternative to:', ['Floyd', 'Dijkstra', 'BFS', 'KMP'], 0),
          fill('Slow moves 1 step, fast moves ___ steps.', ['2']),
          fill('Tortoise and hare meet inside the ___.', ['cycle']),
          mcq('After meeting, distance from head to cycle start equals distance from meeting point to start within ___.', ['cycle', 'tail', 'tree', 'list'], 0, 'medium'),
          mcq('Detect cycle in directed graph (DFS):', ['Recursion stack tracking', 'BFS', 'Sorting', 'Hashing only'], 0, 'medium'),
        ]),
        makeExercise('Merging Lists', [
          mcq('Merge two sorted SLL:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], 0),
          mcq('Extra space for merge two lists:', ['O(n)', 'O(1) if reusing nodes', 'O(log n)', 'O(n²)'], 1),
          mcq('Merge k sorted lists with min-heap (total N):', ['O(N k)', 'O(N log k)', 'O(N²)', 'O(N log N)'], 1),
          mcq('Merge k sorted lists divide-conquer:', ['O(N k)', 'O(N log k)', 'O(N²)', 'O(N!)'], 1),
          mcq('Sort a linked list optimally:', ['Quicksort', 'Heap sort', 'Merge sort', 'Bubble'], 2),
          mcq('Intersection node of two lists (Y-shape):', ['O(n+m)', 'O(n·m)', 'O(log n)', 'O(n²)'], 0),
          fill('Merge sort on linked list uses ___ partitioning.', ['slow-fast']),
          fill('Adding two numbers represented by lists uses a ___ digit.', ['carry']),
          mcq('Add two numbers (lists) where digits stored in reverse:', ['O(n+m)', 'O(n·m)', 'O(log n)', 'O(n²)'], 0, 'medium'),
          mcq('Detect intersection by length difference:', ['O(n+m) time, O(1) space', 'O(n·m)', 'O(log n)', 'O(n²)'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Stacks & Queues',
      description: 'LIFO/FIFO structures and their applications.',
      exercises: [
        makeExercise('Stacks & Queues Basics', [
          mcq('Stack is:', ['FIFO', 'LIFO', 'Random', 'Sorted'], 1),
          mcq('Queue is:', ['FIFO', 'LIFO', 'Random', 'Sorted'], 0),
          mcq('Push/pop on a stack are typically:', ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'], 2),
          mcq('Browser back button typically uses a:', ['Queue', 'Stack', 'Tree', 'Hash'], 1),
          mcq('Print queue in OS uses a:', ['Queue', 'Stack', 'Tree', 'Heap'], 0),
          mcq('Which checks balanced parentheses?', ['Queue', 'Stack', 'Set', 'Tree'], 1),
          fill('A deque allows insert/remove at ___ ends.', ['both']),
          match('Match structure to use:', ['Undo feature', 'BFS', 'Bracket matching'], ['Stack', 'Queue', 'Stack'], { 'Undo feature': 'Stack', 'BFS': 'Queue', 'Bracket matching': 'Stack' }),
          mcq('Implement a queue with two stacks: amortized push/pop is:', ['O(n)', 'O(log n)', 'O(1)', 'O(n log n)'], 2, 'medium'),
          mcq('Stack overflow happens when:', ['Stack is empty', 'Pop on empty', 'Push beyond capacity', 'Top is null'], 2, 'medium'),
        ]),
        makeExercise('Stack Implementations', [
          mcq('Stack via array push/pop:', ['O(1) amortized', 'O(log n)', 'O(n)', 'O(n²)'], 0),
          mcq('Stack via linked list push/pop:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 0),
          mcq('Min-stack supports push/pop/min in:', ['O(log n)', 'O(1)', 'O(n)', 'O(n log n)'], 1),
          mcq('Min-stack uses additional:', ['Hash', 'Auxiliary stack', 'Tree', 'Heap'], 1),
          mcq('Dynamic array stack resize cost amortized:', ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'], 2),
          mcq('Two stacks in one array supports:', ['Either grows independently', 'Only fixed', 'Random', 'Trees'], 0),
          fill('Top of stack pointer increments on ___.', ['push']),
          fill('Empty stack peek/pop should raise ___.', ['error']),
          mcq('Implement stack using queues (push costly):', ['O(n) push, O(1) pop', 'O(1) both', 'O(log n)', 'O(n²) push'], 0, 'medium'),
          mcq('Persistent stack supports old versions in:', ['O(n)', 'O(log n)', 'O(1) per op via cons-list', 'O(n²)'], 2, 'medium'),
        ]),
        makeExercise('Expression Evaluation', [
          mcq('Postfix evaluation uses:', ['Stack', 'Queue', 'Heap', 'Tree'], 0),
          mcq('Infix to postfix uses:', ['Shunting-yard', 'BFS', 'Hash', 'DP'], 0),
          mcq('Operator precedence is honored via:', ['Stack of operators', 'Queue', 'Heap', 'Trie'], 0),
          mcq('Parenthesis matching uses:', ['Stack', 'Queue', 'Heap', 'Hash'], 0),
          mcq('Prefix evaluation scans:', ['Left to right', 'Right to left', 'Random', 'Both'], 1),
          mcq('Evaluate postfix expression of n tokens:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 2),
          fill('Shunting-yard outputs operators when precedence is ___.', ['lower']),
          fill('Postfix is also called ___ Polish notation.', ['Reverse']),
          mcq('Infix to postfix complexity:', ['O(n²)', 'O(n log n)', 'O(n)', 'O(n!)'], 2, 'medium'),
          mcq('Validate balanced ()[]{} in O(n) using:', ['Stack', 'Queue', 'Heap', 'DP'], 0, 'medium'),
        ]),
        makeExercise('Monotonic Stack', [
          mcq('Monotonic stack maintains order:', ['Random', 'Increasing or decreasing', 'Sorted by hash', 'Reversed'], 1),
          mcq('Next greater element runs in:', ['O(n²)', 'O(n)', 'O(log n)', 'O(n log n)'], 1),
          mcq('Largest rectangle in histogram:', ['O(n²)', 'O(n log n)', 'O(n) with stack', 'O(n³)'], 2),
          mcq('Daily temperatures problem uses:', ['Monotonic stack', 'BFS', 'Heap', 'Trie'], 0),
          mcq('Stack pops while top violates:', ['Order condition', 'Hash', 'Range', 'Time'], 0),
          mcq('Sliding window maximum optimal:', ['Monotonic deque O(n)', 'Heap O(n log n)', 'Sort', 'Brute O(n·k)'], 0),
          fill('Monotonic decreasing stack helps find next ___ element.', ['greater']),
          fill('Monotonic increasing stack helps find next ___ element.', ['smaller']),
          mcq('Trapping rain water with stack:', ['O(n²)', 'O(n)', 'O(log n)', 'O(n log n)'], 1, 'medium'),
          mcq('Stock span problem (n days):', ['O(n²)', 'O(n)', 'O(log n)', 'O(n log n)'], 1, 'medium'),
        ]),
        makeExercise('Queue via Stacks & Deque', [
          mcq('Queue from two stacks: enqueue:', ['O(n)', 'O(1)', 'O(log n)', 'O(n²)'], 1),
          mcq('Queue from two stacks: dequeue amortized:', ['O(n)', 'O(1)', 'O(log n)', 'O(n²)'], 1),
          mcq('Deque supports insert/remove at:', ['Front only', 'Rear only', 'Both ends', 'Middle'], 2),
          mcq('Circular queue avoids:', ['Wrapping', 'Wasted space when front advances', 'Push', 'Pop'], 1),
          mcq('Priority queue is NOT necessarily:', ['Sorted', 'FIFO for equal priority', 'Heap', 'Useful'], 1),
          mcq('Java’s ArrayDeque supports stack & queue ops in:', ['O(n)', 'O(log n)', 'O(1) amortized', 'O(n log n)'], 2),
          fill('Sliding window max uses a monotonic ___.', ['deque']),
          fill('Circular queue uses modulo by ___.', ['capacity']),
          mcq('Implement queue with one stack (recursion in dequeue):', ['O(1) enqueue, O(n) dequeue', 'Both O(1)', 'O(log n)', 'Impossible'], 0, 'medium'),
          mcq('Min-queue (track running min in window) optimal:', ['Monotonic deque O(n)', 'Heap O(n log n)', 'Brute O(n·k)', 'Sort'], 0, 'medium'),
        ]),
      ],
    },
  ],

  2: [
    {
      title: 'Hashing',
      description: 'Hash tables, sets, and common problems.',
      exercises: [
        makeExercise('Hash Maps', [
          mcq('Average lookup in a hash map:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 0),
          mcq('Worst case lookup in a hash map (with bad hash):', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 2),
          mcq('Two values mapping to same slot is called:', ['Overflow', 'Collision', 'Conflict', 'Hash hit'], 1),
          mcq('Open addressing handles collisions by:', ['Chaining', 'Probing', 'Resizing', 'Skipping'], 1),
          mcq('Load factor = entries / ?', ['hash size', 'bucket count', 'capacity', 'collisions'], 2),
          mcq('Java HashMap fallback for many collisions:', ['Tree', 'Heap', 'Sorted array', 'Linked list only'], 0),
          fill('A good hash function distributes keys ___.', ['uniformly']),
          fill('Set is a hash map without ___.', ['values']),
          mcq('Two-sum with a hash map runs in:', ['O(n²)', 'O(n log n)', 'O(n)', 'O(log n)'], 2, 'medium'),
          mcq('Anagram check via frequency map (length n):', ['O(n²)', 'O(n)', 'O(n log n)', 'O(1)'], 1, 'medium'),
        ]),
        makeExercise('Collision Resolution', [
          mcq('Separate chaining stores collisions in:', ['Heap', 'Linked list / list per bucket', 'Trie', 'Stack'], 1),
          mcq('Linear probing checks next:', ['Random index', 'Adjacent slot', 'Hash again', 'Tree'], 1),
          mcq('Quadratic probing offsets by:', ['1, 2, 3', '1, 4, 9', '2, 4, 6', '1, 1, 1'], 1),
          mcq('Double hashing uses:', ['Two hash functions', 'Tree', 'Heap', 'Stack'], 0),
          mcq('Cluster formation primarily affects:', ['Chaining', 'Linear probing', 'Random hashing', 'Trie'], 1),
          mcq('Robin Hood hashing equalizes:', ['Probe distances', 'Hash values', 'Bucket sizes', 'Heap depths'], 0),
          fill('Open addressing keeps all entries inside the ___ table.', ['hash']),
          fill('Cuckoo hashing uses ___ hash functions.', ['two']),
          mcq('Worst-case operation in chained hash with bad hash:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 2, 'medium'),
          mcq('Resizing hash table when load factor exceeds threshold gives amortized:', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 0, 'medium'),
        ]),
        makeExercise('Hash Functions', [
          mcq('Good hash functions are:', ['Slow', 'Deterministic & well-distributed', 'Random per call', 'Empty'], 1),
          mcq('String hashing typically uses polynomial rolling hash with prime base for:', ['Speed only', 'Reducing collisions', 'Increasing memory', 'Sorting'], 1),
          mcq('Cryptographic hashes are usually ___ for hash maps.', ['too slow', 'fast', 'random', 'small'], 0),
          mcq('Universal hashing reduces:', ['Adversarial collisions', 'Memory', 'Cache misses', 'I/O'], 0),
          mcq('FNV-1a is a:', ['Sort algo', 'Non-crypto hash', 'BFS variant', 'Graph algo'], 1),
          mcq('Modulo by prime helps distribute keys when:', ['Keys cluster', 'Always', 'Never', 'Heaps used'], 0),
          fill('Hash + modulo by table size produces a ___.', ['bucket']),
          fill('A perfect hash function has zero ___.', ['collisions']),
          mcq('Polynomial rolling hash mod p, base b on string of length n:', ['O(1)', 'O(n)', 'O(n log n)', 'O(n²)'], 1, 'medium'),
          mcq('Birthday paradox implies collisions appear after ~√m inserts in a table of size:', ['m', 'm²', 'log m', '√m'], 0, 'medium'),
        ]),
        makeExercise('Sets & Multisets', [
          mcq('HashSet stores:', ['Unique keys', 'Key-value', 'Sorted keys', 'Trie'], 0),
          mcq('TreeSet (ordered) operations are typically:', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 1),
          mcq('Multiset allows:', ['Duplicates', 'Only unique', 'Random delete', 'No insert'], 0),
          mcq('Union of two sets of size n, m via hash:', ['O(n+m)', 'O(n·m)', 'O(log(n+m))', 'O(n²)'], 0),
          mcq('Intersection check element membership in:', ['O(1) avg', 'O(n)', 'O(log n)', 'O(n²)'], 0),
          mcq('Bitset is a set when keys are:', ['Strings', 'Small integers', 'Floats', 'Trees'], 1),
          fill('Disjoint sets are also called ___.', ['mutually exclusive']),
          fill('A multiset stores frequency via a ___ map.', ['count']),
          mcq('Find pair with given sum in array using set:', ['O(n²)', 'O(n log n)', 'O(n)', 'O(1)'], 2, 'medium'),
          mcq('Distinct elements count via hash set:', ['O(n²)', 'O(n log n)', 'O(n)', 'O(1)'], 2, 'medium'),
        ]),
        makeExercise('Frequency & Counting', [
          mcq('Counter object stores:', ['Unique items only', 'Item → count', 'Sorted items', 'Heap'], 1),
          mcq('Find majority element (>n/2) optimally (Boyer-Moore):', ['O(n) time, O(1) space', 'O(n log n)', 'O(n²)', 'O(n) time, O(n) space'], 0),
          mcq('Top-K frequent elements with bucket sort:', ['O(n log n)', 'O(n)', 'O(n²)', 'O(n log K)'], 1),
          mcq('Group elements by key uses:', ['Hash map of lists', 'Heap', 'Trie', 'BFS'], 0),
          mcq('Find duplicate in n+1 numbers in [1..n]:', ['Sort O(n log n)', 'Set O(n)', 'Floyd cycle O(1) space', 'All'], 3),
          mcq('Subarray sum equals K using prefix sums + hash:', ['O(n²)', 'O(n)', 'O(n log n)', 'O(1)'], 1),
          fill('Counter uses dictionary internally to store ___.', ['counts']),
          fill('Sliding window with hash detects substring of length k with ___ chars.', ['unique']),
          mcq('Top-K frequent with heap:', ['O(n log K)', 'O(n)', 'O(K log n)', 'O(n log n)'], 0, 'medium'),
          mcq('Longest substring with at most K distinct characters:', ['O(n²)', 'O(n)', 'O(n log n)', 'O(n·K)'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Trees',
      description: 'Binary trees, BSTs, and traversals.',
      exercises: [
        makeExercise('Tree Traversals', [
          mcq('Inorder traversal of BST gives:', ['Random order', 'Sorted order', 'Reverse order', 'Level order'], 1),
          mcq('Pre-order visits node:', ['Before children', 'After children', 'Between children', 'Never'], 0),
          mcq('Post-order visits node:', ['Before children', 'After children', 'Between children', 'Never'], 1),
          mcq('Level-order traversal uses:', ['Stack', 'Queue', 'Heap', 'Set'], 1),
          mcq('Height of a tree with one node:', ['-1', '0', '1', '2'], 1),
          mcq('A complete binary tree of n nodes has height:', ['n', 'n/2', 'log n', '√n'], 2),
          fill('A leaf node has ___ children.', ['no']),
          fill('A binary tree node has at most ___ children.', ['two']),
          mcq('In a BST, left subtree contains values that are:', ['Greater', 'Lesser', 'Equal', 'Random'], 1, 'medium'),
          mcq('Search/insert in a balanced BST:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 1, 'medium'),
        ]),
        makeExercise('BST Operations', [
          mcq('Min of BST is at:', ['Rightmost', 'Leftmost', 'Root', 'Random'], 1),
          mcq('Max of BST is at:', ['Rightmost', 'Leftmost', 'Root', 'Random'], 0),
          mcq('Insertion in skewed BST worst case:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 2),
          mcq('AVL tree balance factor range:', ['{-1,0,1}', '{-2,2}', '{0..n}', '{0,1}'], 0),
          mcq('Red-black tree guarantees height:', ['O(1)', 'O(log n)', 'O(n)', 'O(√n)'], 1),
          mcq('Trie is best for:', ['Sorting', 'Prefix queries', 'Range sums', 'Graph BFS'], 1),
          fill('In an AVL tree, height difference of subtrees \u2264 ___.', ['1']),
          fill('Deletion from BST may require finding the in-order ___.', ['successor']),
          mcq('Merging two BSTs of sizes n and m optimally:', ['O((n+m)²)', 'O((n+m) log (n+m))', 'O(n+m)', 'O(n·m)'], 2, 'medium'),
          mcq('Lowest common ancestor in BST runs in:', ['O(1)', 'O(h)', 'O(n)', 'O(n log n)'], 1, 'medium'),
        ]),
        makeExercise('Balanced Trees', [
          mcq('AVL is balanced by:', ['Color', 'Height difference ≤ 1', 'Random', 'Hash'], 1),
          mcq('Red-black trees use:', ['Heights', 'Colors and rules', 'Random', 'Hash'], 1),
          mcq('Splay tree moves accessed nodes to:', ['Bottom', 'Root', 'Random', 'Leaves'], 1),
          mcq('B-tree of order m has at most m:', ['Children per node', 'Levels', 'Keys per node', 'Roots'], 0),
          mcq('B+ tree stores all data in:', ['Root', 'Internal nodes', 'Leaf nodes (linked)', 'Random'], 2),
          mcq('Treap combines:', ['Tree + heap (random priorities)', 'Tree + hash', 'Heap + hash', 'Tree + trie'], 0),
          fill('AVL rotations are at most ___ per insertion to rebalance.', ['2']),
          fill('Red-black trees guarantee O(log n) operations even after ___.', ['updates']),
          mcq('Skip list expected operations:', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 1, 'medium'),
          mcq('B-tree minimizes:', ['Disk I/O', 'CPU cycles only', 'Memory', 'Cache misses only'], 0, 'medium'),
        ]),
        makeExercise('Tree Construction & Properties', [
          mcq('Build tree from inorder + preorder:', ['Unique tree', 'Multiple', 'Impossible', 'Random'], 0),
          mcq('Build tree from inorder + postorder:', ['Unique tree', 'Multiple', 'Impossible', 'Random'], 0),
          mcq('Build tree from preorder + postorder:', ['Unique always', 'Not unique generally', 'Impossible', 'Random'], 1),
          mcq('Diameter of binary tree:', ['Max path between any two leaves', 'Number of nodes', 'Height', 'Hash'], 0),
          mcq('Number of full binary trees with n nodes follows:', ['Linear', 'Catalan numbers', 'Fibonacci', 'Random'], 1),
          mcq('Serialize/deserialize tree commonly uses:', ['Pre-order with nulls', 'Hash only', 'Heap', 'Trie'], 0),
          fill('Mirror image of a tree swaps each node’s ___ children.', ['two']),
          fill('Tree is balanced if for every node, height diff ≤ ___.', ['1']),
          mcq('LCA of binary tree (no parent ptrs) DFS:', ['O(log n)', 'O(n)', 'O(n²)', 'O(1)'], 1, 'medium'),
          mcq('Vertical order traversal uses BFS + hash by:', ['Depth', 'Column index', 'Random', 'Hash of value'], 1, 'medium'),
        ]),
        makeExercise('Tries (Advanced)', [
          mcq('Trie supports prefix search in:', ['O(L)', 'O(n)', 'O(L·n)', 'O(L²)'], 0),
          mcq('Word search II (Boggle) uses:', ['Trie + DFS', 'Heap', 'BFS only', 'DP'], 0),
          mcq('Trie counts: each insertion increments ___ on the path.', ['count', 'hash', 'depth', 'rank'], 0),
          mcq('Replace words in sentence by shortest root uses:', ['Trie', 'Heap', 'BFS', 'DP only'], 0),
          mcq('Bitwise trie helps with:', ['Max XOR pair', 'Sorting', 'Hashing', 'Sum'], 0),
          mcq('Number of distinct substrings via suffix trie:', ['O(n)', 'O(n²) nodes', 'O(n log n)', 'O(n!)'], 1),
          fill('Trie supports autocomplete using ___ traversal.', ['DFS']),
          fill('Generalized suffix tree handles ___ strings.', ['multiple']),
          mcq('Max XOR of subarray using trie of prefix XORs:', ['O(n²)', 'O(n log V)', 'O(n)', 'O(n³)'], 1, 'medium'),
          mcq('Concatenation of n words length L into trie:', ['O(L log n)', 'O(n L)', 'O(n²)', 'O(L²)'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Heaps & Priority Queues',
      description: 'Binary heap operations and applications.',
      exercises: [
        makeExercise('Binary Heap', [
          mcq('Min-heap root holds:', ['Max value', 'Min value', 'Median', 'Random'], 1),
          mcq('Insertion in a heap is:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 1),
          mcq('Extract-min is:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 1),
          mcq('Heap is typically stored as:', ['Linked list', 'Hash table', 'Array', 'Tree of nodes'], 2),
          mcq('Index of left child of i in 0-indexed heap:', ['i+1', '2i', '2i+1', '2i+2'], 2),
          mcq('Index of parent of i (0-indexed):', ['(i-1)/2', '(i+1)/2', '2i+1', 'i/2'], 0),
          fill('Building a heap from an array runs in O(___).', ['n']),
          fill('Heap sort runs in O(___).', ['n log n']),
          mcq('Top-K largest from n elements with min-heap of size K:', ['O(n²)', 'O(n log K)', 'O(K log n)', 'O(K²)'], 1, 'medium'),
          mcq('Priority queue is naturally implemented with:', ['Stack', 'Heap', 'Set', 'Trie'], 1, 'medium'),
        ]),
        makeExercise('Heap Sort', [
          mcq('Heap sort uses heap to:', ['Insert sorted', 'Extract sorted via repeated extract-max', 'Hash', 'BFS'], 1),
          mcq('Heap sort time:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], 1),
          mcq('Heap sort is in-place with O(?) extra space:', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 0),
          mcq('Heap sort stability:', ['Stable', 'Not stable', 'Sometimes', 'Always'], 1),
          mcq('Build-heap operation is:', ['O(n)', 'O(n log n)', 'O(log n)', 'O(n²)'], 0),
          mcq('Heapify down on root after extract:', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 1),
          fill('Heap sort uses a ___-heap to sort ascending.', ['max']),
          fill('Heap sort always runs in O(___) regardless of input.', ['n log n']),
          mcq('Compared to quicksort, heap sort:', ['Faster average', 'No worst-case O(n²)', 'Less memory than merge', 'Both b and c'], 3, 'medium'),
          mcq('Floyd build-heap is O(n) because work at depth d is bounded by:', ['O(2^d · d)', 'O(n/2^d · d)', 'O(n)', 'O(log n)'], 1, 'medium'),
        ]),
        makeExercise('K-th Element Problems', [
          mcq('Find K largest with min-heap of size K:', ['O(n)', 'O(n log K)', 'O(K log n)', 'O(n²)'], 1),
          mcq('Find K smallest with max-heap of size K:', ['O(n)', 'O(n log K)', 'O(K log n)', 'O(n²)'], 1),
          mcq('Median of stream using two heaps:', ['O(n)', 'O(log n) per insert', 'O(1)', 'O(n log n) per insert'], 1),
          mcq('Quickselect average:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], 0),
          mcq('Quickselect worst:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], 2),
          mcq('Median of medians selection:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], 0),
          fill('K-th largest can be found with min-heap of size ___.', ['K']),
          fill('Two-heaps maintain low (max-heap) and high (___-heap).', ['min']),
          mcq('K closest points to origin with heap:', ['O(n log n)', 'O(n log K)', 'O(K log n)', 'O(n²)'], 1, 'medium'),
          mcq('Sliding window median optimal:', ['Two heaps with lazy delete O(n log n)', 'Sort O(n·k)', 'Heap O(n·k log k)', 'Brute O(n²)'], 0, 'medium'),
        ]),
        makeExercise('Heap Variants', [
          mcq('Binomial heap merge:', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 1),
          mcq('Fibonacci heap decrease-key amortized:', ['O(log n)', 'O(1)', 'O(n)', 'O(n log n)'], 1),
          mcq('Pairing heap is simple alternative to:', ['Fibonacci', 'Binary', 'BFS', 'Trie'], 0),
          mcq('D-ary heap reduces height by:', ['Increasing branching', 'Decreasing branching', 'Random', 'Hashing'], 0),
          mcq('Indexed heap supports:', ['Update by key', 'Random delete', 'Both', 'Neither'], 2),
          mcq('Leftist heap supports merge in:', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 1),
          fill('Fibonacci heap supports decrease-key in amortized O(___).', ['1']),
          fill('Binomial trees of order k have 2^___ nodes.', ['k']),
          mcq('Why Fibonacci heap helps Dijkstra:', ['Faster decrease-key', 'Faster extract-min', 'No reason', 'Memory'], 0, 'medium'),
          mcq('Skew heap supports operations in amortized:', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 1, 'medium'),
        ]),
        makeExercise('Heap Applications', [
          mcq('Dijkstra uses priority queue to extract:', ['Max distance', 'Min distance', 'Random', 'Sorted by id'], 1),
          mcq('Huffman coding builds tree by repeatedly extracting:', ['Two min frequencies', 'Two max', 'Random', 'Median'], 0),
          mcq('Merge K sorted arrays with min-heap:', ['O(N)', 'O(N log K)', 'O(N²)', 'O(N log N)'], 1),
          mcq('Task scheduling by deadlines often uses:', ['Heap', 'Hash only', 'BFS', 'Trie'], 0),
          mcq('Event-driven simulation uses:', ['PQ of events', 'Stack', 'Trie', 'BFS only'], 0),
          mcq('A* search uses PQ keyed by:', ['g(n) + h(n)', 'Random', 'Distance only', 'Heuristic only'], 0),
          fill('Heap-based PQ is the backbone of ___’s shortest path.', ['Dijkstra']),
          fill('Huffman coding produces ___ codes by frequency.', ['variable-length']),
          mcq('CPU scheduling SJF picks job with ___ burst:', ['shortest', 'longest', 'random', 'medium'], 0, 'medium'),
          mcq('Min-heap K-way merge memory:', ['O(N)', 'O(K)', 'O(log K)', 'O(N log K)'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Graphs Intro',
      description: 'Representations and basic traversals.',
      exercises: [
        makeExercise('Graphs Basics', [
          mcq('Adjacency list space for V nodes, E edges:', ['O(V²)', 'O(V+E)', 'O(E²)', 'O(log V)'], 1),
          mcq('Adjacency matrix space:', ['O(V)', 'O(V+E)', 'O(V²)', 'O(E²)'], 2),
          mcq('BFS explores nodes by:', ['Depth', 'Level', 'Random', 'Weight'], 1),
          mcq('DFS uses (recursive):', ['Queue', 'Stack', 'Heap', 'Set'], 1),
          mcq('Cycle in undirected graph can be detected by:', ['Topological sort', 'DFS with parent check', 'BFS only', 'Heap'], 1),
          mcq('Dijkstra requires edges to be:', ['Negative', 'Non-negative', 'Equal', 'Integer only'], 1),
          fill('A connected graph with no cycles is a ___.', ['tree']),
          fill('Topological sort applies to ___ graphs.', ['DAG']),
          mcq('Single-source shortest path on unweighted graph:', ['Dijkstra', 'Bellman-Ford', 'BFS', 'DFS'], 2, 'medium'),
          mcq('Time of BFS:', ['O(V·E)', 'O(V+E)', 'O(V²)', 'O(E²)'], 1, 'medium'),
        ]),
        makeExercise('Graph Representations', [
          mcq('Adjacency matrix space:', ['O(V)', 'O(V+E)', 'O(V²)', 'O(E²)'], 2),
          mcq('Adjacency list better when:', ['Dense', 'Sparse', 'Always', 'Never'], 1),
          mcq('Edge list space:', ['O(V)', 'O(E)', 'O(V²)', 'O(V+E)'], 1),
          mcq('Weighted adjacency list stores:', ['Pair (vertex, weight)', 'Vertex only', 'Weight only', 'Hash'], 0),
          mcq('Check edge existence in matrix:', ['O(1)', 'O(V)', 'O(E)', 'O(log V)'], 0),
          mcq('Check edge existence in adj list:', ['O(1)', 'O(degree)', 'O(V)', 'O(E)'], 1),
          fill('Sparse graphs are typically stored as adjacency ___.', ['list']),
          fill('Dense graphs are typically stored as adjacency ___.', ['matrix']),
          mcq('Iterating all edges from adjacency matrix:', ['O(V)', 'O(E)', 'O(V²)', 'O(V+E)'], 2, 'medium'),
          mcq('Iterating all edges from adjacency list:', ['O(V)', 'O(E)', 'O(V+E)', 'O(V²)'], 2, 'medium'),
        ]),
        makeExercise('BFS Patterns', [
          mcq('BFS finds shortest path on unweighted graphs because it expands by:', ['Distance', 'Random', 'Depth', 'Cost'], 0),
          mcq('BFS data structure:', ['Stack', 'Queue', 'Heap', 'Trie'], 1),
          mcq('Multi-source BFS initializes queue with:', ['One source', 'All sources', 'Random subset', 'No source'], 1),
          mcq('Bipartite check uses BFS with:', ['Coloring', 'Heap', 'DP', 'Trie'], 0),
          mcq('Word ladder problem solved with:', ['BFS', 'DFS', 'Hash only', 'Trie only'], 0),
          mcq('0-1 BFS uses:', ['Deque', 'Heap', 'Queue', 'Stack'], 0),
          fill('BFS visits each edge at most ___ times.', ['twice']),
          fill('BFS layer by layer corresponds to ___ from source.', ['distance']),
          mcq('Number of shortest paths via BFS uses extra:', ['Counters per node', 'Heap', 'DP', 'Trie'], 0, 'medium'),
          mcq('Shortest path in grid w/ obstacles via BFS:', ['O(rows·cols)', 'O((rows·cols)²)', 'O(log(rows))', 'O(rows!)'], 0, 'medium'),
        ]),
        makeExercise('DFS Patterns', [
          mcq('DFS detects cycles in undirected graph using:', ['Parent check', 'Hash only', 'BFS layer', 'Heap'], 0),
          mcq('DFS detects cycles in directed graph using:', ['Recursion stack / coloring', 'BFS only', 'Hash of nodes', 'Heap'], 0),
          mcq('Bridge detection uses:', ['Tarjan low-link DFS', 'BFS', 'DP', 'Trie'], 0),
          mcq('Articulation point detection:', ['Tarjan low-link DFS', 'BFS', 'Hash', 'Heap'], 0),
          mcq('DFS tree edges classified into:', ['Tree, back, forward, cross', 'Only tree', 'Only back', 'Random'], 0),
          mcq('Recursive DFS uses stack space:', ['O(1)', 'O(log V)', 'O(V) worst', 'O(E)'], 2),
          fill('Iterative DFS uses an explicit ___.', ['stack']),
          fill('DFS post-order is useful for ___ sort.', ['topological']),
          mcq('DFS time complexity:', ['O(V)', 'O(V+E)', 'O(V²)', 'O(E²)'], 1, 'medium'),
          mcq('Connected components via DFS on undirected:', ['O(V+E)', 'O(V·E)', 'O(V²)', 'O(E²)'], 0, 'medium'),
        ]),
        makeExercise('Topological Sort', [
          mcq('Topological sort applies to:', ['Any graph', 'DAG', 'Trees only', 'Bipartite only'], 1),
          mcq('Kahn’s algorithm uses:', ['BFS with in-degree', 'DFS only', 'Heap', 'Hash'], 0),
          mcq('DFS-based topo sort uses:', ['Pre-order', 'Post-order reversed', 'Level-order', 'Random'], 1),
          mcq('Topo sort time:', ['O(V)', 'O(V+E)', 'O(V²)', 'O(E²)'], 1),
          mcq('Cycle in directed graph means topo sort:', ['Exists', 'Does not exist', 'Random', 'Always exists'], 1),
          mcq('Topological order is unique iff at each step there’s exactly:', ['One zero in-degree node', 'Two', 'No', 'Infinite'], 0),
          fill('Course schedule problem reduces to topological ___.', ['sort']),
          fill('Kahn’s removes nodes with in-degree ___.', ['0']),
          mcq('Lexicographically smallest topo order uses:', ['Min-heap of zero in-degree nodes', 'Stack', 'Random', 'BFS plain'], 0, 'medium'),
          mcq('Detect cycle in directed graph alternative to coloring:', ['Topo sort failure (Kahn)', 'BFS distance', 'DSU', 'Heap'], 0, 'medium'),
        ]),
      ],
    },
  ],

  3: [
    {
      title: 'Dynamic Programming',
      description: 'Memoization, tabulation and classic DPs.',
      exercises: [
        makeExercise('Foundations of DP', [
          mcq('DP is useful when problem has:', ['No structure', 'Optimal substructure & overlapping subproblems', 'Random data', 'Only sorted input'], 1),
          mcq('Top-down DP uses:', ['Iteration only', 'Memoization', 'Greedy', 'Divide & conquer only'], 1),
          mcq('Bottom-up DP uses:', ['Recursion only', 'Tabulation', 'Random', 'Greedy'], 1),
          mcq('Fibonacci with memoization is:', ['O(2ⁿ)', 'O(n)', 'O(n log n)', 'O(n²)'], 1),
          mcq('Coin change (min coins) is:', ['Greedy always', 'DP', 'Sorting', 'BFS only'], 1),
          mcq('LIS naive is O(2ⁿ); DP gives:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(n³)'], 2),
          fill('LIS with patience sort runs in O(n ___).', ['log n']),
          fill('Knapsack (0/1) DP is O(n·___).', ['W']),
          mcq('LCS of strings of lengths m, n in DP:', ['O(m+n)', 'O(m·n)', 'O(m·n²)', 'O(2ⁿ)'], 1, 'medium'),
          mcq('Edit distance DP space can be reduced from O(m·n) to:', ['O(1)', 'O(n)', 'O(m+n)', 'O(m·n)'], 1, 'medium'),
        ]),
        makeExercise('Classic DP Problems', [
          mcq('Subset sum (capacity W, n items) runs in:', ['O(n+W)', 'O(n·W)', 'O(n²)', 'O(2ⁿ)'], 1),
          mcq('Matrix chain multiplication minimum scalar mults DP:', ['O(n)', 'O(n²)', 'O(n³)', 'O(2ⁿ)'], 2),
          mcq('Rod cutting DP is:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(2ⁿ)'], 2),
          mcq('Word break with DP/trie is:', ['O(2ⁿ)', 'O(n²) usually', 'O(n)', 'O(n!)'], 1),
          mcq('Number of ways DP often involves:', ['Sum over choices', 'Product only', 'Subtraction', 'Sorting'], 0),
          mcq('Greedy fails for 0/1 knapsack but works for fractional:', ['False', 'True', 'Sometimes', 'Only when sorted'], 1),
          fill('LCS is symmetric: LCS(a,b) = LCS(b, ___).', ['a']),
          fill('Catalan number C(n) counts ___ binary trees.', ['unique']),
          mcq('Bitmask DP for Hamiltonian path on n vertices:', ['O(2ⁿ · n)', 'O(n²)', 'O(n!)', 'O(2ⁿ · n²)'], 3, 'medium'),
          mcq('Longest palindromic subsequence reduces to:', ['LIS', 'LCS of s and reverse(s)', 'Hashing', 'Suffix array'], 1, 'medium'),
        ]),
        makeExercise('DP on Sequences', [
          mcq('LIS DP O(n²) recurrence uses:', ['Max over previous compatible', 'Random', 'Sum', 'Min'], 0),
          mcq('LIS in O(n log n) uses:', ['Patience / binary search', 'BFS', 'Heap only', 'Trie'], 0),
          mcq('Maximum sum increasing subsequence:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(2ⁿ)'], 2),
          mcq('Longest bitonic subsequence:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(2ⁿ)'], 2),
          mcq('Russian doll envelopes reduces to:', ['LIS in 2D', 'LCS', 'Knapsack', 'Hash'], 0),
          mcq('Number of LIS extends LIS DP with:', ['Counts', 'Heap', 'BFS', 'Trie'], 0),
          fill('LIS dp[i] = 1 + max(dp[j]) for j<i where a[j] ___ a[i].', ['<']),
          fill('Longest common subsequence is symmetric over its two ___.', ['arguments']),
          mcq('Wiggle subsequence longest length DP:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(2ⁿ)'], 0, 'medium'),
          mcq('Longest arithmetic subsequence:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(n² log n)'], 2, 'medium'),
        ]),
        makeExercise('DP on Trees', [
          mcq('Tree DP visits nodes in:', ['Pre-order', 'Post-order', 'Level-order', 'Random'], 1),
          mcq('Diameter of tree DP at each node combines:', ['Two longest depths from children', 'Heaps', 'Hashes', 'BFS only'], 0),
          mcq('Maximum independent set on tree DP:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(2ⁿ)'], 0),
          mcq('House robber III (tree variant):', ['Tree DP', 'Greedy', 'BFS only', 'Hash'], 0),
          mcq('Sum of distances in tree (re-rooting) optimal:', ['O(n²)', 'O(n log n)', 'O(n) re-rooting', 'O(n!)'], 2),
          mcq('Knapsack on tree (subtree weight) DP:', ['O(n·W)', 'O(n)', 'O(n²·W)', 'O(2ⁿ)'], 0),
          fill('Re-rooting computes answers from any node by reusing ___ subtree info.', ['child']),
          fill('Tree DP avoids cycles since trees have no ___.', ['cycles']),
          mcq('Number of paths of length k in tree:', ['O(n)', 'O(n·k)', 'O(n²)', 'O(n!)'], 1, 'medium'),
          mcq('Centroid decomposition useful for:', ['Path queries on trees', 'Hashing', 'Sorting', 'BFS only'], 0, 'medium'),
        ]),
        makeExercise('Bitmask DP', [
          mcq('Bitmask DP encodes subsets in:', ['Integer bits', 'Hash', 'Tree', 'Trie'], 0),
          mcq('TSP with bitmask DP:', ['O(2ⁿ · n)', 'O(2ⁿ · n²)', 'O(n!)', 'O(n²)'], 1),
          mcq('Number of subsets of n elements:', ['n', 'n²', '2ⁿ', 'n!'], 2),
          mcq('Iterate over submasks of mask:', ['O(2^n)', 'O(3^n) over all masks', 'O(n)', 'O(n²)'], 1),
          mcq('Bit manipulation: low bit isolation:', ['x & -x', 'x | -x', 'x ^ -x', '~x'], 0),
          mcq('Count set bits using Brian Kernighan:', ['O(log V)', 'O(set bits)', 'O(V)', 'O(1)'], 1),
          fill('Bitmask DP fits when n ≤ ~___.', ['20']),
          fill('Subset sum via bitmask is exponential in ___.', ['n']),
          mcq('Hamiltonian path with bitmask DP:', ['O(2ⁿ · n²)', 'O(n!)', 'O(2ⁿ)', 'O(n²)'], 0, 'medium'),
          mcq('Assignment problem (n workers ↔ tasks) bitmask DP:', ['O(n!)', 'O(2ⁿ · n)', 'O(n³)', 'O(n²)'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Graph Algorithms',
      description: 'Shortest paths, MSTs, flows.',
      exercises: [
        makeExercise('Shortest Paths', [
          mcq('Dijkstra with binary heap:', ['O(V²)', 'O((V+E) log V)', 'O(V·E)', 'O(E²)'], 1),
          mcq('Bellman-Ford handles:', ['Only positive edges', 'Negative edges', 'Floats only', 'DAGs only'], 1),
          mcq('Bellman-Ford complexity:', ['O(V+E)', 'O(V·E)', 'O(V² log V)', 'O(E²)'], 1),
          mcq('All-pairs shortest paths via Floyd-Warshall:', ['O(V²)', 'O(V³)', 'O(V·E)', 'O(E²)'], 1),
          mcq('A* uses:', ['Heuristic', 'Random', 'Greedy only', 'BFS only'], 0),
          mcq('Topological order is unique iff:', ['Graph is DAG', 'Hamiltonian path exists', 'Graph has cycles', 'Always'], 1),
          fill('Negative cycle detection is possible with ___.', ['Bellman-Ford']),
          fill('Shortest path on DAG runs in O(___).', ['V+E']),
          mcq('Johnson\u2019s algorithm complexity:', ['O(V²)', 'O(V·E·log V) approx', 'O(V·E)', 'O(E²)'], 1, 'medium'),
          mcq('Single-source longest path is hard in general because problem is:', ['NP-hard', 'Polynomial', 'Linear', 'Constant'], 0, 'medium'),
        ]),
        makeExercise('MST & Flow', [
          mcq('Kruskal uses:', ['DFS', 'BFS', 'Union-Find', 'Heap only'], 2),
          mcq('Prim with heap:', ['O(V²)', 'O((V+E) log V)', 'O(V·E)', 'O(E²)'], 1),
          mcq('MST is unique iff:', ['Graph is connected', 'Edge weights are distinct', 'V is even', 'Always'], 1),
          mcq('Max-flow equals:', ['Min-cut', 'Max-cut', 'Sum of edges', 'Number of paths'], 0),
          mcq('Ford-Fulkerson with BFS is called:', ['Edmonds-Karp', 'Dinic', 'Hopcroft', 'Karger'], 0),
          mcq('Dinic\u2019s algorithm complexity (general):', ['O(V·E)', 'O(V²·E)', 'O(V·E²)', 'O(E²)'], 1),
          fill('Bipartite matching reduces to ___ flow.', ['max']),
          fill('Strongly connected components: Tarjan or ___.', ['Kosaraju']),
          mcq('Articulation points found via:', ['BFS', 'DFS with low-link', 'Union-Find', 'Heap'], 1, 'medium'),
          mcq('A graph has Eulerian circuit iff:', ['All vertices even-degree & connected', 'Bipartite', 'DAG', 'Tree'], 0, 'medium'),
        ]),
        makeExercise('Strongly Connected Components', [
          mcq('SCC algorithms include:', ['Tarjan & Kosaraju', 'BFS only', 'Dijkstra', 'Bellman-Ford'], 0),
          mcq('Tarjan’s SCC time:', ['O(V·E)', 'O(V+E)', 'O(V²)', 'O(E²)'], 1),
          mcq('Kosaraju uses:', ['Two DFS passes (graph + transpose)', 'BFS only', 'Heap', 'DP'], 0),
          mcq('SCC condensation graph is:', ['DAG', 'Cyclic', 'Bipartite', 'Tree'], 0),
          mcq('Low-link in Tarjan tracks:', ['Earliest reachable node in DFS', 'Random', 'Heap min', 'BFS layer'], 0),
          mcq('2-SAT reduces to:', ['SCC of implication graph', 'BFS', 'DP only', 'Hash'], 0),
          fill('SCC stands for ___ connected component.', ['strongly']),
          fill('After Kosaraju, components are output in topological order on the ___ graph.', ['transpose']),
          mcq('2-SAT solvability check via SCC:', ['Both x and ¬x in same SCC → unsat', 'Always sat', 'Always unsat', 'Random'], 0, 'medium'),
          mcq('Number of SCCs in DAG of n nodes:', ['1', 'n', 'log n', 'depends; ≤ n'], 3, 'medium'),
        ]),
        makeExercise('Network Flow Variants', [
          mcq('Min-cut equals:', ['Max-flow', 'Sum of edges', 'Number of vertices', 'BFS depth'], 0),
          mcq('Edmonds-Karp uses BFS to find augmenting paths in:', ['O(V·E²)', 'O(V²·E)', 'O(V+E)', 'O(E²)'], 0),
          mcq('Dinic’s algorithm uses:', ['Level graph + blocking flows', 'DFS only', 'Heap', 'DP'], 0),
          mcq('Push-relabel general:', ['O(V²·E)', 'O(V·E²)', 'O(V³)', 'O(E²)'], 2),
          mcq('Bipartite matching via Hopcroft-Karp:', ['O(E·√V)', 'O(V·E)', 'O(V²)', 'O(E²)'], 0),
          mcq('Min-cost max-flow uses:', ['Bellman-Ford / SPFA inside flow loop', 'BFS only', 'Heap only', 'DP'], 0),
          fill('A bipartite graph has chromatic number ___.', ['2']),
          fill('Max bipartite matching = min vertex ___ (König).', ['cover']),
          mcq('Min-cut/max-flow useful in image segmentation:', ['False', 'True', 'Sometimes', 'Never'], 1, 'medium'),
          mcq('Project selection problem reduces to:', ['Max-flow / min-cut', 'Sort', 'BFS', 'Hash'], 0, 'medium'),
        ]),
        makeExercise('Advanced Graph Theory', [
          mcq('Eulerian path exists iff:', ['0 or 2 odd-degree vertices (undirected)', '1 odd', '3 odd', 'All even only'], 0),
          mcq('Hamiltonian path problem complexity:', ['NP-complete', 'P', 'Linear', 'Logarithmic'], 0),
          mcq('Chromatic number is min colors for proper:', ['Vertex coloring', 'Edge coloring', 'Face coloring', 'Random'], 0),
          mcq('Planar graph 4-color theorem:', ['Always 4-colorable', '5-colorable only', '3-colorable only', 'Not colorable'], 0),
          mcq('Tree edge traversal Euler tour gives:', ['2(n-1) edges traversed', 'n edges', 'n²', 'log n'], 0),
          mcq('Heavy-Light decomposition supports path queries in:', ['O(log² n)', 'O(n)', 'O(√n)', 'O(1)'], 0),
          fill('Bipartite graphs have no odd ___.', ['cycles']),
          fill('Tree has exactly n - ___ edges.', ['1']),
          mcq('Max independent set on general graph is:', ['NP-hard', 'Polynomial', 'Linear', 'Logarithmic'], 0, 'medium'),
          mcq('Minimum spanning arborescence (directed MST):', ['Chu-Liu/Edmonds', 'Prim', 'Kruskal', 'Bellman-Ford'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Advanced Structures',
      description: 'Segment trees, Fenwick trees, tries, union-find.',
      exercises: [
        makeExercise('Range Queries', [
          mcq('Segment tree update/query:', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 1),
          mcq('Fenwick (BIT) update/query:', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 1),
          mcq('Build segment tree:', ['O(log n)', 'O(n)', 'O(n log n)', 'O(n²)'], 1),
          mcq('Lazy propagation handles:', ['Point updates', 'Range updates', 'Hashing', 'Sorting'], 1),
          mcq('Sparse table best for:', ['Static range min/max', 'Updates', 'Hashing', 'Sorting'], 0),
          mcq('Sparse table query:', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 0),
          fill('Segment tree uses about ___n memory.', ['4']),
          fill('BIT cannot easily support arbitrary range ___.', ['min']),
          mcq('Persistent segment tree adds:', ['O(1) per update', 'O(log n) per update with versioning', 'O(n) per update', 'No change'], 1, 'medium'),
          mcq('2D BIT update/query:', ['O(log n)', 'O((log n)²)', 'O(n)', 'O(n log n)'], 1, 'medium'),
        ]),
        makeExercise('Tries & DSU', [
          mcq('Trie insert for word length L:', ['O(1)', 'O(L)', 'O(n)', 'O(n L)'], 1),
          mcq('Trie best for:', ['Sorting', 'Prefix queries', 'Hashing', 'Range sums'], 1),
          mcq('Union-Find with rank + path compression nearly:', ['O(1)', 'O(log n)', 'O(α(n))', 'O(n)'], 2),
          mcq('Union by rank prevents:', ['Cycles', 'Skewed trees', 'Hash collisions', 'Negative weights'], 1),
          mcq('DSU primarily supports:', ['Find & Union', 'Insert', 'Sort', 'BFS'], 0),
          mcq('Trie size is O(?):', ['L', 'sum of lengths', 'n²', 'log n'], 1),
          fill('Aho-Corasick builds an automaton from a ___.', ['trie']),
          fill('DSU is ideal for Kruskal\u2019s ___ algorithm.', ['MST']),
          mcq('Compressed trie (radix tree) reduces memory by:', ['Hashing', 'Path compression', 'Lazy delete', 'Splaying'], 1, 'medium'),
          mcq('Counting connected components dynamically as edges are added:', ['Heap', 'DSU', 'Trie', 'Segment tree'], 1, 'medium'),
        ]),
        makeExercise('Segment Tree Lazy', [
          mcq('Lazy propagation supports:', ['Range updates O(log n)', 'Point updates O(n)', 'No updates', 'Hash'], 0),
          mcq('Lazy values stored at:', ['Leaves only', 'Internal nodes', 'Root only', 'Hash table'], 1),
          mcq('Range add + range sum with lazy:', ['O(1) per op', 'O(log n)', 'O(n)', 'O(n log n)'], 1),
          mcq('Lazy push-down happens before:', ['Querying child', 'Returning result', 'Building tree', 'Random'], 0),
          mcq('Range assign + range max queries supported by:', ['Lazy seg tree', 'BIT', 'Trie', 'Heap'], 0),
          mcq('Persistent seg tree extra memory per update:', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 1),
          fill('Lazy propagation defers updates until they are ___.', ['needed']),
          fill('Without lazy, range update is O(___).', ['n']),
          mcq('Range XOR + range XOR sum:', ['O(log n) per op with lazy', 'O(1)', 'O(n)', 'Not possible'], 0, 'medium'),
          mcq('Merge sort tree answers # ranks in range in:', ['O(log² n) per query', 'O(log n)', 'O(n)', 'O(n log n)'], 0, 'medium'),
        ]),
        makeExercise('Fenwick Variants', [
          mcq('BIT supports prefix sum / point update in:', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 1),
          mcq('Range update + point query via BIT uses:', ['Difference array trick', 'Hash', 'Heap', 'Trie'], 0),
          mcq('Range update + range query via BIT uses:', ['Two BITs', 'One BIT', 'Heap', 'Trie'], 0),
          mcq('2D BIT update/query:', ['O(log n)', 'O((log n)²)', 'O(n)', 'O(n log n)'], 1),
          mcq('BIT for max queries supports point update only easily:', ['False', 'True', 'Always', 'Never'], 1),
          mcq('BIT vs segment tree memory:', ['BIT smaller', 'Same', 'BIT larger', 'Random'], 0),
          fill('BIT 1-indexed; lowbit(i) = i & -___.', ['i']),
          fill('Inversion count uses BIT in O(n log ___).', ['n']),
          mcq('Counting inversions in array of n with BIT:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(n log² n)'], 1, 'medium'),
          mcq('Order statistics tree replaces BIT when needing K-th:', ['False; both can do via BIT + binary search', 'True; BIT cannot', 'Random', 'No'], 0, 'medium'),
        ]),
        makeExercise('Suffix Structures', [
          mcq('Suffix array sorts all suffixes in O(?) (efficient):', ['O(n)', 'O(n log n)', 'O(n² log n)', 'O(n!)'], 1),
          mcq('LCP array helps with:', ['Common prefix of consecutive suffixes', 'Hash', 'BFS', 'DP only'], 0),
          mcq('Suffix tree size:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(n!)'], 0),
          mcq('Substring search via suffix array:', ['O(m + log n)', 'O(n)', 'O(n + m)', 'O(n²)'], 0),
          mcq('Number of distinct substrings via suffix array + LCP:', ['O(n²)', 'O(n log n)', 'O(n)', 'O(n³)'], 1),
          mcq('Z-function similar to:', ['Failure function', 'Hash table', 'BFS', 'DP'], 0),
          fill('Suffix automaton size is O(___) states.', ['n']),
          fill('LCP between suffixes can be answered in O(1) using ___.', ['RMQ']),
          mcq('Longest repeated substring via suffix array:', ['O(n log n)', 'O(n)', 'O(n²)', 'O(n!)'], 0, 'medium'),
          mcq('Smallest cyclic rotation via Booth/Lyndon:', ['O(n)', 'O(n log n)', 'O(n²)', 'O(n!)'], 0, 'medium'),
        ]),
      ],
    },
  ],
};
