/**
 * Mathematics extra units — appended to the core MATHEMATICS bank.
 */

import type { SeedUnit } from '../seed-bank';
import { mcq, fill, match, makeExercise } from '../seed-bank';

export const MATHEMATICS_EXTRA: Record<1 | 2 | 3, SeedUnit[]> = {
  1: [
    {
      title: 'Number Systems',
      description: 'Naturals, integers, rationals, irrationals, real numbers.',
      exercises: [
        makeExercise('Sets of Numbers', [
          mcq('√2 is:', ['Rational', 'Irrational', 'Integer', 'Natural'], 1),
          mcq('Smallest natural number:', ['0', '1', '-1', 'No smallest'], 1),
          mcq('Set of integers:', ['{0,1,2,...}', '{...,-2,-1,0,1,2,...}', 'Q', 'R'], 1),
          mcq('22/7 is:', ['Irrational', 'Rational approximation of π', 'Equal to π', 'Imaginary'], 1),
          mcq('Every integer is a:', ['Natural number', 'Rational number', 'Irrational', 'Imaginary'], 1),
          mcq('Sum of two irrationals can be:', ['Always irrational', 'Sometimes rational', 'Always rational', 'Always imaginary'], 1),
          fill('π is an ___ number.', ['irrational']),
          fill('Symbol Q stands for ___ numbers.', ['rational']),
          mcq('LCM of 12 and 18:', ['6', '18', '36', '72'], 2, 'medium'),
          mcq('HCF of 24 and 36:', ['6', '8', '12', '24'], 2, 'medium'),
        ]),
        makeExercise('Divisibility', [
          mcq('A number is divisible by 3 if sum of digits divisible by:', ['2', '3', '5', '9'], 1),
          mcq('Divisibility by 9 if digit sum divisible by:', ['3', '6', '9', '12'], 2),
          mcq('Divisibility by 4 if last two digits divisible by:', ['2', '4', '5', '8'], 1),
          mcq('Divisibility by 11 uses:', ['Sum', 'Alternating sum', 'Difference of squares', 'Product'], 1),
          mcq('Prime number has divisors:', ['1', '2 (1 and itself)', '3', 'Many'], 1),
          mcq('Smallest prime:', ['1', '2', '3', '5'], 1),
          fill('All primes >2 are ___.', ['odd']),
          fill('Number of primes is ___.', ['infinite']),
          mcq('Is 91 prime?', ['Yes', 'No (7×13)', 'Yes, 7 is its only divisor', 'Even'], 1, 'medium'),
          mcq('GCD(a,b) × LCM(a,b) =', ['a + b', 'a × b', 'a − b', 'a/b'], 1, 'medium'),
        ]),
        makeExercise('Exponents & Surds', [
          mcq('a^0 =', ['0', '1', 'a', 'undefined'], 1),
          mcq('a^m × a^n =', ['a^{m+n}', 'a^{m-n}', 'a^{mn}', 'a^{m/n}'], 0),
          mcq('(a^m)^n =', ['a^{m+n}', 'a^{mn}', 'a^{m-n}', 'a^{m/n}'], 1),
          mcq('a^{-n} =', ['n/a', '1/a^n', '-a^n', 'a^n'], 1),
          mcq('√(ab) =', ['√a + √b', '√a · √b', 'a/√b', '√(a+b)'], 1),
          mcq('Rationalise 1/√2:', ['√2/2', '√2', '1/2', '2/√2'], 0),
          fill('Surd √n for non-square n is ___.', ['irrational']),
          fill('Index of √a is ___.', ['1/2']),
          mcq('Simplify (√3 + 1)(√3 − 1):', ['2', '4', '√3', '0'], 0, 'medium'),
          mcq('27^{2/3} =', ['9', '6', '3', '81'], 0, 'medium'),
        ]),
        makeExercise('Decimal Representations', [
          mcq('Terminating decimal of 1/8:', ['0.125', '0.250', '0.0125', '0.0625'], 0),
          mcq('Recurring decimal example:', ['0.25', '0.333…', '√2', 'π'], 1),
          mcq('Rational ↔ recurring or:', ['Random', 'Terminating', 'Always non-recurring', 'Never decimal'], 1),
          mcq('Irrational decimals are:', ['Recurring', 'Non-terminating, non-recurring', 'Terminating', 'Always 0'], 1),
          mcq('Bar notation 0.\\overline{3} equals:', ['1/3', '1/2', '0.3', '3'], 0),
          mcq('A fraction p/q in lowest terms terminates iff q has prime factors:', ['only 2 or 5', '3 only', '7 only', 'any'], 0),
          fill('1/4 in decimal is ___.', ['0.25']),
          fill('1/6 in decimal is 0.1\\overline{6}; the bar over ___.', ['6']),
          mcq('Convert 0.\\overline{2} to fraction:', ['1/9', '2/9', '2/10', '2/11'], 1, 'medium'),
          mcq('Convert 0.\\overline{12} to fraction:', ['12/99', '12/90', '12/100', '6/49'], 0, 'medium'),
        ]),        makeExercise('Number Operations', [
          mcq('(-3) + (-4) =', ['-7', '7', '-1', '1'], 0),
          mcq('(-2) × (-5) =', ['-10', '10', '0', '7'], 1),
          mcq('Order of operations starts with:', ['Add', 'Brackets', 'Mul', 'Sub'], 1),
          mcq('|-7| =', ['-7', '7', '0', '49'], 1),
          mcq('Reciprocal of 2/3:', ['3/2', '2/3', '-2/3', '0'], 0),
          mcq('Sum of two negative integers is:', ['Positive', 'Negative', 'Zero', 'Random'], 1),
          fill('Additive identity is ___.', ['0']),
          fill('Multiplicative identity is ___.', ['1']),
          mcq('|-3| + |-4| - |2| =', ['1', '5', '7', '9'], 1, 'medium'),
          mcq('Average of -2, 4, 6, -4 =', ['0', '1', '2', '4'], 1, 'medium'),
        ]),      ],
    },
    {
      title: 'Linear Equations',
      description: 'One/two-variable linear equations and graphs.',
      exercises: [
        makeExercise('Single Variable', [
          mcq('Solve 2x + 3 = 11:', ['3', '4', '5', '6'], 1),
          mcq('Solve x/2 = 5:', ['2.5', '5', '10', '20'], 2),
          mcq('Solve 5x − 4 = 16:', ['3', '4', '5', '6'], 1),
          mcq('Solve 3(x+1) = 12:', ['2', '3', '4', '5'], 1),
          mcq('Solve x − 7 = −2:', ['5', '7', '−9', '9'], 0),
          mcq('Number of solutions of ax = b (a ≠ 0):', ['0', '1', '2', '∞'], 1),
          fill('Inverse of subtraction is ___.', ['addition']),
          fill('Solve x + 3 = 0 ⇒ x = ___.', ['-3']),
          mcq('Solve 2(3x − 1) = 4(x + 2):', ['3', '4', '5', '6'], 2, 'medium'),
          mcq('A number doubled and increased by 5 equals 21. Number:', ['6', '8', '10', '12'], 1, 'medium'),
        ]),
        makeExercise('Two Variables', [
          mcq('Pair of linear equations: number of solutions can be:', ['Always 1', '0,1, or ∞', 'Always ∞', 'Always 2'], 1),
          mcq('y = 2x + 3 has slope:', ['3', '2', '1', '0'], 1),
          mcq('Line through (0,0) with slope 1:', ['y=x', 'y=2x', 'y=x+1', 'y=0'], 0),
          mcq('Parallel lines have:', ['Same slope', 'Equal intercepts', 'Perpendicular', 'No slope'], 0),
          mcq('Perpendicular lines have product of slopes:', ['0', '1', '-1', '∞'], 2),
          mcq('Substitution method involves:', ['Adding equations', 'Replacing one variable', 'Graphing only', 'Cross multiplication'], 1),
          fill('Slope of y=mx+c is ___.', ['m']),
          fill('y-intercept of y=mx+c is ___.', ['c']),
          mcq('Solve x + y = 5, x − y = 1: (x,y):', ['(3,2)', '(2,3)', '(4,1)', '(1,4)'], 0, 'medium'),
          mcq('Lines x+y=2 and 2x+2y=4 are:', ['Parallel', 'Coincident', 'Perpendicular', 'Intersecting at one point'], 1, 'medium'),
        ]),
        makeExercise('Word Problems', [
          mcq('Sum of two numbers is 30 and difference 10. Larger number:', ['10', '15', '20', '25'], 2),
          mcq('Age problem: father is 4× son, in 5 yrs 3×. Son\u2019s age:', ['5', '10', '15', '20'], 1),
          mcq('Train 240 km in 4 h, speed:', ['40 km/h', '50 km/h', '60 km/h', '70 km/h'], 2),
          mcq('Boat upstream 8 km/h, still water 10 km/h: stream:', ['1', '2', '3', '4'], 1),
          mcq('Two pipes fill in 6 and 12 h. Together time:', ['3', '4', '5', '6'], 1),
          mcq('Sum of 3 consecutive integers = 33. Smallest:', ['10', '11', '12', '13'], 0),
          fill('Product of two numbers = ___ × HCF.', ['LCM']),
          fill('Distance = speed × ___.', ['time']),
          mcq('Cost of 5 pens & 3 books = 49 and 3 pens & 5 books = 51. Pen:', ['4', '5', '6', '7'], 0, 'medium'),
          mcq('Area = 60, length-width difference 4. Width:', ['5', '6', '7', '10'], 1, 'medium'),
        ]),
        makeExercise('Graphing Lines', [
          mcq('y-intercept is value of y when x =', ['0', '1', '-1', 'undefined'], 0),
          mcq('x-intercept is value of x when y =', ['0', '1', '-1', 'undefined'], 0),
          mcq('Slope of horizontal line:', ['0', '1', 'Undefined', '∞'], 0),
          mcq('Slope of vertical line:', ['0', '1', 'Undefined', '-1'], 2),
          mcq('Slope between (1,2) and (3,8):', ['2', '3', '4', '6'], 1),
          mcq('Equation of line passing through (0,2) with slope 3:', ['y=3x+2', 'y=2x+3', 'y=x+5', 'y=3x'], 0),
          fill('Two-point form uses slope = (y2-y1)/(x2-___).', ['x1']),
          fill('Standard form ax + by + c = ___.', ['0']),
          mcq('Line 2x+3y=6 cuts x-axis at:', ['(2,0)', '(3,0)', '(0,2)', '(0,3)'], 1, 'medium'),
          mcq('Line through (1,1) parallel to y = 2x:', ['y=2x-1', 'y=2x+1', 'y=-2x+3', 'y=x'], 0, 'medium'),
        ]),
        makeExercise('Systems of Equations', [
          mcq('Methods to solve linear systems:', ['Substitution / elimination / graph', 'Random', 'Differentiation', 'Logarithm'], 0),
          mcq('No solution means lines are:', ['Coincident', 'Parallel distinct', 'Intersecting', 'Curved'], 1),
          mcq('Infinite solutions when lines are:', ['Coincident', 'Parallel distinct', 'Intersecting', 'Perpendicular'], 0),
          mcq('System x+y=4, x-y=2: solution:', ['(3,1)', '(1,3)', '(2,2)', '(4,0)'], 0),
          mcq('Cramer’s rule uses:', ['Substitution', 'Determinants', 'Graph', 'Trial'], 1),
          mcq('Consistent system has:', ['At least one solution', 'No solution', 'Random', 'Infinite always'], 0),
          fill('Two equations in two unknowns yield a unique solution iff lines are not ___.', ['parallel']),
          fill('A homogeneous system always has the ___ solution.', ['trivial']),
          mcq('System 2x+y=5, 4x+2y=10:', ['Unique', 'Infinite (coincident)', 'No sol', 'Two sols'], 1, 'medium'),
          mcq('System x+y=2, x+y=5:', ['Unique', 'Infinite', 'No solution', 'Two sols'], 2, 'medium'),
        ]),
      ],
    },
    {
      title: 'Trigonometry Basics',
      description: 'Ratios in right triangles, identities, applications.',
      exercises: [
        makeExercise('Trig Ratios', [
          mcq('sin 30°:', ['0', '1/2', '√3/2', '1'], 1),
          mcq('cos 60°:', ['0', '1/2', '√3/2', '1'], 1),
          mcq('tan 45°:', ['0', '1', '√3', '∞'], 1),
          mcq('sin 90°:', ['0', '1', '√3/2', '1/2'], 1),
          mcq('cos 0°:', ['0', '1', '1/2', '√3/2'], 1),
          mcq('tan 60°:', ['1', '√3', '1/√3', '0'], 1),
          fill('sin²θ + cos²θ = ___.', ['1']),
          fill('sec θ = 1/___.', ['cos θ']),
          mcq('If sin θ = 3/5, cos θ:', ['3/5', '4/5', '5/3', '1'], 1, 'medium'),
          mcq('1 + tan²θ =', ['cot²θ', 'cosec²θ', 'sec²θ', 'sin²θ'], 2, 'medium'),
        ]),
        makeExercise('Heights & Distances', [
          mcq('Angle of elevation is between line of sight and:', ['Vertical', 'Horizontal', 'Object', 'Eye'], 1),
          mcq('Angle of depression is below:', ['Horizontal', 'Vertical', 'Object', 'Sun'], 0),
          mcq('Tower of 30 m, observer 30 m away. Elevation:', ['30°', '45°', '60°', '90°'], 1),
          mcq('At noon shadow length:', ['Maximum', 'Minimum', 'Same as object', 'Infinity'], 1),
          mcq('Aeroplane flying at 60° elevation, ground point straight under:', ['Same height', 'Foot of perpendicular', 'Far horizon', 'Sun'], 1),
          mcq('Tangent of angle = opposite/___.', ['adjacent', 'hypotenuse', 'sine', 'cosine'], 0),
          fill('In a right triangle with legs 3, 4 hypotenuse is ___.', ['5']),
          fill('sin 45° = cos 45° = 1/___.', ['√2']),
          mcq('Tower 100 m, shadow 100 m. Sun\u2019s elevation:', ['30°', '45°', '60°', '90°'], 1, 'medium'),
          mcq('At 30° elevation, distance for 30 m height ≈', ['30', '52', '17', '60'], 1, 'medium'),
        ]),
        makeExercise('Identities', [
          mcq('sin(90°−θ) =', ['cos θ', 'sin θ', '−sin θ', 'tan θ'], 0),
          mcq('cos(90°−θ) =', ['sin θ', 'cos θ', '−cos θ', '0'], 0),
          mcq('1 − cos²θ =', ['sin²θ', 'tan²θ', 'sec²θ', 'cosec²θ'], 0),
          mcq('cosec²θ − 1 =', ['cot²θ', 'tan²θ', 'cos²θ', 'sin²θ'], 0),
          mcq('sin²θ − cos²θ =', ['1', '-cos 2θ', 'cos 2θ', '0'], 1),
          mcq('cot θ × tan θ =', ['0', '1', 'sin²θ', 'cos²θ'], 1),
          fill('1 − sin²θ = ___.', ['cos²θ']),
          fill('sec²θ − tan²θ = ___.', ['1']),
          mcq('Simplify (1+tan²θ)(1−sin²θ):', ['1', '0', 'cos²θ', '2'], 0, 'medium'),
          mcq('If tan θ = 1, sin 2θ:', ['0', '1', '−1', '√2'], 1, 'medium'),
        ]),
        makeExercise('Special Triangles', [
          mcq('In 30-60-90 ratio of sides:', ['1:1:√2', '1:√3:2', '1:2:3', '1:1:1'], 1),
          mcq('In 45-45-90 ratio of sides:', ['1:1:√2', '1:√3:2', '1:2:3', '1:1:1'], 0),
          mcq('Equilateral triangle has all angles:', ['60°', '90°', '45°', '30°'], 0),
          mcq('Isosceles right triangle has angles:', ['30,60,90', '45,45,90', '90,45,45 only acute', '20,70,90'], 1),
          mcq('Hypotenuse is the:', ['Longest side', 'Shortest', 'Right side', 'Top side'], 0),
          mcq('Opposite to 90° is the:', ['Hypotenuse', 'Leg', 'Median', 'Altitude'], 0),
          fill('Pythagoras: a² + b² = ___².', ['c']),
          fill('Sine rule and cosine rule are for ___ triangles.', ['general']),
          mcq('Side opposite 30° in 1:√3:2 triangle of hypotenuse 10 is:', ['5', '5√3', '10', '8'], 0, 'medium'),
          mcq('Hypotenuse of 45-45-90 with leg 7:', ['7', '7√2', '14', '49'], 1, 'medium'),
        ]),
      ],
    },
  ],

  2: [
    {
      title: 'Sequences & Series',
      description: 'AP, GP, sums, infinite GP, applications.',
      exercises: [
        makeExercise('Arithmetic Progression', [
          mcq('AP nth term: a_n =', ['a + (n−1)d', 'a × (n−1)', 'a/n', 'd^n'], 0),
          mcq('Sum n terms: S_n =', ['n/2 (2a + (n−1)d)', 'a r^{n-1}', 'a/(1-r)', 'a × n'], 0),
          mcq('Common difference of 3,7,11,...:', ['2', '3', '4', '5'], 2),
          mcq('Sum of first 10 natural numbers:', ['45', '50', '55', '60'], 2),
          mcq('AP 5,8,11,...; 10th term:', ['28', '29', '32', '33'], 2),
          mcq('In AP, twice middle term equals:', ['Sum of equidistant terms', 'Last term', 'First term', 'Common diff'], 0),
          fill('In AP if a_n = 23, a=3, d=2 then n = ___.', ['11']),
          fill('Sum of first n odd numbers = n___.', ['²']),
          mcq('AP 2,5,8,...; sum to 20 terms:', ['590', '610', '630', '600'], 0, 'medium'),
          mcq('Find x if x, 2x+1, 4x are in AP:', ['1', '2', '3', '4'], 1, 'medium'),
        ]),
        makeExercise('Geometric Progression', [
          mcq('GP nth term: a_n =', ['ar^{n-1}', 'a + (n-1)d', 'a/n', 'a^n'], 0),
          mcq('Common ratio of 2,6,18,...:', ['2', '3', '6', '12'], 1),
          mcq('Sum n terms (r ≠ 1):', ['a(1−r^n)/(1−r)', 'a + nd', 'ar', 'a/r'], 0),
          mcq('Infinite GP sum (|r|<1):', ['a/(1−r)', 'a/r', 'ar', 'a(1−r)'], 0),
          mcq('Common ratio of 1, 1/2, 1/4,...:', ['1/2', '2', '1/4', '4'], 0),
          mcq('GP 3,6,12,...; 5th term:', ['24', '48', '60', '72'], 1),
          fill('GP middle term² = product of equidistant ___.', ['terms']),
          fill('Geometric mean of a, b is ___.', ['√(ab)']),
          mcq('Sum 1 + 1/2 + 1/4 + ... =', ['1', '2', '3/2', '∞'], 1, 'medium'),
          mcq('Find x if 2, x, 8 are in GP:', ['4', '−4', '±4', '6'], 2, 'medium'),
        ]),
        makeExercise('Special Series', [
          mcq('Σi from 1 to n =', ['n(n+1)/2', 'n²', 'n(n+1)(2n+1)/6', 'n³'], 0),
          mcq('Σi² from 1 to n =', ['n(n+1)/2', 'n²(n+1)²/4', 'n(n+1)(2n+1)/6', 'n³'], 2),
          mcq('Σi³ from 1 to n =', ['n²(n+1)²/4', 'n(n+1)/2', 'n(2n+1)/6', 'n!'], 0),
          mcq('Sum of 1+2+...+100:', ['5050', '5000', '5100', '4950'], 0),
          mcq('Sum of first 10 squares:', ['285', '385', '335', '285 + 100'], 1),
          mcq('Sum of first 5 cubes:', ['100', '225', '125', '15²'], 1),
          fill('Σ1 from 1 to n equals ___.', ['n']),
          fill('Σi³ = (Σ___)².', ['i']),
          mcq('Compute 2² + 4² + 6² for n=3:', ['56', '20', '48', '60'], 0, 'medium'),
          mcq('Σ(2i−1) for i=1..n =', ['n', 'n²', 'n(n+1)', '2n'], 1, 'medium'),
        ]),
        makeExercise('Applications', [
          mcq('Compound interest formula: A =', ['P(1+r)^n', 'P + Prn', 'Pr/n', 'P/n'], 0),
          mcq('Bouncing ball total distance (initial h, coefficient r<1) is GP-related:', ['Yes', 'No', 'Random', 'Only finite drops'], 0),
          mcq('Annuity uses:', ['AP only', 'GP/finite series', 'Random', 'Single payment only'], 1),
          mcq('Population growth modeled by:', ['AP', 'GP / exponential', 'Constant', 'Linear only'], 1),
          mcq('Salary increment yearly +x is:', ['AP', 'GP', 'Random', 'No pattern'], 0),
          mcq('Halving time of substance halflife:', ['AP', 'GP', 'Constant', 'Linear'], 1),
          fill('Compound interest grows in ___ progression.', ['geometric']),
          fill('Simple interest is in ___ progression.', ['arithmetic']),
          mcq('₹1000 at 10% CI annual for 2 years:', ['1100', '1200', '1210', '1220'], 2, 'medium'),
          mcq('Saving ₹1000/month grows linearly: AP of ___.', ['common difference 1000', 'ratio 1000', 'random', 'half'], 0, 'medium'),
        ]),
        makeExercise('Mathematical Induction', [
          mcq('Induction proves statements for:', ['All real n', 'All natural n', 'Integers only', 'Rationals'], 1),
          mcq('Steps of induction:', ['Base + step', 'Only base', 'Only step', 'Random'], 0),
          mcq('Base case typically:', ['n=1', 'n=0 or 1', 'n=∞', 'n=any'], 1),
          mcq('Inductive step assumes:', ['P(k)', 'P(0)', 'P(k+1)', 'No assumption'], 0),
          mcq('Then prove:', ['P(k+1)', 'P(k-1)', 'P(0)', 'P(∞)'], 0),
          mcq('Strong induction assumes for all m ≤ k:', ['P(m)', 'Random', 'Only P(k)', 'No assumption'], 0),
          fill('Induction is justified by the well-___ principle.', ['ordering']),
          fill('Sum of first n natural numbers proven by ___.', ['induction']),
          mcq('Prove 1+2+...+n = n(n+1)/2; base case n=1 LHS=', ['0', '1', '2', '3'], 1, 'medium'),
          mcq('Induction often fails to prove statements about ___.', ['Reals continuously', 'Naturals', 'Integers', 'Rationals'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Complex Numbers',
      description: 'i, modulus, argument, polar form, De Moivre.',
      exercises: [
        makeExercise('Basics', [
          mcq('i² =', ['1', '-1', '0', 'i'], 1),
          mcq('i³ =', ['i', '-1', '-i', '1'], 2),
          mcq('Modulus of 3 + 4i:', ['3', '4', '5', '7'], 2),
          mcq('Conjugate of a + bi:', ['a - bi', '-a + bi', 'b - ai', '-a - bi'], 0),
          mcq('Real part of 5 + 2i:', ['5', '2', '7', '-3'], 0),
          mcq('Imag part of 5 - 2i:', ['5', '2', '-2', '-5'], 2),
          fill('z = a + bi has modulus √(a² + ___).', ['b²']),
          fill('Argument of i is π/___.', ['2']),
          mcq('|3 - 4i|² =', ['25', '7', '5', '12'], 0, 'medium'),
          mcq('(1+i)² =', ['2i', '2', '−2', '0'], 0, 'medium'),
        ]),
        makeExercise('Polar Form & De Moivre', [
          mcq('Polar form: z = r(cos θ + i sin θ); r =', ['|z|', 'Re(z)', 'Im(z)', 'arg z'], 0),
          mcq('Argument θ for 1+i:', ['0', 'π/4', 'π/2', 'π'], 1),
          mcq('De Moivre: (cosθ + i sinθ)^n =', ['cos nθ + i sin nθ', 'n cos θ', 'cos^n θ', 'cos θ + n sin θ'], 0),
          mcq('Roots of unity for n=3 number:', ['1', '2', '3', '6'], 2),
          mcq('e^{iπ} =', ['1', '0', '-1', 'i'], 2),
          mcq('e^{iπ/2} =', ['1', 'i', '-1', '-i'], 1),
          fill('Argument of -i is -π/___.', ['2']),
          fill('|z₁ z₂| = |z₁| × |___|.', ['z₂']),
          mcq('(1+i)^4 =', ['-4', '4', '4i', '−4i'], 0, 'medium'),
          mcq('Roots of x⁴ = 1 are 1, -1, i, ___.', ['2', '0', '-i', 'i²'], 2, 'medium'),
        ]),
        makeExercise('Equations & Locus', [
          mcq('z + \\bar z =', ['2 Re(z)', '2 Im(z)', '0', '|z|²'], 0),
          mcq('z − \\bar z =', ['2 Re(z)', '2i Im(z)', '0', '|z|²'], 1),
          mcq('z \\bar z =', ['Re(z)²', '|z|²', 'Im(z)²', '0'], 1),
          mcq('|z − a| = r is locus of:', ['Line', 'Circle radius r', 'Ellipse', 'Parabola'], 1),
          mcq('|z − 1| = |z + 1| is:', ['Real axis', 'Imag axis', 'Origin only', 'No locus'], 1),
          mcq('Re(z) = 3 is a:', ['Horizontal line', 'Vertical line x=3', 'Circle', 'Ellipse'], 1),
          fill('Conjugate z̄ reflects z across ___ axis.', ['real']),
          fill('Multiplying by i rotates z by π/___.', ['2']),
          mcq('|z| = 1 represents:', ['Unit circle', 'Origin', 'Real axis', 'Imag axis'], 0, 'medium'),
          mcq('arg(z) = π/4 represents:', ['Ray from origin at 45°', 'Whole plane', 'Circle', 'Vertical line'], 0, 'medium'),
        ]),
        makeExercise('Roots of Unity', [
          mcq('nth roots of unity satisfy:', ['z^n = 1', 'z = n', 'z + n = 0', 'z^n = n'], 0),
          mcq('Number of nth roots of unity:', ['1', '2', 'n', 'n!'], 2),
          mcq('Primitive root ω of unity (n=3): ω =', ['e^{i 2π/3}', 'e^{iπ}', '1', 'i'], 0),
          mcq('Sum of all nth roots of unity:', ['0', '1', 'n', '-1'], 0),
          mcq('Product of all nth roots of unity (n>1):', ['(-1)^{n+1}', '0', '1', 'n'], 0),
          mcq('Roots of unity lie on:', ['Real axis', 'Unit circle', 'Imag axis', 'Hyperbola'], 1),
          fill('A primitive nth root has order ___.', ['n']),
          fill('Cube roots of unity sum to ___.', ['0']),
          mcq('1 + ω + ω² = (where ω cube root of unity):', ['0', '1', '3', 'ω'], 0, 'medium'),
          mcq('ω³ (cube root of unity) =', ['1', '0', 'ω', '-1'], 0, 'medium'),
        ]),
        makeExercise('Argand Plane', [
          mcq('Argand plane represents complex numbers as:', ['Lines', 'Points (a,b)', 'Vectors only', 'Curves'], 1),
          mcq('Real axis represents:', ['Imaginary part', 'Real part', 'Modulus', 'Argument'], 1),
          mcq('Imaginary axis represents:', ['Real part', 'Imaginary part', 'Modulus', 'Argument'], 1),
          mcq('Distance between z1 and z2 in plane:', ['|z1 - z2|', 'z1 + z2', 'arg z1', 'Re(z1)'], 0),
          mcq('Triangle inequality for complex:', ['|z1 + z2| ≤ |z1| + |z2|', '=', '≥', 'No relation'], 0),
          mcq('z + iz rotates z by:', ['90°', '45° plus scaling √2', '180°', '60°'], 1),
          fill('Multiplication by i corresponds to ___° rotation.', ['90']),
          fill('Conjugate reflects across the ___ axis.', ['real']),
          mcq('Locus |z - i| = 2 is:', ['Line', 'Circle radius 2 centered at i', 'Ellipse', 'Hyperbola'], 1, 'medium'),
          mcq('Vertices of equilateral triangle with one at origin and another at 1 lie at:', ['e^{iπ/3}', 'e^{iπ/2}', 'i', '-1'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Matrices & Determinants',
      description: 'Operations, inverse, properties, applications.',
      exercises: [
        makeExercise('Matrix Basics', [
          mcq('Order of [3 1; 2 5] is:', ['1×2', '2×1', '2×2', '3×3'], 2),
          mcq('Identity matrix I has ones on:', ['Off-diagonal', 'Diagonal', 'All entries', 'First row only'], 1),
          mcq('Transpose swaps:', ['Rows ↔ columns', 'Sign', 'Determinant', 'Eigenvalues only'], 0),
          mcq('Symmetric matrix:', ['A = -A^T', 'A = A^T', 'A^T = I', 'No condition'], 1),
          mcq('Skew-symmetric matrix:', ['A = -A^T', 'A = A^T', 'A^2=I', 'I=A'], 0),
          mcq('Square matrix has number of rows:', ['Equal to columns', 'Greater than columns', 'Less than columns', 'Zero'], 0),
          fill('Trace is sum of ___ entries.', ['diagonal']),
          fill('Multiplication AB is defined when columns of A = rows of ___.', ['B']),
          mcq('A 2×2 has determinant ad − bc with A=[a b;c d]; True?', ['False', 'True', 'Sometimes', 'Only diagonal'], 1, 'medium'),
          mcq('det(I_n) =', ['0', '1', 'n', 'n!'], 1, 'medium'),
        ]),
        makeExercise('Determinants', [
          mcq('det(AB) =', ['det A + det B', 'det A · det B', '0', 'det B / det A'], 1),
          mcq('det(kA) for n×n =', ['k det A', 'k^n det A', 'det A / k', 'k^2 det A'], 1),
          mcq('Swapping two rows multiplies det by:', ['1', '−1', '2', '0'], 1),
          mcq('Adding multiple of one row to another changes det by:', ['Doubles', 'No change', 'Halves', 'Zero'], 1),
          mcq('Matrix is invertible iff det ≠ ?', ['1', '0', '∞', '−1'], 1),
          mcq('A = [[2,1],[3,4]] det:', ['5', '8', '11', '−5'], 0),
          fill('det(A^T) = det(___).', ['A']),
          fill('det(A^{-1}) = 1/det(___).', ['A']),
          mcq('Cramer\u2019s rule applies when det ≠ ___.', ['1', '0', '∞', 'A'], 1, 'medium'),
          mcq('Triangular det =', ['Sum of diag', 'Product of diag', '0', 'Trace'], 1, 'medium'),
        ]),
        makeExercise('Inverse & Systems', [
          mcq('A^{-1} A =', ['0', 'I', 'A', 'A^T'], 1),
          mcq('Inverse of [[a,b],[c,d]] = (1/det) ×', ['[[d,-b],[-c,a]]', '[[a,c],[b,d]]', '[[d,b],[c,a]]', '[[a,-b],[c,-d]]'], 0),
          mcq('System Ax=b unique solution if:', ['det(A)=0', 'det(A)≠0', 'b=0', 'A=0'], 1),
          mcq('Homogeneous Ax=0 has non-trivial sols if:', ['det≠0', 'det=0', 'A=I', 'b≠0'], 1),
          mcq('Rank-nullity: rank + nullity =', ['rows', 'columns of A', 'det', '0'], 1),
          mcq('Number of solutions of inconsistent system:', ['1', '∞', '0', '2'], 2),
          fill('A is invertible ↔ det(A) ___ 0.', ['≠']),
          fill('Adjugate · A = (det A) ___.', ['I']),
          mcq('A 3×3 system reduced to rank 2 with consistent b has:', ['Unique sol', '∞ sols', 'No sol', 'Two sols'], 1, 'medium'),
          mcq('A · adj(A) =', ['I', 'A^{-1}', '(det A) I', '0'], 2, 'medium'),
        ]),
      ],
    },
  ],

  3: [
    {
      title: 'Group Theory',
      description: 'Groups, subgroups, cyclic groups, homomorphisms.',
      exercises: [
        makeExercise('Group Axioms', [
          mcq('Group needs operation that is:', ['Commutative only', 'Associative, identity, inverse', 'Random', 'Always commutative'], 1),
          mcq('(Z, +) is a:', ['Group', 'Field', 'Ring only', 'Vector space'], 0),
          mcq('Identity in (Z, +):', ['1', '0', '−1', 'No identity'], 1),
          mcq('Inverse of 5 in (Z,+):', ['1/5', '−5', '5', '0'], 1),
          mcq('A group with finite elements is called:', ['Infinite', 'Finite/countable', 'Continuous', 'Topological'], 1),
          mcq('Commutative group is called:', ['Abelian', 'Cyclic', 'Symmetric', 'Quotient'], 0),
          fill('Order of a group is the number of ___.', ['elements']),
          fill('In group, every element has an ___.', ['inverse']),
          mcq('S_n is the symmetric group of order:', ['n', 'n!', '2n', 'n²'], 1, 'medium'),
          mcq('Z_n under addition is:', ['Always abelian', 'Non-abelian', 'Trivial', 'Empty'], 0, 'medium'),
        ]),
        makeExercise('Subgroups & Cyclic', [
          mcq('Subgroup test (Lagrange):', ['Order divides group', 'Order doubles', 'Order squares', 'Random'], 0),
          mcq('Cyclic group is generated by:', ['Two elements', 'Single element', 'No element', 'Infinitely many'], 1),
          mcq('Z under + is cyclic generated by:', ['1', '0', '2', '−1 only'], 0),
          mcq('Z_6 has order:', ['6', '5', '7', '12'], 0),
          mcq('Generators of Z_6:', ['1, 5', '2, 4', '0, 3', '1, 2, 3, 4, 5'], 0),
          mcq('Every cyclic group is:', ['Abelian', 'Non-abelian', 'Infinite only', 'Empty'], 0),
          fill('Lagrange: |H| divides |___|.', ['G']),
          fill('Index [G:H] = |G|/|___|.', ['H']),
          mcq('Number of subgroups of Z_p (p prime):', ['1', '2 (trivial and itself)', 'p', 'Infinite'], 1, 'medium'),
          mcq('Z_4 is:', ['Cyclic', 'Klein four-group', 'Non-abelian', 'Empty'], 0, 'medium'),
        ]),
        makeExercise('Homomorphisms', [
          mcq('Homomorphism preserves:', ['Operation', 'Identity', 'Inverses', 'All'], 3),
          mcq('Kernel of hom is a:', ['Subset only', 'Normal subgroup', 'Quotient', 'Field'], 1),
          mcq('Isomorphism is bijective:', ['Function', 'Homomorphism', 'Map only', 'Linear function only'], 1),
          mcq('Image of identity in homomorphism:', ['Random', 'Identity of codomain', 'Zero', 'No image'], 1),
          mcq('First isomorphism theorem: G/ker f ≅', ['ker f', 'image f', 'G', 'Trivial'], 1),
          mcq('Trivial homomorphism sends everything to:', ['Identity', 'Generator', 'Random', 'Inverses only'], 0),
          fill('Kernel of homomorphism is always a ___ subgroup.', ['normal']),
          fill('Two groups are isomorphic if there exists a bijective ___.', ['homomorphism']),
          mcq('|hom(Z, Z_n)| =', ['1', 'n', '2n', '∞'], 1, 'medium'),
          mcq('Aut(Z) is isomorphic to:', ['Z', 'Z/2', 'Trivial', 'Z²'], 1, 'medium'),
        ]),
        makeExercise('Permutations & Symmetric Groups', [
          mcq('S_3 has order:', ['3', '6', '9', '12'], 1),
          mcq('S_n is non-abelian for n ≥:', ['2', '3', '4', '5'], 1),
          mcq('A cycle (1 2 3) has order:', ['1', '2', '3', '6'], 2),
          mcq('Composition of permutations is:', ['Commutative always', 'Associative always', 'Random', 'Linear'], 1),
          mcq('Transposition swaps:', ['One element', 'Two elements', 'All elements', 'None'], 1),
          mcq('Every permutation is a product of:', ['Cycles', 'Transpositions', 'Both possible', 'Neither'], 2),
          fill('Sign of an even permutation is +___.', ['1']),
          fill('Alternating group A_n has order n!/___.', ['2']),
          mcq('Order of (1 2)(3 4 5) in S_5:', ['2', '3', '5', '6'], 3, 'medium'),
          mcq('Number of elements of S_4 of order 2:', ['3', '6', '9', '12'], 2, 'medium'),
        ]),
        makeExercise('Rings & Fields (Intro)', [
          mcq('Ring requires:', ['Two operations + and · with axioms', 'One operation', 'No identity', 'Random'], 0),
          mcq('Commutative ring + multiplicative identity = ?', ['Field', 'Group', 'Ring with unity', 'Set'], 2),
          mcq('Field has multiplicative inverses for:', ['Zero only', 'All non-zero', 'All', 'None'], 1),
          mcq('Z is a:', ['Field', 'Commutative ring with 1', 'Group only', 'Vector space'], 1),
          mcq('Q, R, C are:', ['Rings only', 'Fields', 'Groups only', 'Vector spaces only'], 1),
          mcq('Z_p is field iff p is:', ['Composite', 'Prime', 'Even', '1'], 1),
          fill('Integral domain has no zero ___.', ['divisors']),
          fill('Polynomial ring Q[x] is an integral ___.', ['domain']),
          mcq('Characteristic of a field can be:', ['0 or prime', 'Any integer', 'Always 1', 'Always ∞'], 0, 'medium'),
          mcq('Z_6 is:', ['Field', 'Ring with zero divisors', 'Integral domain', 'Trivial'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Real Analysis (Advanced)',
      description: 'Continuity, sequences, series, uniform convergence.',
      exercises: [
        makeExercise('Limits & Continuity', [
          mcq('ε-δ defines:', ['Series', 'Limit/continuity', 'Derivative', 'Integral'], 1),
          mcq('Continuous on closed interval implies:', ['Boundedness', 'Discontinuity', 'Diff iable', 'Smooth'], 0),
          mcq('Intermediate value theorem requires:', ['Continuity on closed interval', 'Differentiability', 'Monotonicity', 'Integrability'], 0),
          mcq('Uniformly continuous on compact set if:', ['Continuous', 'Bounded only', 'Diff', 'Integrable'], 0),
          mcq('1/x is continuous on:', ['R', '(0, ∞)', '[0,1]', 'R\\{0}'], 1),
          mcq('Removable discontinuity occurs when:', ['Limit exists but ≠ value', 'Limit doesn\u2019t exist', 'Function unbounded', 'Random'], 0),
          fill('Bolzano-Weierstrass: every bounded sequence has convergent ___.', ['subsequence']),
          fill('Heine-Borel: closed bounded subsets of R are ___.', ['compact']),
          mcq('f is continuous and strictly monotone on closed interval ⇒ f^{-1} is:', ['Continuous', 'Discontinuous', 'Constant', 'Random'], 0, 'medium'),
          mcq('f(x) = sin(1/x) at x=0 has:', ['Removable disc', 'Essential disc (no limit)', 'Continuous', 'Defined'], 1, 'medium'),
        ]),
        makeExercise('Sequences', [
          mcq('Cauchy sequence is convergent in:', ['Q', 'R (complete)', 'Random metric', 'No space'], 1),
          mcq('Monotone bounded sequence in R:', ['Diverges', 'Converges', 'Oscillates', 'Random'], 1),
          mcq('lim (1+1/n)^n =', ['1', 'e', 'π', '∞'], 1),
          mcq('Squeeze theorem requires:', ['Bracketing functions', 'Random', 'Continuity only', 'Integrability'], 0),
          mcq('Geometric sequence r^n converges if:', ['|r|<1', '|r|>1', 'r=1', 'r=−1'], 0),
          mcq('lim n→∞ ln n / n =', ['0', '1', '∞', 'Undefined'], 0),
          fill('Cauchy ↔ Convergent in ___ space.', ['complete']),
          fill('Limit of sum is sum of ___.', ['limits']),
          mcq('lim n→∞ n^{1/n} =', ['0', '1', 'e', '∞'], 1, 'medium'),
          mcq('Sequence a_n = (-1)^n is:', ['Convergent', 'Divergent (oscillates)', 'Cauchy', 'Constant'], 1, 'medium'),
        ]),
        makeExercise('Series', [
          mcq('Geometric series sum a + ar + ar² + ... (|r|<1):', ['a/(1-r)', 'a r', 'a + r', '0'], 0),
          mcq('Σ 1/n is:', ['Convergent', 'Divergent (harmonic)', 'Alternating', 'Cauchy'], 1),
          mcq('Σ 1/n^p converges for:', ['p>1', 'p<1', 'Any p', 'p=0'], 0),
          mcq('Alternating series test requires:', ['Decreasing terms → 0', 'Random', 'Constant', 'Increasing'], 0),
          mcq('Absolute convergence ⇒ convergence:', ['False', 'True', 'Sometimes', 'Only positive series'], 1),
          mcq('Power series Σ a_n x^n radius R determined by:', ['Ratio/root test', 'Random', 'Mass', 'Density'], 0),
          fill('Σ n converges? ___.', ['no']),
          fill('Σ x^n converges for |x| ___.', ['<1']),
          mcq('Radius of convergence of Σ x^n / n!:', ['0', '1', 'e', '∞'], 3, 'medium'),
          mcq('Σ (−1)^n / n converges by:', ['Comparison', 'Alternating series test', 'Ratio', 'Geometric'], 1, 'medium'),
        ]),
        makeExercise('Uniform Convergence', [
          mcq('Pointwise convergence guarantees uniform:', ['Always', 'Not always', 'Never', 'Sometimes only on R'], 1),
          mcq('Uniform convergence preserves:', ['Continuity of limit', 'Discontinuity', 'Random', 'Differentiability always'], 0),
          mcq('Weierstrass M-test bounds terms by ___ series.', ['Random', 'Convergent', 'Divergent', 'Alternating'], 1),
          mcq('Uniform Cauchy criterion implies:', ['Pointwise only', 'Uniform convergence', 'No convergence', 'Random'], 1),
          mcq('Uniform limit of Riemann-integrable functions is:', ['Always Riemann-integrable', 'Discontinuous', 'Random', 'Diff iable'], 0),
          mcq('Uniform conv on compact set ensures interchange of limit & ___.', ['Sum', 'Integral / continuity', 'Derivative always', 'Topology'], 1),
          fill('A series of continuous functions, uniformly convergent, has continuous ___.', ['sum']),
          fill('Differentiation needs uniform convergence of the ___.', ['derivative']),
          mcq('Sequence f_n(x) = x^n on [0,1] converges:', ['Uniformly to 0', 'Pointwise but not uniformly', 'Not at all', 'Uniformly to 1'], 1, 'medium'),
          mcq('Stone-Weierstrass theorem extends polynomial approximation to:', ['Continuous functions on compact', 'All functions', 'Discontinuous only', 'Random'], 0, 'medium'),
        ]),
        makeExercise('Lebesgue Measure (Intro)', [
          mcq('Lebesgue measure of [0,1]:', ['0', '1', '∞', '1/2'], 1),
          mcq('Countable union of measure-zero sets has measure:', ['0', '1', '∞', 'Random'], 0),
          mcq('A function is measurable if preimage of open set is:', ['Measurable', 'Open only', 'Closed only', 'Compact'], 0),
          mcq('Almost everywhere means except on:', ['Measure-zero set', 'Open set', 'Closed set', 'Countable set always'], 0),
          mcq('Lebesgue integral generalizes:', ['Riemann', 'Differentiation', 'Series', 'No relation'], 0),
          mcq('Cantor set has measure:', ['0', '1', '1/2', '∞'], 0),
          fill('Sigma-algebra is closed under countable ___.', ['unions']),
          fill('A.e. equality identifies functions in L^p ___.', ['spaces']),
          mcq('Riemann ⇒ Lebesgue integrable, but not vice versa:', ['False', 'True', 'Equivalent', 'No'], 1, 'medium'),
          mcq('Borel sets are generated by ___ sets in topology.', ['Open', 'Closed only', 'Compact only', 'Connected'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Differential Equations',
      description: 'ODEs, separable, linear, second-order linear.',
      exercises: [
        makeExercise('First-Order ODE', [
          mcq('dy/dx = ky has solution:', ['y = C e^{kx}', 'y = kx', 'y = sin x', 'y = ln x'], 0),
          mcq('Separable equation: dy/dx = f(x) g(y) integrates to:', ['∫dy/g = ∫f dx', 'd ln y', '∫f g dx', 'Random'], 0),
          mcq('Linear first-order: dy/dx + P(x) y = Q(x) integrating factor:', ['e^{∫P dx}', 'e^P', '∫Q dx', '1/Q'], 0),
          mcq('Initial value problem requires:', ['One condition for first-order', 'No condition', 'Boundary conditions', 'Two conditions'], 0),
          mcq('Order of ODE is:', ['Highest derivative', 'Lowest derivative', 'Number of variables', 'Degree always'], 0),
          mcq('Degree of ODE is:', ['Power of highest derivative (when polynomial)', 'Order', 'Random', 'Number of constants'], 0),
          fill('General solution has ___ arbitrary constants for n-th order ODE.', ['n']),
          fill('Exact ODE: M dx + N dy = 0 with ∂M/∂y = ∂N/∂___.', ['x']),
          mcq('Solve dy/dx = y, y(0)=1:', ['y = e^x', 'y = x', 'y = sin x', 'y = cos x'], 0, 'medium'),
          mcq('dy/dx + y = 0 solution:', ['y = C e^{-x}', 'y = C e^{x}', 'y = C', 'y = 0 only'], 0, 'medium'),
        ]),
        makeExercise('Second-Order Linear', [
          mcq('y\u2032\u2032 + ω² y = 0 has solution:', ['A cos ωx + B sin ωx', 'A x', 'A e^x', 'A x²'], 0),
          mcq('Characteristic eqn for y\u2032\u2032 + 3y\u2032 + 2y = 0:', ['r² + 3r + 2 = 0', 'r² − 3 = 0', 'r + 3 = 0', 'r² = 0'], 0),
          mcq('Roots distinct real → solution form:', ['A e^{r₁x} + B e^{r₂x}', 'A cos rx', 'A x e^{rx}', 'A'], 0),
          mcq('Repeated root r → solution:', ['(A + B x) e^{rx}', 'A e^{rx}', 'cos rx', 'sin rx'], 0),
          mcq('Complex roots a ± bi → solution:', ['e^{ax}(A cos bx + B sin bx)', 'A e^{ax}', 'cos x', 'sin x'], 0),
          mcq('Wronskian non-zero indicates:', ['Linear dependence', 'Linear independence', 'Random', 'Constant'], 1),
          fill('Homogeneous + particular = ___ solution.', ['general']),
          fill('Method of undetermined ___ guesses particular solution.', ['coefficients']),
          mcq('y\u2032\u2032 − y = 0 with y(0)=0, y\u2032(0)=1: y =', ['sinh x', 'cosh x', 'sin x', 'e^x'], 0, 'medium'),
          mcq('Damped oscillator: y\u2032\u2032 + 2y\u2032 + y = 0 has roots:', ['Repeated -1', 'Complex', 'Real distinct', 'Pure imaginary'], 0, 'medium'),
        ]),
        makeExercise('Applications', [
          mcq('Population growth dP/dt = rP yields:', ['Linear', 'Exponential', 'Quadratic', 'Cubic'], 1),
          mcq('Newton\u2019s law of cooling: dT/dt = -k(T − T_s):', ['Heat eqn', 'First-order linear', 'Wave eqn', 'Laplace'], 1),
          mcq('Logistic model: dP/dt = rP(1 − P/K) gives:', ['Bounded growth', 'Unlimited', 'Constant', 'Linear'], 0),
          mcq('Mass-spring: m x\u2032\u2032 + k x = 0 frequency:', ['√(k/m)', '√(m/k)', 'k m', 'k + m'], 0),
          mcq('RC circuit voltage decay:', ['Exponential', 'Linear', 'Sinusoidal', 'Constant'], 0),
          mcq('Pendulum (small angle): θ\u2032\u2032 + (g/L) θ = 0:', ['SHM', 'Random', 'Constant', 'Exponential'], 0),
          fill('Laplace transform turns ODE into ___ equation.', ['algebraic']),
          fill('Boundary value problem specifies values at ___ points.', ['multiple']),
          mcq('Heat equation is:', ['First-order ODE', 'Second-order PDE in space', 'Algebraic', 'Linear ODE only'], 1, 'medium'),
          mcq('Wave equation: u_tt =', ['c² u_xx', 'c u', 'u_x', 'u_tt only'], 0, 'medium'),
        ]),
      ],
    },
  ],
};
