/**
 * Physics extra units — appended to the core PHYSICS bank in seed-bank.ts.
 * Adds extensive coverage so each level has 5–6+ units and many exercises.
 */

import type { SeedUnit } from '../seed-bank';
import { mcq, fill, match, makeExercise } from '../seed-bank';

export const PHYSICS_EXTRA: Record<1 | 2 | 3, SeedUnit[]> = {
  1: [
    {
      title: 'Gravitation Basics',
      description: 'Universal gravitation, weight, free fall, satellites.',
      exercises: [
        makeExercise('Gravity Fundamentals', [
          mcq('Gravitational force between two masses varies as:', ['1/r', '1/r²', 'r', 'r²'], 1),
          mcq('SI unit of g:', ['m/s', 'm/s²', 'N', 'kg'], 1),
          mcq('Weight differs from mass because weight depends on:', ['Volume', 'g', 'Time', 'Length'], 1),
          mcq('On the Moon a body weighs ___ that on Earth.', ['More', 'About 1/6th', 'Same', 'Twice'], 1),
          mcq('At Earth\u2019s centre a body\u2019s weight is:', ['Maximum', 'Zero', 'Doubled', 'Same as surface'], 1),
          mcq('A free-falling body has acceleration:', ['0', 'g downward', 'g upward', 'Variable'], 1),
          fill('Newton\u2019s law of gravitation: F = G m\u2081 m\u2082 / ___.', ['r²']),
          fill('Acceleration due to gravity on Earth ≈ ___ m/s².', ['9.8']),
          mcq('A satellite in orbit is in:', ['Equilibrium', 'Constant free fall', 'Antigravity', 'Rest'], 1, 'medium'),
          mcq('If r is doubled, gravitational force becomes:', ['Half', 'One-fourth', 'Twice', 'Four times'], 1, 'medium'),
        ]),
        makeExercise('Free Fall', [
          mcq('Object falls from rest. After 2 s velocity (g=10):', ['5 m/s', '10 m/s', '20 m/s', '40 m/s'], 2),
          mcq('Distance fallen in 2 s from rest (g=10):', ['10 m', '20 m', '40 m', '80 m'], 1),
          mcq('Air resistance ignored is called:', ['Real fall', 'Free fall', 'Drift', 'Slip'], 1),
          mcq('Two bodies dropped together (no air) hit ground:', ['Heavier first', 'Lighter first', 'Together', 'Random'], 2),
          mcq('Velocity at top of vertical throw:', ['Max', 'Zero', 'Negative', 'Same as launch'], 1),
          mcq('Projectile motion vertical component obeys:', ['Constant v', 'Free fall under g', 'Constant a only horizontally', 'No acceleration'], 1),
          fill('v = u + g___.', ['t']),
          fill('Distance s = ½ g t² when starting from ___.', ['rest']),
          mcq('A stone thrown up at 20 m/s reaches max height (g=10):', ['10 m', '20 m', '30 m', '40 m'], 1, 'medium'),
          mcq('Time to reach max height for 20 m/s upward (g=10):', ['1 s', '2 s', '3 s', '4 s'], 1, 'medium'),
        ]),
        makeExercise('Satellites & Orbits', [
          mcq('Geostationary orbit period:', ['1 hr', '12 hr', '24 hr', '48 hr'], 2),
          mcq('Orbit radius for geostationary ≈', ['400 km', '36,000 km', '7,000 km', '1 km'], 1),
          mcq('Escape velocity from Earth ≈', ['3 km/s', '7 km/s', '11.2 km/s', '30 km/s'], 2),
          mcq('A satellite\u2019s centripetal force is supplied by:', ['Friction', 'Gravity', 'Tension', 'Air'], 1),
          mcq('Higher orbit means:', ['Faster speed', 'Slower speed', 'Same speed', 'Zero speed'], 1),
          mcq('Kepler\u2019s 3rd law: T² ∝ ?', ['r', 'r²', 'r³', '1/r'], 2),
          fill('Orbital speed v = √(GM/___).', ['r']),
          fill('Astronauts feel weightless because they are in continuous ___.', ['free fall']),
          mcq('Increasing satellite mass at same orbit changes orbital period by:', ['Doubling', 'Halving', 'Nothing', 'Squaring'], 2, 'medium'),
          mcq('Lowest stable LEO altitude:', ['~10 km', '~200 km', '~36,000 km', '~1 lakh km'], 1, 'medium'),
        ]),
        makeExercise('Pressure Under Gravity', [
          mcq('Pressure in a fluid increases with:', ['Width', 'Depth', 'Length', 'Surface area'], 1),
          mcq('Atmospheric pressure ≈', ['1 Pa', '101 kPa', '1 MPa', '10 Pa'], 1),
          mcq('Pascal\u2019s law concerns:', ['Solids', 'Fluid pressure', 'Magnetism', 'Light'], 1),
          mcq('Buoyant force depends on:', ['Body mass only', 'Displaced fluid weight', 'Volume of body only in vacuum', 'Surface'], 1),
          mcq('Hydraulic press uses:', ['Newton\u2019s 1st law', 'Pascal\u2019s law', 'Hooke\u2019s law', 'Gauss law'], 1),
          mcq('Unit of pressure:', ['Pascal', 'Newton', 'Watt', 'Joule'], 0),
          fill('P = h ρ ___.', ['g']),
          fill('1 atm ≈ ___ Pa.', ['101325']),
          mcq('Pressure at 10 m water depth (ρ=1000, g=10) above atmospheric:', ['1 kPa', '10 kPa', '100 kPa', '1 MPa'], 2, 'medium'),
          mcq('A floating body has buoyancy equal to its:', ['Volume', 'Weight', 'Density', 'Area'], 1, 'medium'),
        ]),
        makeExercise('Weight, Mass & Apparent Weight', [
          mcq('Mass is conserved during free fall? :', ['No', 'Yes', 'Sometimes', 'Only in vacuum'], 1),
          mcq('Apparent weight in free-fall lift:', ['mg', '0', '2mg', 'mg/2'], 1),
          mcq('In an accelerating lift upward, apparent weight is:', ['Less than mg', 'More than mg', 'Equal to mg', 'Zero'], 1),
          mcq('Weighing scale reads:', ['Mass', 'Force you exert on scale', 'Volume', 'Density'], 1),
          mcq('Spring balance measures:', ['Mass', 'Weight', 'Volume', 'Density'], 1),
          mcq('Beam balance measures:', ['Weight', 'Mass', 'Force', 'Acceleration'], 1),
          fill('Weight W = m × ___.', ['g']),
          fill('Apparent weight in free fall is ___.', ['zero']),
          mcq('A 60 kg person in lift accelerating up at 2 m/s² (g=10) reads:', ['600 N', '720 N', '480 N', '300 N'], 1, 'medium'),
          mcq('Same person in lift falling freely reads:', ['600 N', '0 N', '120 N', '300 N'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Heat & Temperature',
      description: 'Thermal energy, expansion, latent heat, transfer.',
      exercises: [
        makeExercise('Temperature Scales', [
          mcq('SI unit of temperature:', ['°C', 'K', '°F', 'R'], 1),
          mcq('0 °C in Kelvin:', ['0', '273', '273.15', '373'], 2),
          mcq('100 °C in Kelvin:', ['273', '373', '373.15', '0'], 2),
          mcq('Absolute zero:', ['0 K', '0 °C', '-100 °C', '273 K'], 0),
          mcq('Conversion °C → °F:', ['F=C+32', 'F=9C/5+32', 'F=5C/9+32', 'F=C×2'], 1),
          mcq('Triple point of water (K):', ['0', '100', '273.16', '373'], 2),
          fill('A clinical thermometer typically reads in ___.', ['°C']),
          fill('Two systems at thermal equilibrium share the same ___.', ['temperature']),
          mcq('40 °C equals:', ['100 K', '313 K', '313.15 K', '40 K'], 2, 'medium'),
          mcq('25 °C equals:', ['25 K', '77 °F', '50 °F', '298 °F'], 1, 'medium'),
        ]),
        makeExercise('Heat Transfer', [
          mcq('Convection occurs in:', ['Solids only', 'Fluids', 'Vacuum', 'Magnets'], 1),
          mcq('Conduction is dominant in:', ['Gases', 'Solids', 'Vacuum', 'Plasma'], 1),
          mcq('Radiation does NOT need:', ['Source', 'Medium', 'Energy', 'Surface'], 1),
          mcq('Black body absorbs:', ['No radiation', 'All incident radiation', 'Visible only', 'Some'], 1),
          mcq('SI unit of thermal conductivity:', ['W/m·K', 'J/kg', 'kg/m', 'Pa·s'], 0),
          mcq('Greenhouse effect involves:', ['Conduction', 'Radiation trapping', 'Convection only', 'Evaporation'], 1),
          fill('Hot air rises by ___.', ['convection']),
          fill('A vacuum flask reduces all three modes including ___.', ['radiation']),
          mcq('Stefan\u2019s law: P ∝ T to the power:', ['2', '3', '4', '5'], 2, 'medium'),
          mcq('Doubling absolute temperature multiplies emitted power by:', ['2', '4', '8', '16'], 3, 'medium'),
        ]),
        makeExercise('Specific Heat & Latent Heat', [
          mcq('SI unit of specific heat:', ['J/kg·K', 'J/K', 'kJ/mol', 'J/m'], 0),
          mcq('Water has specific heat about:', ['4.2 J/g·°C', '0.42 J/g·°C', '42 J/g·°C', '420 J/g·°C'], 0),
          mcq('Latent heat is energy per unit ___.', ['volume', 'mass', 'temp', 'time'], 1),
          mcq('Latent heat of fusion of ice ≈', ['80 cal/g', '40 cal/g', '540 cal/g', '0'], 0),
          mcq('Latent heat of vaporisation of water ≈', ['80 cal/g', '540 cal/g', '40 cal/g', '0'], 1),
          mcq('At melting point, added heat causes:', ['Temp rise', 'Phase change', 'Pressure rise', 'Nothing'], 1),
          fill('Q = m c Δ___.', ['T']),
          fill('Latent heat does not change ___.', ['temperature']),
          mcq('Heat to raise 200 g water by 20 °C (c=4.2 J/g·K):', ['840 J', '4200 J', '16800 J', '8400 J'], 2, 'medium'),
          mcq('Why sweating cools the body:', ['Conduction', 'Evaporation absorbs latent heat', 'Radiation', 'Specific heat'], 1, 'medium'),
        ]),
        makeExercise('Thermal Expansion', [
          mcq('Linear expansion: ΔL = α L ___.', ['ΔT', 'V', 'P', 'm'], 0),
          mcq('Bimetallic strip uses:', ['Magnetism', 'Different α', 'Density', 'Pressure'], 1),
          mcq('Volume expansion γ ≈ ___ × α (solids):', ['1', '2', '3', '4'], 2),
          mcq('Water shows anomaly between:', ['0–4 °C', '4–10 °C', '10–20 °C', '50–100 °C'], 0),
          mcq('Why railway gaps exist:', ['Decoration', 'Allow expansion', 'Electrical', 'Friction'], 1),
          mcq('Thermometer relies on:', ['Conduction only', 'Expansion of substance', 'Magnetism', 'Light only'], 1),
          fill('Coefficient α has units of ___\u207b\u00b9.', ['K']),
          fill('Liquids expand more than ___.', ['solids']),
          mcq('A 100 m steel rod (α=12e-6/K) expands by 30 K:', ['3.6 mm', '36 mm', '0.36 mm', '0.036 mm'], 1, 'medium'),
          mcq('Pyrex glass is preferred to ordinary glass because of:', ['Higher α', 'Lower α', 'Higher density', 'Magnetism'], 1, 'medium'),
        ]),
        makeExercise('Calorimetry', [
          mcq('Calorimeter measures:', ['Mass', 'Heat exchanged', 'Volume', 'Density'], 1),
          mcq('Principle of calorimetry: heat lost = heat ___.', ['absorbed by surroundings', 'gained by other body', 'radiated', 'reflected'], 1),
          mcq('Common calorimeter material:', ['Iron', 'Copper', 'Wood', 'Glass'], 1),
          mcq('Mixing hot and cold leads to:', ['Final = max', 'Final between', 'Final = min', 'Random'], 1),
          mcq('SI unit of heat:', ['cal', 'kcal', 'J', 'W'], 2),
          mcq('1 calorie ≈', ['0.42 J', '4.18 J', '42 J', '418 J'], 1),
          fill('Q = m c Δ___ for sensible heat.', ['T']),
          fill('Phase change uses Q = m ___.', ['L']),
          mcq('100 g water at 80 °C mixed with 100 g at 20 °C → final:', ['40 °C', '50 °C', '60 °C', '70 °C'], 1, 'medium'),
          mcq('Higher specific heat of substance means:', ['Heats fast', 'Heats slow', 'Boils fast', 'Freezes fast'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Light & Sound',
      description: 'Reflection, refraction, lenses, sound waves.',
      exercises: [
        makeExercise('Reflection of Light', [
          mcq('Angle of incidence = angle of:', ['Refraction', 'Reflection', 'Deviation', 'Dispersion'], 1),
          mcq('Image in plane mirror is:', ['Real', 'Virtual, erect, same size', 'Inverted', 'Larger'], 1),
          mcq('Concave mirror is:', ['Diverging', 'Converging', 'Flat', 'Cylindrical'], 1),
          mcq('Convex mirror image is:', ['Magnified, real', 'Diminished, virtual', 'Same size', 'Inverted'], 1),
          mcq('Focal length f and radius R:', ['f=R', 'f=R/2', 'f=2R', 'f=R²'], 1),
          mcq('Used as rear-view mirror:', ['Concave', 'Convex', 'Plane', 'Cylindrical'], 1),
          fill('1/f = 1/v + 1/___.', ['u']),
          fill('Magnification m = -v/___.', ['u']),
          mcq('Concave mirror at f=10 cm, object at 20 cm: image distance:', ['10', '20', '30', '40'], 1, 'medium'),
          mcq('Image by convex mirror is always:', ['Real', 'Behind the mirror, virtual', 'Inverted', 'Magnified'], 1, 'medium'),
        ]),
        makeExercise('Refraction & Lenses', [
          mcq('Light bends because of change in:', ['Frequency', 'Speed', 'Color', 'Mass'], 1),
          mcq('Snell\u2019s law: n\u2081 sinθ\u2081 = n\u2082 ___.', ['cosθ\u2082', 'sinθ\u2082', 'tanθ\u2082', 'θ\u2082'], 1),
          mcq('Total internal reflection occurs when:', ['Going dense → rare beyond critical angle', 'Going rare → dense', 'Always', 'Never'], 0),
          mcq('Convex lens is:', ['Diverging', 'Converging', 'Flat', 'Plane'], 1),
          mcq('Power of lens unit:', ['Watt', 'Diopter', 'Lumen', 'Candela'], 1),
          mcq('SI unit of refractive index:', ['m', 'No unit', 'kg', 's'], 1),
          fill('Power P = 1/f where f in ___.', ['metres']),
          fill('Critical angle sin\u207b\u00b9(1/___).', ['n']),
          mcq('Lens of f = 25 cm power:', ['+0.25 D', '+4 D', '+25 D', '-4 D'], 1, 'medium'),
          mcq('Dispersion in prism is due to varying:', ['Mass', 'n with wavelength', 'Speed of sound', 'Density'], 1, 'medium'),
        ]),
        makeExercise('Sound Waves', [
          mcq('Sound is a:', ['Transverse wave', 'Longitudinal wave', 'EM wave', 'Particle'], 1),
          mcq('Speed of sound in air ≈', ['33 m/s', '343 m/s', '3000 m/s', '3 × 10⁸ m/s'], 1),
          mcq('Sound needs a:', ['Vacuum', 'Medium', 'Magnet', 'Battery'], 1),
          mcq('Pitch is related to:', ['Amplitude', 'Frequency', 'Phase', 'Speed'], 1),
          mcq('Loudness depends mainly on:', ['Frequency', 'Amplitude', 'Phase', 'Wavelength'], 1),
          mcq('Echo requires reflection separation ≥ about:', ['0.1 s', '1 s', '0.5 s', '0.01 s'], 0),
          fill('v = f λ where λ is ___.', ['wavelength']),
          fill('Audible range ≈ 20 Hz to ___ Hz.', ['20000']),
          mcq('Doppler effect describes change in:', ['Mass', 'Apparent frequency due to motion', 'Energy', 'Phase only'], 1, 'medium'),
          mcq('Sonar uses:', ['Light', 'Ultrasound', 'X-rays', 'Microwaves'], 1, 'medium'),
        ]),
        makeExercise('Human Eye & Defects', [
          mcq('Eye lens behaves like:', ['Concave', 'Convex', 'Flat', 'Cylindrical'], 1),
          mcq('Image on retina is:', ['Erect, real', 'Inverted, real', 'Erect, virtual', 'Inverted, virtual'], 1),
          mcq('Myopia corrected by:', ['Convex lens', 'Concave lens', 'Cylindrical', 'Bifocal only'], 1),
          mcq('Hypermetropia corrected by:', ['Convex lens', 'Concave lens', 'Cylindrical', 'Plane'], 0),
          mcq('Cylindrical lens corrects:', ['Myopia', 'Astigmatism', 'Cataract', 'Color blindness'], 1),
          mcq('Persistence of vision ≈', ['1/16 s', '1/24 s', '1/100 s', '1 s'], 0),
          fill('Power of accommodation is the lens\u2019s ___ change.', ['focal-length']),
          fill('Far point of normal eye is at ___.', ['infinity']),
          mcq('Near point of normal eye:', ['10 cm', '25 cm', '50 cm', '100 cm'], 1, 'medium'),
          mcq('Color blindness is due to:', ['Defective rods', 'Defective cones', 'Lens damage', 'Iris damage'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Electricity Basics',
      description: 'Current, voltage, Ohm\u2019s law, simple circuits.',
      exercises: [
        makeExercise('Current & Voltage', [
          mcq('Unit of current:', ['Volt', 'Ampere', 'Ohm', 'Coulomb'], 1),
          mcq('Unit of voltage:', ['Ampere', 'Volt', 'Watt', 'Ohm'], 1),
          mcq('Unit of resistance:', ['Ohm', 'Ampere', 'Henry', 'Farad'], 0),
          mcq('Conventional current direction:', ['Electron flow', 'Opposite to electron flow', 'Random', 'Always zero'], 1),
          mcq('1 A = 1 C / ?', ['m', 's', 'kg', 'V'], 1),
          mcq('Voltmeter is connected:', ['In series', 'In parallel', 'Anywhere', 'In ground'], 1),
          fill('Charge Q = I × ___.', ['t']),
          fill('Ammeter is connected in ___.', ['series']),
          mcq('Current of 2 A flows for 30 s. Charge:', ['10 C', '30 C', '60 C', '120 C'], 2, 'medium'),
          mcq('Voltmeter has very ___ resistance.', ['low', 'high', 'zero', 'negative'], 1, 'medium'),
        ]),
        makeExercise('Ohm\u2019s Law', [
          mcq('Ohm\u2019s law: V =', ['IR', 'I/R', 'R/I', 'I+R'], 0),
          mcq('Doubling V across same R doubles:', ['R', 'I', 'P only', 'Nothing'], 1),
          mcq('Power dissipated:', ['VI', 'V/I', 'V+I', 'V-I'], 0),
          mcq('Resistance unit:', ['Ohm', 'V/A·s', 'kg·m', 'J'], 0),
          mcq('Series resistors add as:', ['Sum', 'Reciprocal sum', 'Average', 'Product'], 0),
          mcq('Parallel resistors combine as:', ['Sum', 'Reciprocal of reciprocal sum', 'Average', 'Product'], 1),
          fill('P = I² × ___.', ['R']),
          fill('Two equal R in parallel give R/___.', ['2']),
          mcq('Three 6 Ω in parallel give:', ['18', '6', '2', '1'], 2, 'medium'),
          mcq('5 V across 10 Ω → I:', ['0.5 A', '2 A', '50 A', '5 A'], 0, 'medium'),
        ]),
        makeExercise('Heating & Power', [
          mcq('Joule\u2019s law: H = I² R ___.', ['t', 'V', 'm', 'Q'], 0),
          mcq('Filament bulb works on:', ['Conduction', 'Heating effect of current', 'Magnetic effect', 'Chemical effect'], 1),
          mcq('Fuse blows when:', ['V is high', 'I exceeds rating', 'R is high', 'No current'], 1),
          mcq('Electric iron uses:', ['Magnetic effect', 'Heating effect', 'Chemical effect', 'Light effect'], 1),
          mcq('1 kWh =', ['3.6 × 10⁶ J', '10³ J', '10⁶ J', '10⁹ J'], 0),
          mcq('100 W bulb draws ___ at 200 V:', ['0.5 A', '1 A', '2 A', '5 A'], 0),
          fill('P = V × ___.', ['I']),
          fill('Energy = P × ___.', ['t']),
          mcq('A 2000 W heater for 3 h consumes:', ['2 kWh', '4 kWh', '6 kWh', '8 kWh'], 2, 'medium'),
          mcq('Electric kettle filament should have:', ['Low resistance', 'High resistance', 'Zero R', 'Negative R'], 1, 'medium'),
        ]),
        makeExercise('Magnetic Effects of Current', [
          mcq('A current-carrying wire produces:', ['Electric field only', 'Magnetic field', 'Gravitational field', 'No field'], 1),
          mcq('Right-hand thumb rule gives direction of:', ['Force', 'B around wire', 'Current', 'Voltage'], 1),
          mcq('A solenoid behaves like a:', ['Capacitor', 'Bar magnet', 'Resistor', 'Diode'], 1),
          mcq('Electromagnet uses:', ['Permanent magnet', 'Solenoid + soft iron', 'Battery only', 'Resistor'], 1),
          mcq('Force on current in field: F =', ['BIL', 'BL/I', 'I/B', 'B/I'], 0),
          mcq('Direction of force given by:', ['Lenz\u2019s rule', 'Fleming\u2019s LH rule', 'Right-foot rule', 'Newton\u2019s 1st'], 1),
          fill('Magnetic flux unit is ___.', ['Weber']),
          fill('1 Tesla = 1 N / (A·___).', ['m']),
          mcq('Doubling current in solenoid doubles:', ['Voltage', 'B', 'R', 'L'], 1, 'medium'),
          mcq('A motor converts:', ['Heat → mech', 'Electrical → mechanical', 'Mech → light', 'Sound → electric'], 1, 'medium'),
        ]),
      ],
    },
  ],

  2: [
    {
      title: 'Rotational Motion',
      description: 'Torque, moment of inertia, angular momentum.',
      exercises: [
        makeExercise('Angular Kinematics', [
          mcq('Angular velocity unit:', ['rad/s', 'm/s', 's', 'Hz'], 0),
          mcq('Angular acceleration unit:', ['rad/s²', 'rad', 'rad·s', 'Hz²'], 0),
          mcq('1 revolution =', ['π rad', '2π rad', '180°', '90°'], 1),
          mcq('Period T and frequency f:', ['T=f', 'T=1/f', 'T=2f', 'T=f²'], 1),
          mcq('Linear velocity v in circular motion:', ['ω r', 'ω/r', 'r/ω', 'ωr²'], 0),
          mcq('Centripetal acceleration:', ['v² r', 'v²/r', 'r/v²', 'v/r'], 1),
          fill('ω = 2π ___.', ['f']),
          fill('Centripetal force F = m v²/___.', ['r']),
          mcq('Body in circle at v=2, r=1: a_c:', ['1', '2', '4', '8'], 2, 'medium'),
          mcq('If r doubled at same ω, v becomes:', ['Half', 'Same', 'Twice', 'Four times'], 2, 'medium'),
        ]),
        makeExercise('Torque & Moment of Inertia', [
          mcq('Torque τ =', ['F·r', 'F×r', 'F/r', 'F+r'], 1),
          mcq('SI unit of torque:', ['Nm', 'J', 'W', 'kg'], 0),
          mcq('Moment of inertia is rotational analog of:', ['Velocity', 'Mass', 'Acceleration', 'Force'], 1),
          mcq('I of point mass m at r:', ['m r²', 'm/r', 'm²r', 'r/m'], 0),
          mcq('I of solid sphere about diameter:', ['MR²', '2/5 MR²', '2/3 MR²', '1/2 MR²'], 1),
          mcq('I of thin ring about axis through centre:', ['MR²', '½ MR²', '⅔ MR²', '¼ MR²'], 0),
          fill('τ = I ___.', ['α']),
          fill('Parallel axis: I = I_cm + M ___².', ['d']),
          mcq('Doubling distance doubles torque if force same? :', ['No', 'Yes', 'Halves', 'Squares'], 1, 'medium'),
          mcq('Solid disc rotational KE = ½ I ω² with I=½MR² gives:', ['¼ M v²', '½ M v²', '¾ M v²', 'M v²'], 0, 'medium'),
        ]),
        makeExercise('Angular Momentum', [
          mcq('L = I ___.', ['ω', 'α', 'τ', 'F'], 0),
          mcq('In absence of external torque L is:', ['Variable', 'Conserved', 'Zero', 'Negative'], 1),
          mcq('Spinning skater pulling arms in:', ['Slows', 'Speeds up', 'Stops', 'Random'], 1),
          mcq('Unit of L:', ['kg m²/s', 'kg m/s', 'N m', 'N s'], 0),
          mcq('Earth\u2019s rotation has L mostly:', ['Variable', 'Constant', 'Zero', 'Negative'], 1),
          mcq('Direction of L given by:', ['Left-hand rule', 'Right-hand rule', 'Newton\u2019s 1st', 'Kepler\u2019s law'], 1),
          fill('τ = dL/___.', ['dt']),
          fill('Without τ_ext, L is ___.', ['conserved']),
          mcq('A figure skater spins faster on pulling arms in because:', ['Mass changes', 'I decreases, ω rises', 'τ increases', 'Energy decreases'], 1, 'medium'),
          mcq('Earth would spin slightly faster if oceans:', ['Filled poles', 'Receded to poles (lower I)', 'Stopped tides', 'No effect'], 1, 'medium'),
        ]),
        makeExercise('Rolling Motion', [
          mcq('Rolling without slipping: v = ω ___.', ['m', 'R', 'I', 'g'], 1),
          mcq('Total KE in rolling = trans + ___.', ['rotational', 'thermal', 'potential', 'pressure'], 0),
          mcq('Rolling sphere KE_trans / KE_rot ratio:', ['5:2', '2:5', '1:1', '3:2'], 0),
          mcq('Hollow sphere rolls down incline ___ a solid sphere.', ['faster than', 'slower than', 'same as', 'opposite to'], 1),
          mcq('Friction in pure rolling does:', ['Always positive work', 'No work', 'Negative only', 'Random'], 1),
          mcq('A wheel rolling at v has top speed:', ['v', '0', '2v', '½v'], 2),
          fill('Bottom point of rolling wheel has instantaneous speed ___.', ['zero']),
          fill('In pure rolling, point of contact is the instantaneous ___.', ['axis']),
          mcq('Cylinder vs disc on incline (no slip): cylinder finishes:', ['Earlier', 'Same', 'Later', 'Random'], 0, 'medium'),
          mcq('Rolling adds factor 1+I/MR² to inertia in incline:', ['False', 'True', 'Sometimes', 'Only for sphere'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Oscillations & Waves',
      description: 'SHM, pendulum, waves on strings, sound revisited.',
      exercises: [
        makeExercise('SHM Basics', [
          mcq('In SHM, restoring force ∝', ['Displacement', '−Displacement', 'Velocity', 'Mass'], 1),
          mcq('Time period of spring: T =', ['2π √(m/k)', '2π √(k/m)', 'π m/k', 'k/m'], 0),
          mcq('Time period of simple pendulum:', ['2π √(L/g)', '2π √(g/L)', 'π L/g', 'L/g'], 0),
          mcq('Pendulum at higher altitude has period:', ['Shorter', 'Longer', 'Same', 'Zero'], 1),
          mcq('Energy in SHM oscillates between:', ['KE & PE', 'KE only', 'Heat', 'Sound'], 0),
          mcq('Amplitude is:', ['Max displacement', 'Period', 'Frequency', 'Phase'], 0),
          fill('ω = √(k/m) for spring of constant ___.', ['k']),
          fill('Total energy in SHM ∝ A___.', ['²']),
          mcq('Spring k=100, m=0.25 kg, ω is:', ['10', '20', '50', '100'], 1, 'medium'),
          mcq('At extreme position, KE is:', ['Max', 'Zero', 'Half max', 'Negative'], 1, 'medium'),
        ]),
        makeExercise('Pendulum & Damping', [
          mcq('Damped oscillator amplitude:', ['Constant', 'Decays', 'Grows', 'Random'], 1),
          mcq('Forced oscillator at resonance has:', ['Min amplitude', 'Max amplitude', 'Zero', 'Negative'], 1),
          mcq('Quality factor Q is:', ['Energy / energy lost per radian', 'Frequency', 'Amplitude', 'Phase'], 0),
          mcq('Pendulum on Moon period vs Earth (same L):', ['Shorter', 'Longer', 'Same', 'Zero'], 1),
          mcq('A heavy pendulum bob (same L) has period:', ['Same', 'Larger', 'Smaller', 'Zero'], 0),
          mcq('Resonance example:', ['Tuning fork on box', 'Free fall', 'Sliding block', 'Closed circuit'], 0),
          fill('Damping coefficient relates to ___ losses.', ['energy']),
          fill('Resonance frequency equals ___ frequency.', ['natural']),
          mcq('A pendulum of L=1 m on Earth period (g=9.8):', ['1 s', '2 s', '3.14 s', '6.28 s'], 1, 'medium'),
          mcq('Tacoma bridge collapsed due to:', ['Earthquake', 'Wind-driven resonance', 'Overload', 'Lightning'], 1, 'medium'),
        ]),
        makeExercise('Waves on Strings', [
          mcq('Wave speed on string: v =', ['√(T/μ)', '√(μ/T)', 'T/μ', 'μ/T'], 0),
          mcq('Standing wave nodes have amplitude:', ['Max', 'Zero', 'Half', 'Negative'], 1),
          mcq('Antinodes have amplitude:', ['Zero', 'Max', 'Half', 'Negative'], 1),
          mcq('Fundamental frequency of string of length L:', ['v/2L', '2v/L', 'v/L', 'v/4L'], 0),
          mcq('Higher tension means:', ['Higher v', 'Lower v', 'Same v', 'No wave'], 0),
          mcq('Linear density μ unit:', ['kg/m', 'kg', 'kg/m²', 'm/kg'], 0),
          fill('Harmonics of a string fixed at both ends are ___ multiples.', ['integer']),
          fill('Wavelength of fundamental is 2 ___.', ['L']),
          mcq('String, T=100 N, μ=0.04 kg/m → v:', ['25', '50', '100', '200'], 1, 'medium'),
          mcq('Doubling tension multiplies wave speed by:', ['2', '√2', '4', '½'], 1, 'medium'),
        ]),
        makeExercise('Sound: Beats & Resonance', [
          mcq('Beats frequency = |f₁ − ___|.', ['f₂', 'f₁', '2f', 'v'], 0),
          mcq('Two tuning forks 256 & 260 Hz produce beats/s:', ['2', '4', '8', '16'], 1),
          mcq('Closed pipe fundamental λ:', ['L', '2L', '4L', 'L/2'], 2),
          mcq('Open pipe fundamental λ:', ['L', '2L', '4L', 'L/4'], 1),
          mcq('Echo > 0.1 s requires path > about:', ['17 m round trip', '5 m', '2 m', '100 m'], 0),
          mcq('Reverberation occurs in:', ['Open air', 'Enclosed spaces', 'Vacuum', 'Outer space'], 1),
          fill('Harmonics in closed pipe are odd ___.', ['multiples']),
          fill('Speed of sound increases with ___ temp.', ['rising']),
          mcq('Closed pipe of L=0.85 m, v=340 m/s, fundamental:', ['100 Hz', '200 Hz', '400 Hz', '800 Hz'], 0, 'medium'),
          mcq('Doppler shift for receding source:', ['Frequency increases', 'Frequency decreases', 'Same', 'Zero'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Optics',
      description: 'Wave optics: interference, diffraction, polarisation.',
      exercises: [
        makeExercise('Wave Nature of Light', [
          mcq('Young\u2019s experiment shows:', ['Particle nature', 'Interference of light', 'Photoelectric effect', 'Black body'], 1),
          mcq('Fringe width β =', ['λD/d', 'd/λD', 'λ/dD', 'Dd/λ'], 0),
          mcq('Coherent sources have constant:', ['Amplitude only', 'Phase difference', 'Speed', 'Mass'], 1),
          mcq('Diffraction is bending of waves around:', ['Edges/obstacles', 'Mass', 'Vacuum', 'Absorbers'], 0),
          mcq('Polarisation happens for:', ['Sound only', 'Transverse waves', 'Longitudinal waves only', 'Particles'], 1),
          mcq('Brewster\u2019s angle gives:', ['Total internal reflection', 'Plane polarised reflected ray', 'Maximum interference', 'Diffraction zero'], 1),
          fill('Fringe spacing varies inversely with slit ___.', ['separation']),
          fill('Single slit central bright fringe is ___ as wide.', ['twice']),
          mcq('Increasing wavelength increases fringe width? :', ['No', 'Yes', 'Sometimes', 'No effect'], 1, 'medium'),
          mcq('Polaroid sunglasses cut glare by blocking:', ['UV only', 'Horizontally polarised reflected light', 'Sound', 'Heat only'], 1, 'medium'),
        ]),
        makeExercise('Optical Instruments', [
          mcq('Microscope produces image:', ['Real, smaller', 'Real, larger or virtual highly enlarged', 'Same size', 'Inverted small'], 1),
          mcq('Telescope objective is:', ['Short f', 'Long f converging', 'Diverging', 'Plane'], 1),
          mcq('Eyepiece of telescope is:', ['Long f', 'Short f converging', 'Diverging', 'Plane'], 1),
          mcq('Magnifying glass uses:', ['Concave lens', 'Convex lens, object inside f', 'Plane mirror', 'Diverging mirror'], 1),
          mcq('Resolving power increases with:', ['Smaller aperture', 'Larger aperture', 'Lower λ unrelated', 'Smaller f'], 1),
          mcq('Camera with smaller f-number is:', ['Smaller aperture', 'Larger aperture', 'Same', 'Closed'], 1),
          fill('Microscope magnification ≈ m_o × m____.', ['e']),
          fill('Telescope magnification ≈ f_o / f____.', ['e']),
          mcq('Compound microscope final image is:', ['Real, erect', 'Virtual, inverted', 'Real, inverted', 'Virtual, erect'], 1, 'medium'),
          mcq('Astronomical telescope final image is:', ['Real erect', 'Virtual inverted', 'Real inverted', 'Virtual erect'], 1, 'medium'),
        ]),
        makeExercise('Photometry & Colour', [
          mcq('Luminous flux unit:', ['Candela', 'Lumen', 'Lux', 'Watt'], 1),
          mcq('Illuminance unit:', ['Lumen', 'Lux', 'Candela', 'Watt'], 1),
          mcq('White light contains ___ colours.', ['3', '7 (visible spectrum)', '12', '24'], 1),
          mcq('Red appears red because object:', ['Absorbs red', 'Reflects red', 'Emits all', 'Reflects nothing'], 1),
          mcq('Primary colours of light:', ['RGB', 'CMY', 'BYC', 'YGB'], 0),
          mcq('CMY are primary in:', ['Light addition', 'Pigment subtraction', 'Both', 'Neither'], 1),
          fill('Lux = Lumen / m___.', ['²']),
          fill('Wavelength of red ≈ 700 ___.', ['nm']),
          mcq('Bluer sky is due to:', ['Absorption', 'Rayleigh scattering', 'Refraction', 'Diffraction'], 1, 'medium'),
          mcq('Sunset reddens because:', ['Less scattering', 'More scattering of short λ leaves longer λ', 'Diffraction', 'Polarisation'], 1, 'medium'),
        ]),
      ],
    },
  ],

  3: [
    {
      title: 'Special Relativity',
      description: 'Postulates, time dilation, length contraction, mass-energy.',
      exercises: [
        makeExercise('Postulates & Time Dilation', [
          mcq('Speed of light c is:', ['Frame-dependent', 'Same in all inertial frames', 'Variable in vacuum', 'Zero'], 1),
          mcq('Lorentz factor γ at v=0.6c:', ['1', '1.25', '1.5', '2'], 1),
          mcq('Time dilation: moving clock runs:', ['Faster', 'Slower', 'Same', 'Stops'], 1),
          mcq('Length contraction occurs along:', ['Perpendicular direction', 'Direction of motion', 'Both', 'Neither'], 1),
          mcq('Mass-energy: E =', ['mc²', 'mc', 'm/c²', 'c²/m'], 0),
          mcq('Two frames moving at constant v are:', ['Non-inertial', 'Inertial', 'Accelerated', 'Random'], 1),
          fill('γ = 1 / √(1 − v²/___).', ['c²']),
          fill('Proper time is measured in object\u2019s ___ frame.', ['rest']),
          mcq('Muon lifetime appears longer to lab observer because of:', ['Length contraction', 'Time dilation', 'Doppler', 'Magnetism'], 1, 'medium'),
          mcq('Twin paradox resolution involves the travelling twin\u2019s:', ['Acceleration', 'Mass', 'Magnetism', 'Sound'], 0, 'medium'),
        ]),
        makeExercise('Relativistic Dynamics', [
          mcq('Relativistic momentum p =', ['mv', 'γmv', 'mv²', 'γm'], 1),
          mcq('Total energy E =', ['γmc²', 'mc²', 'mc', 'pc only'], 0),
          mcq('Massless particle (photon) energy:', ['mc²', 'pc', 'mv', '0'], 1),
          mcq('At v→c, KE:', ['Tends to 0', 'Tends to ∞', 'Constant', 'Negative'], 1),
          mcq('Invariant mass equation: E² =', ['(pc)² + (mc²)²', 'pc + mc²', 'p² + m²', 'm²c⁴ - p²c²'], 0),
          mcq('Rest energy of electron ≈', ['511 eV', '511 keV', '511 MeV', '511 GeV'], 1),
          fill('p = γ m ___.', ['v']),
          fill('Photon energy E = h ___.', ['f']),
          mcq('At v=0.8c, γ:', ['5/3', '5/4', '3/5', '4/5'], 0, 'medium'),
          mcq('Pair production requires photon energy ≥ 2 m_e c² ≈', ['511 keV', '1.022 MeV', '2 MeV', '5 MeV'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Statistical Mechanics',
      description: 'Boltzmann factor, partition functions, ensembles.',
      exercises: [
        makeExercise('Boltzmann Distribution', [
          mcq('Probability ∝', ['e^{−E/kT}', 'e^{E/kT}', 'kT/E', 'E/kT'], 0),
          mcq('Equipartition: each quadratic term contributes:', ['kT', 'kT/2', '2kT', 'kT²'], 1),
          mcq('Maxwell-Boltzmann describes:', ['Photons', 'Classical gas speeds', 'Electrons in metal', 'BEC'], 1),
          mcq('Boltzmann constant k_B ≈', ['1.38e-23 J/K', '6.6e-34', '9.8', '8.31'], 0),
          mcq('Internal energy of monatomic ideal gas (per mole):', ['3/2 RT', 'RT', '5/2 RT', '7/2 RT'], 0),
          mcq('At higher T, Maxwell distribution shifts:', ['Toward 0', 'Toward higher v', 'No change', 'Becomes delta'], 1),
          fill('Average KE per atom = 3/2 k ___.', ['T']),
          fill('Boltzmann factor enters classical and ___ statistics.', ['quantum']),
          mcq('Diatomic ideal gas U/n at T (rigid rotor, ignoring vib):', ['3/2 RT', '5/2 RT', '7/2 RT', '9/2 RT'], 1, 'medium'),
          mcq('Vibrational mode adds at high T per molecule:', ['k_BT/2', 'k_BT', '3 k_BT/2', '0'], 1, 'medium'),
        ]),
        makeExercise('Partition Function', [
          mcq('Z = Σ e^{___}.', ['+E_i/kT', '−E_i/kT', 'E_i', 'kT/E_i'], 1),
          mcq('Helmholtz free energy F =', ['−kT ln Z', 'kT ln Z', 'Z/kT', 'kT/Z'], 0),
          mcq('Average energy ⟨E⟩ from Z:', ['−∂lnZ/∂β', '∂lnZ/∂β', '∂Z/∂β', 'Z β'], 0),
          mcq('β =', ['kT', '1/kT', 'T/k', 'k/T'], 1),
          mcq('Two-level system Z =', ['e^{−E1/kT}+e^{−E2/kT}', 'kT', 'E1+E2', '0'], 0),
          mcq('Entropy S =', ['k_B ln Ω', 'k_B Ω', 'Ω/k_B', 'T ln Ω'], 0),
          fill('Macrostate counts microstates Ω; thus S=k_B ln ___.', ['Ω']),
          fill('Maxwell relations come from ___ derivatives.', ['mixed']),
          mcq('At high T, Z of two-level system tends to:', ['1', '2', 'kT', '0'], 1, 'medium'),
          mcq('Heat capacity at low T for two-level (Schottky) shows:', ['Linear rise', 'Peak', 'Decay only', 'Constant'], 1, 'medium'),
        ]),
        makeExercise('Ensembles', [
          mcq('Microcanonical fixes:', ['T,V,N', 'E,V,N', 'T,P,N', 'E,P,μ'], 1),
          mcq('Canonical fixes:', ['E,V,N', 'T,V,N', 'T,P,N', 'T,μ,V'], 1),
          mcq('Grand canonical fixes:', ['T,V,μ', 'T,V,N', 'E,V,N', 'P,V,N'], 0),
          mcq('Chemical potential μ controls:', ['Energy', 'Particle exchange', 'Volume', 'Spin'], 1),
          mcq('Bose-Einstein occupation: 1/(e^{(E-μ)/kT} ___ 1):', ['+', '-', '×', '/'], 1),
          mcq('Fermi-Dirac occupation: 1/(e^{(E-μ)/kT} ___ 1):', ['+', '-', '×', '/'], 0),
          fill('At high T, BE/FD reduce to ___ statistics.', ['Maxwell-Boltzmann']),
          fill('Fermi energy is μ at T = ___.', ['0']),
          mcq('Photons have chemical potential:', ['kT', '0', '∞', 'Negative'], 1, 'medium'),
          mcq('Pauli exclusion is a consequence of statistics being:', ['BE', 'FD', 'MB', 'Classical'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Solid State & Semiconductors',
      description: 'Crystal lattice, bands, p-n junction, devices.',
      exercises: [
        makeExercise('Crystals & Bonding', [
          mcq('Crystals have:', ['Random atoms', 'Periodic lattice', 'Liquid order', 'Gas-like positions'], 1),
          mcq('Number of Bravais lattices in 3D:', ['7', '14', '32', '230'], 1),
          mcq('Ionic bond example:', ['NaCl', 'O₂', 'CH₄', 'Cu metal'], 0),
          mcq('Covalent bond example:', ['NaCl', 'CH₄', 'Cu metal', 'Ar gas'], 1),
          mcq('Metallic bonding involves:', ['Localised electrons', 'Sea of delocalised electrons', 'Ionic only', 'No bonding'], 1),
          mcq('Hydrogen bonding occurs in:', ['Methane', 'Water', 'Argon', 'Iron'], 1),
          fill('Unit cell repeats by translation in a ___.', ['lattice']),
          fill('Diamond is a ___ lattice.', ['covalent']),
          mcq('FCC packing fraction:', ['0.52', '0.68', '0.74', '0.95'], 2, 'medium'),
          mcq('BCC packing fraction:', ['0.52', '0.68', '0.74', '0.95'], 1, 'medium'),
        ]),
        makeExercise('Band Theory', [
          mcq('Conductors have:', ['Empty CB only', 'Overlapping or partially filled bands', 'Large gap', 'No bands'], 1),
          mcq('Semiconductor band gap typical:', ['~10 eV', '~1 eV', '~100 eV', '0'], 1),
          mcq('Insulators have band gap:', ['Small', 'Large (>3 eV)', 'Zero', 'Negative'], 1),
          mcq('At 0 K intrinsic semiconductor is:', ['Conductor', 'Insulator', 'Metal', 'Plasma'], 1),
          mcq('n-type doping uses:', ['Group III', 'Group V', 'Noble gas', 'Halogen'], 1),
          mcq('p-type doping uses:', ['Group III', 'Group V', 'Noble gas', 'Halogen'], 0),
          fill('Holes act like ___ charge carriers.', ['positive']),
          fill('Fermi level lies near CB in ___ semiconductor.', ['n-type']),
          mcq('Mobility μ measures:', ['Velocity per E', 'Charge', 'Number', 'Energy'], 0, 'medium'),
          mcq('Conductivity σ = n e μ_n + p e μ_p? :', ['False', 'True', 'Sometimes', 'Only metals'], 1, 'medium'),
        ]),
        makeExercise('p-n Junction & Devices', [
          mcq('Forward biased p-n junction has:', ['Wider depletion region', 'Narrower depletion region', 'Same', 'Zero'], 1),
          mcq('Reverse biased p-n junction has:', ['Larger current', 'Tiny current (saturation)', 'Same', 'Zero always'], 1),
          mcq('Diode equation: I = I_s (e^{qV/kT} − ___).', ['1', '0', 'V', 'q'], 0),
          mcq('Zener diode operates in:', ['Forward', 'Breakdown reverse', 'Off', 'No state'], 1),
          mcq('LED converts:', ['Heat → light', 'Forward current → light', 'Sound → light', 'Magnetism'], 1),
          mcq('Photodiode generates current under:', ['Heat', 'Light', 'Magnetism', 'Pressure'], 1),
          fill('Transistor has ___ terminals.', ['three']),
          fill('BJT current relation: I_E = I_B + ___.', ['I_C']),
          mcq('Current gain β of transistor relates I_C to:', ['I_E', 'I_B', 'V_BE', 'V_CE'], 1, 'medium'),
          mcq('MOSFET controls current via:', ['Magnetic field', 'Gate voltage', 'Light', 'Heat'], 1, 'medium'),
        ]),
      ],
    },
  ],
};
