/**
 * Python question bank.
 * Levels: 1 = beginner, 2 = intermediate, 3 = advanced.
 */

import type { SeedUnit } from '../seed-bank';
import { mcq, fill, match, makeExercise } from '../seed-bank';

export const PYTHON: Record<1 | 2 | 3, SeedUnit[]> = {
  1: [
    {
      title: 'Syntax & Variables',
      description: 'Indentation, types, naming and printing.',
      exercises: [
        makeExercise('Hello, Python', [
          mcq('Print syntax in Python 3:', ['print "x"', 'print(x)', 'echo x', 'puts x'], 1),
          mcq('Comment in Python starts with:', ['//', '#', '--', '/*'], 1),
          mcq('Python is:', ['Compiled to native machine code only', 'Dynamically typed', 'Statically typed', 'Strongly OOP only'], 1),
          mcq('File extension:', ['.pyx', '.py', '.pn', '.pl'], 1),
          mcq('Boolean values:', ['true / false', 'True / False', 'TRUE / FALSE', '1 / 0'], 1),
          mcq('None is similar to:', ['undefined', 'null', 'void', 'nil-pointer only'], 1),
          fill('Variables are created on first ___.', ['assignment']),
          fill('Indentation matters; use spaces or ___.', ['tabs']),
          mcq('Type of 3.14:', ['int', 'float', 'str', 'bool'], 1, 'medium'),
          mcq('Result of 7 // 2:', ['3.5', '3', '4', '7'], 1, 'medium'),
        ]),
        makeExercise('Strings & Numbers', [
          mcq('len(\"hello\"):', ['4', '5', '6', 'error'], 1),
          mcq('\"a\" + \"b\":', ['ab', 'a b', 'b a', 'error'], 0),
          mcq('\"ha\" * 3:', ['hahaha', 'ha3', '3ha', 'error'], 0),
          mcq('Index of first char:', ['1', '0', '-1', 'undefined'], 1),
          mcq('\"abc\"[-1]:', ['a', 'b', 'c', 'error'], 2),
          mcq('Type of \"42\":', ['int', 'str', 'float', 'list'], 1),
          fill('Convert string to int with ___().', ['int']),
          fill('f-strings start with the letter ___.', ['f']),
          mcq('Result of 2 ** 10:', ['20', '1024', '512', '100'], 1, 'medium'),
          mcq('Result of int(\"3.5\"):', ['3', '4', 'ValueError', '3.5'], 2, 'medium'),
        ]),        makeExercise('Operators', [
          mcq('Modulo operator:', ['/', '%', '//', '**'], 1),
          mcq('Floor division:', ['/', '%', '//', '**'], 2),
          mcq('Exponent operator:', ['^', '**', 'pow', '%'], 1),
          mcq('Equality:', ['=', '==', '===', 'eq'], 1),
          mcq('Not equal:', ['<>', '!=', '/=', 'not'], 1),
          mcq('Chained comparison 1 < x < 10 means:', ['Syntax error', '1 < x AND x < 10', 'Bitwise', 'Random'], 1),
          fill('Bitwise AND uses ___.', ['&']),
          fill('Right shift uses ___.', ['>>']),
          mcq('Result of -7 % 3 in Python:', ['-1', '2', '1', '-2'], 1, 'medium'),
          mcq('Result of True + 1:', ['Error', '2', '1', 'TrueTrue'], 1, 'medium'),
        ]),
        makeExercise('I/O & Print', [
          mcq('Read input from user:', ['scan()', 'input()', 'gets()', 'read()'], 1),
          mcq('input() returns a:', ['int', 'str', 'float', 'bool'], 1),
          mcq('print separator default:', ['comma', 'space', 'newline', 'tab'], 1),
          mcq('Change separator with:', ['sep=', 'split=', 'separator=', 'gap='], 0),
          mcq('print end default:', ['\\n', '', ' ', '\\t'], 0),
          mcq('Print to a file:', ['file=f', 'to=f', 'out=f', 'dst=f'], 0),
          fill('Format with f"{x}" introduced in Python ___.', ['3.6']),
          fill('Suppress newline with end=___.', ['\'\'']),
          mcq('print(1, 2, sep="-") gives:', ['1 2', '1-2', '12', '1,2'], 1, 'medium'),
          mcq('repr() returns:', ['User-friendly str', 'Unambiguous string', 'Bytes', 'Type'], 1, 'medium'),
        ]),
        makeExercise('Type Conversion', [
          mcq('int("42") returns:', ['42', '"42"', '4.2', 'Error'], 0),
          mcq('str(3.14) returns:', ['3.14 (str)', '3', '3.14 (float)', 'Error'], 0),
          mcq('float("1e3") returns:', ['1000.0', '1e3 (str)', '1', 'Error'], 0),
          mcq('bool(0):', ['True', 'False', 'Error', 'None'], 1),
          mcq('bool(""):', ['True', 'False', 'Error', 'None'], 1),
          mcq('bool([]):', ['True', 'False', 'Error', 'None'], 1),
          fill('list("abc") gives ___.', ['[\'a\', \'b\', \'c\']']),
          fill('chr(65) returns ___.', ['A']),
          mcq('ord("A"):', ['64', '65', '66', '97'], 1, 'medium'),
          mcq('hex(255):', ['0xff', 'FF', '255', '0o377'], 0, 'medium'),
        ]),      ],
    },
    {
      title: 'Control Flow',
      description: 'if/else, while, for and range.',
      exercises: [
        makeExercise('Conditionals & Loops', [
          mcq('if-elif-else uses keyword:', ['else if', 'elif', 'elsif', 'switch'], 1),
          mcq('Logical and:', ['&&', 'and', 'AND', '&'], 1),
          mcq('Logical or:', ['||', 'or', 'OR', '|'], 1),
          mcq('range(5) yields:', ['1..5', '0..4', '0..5', '1..4'], 1),
          mcq('Number of iterations of `for i in range(3)`:', ['2', '3', '4', 'infinite'], 1),
          mcq('break exits:', ['Function', 'Loop', 'Module', 'Program'], 1),
          fill('continue jumps to next loop ___.', ['iteration']),
          fill('A while loop runs while condition is ___.', ['true']),
          mcq('range(2, 10, 3) gives:', ['2,5,8', '2,4,6,8', '3,6,9', '2,3,4,...,10'], 0, 'medium'),
          mcq('Else after for runs when:', ['Loop body never runs', 'Loop completes without break', 'Loop breaks', 'Always'], 1, 'medium'),
        ]),
        makeExercise('If / Elif / Else', [
          mcq('Indentation level for if body:', ['Same as if', 'Greater than if', 'No matter', 'Less than if'], 1),
          mcq('Ternary expression:', ['x if cond else y', 'cond ? x : y', 'if cond x else y', 'cond and x or y only'], 0),
          mcq('Truthiness of 0:', ['True', 'False', 'Error', 'None'], 1),
          mcq('Truthiness of []:', ['True', 'False', 'Error', 'None'], 1),
          mcq('Truthiness of "False" (string):', ['True', 'False', 'Error', 'None'], 0),
          mcq('Number of else blocks possible:', ['Many', 'Exactly one', 'Zero', 'Optional none/one'], 3),
          fill('Negation operator: ___.', ['not']),
          fill('Chained logical: a or b or c short-circuits at first ___.', ['truthy']),
          mcq('Nested if used to:', ['Replace functions', 'Branch within branch', 'Speed code', 'Avoid loops'], 1, 'medium'),
          mcq('Match-case statement (PEP 634) added in Python:', ['3.8', '3.9', '3.10', '3.11'], 2, 'medium'),
        ]),
        makeExercise('While Loops', [
          mcq('Infinite loop:', ['while False:', 'while True:', 'for ever:', 'loop:'], 1),
          mcq('Exit while early:', ['exit', 'break', 'leave', 'stop'], 1),
          mcq('Skip iteration:', ['skip', 'continue', 'next', 'pass'], 1),
          mcq('pass statement is:', ['Crashes', 'No-op placeholder', 'Returns None', 'Yields'], 1),
          mcq('while-else runs else when:', ['Always', 'Loop ends without break', 'Break occurs', 'Never'], 1),
          mcq('Counter pattern needs:', ['No init', 'Init before loop', 'Init after', 'Random'], 1),
          fill('A while loop checks the condition ___ each iteration.', ['before']),
          fill('Decrementing counter often uses ___ -= 1.', ['x']),
          mcq('How many iterations: i=0; while i<5: i+=2', ['2', '3', '5', '6'], 1, 'medium'),
          mcq('Sentinel-controlled loop ends when:', ['Sentinel value seen', 'Counter zero', 'Memory full', 'Random'], 0, 'medium'),
        ]),
        makeExercise('For Loops & Range', [
          mcq('Iterate list items:', ['for i in list:', 'foreach list:', 'for(i;list)', 'iter list'], 0),
          mcq('Iterate with index:', ['enumerate(lst)', 'index(lst)', 'zip(lst)', 'map(lst)'], 0),
          mcq('Iterate two lists in parallel:', ['zip(a,b)', 'pair(a,b)', 'merge(a,b)', 'list(a,b)'], 0),
          mcq('Reverse iteration:', ['reversed(lst)', 'lst.reverse()', 'lst[::-1] always required', 'flip(lst)'], 0),
          mcq('range(stop) starts at:', ['1', '0', '-1', 'stop'], 1),
          mcq('range(1, 5) produces:', ['1,2,3,4', '1,2,3,4,5', '0..4', '1..5'], 0),
          fill('len(range(10)) is ___.', ['10']),
          fill('Iterating a dict by default yields ___.', ['keys']),
          mcq('sum(range(1,11)) =', ['45', '50', '55', '60'], 2, 'medium'),
          mcq('list(range(10, 0, -2)) =', ['[10,8,6,4,2]', '[10,8,6,4,2,0]', '[]', '[10,9,..,1]'], 0, 'medium'),
        ]),
        makeExercise('Break, Continue, Pass', [
          mcq('break exits ___ enclosing loop.', ['All', 'Innermost', 'Outermost', 'None'], 1),
          mcq('continue skips to:', ['End of program', 'Next iteration', 'Outer loop', 'Function return'], 1),
          mcq('pass is mostly used for:', ['Empty blocks needed by syntax', 'Threading', 'Logging', 'I/O'], 0),
          mcq('Use case for nested break: exit inner loop. Outer loop continues:', ['False', 'True', 'Always exits both', 'Random'], 1),
          mcq('continue inside if inside loop:', ['Allowed', 'Forbidden', 'Compile error', 'Same as break'], 0),
          mcq('Loop with no body raises:', ['SyntaxError', 'IndentationError', 'NameError', 'TypeError'], 1),
          fill('Use ___ to keep stub functions runnable.', ['pass']),
          fill('break in for-else skips the ___ block.', ['else']),
          mcq('In nested loops, break stops:', ['Both loops', 'Innermost only', 'Random', 'Outermost only'], 1, 'medium'),
          mcq('Common idiom: continue when item is None, else process:', ['Anti-pattern', 'Reduces nesting', 'Slower', 'Crash'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Functions',
      description: 'Defining functions, arguments, return values.',
      exercises: [
        makeExercise('Functions Basics', [
          mcq('Define a function with:', ['function', 'def', 'fun', 'fn'], 1),
          mcq('Return a value with:', ['yield', 'return', 'send', 'output'], 1),
          mcq('Default arg in `def f(x=5)`:', ['Required', 'Optional with default 5', 'Forbidden', 'Type-only'], 1),
          mcq('*args collects:', ['Keyword args', 'Positional args', 'Files', 'Globals'], 1),
          mcq('**kwargs collects:', ['Positional args', 'Keyword args', 'Errors', 'Files'], 1),
          mcq('A function without explicit return returns:', ['0', 'None', 'Empty string', 'Last value'], 1),
          fill('Functions are first-class ___ in Python.', ['objects']),
          fill('Lambda functions are ___ functions.', ['anonymous']),
          mcq('Mutable default arg pitfall: list as default keeps changes:', ['False', 'True (shared)', 'Sometimes', 'Only ints'], 1, 'medium'),
          mcq('Recursion limit default:', ['100', '1000', '10000', 'Infinite'], 1, 'medium'),
        ]),
        makeExercise('Arguments & Returns', [
          mcq('Positional args are matched by:', ['Name', 'Position', 'Hash', 'Random'], 1),
          mcq('Keyword args are matched by:', ['Position', 'Name', 'Type', 'Hash'], 1),
          mcq('Returning multiple values returns:', ['Tuple', 'List', 'Set', 'Error'], 0),
          mcq('Function f(): pass returns:', ['0', 'None', '""', 'Error'], 1),
          mcq('Mixing positional and keyword: positional must come:', ['After kwargs', 'Before kwargs', 'Either', 'Not allowed'], 1),
          mcq('Mark args as keyword-only with:', [', *', ', **', 'kwonly:', 'k='], 0),
          fill('Mark args as positional-only after ___.', ['/']),
          fill('Variadic positional uses ___ prefix.', ['*']),
          mcq('def f(a, b=2, *c, **d): which is the dict-collecting param?', ['a', 'b', 'c', 'd'], 3, 'medium'),
          mcq('Returning early can:', ['Crash', 'Reduce nesting & exit fn', 'Skip imports', 'Hide bugs'], 1, 'medium'),
        ]),
        makeExercise('Lambdas & First-class', [
          mcq('Lambda syntax:', ['lambda x: x+1', 'def x: x+1', 'fn x => x+1', '|x| x+1'], 0),
          mcq('Lambdas can have:', ['Statements', 'Single expression', 'Multiple returns', 'Loops'], 1),
          mcq('Sort by key:', ['sorted(lst, key=fn)', 'sorted(lst, fn)', 'lst.sort(fn)', 'sortby(lst, fn)'], 0),
          mcq('map applies fn to:', ['Each element', 'Last element', 'Random', 'First only'], 0),
          mcq('filter keeps elements where:', ['fn returns True', 'fn returns False', 'Random', 'Always'], 0),
          mcq('reduce is in module:', ['itertools', 'functools', 'collections', 'operator'], 1),
          fill('Functions are ___-class objects in Python.', ['first']),
          fill('A function passed as argument is a ___-order function.', ['higher']),
          mcq('list(map(lambda x: x*2, [1,2,3])):', ['[1,2,3]', '[2,4,6]', '[3,6,9]', 'Error'], 1, 'medium'),
          mcq('Lambda capture of loop variable captures by:', ['Value at definition', 'Reference (late binding)', 'Copy', 'Hash'], 1, 'medium'),
        ]),
        makeExercise('Scope & Globals', [
          mcq('Look-up order in Python:', ['LEGB', 'GBLE', 'GLEB', 'BELG'], 0),
          mcq('global keyword declares:', ['New local', 'Use module-level binding', 'Constant', 'Type'], 1),
          mcq('nonlocal keyword refers to:', ['Module', 'Enclosing function scope', 'Class only', 'Builtins'], 1),
          mcq('Function variables default to:', ['Global', 'Local', 'Class attrs', 'Module'], 1),
          mcq('Read of x without assigning x first refers to:', ['Local', 'Enclosing/global', 'Always error', 'New None'], 1),
          mcq('Modifying global int inside fn requires:', ['Nothing', 'global keyword', 'nonlocal', 'class'], 1),
          fill('Closures capture variables by ___.', ['reference']),
          fill('Module-level scope is ___ scope in LEGB.', ['G']),
          mcq('A name in builtins (like len) can be shadowed by:', ['Only globals', 'Any local with same name', 'Never', 'Only types'], 1, 'medium'),
          mcq('Best practice: minimise use of:', ['Locals', 'globals', 'Functions', 'Returns'], 1, 'medium'),
        ]),
        makeExercise('Recursion', [
          mcq('Base case in recursion:', ['Always returns recursively', 'Stops recursion', 'Crashes', 'Skipped'], 1),
          mcq('Each recursive call adds a:', ['Heap object', 'Stack frame', 'Module', 'Thread'], 1),
          mcq('factorial(0) base case returns:', ['0', '1', 'None', 'Error'], 1),
          mcq('Default recursion limit is about:', ['100', '1000', '10000', 'Unlimited'], 1),
          mcq('Tail-call optimisation in CPython:', ['Always done', 'Not done', 'On flag', 'Random'], 1),
          mcq('Recursive Fibonacci is exponentially slow without:', ['Globals', 'Memoisation', 'Threads', 'I/O'], 1),
          fill('functools.lru_cache adds memoisation transparently to a ___.', ['function']),
          fill('sys.setrecursionlimit changes the recursion ___.', ['limit']),
          mcq('Use case for recursion:', ['Tree traversal', 'Counting to 1M', 'Bytewise IO', 'Logging'], 0, 'medium'),
          mcq('Mutual recursion involves:', ['Single function', 'Two or more functions calling each other', 'Globals only', 'Loops only'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Lists, Tuples, Dicts',
      description: 'Built-in collections and basic operations.',
      exercises: [
        makeExercise('Collections', [
          mcq('List literal:', ['(1,2,3)', '[1,2,3]', '{1,2,3}', '<1,2,3>'], 1),
          mcq('Tuple literal:', ['[1,2,3]', '(1,2,3)', '{1,2,3}', '<1,2,3>'], 1),
          mcq('Dict literal:', ['[k:v]', '(k,v)', '{k:v}', '<k=v>'], 2),
          mcq('Add to list:', ['list.add()', 'list.append()', 'list.push()', 'list.insertEnd()'], 1),
          mcq('Tuples are:', ['Mutable', 'Immutable', 'Sometimes mutable', 'Always empty'], 1),
          mcq('Dict lookup average:', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 0),
          fill('A set has only ___ elements.', ['unique']),
          fill('Lists support negative ___.', ['indexing']),
          mcq('Result of [1,2,3] + [4]:', ['[5,2,3]', '[1,2,3,4]', '[1,6,3]', 'Error'], 1, 'medium'),
          mcq('Iterate dict items with:', ['d.list()', 'd.items()', 'd.entries()', 'd.pairs()'], 1, 'medium'),
        ]),
        makeExercise('List Methods', [
          mcq('Append element:', ['append', 'add', 'push', 'insert'], 0),
          mcq('Insert at index:', ['insert(i, x)', 'add(i, x)', 'append(i, x)', 'put(i, x)'], 0),
          mcq('Remove first matching value:', ['remove(x)', 'delete(x)', 'pop(x)', 'discard(x)'], 0),
          mcq('Pop last item:', ['pop()', 'popLast()', 'tail()', 'take()'], 0),
          mcq('Extend with another iterable:', ['extend', 'merge', 'concat', 'add'], 0),
          mcq('Sort in place:', ['lst.sort()', 'sorted(lst)', 'lst.order()', 'lst.asc()'], 0),
          fill('Reverse in place: lst.___().', ['reverse']),
          fill('Index lookup: lst.___(x).', ['index']),
          mcq('Copy list shallow:', ['lst.copy()', 'list(lst)', 'lst[:]', 'All of these'], 3, 'medium'),
          mcq('list comprehension vs map: comprehension is generally:', ['Slower', 'More readable / similar speed', 'Crashing', 'Reverse'], 1, 'medium'),
        ]),
        makeExercise('Slicing', [
          mcq('a[1:4]:', ['Indices 1,2,3', 'Indices 1,2,3,4', '1 to end', '0 to 4'], 0),
          mcq('a[:3]:', ['First 3', 'Last 3', 'Middle', 'All but 3'], 0),
          mcq('a[-3:]:', ['First 3', 'Last 3', 'All but 3', 'Middle'], 1),
          mcq('a[::2]:', ['Every 2nd', 'First 2', 'Last 2', 'Reverse'], 0),
          mcq('a[::-1]:', ['Empty', 'Reverse', 'Sort', 'Copy'], 1),
          mcq('Slice creates a:', ['View', 'New list (lists)', 'Reference', 'Generator'], 1),
          fill('a[i:j:k] step is ___.', ['k']),
          fill('Out-of-range slice raises ___.', ['no error']),
          mcq('len([1,2,3,4,5][1:4]):', ['2', '3', '4', '5'], 1, 'medium'),
          mcq('a[10:20] on len 5 list:', ['Error', '[]', '[5]', 'None'], 1, 'medium'),
        ]),
        makeExercise('Dict Methods', [
          mcq('Get with default:', ['d.get(k, default)', 'd[k] or default', 'd.fetch(k)', 'd.lookup(k)'], 0),
          mcq('Add or update key:', ['d[k] = v', 'd.add(k, v)', 'd.put(k, v)', 'd.set(k, v)'], 0),
          mcq('Remove key, return value:', ['d.pop(k)', 'd.del(k)', 'd.remove(k)', 'd.discard(k)'], 0),
          mcq('Iterate keys:', ['d.keys()', 'keys(d)', 'd.iterkeys()', 'list(d.k)'], 0),
          mcq('Iterate values:', ['d.values()', 'd.vals()', 'd.list()', 'd[*]'], 0),
          mcq('Test key:', ['k in d', 'd has k', 'd.contains(k)', 'd[k]?'], 0),
          fill('d.update(other) merges other into ___.', ['d']),
          fill('Dicts are insertion-ordered since Python ___.', ['3.7']),
          mcq('d.setdefault(k, []).append(v) implements:', ['Multimap', 'Set', 'Tree', 'Stack'], 0, 'medium'),
          mcq('Dict comprehension {x:x*x for x in range(3)} =', ['{0:0, 1:1, 2:4}', '{1:1, 2:4, 3:9}', '{0,1,4}', 'Error'], 0, 'medium'),
        ]),
        makeExercise('Sets', [
          mcq('Set literal:', ['{1,2,3}', '[1,2,3]', '(1,2,3)', '<1,2,3>'], 0),
          mcq('Empty set:', ['{}', 'set()', '[]', '()'], 1),
          mcq('Add element:', ['add', 'append', 'insert', 'push'], 0),
          mcq('Union:', ['|', '&', '-', '^'], 0),
          mcq('Intersection:', ['|', '&', '-', '^'], 1),
          mcq('Difference:', ['|', '&', '-', '^'], 2),
          fill('Symmetric difference operator is ___.', ['^']),
          fill('Sets contain only ___ elements.', ['hashable']),
          mcq('Membership test in set is:', ['O(1) average', 'O(n)', 'O(log n)', 'O(n^2)'], 0, 'medium'),
          mcq('frozenset is:', ['Mutable', 'Immutable hashable set', 'Sorted set', 'List wrapper'], 1, 'medium'),
        ]),
      ],
    },
  ],

  2: [
    {
      title: 'Comprehensions & Iterators',
      description: 'List/dict/set comprehensions and generators.',
      exercises: [
        makeExercise('Comprehensions', [
          mcq('List comprehension produces a:', ['Generator', 'List', 'Dict', 'Tuple'], 1),
          mcq('Generator expression uses:', ['[]', '()', '{}', '<>'], 1),
          mcq('Set comprehension:', ['[x for x in s]', '{x for x in s}', '(x for x in s)', '<x for x in s>'], 1),
          mcq('Dict comprehension form:', ['{k:v for ...}', '{k,v for ...}', '[k:v for ...]', '(k:v for ...)'], 0),
          mcq('Generator vs list memory:', ['Same', 'Generator is lazy/streaming', 'Generator stores everything', 'List is lazy'], 1),
          mcq('next() advances a:', ['List', 'Generator/iterator', 'Set', 'Dict'], 1),
          fill('A generator function uses the ___ keyword.', ['yield']),
          fill('itertools.chain joins multiple ___ lazily.', ['iterables']),
          mcq('[x*x for x in range(5) if x%2==0] is:', ['[0,4,16]', '[1,9]', '[0,1,4,9,16]', '[0,2,4]'], 0, 'medium'),
          mcq('zip(a,b) yields pairs of:', ['Lists', 'Tuples', 'Dicts', 'Sets'], 1, 'medium'),
        ]),
        makeExercise('Generators', [
          mcq('Generator is created by:', ['return', 'yield', 'await', 'class'], 1),
          mcq('Generators are:', ['Lazy', 'Eager', 'Async only', 'None'], 0),
          mcq('next() on exhausted generator raises:', ['StopIteration', 'EOFError', 'RuntimeError', 'Nothing'], 0),
          mcq('Generator memory usage:', ['Stores all values', 'Streams one at a time', 'Random', 'None'], 1),
          mcq('Generator expression syntax:', ['[x for x in ...]', '(x for x in ...)', '{x for x in ...}', '<x for x in ...>'], 1),
          mcq('yield from delegates to:', ['Function', 'Sub-generator/iterable', 'Class', 'Module'], 1),
          fill('A generator function returns a ___ object on call.', ['generator']),
          fill('Calling a generator function does not run its body until ___ called.', ['next']),
          mcq('Send value into generator with:', ['gen.send(x)', 'gen.put(x)', 'gen.write(x)', 'next(gen, x)'], 0, 'medium'),
          mcq('Generator close() raises inside:', ['GeneratorExit', 'StopIteration', 'KeyboardInterrupt', 'IOError'], 0, 'medium'),
        ]),
        makeExercise('Iterators Protocol', [
          mcq('Iterable defines:', ['__iter__', '__next__', 'Both', 'Neither'], 0),
          mcq('Iterator defines:', ['__iter__', '__next__', 'Both', 'Neither'], 2),
          mcq('iter(obj) returns:', ['Iterator', 'List', 'Generator only', 'Dict'], 0),
          mcq('next(it, default) on exhaustion returns:', ['Crash', 'default', 'None always', 'Repeats last'], 1),
          mcq('itertools.count is:', ['Finite', 'Infinite counter', 'Sorter', 'Reducer'], 1),
          mcq('itertools.islice is for:', ['Slicing iterators lazily', 'Sorting', 'Reversing', 'Mapping'], 0),
          fill('itertools.cycle repeats an iterable ___.', ['forever']),
          fill('itertools.chain concatenates iterables ___.', ['lazily']),
          mcq('Sum of an infinite generator:', ['Returns sum', 'Hangs', 'Errors', 'Returns 0'], 1, 'medium'),
          mcq('Iterator can be iterated:', ['Many times', 'Once (then exhausted)', 'Twice', 'Random'], 1, 'medium'),
        ]),
        makeExercise('Dict & Set Comprehensions', [
          mcq('Dict comp: {x:x*x for x in range(3)} =', ['{0:0,1:1,2:4}', '[0:0,1:1,2:4]', '(0,1,4)', 'Error'], 0),
          mcq('Set comp: {x%3 for x in range(10)} has length:', ['10', '3', '4', '5'], 1),
          mcq('Conditional inside comprehension uses:', ['if cond at end', 'if cond at start', 'where cond', 'with cond'], 0),
          mcq('Ternary inside comprehension goes:', ['Before for', 'After for', 'Replaces for', 'Forbidden'], 0),
          mcq('Nested for in comprehension order:', ['Outer first then inner', 'Inner first', 'Random', 'Reverse'], 0),
          mcq('Comprehensions create scope:', ['No scope', 'Own scope (Python 3)', 'Class scope', 'Global'], 1),
          fill('Walrus operator := allows assignment in ___ contexts (3.8+).', ['expression']),
          fill('A frozenset comprehension is built via frozenset(___).', ['gen-expr']),
          mcq('{i: chr(65+i) for i in range(3)} keys are:', ['0,1,2', '1,2,3', 'A,B,C', '65,66,67'], 0, 'medium'),
          mcq('Reading: [x for sub in lst for x in sub] =', ['Flatten', 'Sort', 'Reverse', 'Zip'], 0, 'medium'),
        ]),
        makeExercise('itertools & functools', [
          mcq('itertools.product computes:', ['Cartesian product', 'Sum', 'Sort', 'Slice'], 0),
          mcq('itertools.permutations("abc", 2):', ['ab,ac,ba,bc,ca,cb', 'ab,ac,bc', 'aa,bb,cc', 'abc'], 0),
          mcq('itertools.combinations("abc", 2):', ['ab,ac,bc', 'ab,ba,ac,ca,bc,cb', 'abc', 'aa,bb,cc'], 0),
          mcq('functools.reduce signature:', ['reduce(fn, iter, initial?)', 'reduce(iter, fn)', 'reduce(iter)', 'reduce(fn)'], 0),
          mcq('functools.partial pre-applies:', ['Args', 'Kwargs', 'Both args/kwargs', 'Nothing'], 2),
          mcq('functools.lru_cache memoises:', ['Methods only', 'Functions', 'Classes', 'Modules'], 1),
          fill('functools.cache (3.9+) is unbounded ___.', ['lru_cache']),
          fill('itertools.groupby groups ___ adjacent runs.', ['equal']),
          mcq('reduce(lambda a,b: a+b, [1,2,3], 10) =', ['6', '15', '16', '60'], 2, 'medium'),
          mcq('list(itertools.accumulate([1,2,3,4])) =', ['[1,3,6,10]', '[1,2,3,4]', '[10]', '[1,2,3,4,10]'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'OOP',
      description: 'Classes, inheritance, dunder methods.',
      exercises: [
        makeExercise('Classes', [
          mcq('Define a class with:', ['class', 'struct', 'object', 'def'], 0),
          mcq('First param of an instance method is conventionally:', ['this', 'self', 'cls', 'me'], 1),
          mcq('Class method first param:', ['this', 'self', 'cls', 'klass'], 2),
          mcq('Static methods take:', ['self', 'cls', 'No special first arg', 'Both'], 2),
          mcq('Constructor name:', ['__new__', '__init__', '__construct__', 'init'], 1),
          mcq('All Python classes inherit from:', ['Base', 'Object', 'object', 'class'], 2),
          fill('Inheritance: `class Dog(___):`.', ['Animal']),
          fill('Operator overloading uses ___ methods.', ['dunder']),
          mcq('__str__ vs __repr__: __repr__ is intended to be:', ['User-friendly', 'Unambiguous/dev-friendly', 'Empty', 'Same as str()'], 1, 'medium'),
          mcq('Calling super().__init__() does:', ['Nothing', 'Calls parent constructor', 'Crashes', 'Returns self'], 1, 'medium'),
        ]),
        makeExercise('Inheritance & MRO', [
          mcq('All Python classes ultimately inherit from:', ['object', 'Object', 'class', 'None'], 0),
          mcq('MRO order is computed by:', ['DFS', 'C3 linearisation', 'BFS', 'Random'], 1),
          mcq('Diamond inheritance handled by:', ['MRO via super()', 'Random pick', 'Compile error', 'Manual chain'], 0),
          mcq('Override a method by:', ['Same name in subclass', 'Different name', 'Decorator only', 'Not allowed'], 0),
          mcq('Check instance type:', ['isinstance(x, T)', 'type(x) == T only', 'class(x)', 'x.is(T)'], 0),
          mcq('issubclass(A, B):', ['Tests subclass relation', 'Instance test', 'Type cast', 'Compile time'], 0),
          fill('Class.__mro__ shows the ___ of bases.', ['order']),
          fill('super() implicitly uses ___ for delegation.', ['MRO']),
          mcq('Multiple inheritance: A(B, C) MRO has B before:', ['C', 'A', 'object', 'self'], 0, 'medium'),
          mcq('Mixin is:', ['Abstract base only', 'Class providing methods to combine', 'Decorator', 'Module'], 1, 'medium'),
        ]),
        makeExercise('Special Methods', [
          mcq('Length protocol:', ['__len__', '__size__', '__count__', '__items__'], 0),
          mcq('Iteration protocol:', ['__iter__', '__loop__', '__cycle__', '__seq__'], 0),
          mcq('Equality:', ['__eq__', '__equals__', '__cmp__', '__same__'], 0),
          mcq('Hashing:', ['__hash__', '__id__', '__digest__', '__key__'], 0),
          mcq('Context manager protocol:', ['__enter__/__exit__', '__open__/__close__', '__begin__/__end__', '__in__/__out__'], 0),
          mcq('Callable object protocol:', ['__call__', '__invoke__', '__run__', '__exec__'], 0),
          fill('__repr__ should ideally return code that recreates the ___.', ['object']),
          fill('__getitem__ enables ___-style access.', ['index']),
          mcq('Defining only __eq__ without __hash__:', ['Object becomes unhashable', 'No effect', 'Crashes', 'Hash is sum'], 0, 'medium'),
          mcq('@total_ordering needs at least:', ['__eq__ + one ordering op', 'All 6 ops', 'Just __lt__', 'No requirements'], 0, 'medium'),
        ]),
        makeExercise('Properties & Class Methods', [
          mcq('@property turns method into:', ['Attribute access', 'Static fn', 'Decorator', 'Class member'], 0),
          mcq('Setter for property uses:', ['@x.setter', '@x.set', '@setter(x)', '@x.assign'], 0),
          mcq('@classmethod first arg:', ['self', 'cls', 'klass', 'name'], 1),
          mcq('@staticmethod first arg:', ['self', 'cls', 'No special', 'instance'], 2),
          mcq('Class attributes are:', ['Per-instance', 'Shared on class', 'Random', 'Hashed'], 1),
          mcq('Instance attributes are stored in:', ['__dict__', '__slots__ only', '__class__', '__init__'], 0),
          fill('__slots__ avoids per-instance ___.', ['__dict__']),
          fill('Class methods are commonly used as alternative ___.', ['constructors']),
          mcq('Setter validates input then assigns to underlying:', ['_attr', 'attr', 'self.x', 'public'], 0, 'medium'),
          mcq('Property without setter is:', ['Read-only', 'Mutable', 'Hashable only', 'Static'], 0, 'medium'),
        ]),
        makeExercise('Dataclasses', [
          mcq('@dataclass auto generates:', ['__init__/__repr__/__eq__', 'Threading', 'I/O', 'Logging'], 0),
          mcq('Dataclasses introduced in Python:', ['3.5', '3.6', '3.7', '3.8'], 2),
          mcq('Frozen dataclass:', ['Mutable', 'Immutable & hashable', 'Sortable only', 'Async'], 1),
          mcq('Field default uses:', ['Default arg', 'field(default=...)', 'Both', 'Neither'], 2),
          mcq('Mutable default for field requires:', ['Direct value', 'field(default_factory=list)', 'Tuple', 'None'], 1),
          mcq('Order=True adds:', ['Sort method', 'Comparison ops', 'Hashing', 'Async'], 1),
          fill('attr-style alternative library is ___s.', ['attr']),
          fill('A dataclass field can use type ___ for typing.', ['hint']),
          mcq('Inheriting a dataclass:', ['Forbidden', 'Allowed; subclass also a dataclass', 'Random', 'Crashes'], 1, 'medium'),
          mcq('__post_init__ runs:', ['After __init__', 'Before __init__', 'Never', 'On del'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Exceptions & Files',
      description: 'try/except, with statements, file I/O.',
      exercises: [
        makeExercise('Errors & I/O', [
          mcq('Catch exception with:', ['catch', 'except', 'rescue', 'on'], 1),
          mcq('Always-run cleanup:', ['always', 'finally', 'ensure', 'close'], 1),
          mcq('Raise exception:', ['throw', 'raise', 'panic', 'error'], 1),
          mcq('with-statement is for:', ['Loops', 'Context managers', 'Closures', 'Threads'], 1),
          mcq('Open file for read:', ['open(p, \"r\")', 'open(p, \"w\")', 'read(p)', 'file(p)'], 0),
          mcq('Newline-stripped file iter:', ['for line in f', 'f.lines()', 'f.iter()', 'next(f)'], 0),
          fill('Custom exception extends ___.', ['Exception']),
          fill('Re-raise without args using bare ___.', ['raise']),
          mcq('FileNotFoundError is a subclass of:', ['Exception', 'OSError', 'ValueError', 'TypeError'], 1, 'medium'),
          mcq('Multiple exception types caught with:', ['except A | B', 'except (A, B)', 'except A,B', 'except A B'], 1, 'medium'),
        ]),
        makeExercise('Exception Hierarchy', [
          mcq('Base of most user exceptions:', ['BaseException', 'Exception', 'Error', 'Throwable'], 1),
          mcq('KeyboardInterrupt is subclass of:', ['Exception', 'BaseException', 'IOError', 'OSError'], 1),
          mcq('TypeError raised when:', ['Wrong type used', 'Value out of range', 'Missing key', 'IO fails'], 0),
          mcq('ValueError raised when:', ['Wrong type', 'Right type but invalid value', 'Missing attribute', 'Generator exhausted'], 1),
          mcq('ZeroDivisionError parent:', ['ArithmeticError', 'TypeError', 'OSError', 'LookupError'], 0),
          mcq('IndexError vs KeyError: KeyError is for:', ['Lists', 'Dicts/sets', 'Files', 'Threads'], 1),
          fill('A custom exception should subclass ___.', ['Exception']),
          fill('AttributeError raised when ___ missing.', ['attribute']),
          mcq('Catching BaseException is generally:', ['Recommended', 'Discouraged (catches SystemExit)', 'Required', 'Forbidden'], 1, 'medium'),
          mcq('Exception chaining uses:', ['raise X from Y', 'raise X with Y', 'raise X by Y', 'raise X.Y'], 0, 'medium'),
        ]),
        makeExercise('try/except/finally', [
          mcq('finally runs:', ['Only on exception', 'Always', 'Never if exception', 'Only on success'], 1),
          mcq('else clause of try runs:', ['On exception only', 'When no exception', 'Always', 'Never'], 1),
          mcq('Bare except catches:', ['All exceptions including SystemExit', 'Only Exception', 'Only ValueError', 'Nothing'], 0),
          mcq('Re-raise current exception:', ['raise', 'raise e', 'throw', 'rethrow'], 0),
          mcq('Catch and add context:', ['raise NewError() from old', 'raise NewError(old)', 'rethrow', 'except chain'], 0),
          mcq('Multiple except blocks: only the ___ matching runs.', ['Last', 'First', 'Random', 'All'], 1),
          fill('try-finally guarantees ___.', ['cleanup']),
          fill('Use ___ statement to manage resources cleanly.', ['with']),
          mcq('Returning from finally:', ['Allowed but masks exception', 'Forbidden', 'Throws', 'Logs'], 0, 'medium'),
          mcq('exception groups (PEP 654, 3.11) syntax:', ['except*', 'except[]', 'except all', 'try*'], 0, 'medium'),
        ]),
        makeExercise('Files & Paths', [
          mcq('Open file binary read:', ['"rb"', '"r"', '"wb"', '"a"'], 0),
          mcq('Append text:', ['"r"', '"w"', '"a"', '"x"'], 2),
          mcq('Exclusive create (fails if exists):', ['"r"', '"w"', '"a"', '"x"'], 3),
          mcq('Best practice file open:', ['Manually close', 'Use with-statement', 'Use try only', 'Open and forget'], 1),
          mcq('Read all bytes of small file:', ['f.read()', 'f.readline()', 'f.readlines()', 'f.iter()'], 0),
          mcq('Modern path API:', ['os.path', 'pathlib.Path', 'sys.path', 'glob.path'], 1),
          fill('pathlib paths support / operator for ___.', ['joining']),
          fill('Default text encoding is platform-dependent unless you pass ___=...', ['encoding']),
          mcq('Reading a huge file line-by-line is best done by:', ['readlines()', 'iterating the file object', 'read() then split', 'mmap'], 1, 'medium'),
          mcq('Path.exists() returns:', ['bool', 'Path', 'str', 'int'], 0, 'medium'),
        ]),
        makeExercise('Context Managers', [
          mcq('with-statement calls:', ['__enter__/__exit__', '__init__/__del__', '__open__/__close__', '__call__'], 0),
          mcq('contextlib decorator:', ['@contextmanager', '@with', '@ctx', '@manager'], 0),
          mcq('Returning False from __exit__ when exception:', ['Suppresses', 'Re-raises (propagates)', 'Crashes', 'Logs'], 1),
          mcq('Nested with-blocks can be combined with:', ['Comma', 'Backslash only', 'No combine', 'Plus'], 0),
          mcq('contextlib.suppress(Type) is used to:', ['Catch and ignore Type', 'Re-raise', 'Log only', 'Re-throw'], 0),
          mcq('Async context manager protocol:', ['__aenter__/__aexit__', '__aopen__/__aclose__', '__enter__/__exit__', 'No protocol'], 0),
          fill('contextlib.ExitStack stacks multiple ___ managers.', ['context']),
          fill('with X() as y treats y as the result of ___().', ['__enter__']),
          mcq('Tempfile context closes and ___ on exit.', ['Persists', 'Deletes', 'Locks', 'Renames'], 1, 'medium'),
          mcq('@contextmanager wraps a ___ function.', ['Regular', 'Generator', 'Async', 'Class'], 1, 'medium'),
        ]),
      ],
    },
    {
      title: 'Modules & Packages',
      description: 'Imports, virtualenv, pip and the standard library.',
      exercises: [
        makeExercise('Imports & Stdlib', [
          mcq('Import math:', ['use math', 'import math', 'include math', 'require math'], 1),
          mcq('Import a specific name:', ['from m import x', 'import m.x', 'use m.x', 'import x of m'], 0),
          mcq('Package installer:', ['npm', 'pip', 'gem', 'composer'], 1),
          mcq('Isolated environment:', ['conda only', 'venv', 'docker only', 'jail'], 1),
          mcq('__name__ == \"__main__\" tests:', ['Module imported', 'Script run directly', 'Inside class', 'Generator'], 1),
          mcq('os.path.join is preferred because:', ['It uses /', 'Cross-platform separator', 'Faster', 'Optional only'], 1),
          fill('JSON parsing in stdlib uses the ___ module.', ['json']),
          fill('Hashing is in the ___ module.', ['hashlib']),
          mcq('collections.Counter is good for:', ['Sorting', 'Frequency counts', 'Threading', 'I/O'], 1, 'medium'),
          mcq('functools.lru_cache memoizes:', ['Classes', 'Functions', 'Modules', 'Globals'], 1, 'medium'),
        ]),
        makeExercise('Imports & Packages', [
          mcq('Relative import:', ['from . import x', 'import . x', 'from x import .', 'use rel x'], 0),
          mcq('Absolute import:', ['import pkg.mod', 'from . import mod', 'use mod', 'load mod'], 0),
          mcq('Package marker (legacy):', ['__init__.py', '__main__.py', 'pkg.py', 'index.py'], 0),
          mcq('Namespace package needs:', ['__init__.py', 'No __init__.py (PEP 420)', '__pkg__.py', 'setup.py'], 1),
          mcq('Run module as script:', ['python -m pkg.mod', 'python pkg.mod', 'python pkg/mod', 'python -r pkg'], 0),
          mcq('Avoid * imports because:', ['They are slow', 'Pollute namespace', 'Crash', 'Forbidden'], 1),
          fill('Import path is sys.___.', ['path']),
          fill('Cached bytecode goes into ___ directory.', ['__pycache__']),
          mcq('Wildcard import respects __all__ if defined:', ['False', 'True', 'Sometimes', 'Never'], 1, 'medium'),
          mcq('Circular imports often resolved by:', ['Moving import inside function', 'Refactor only', 'Both', 'Neither'], 2, 'medium'),
        ]),
        makeExercise('pip & venv', [
          mcq('Create venv:', ['python -m venv .venv', 'venv create .venv', 'pip venv .venv', 'python venv .venv'], 0),
          mcq('Activate venv (Linux):', ['source .venv/bin/activate', 'activate .venv', '. venv start', 'venv on'], 0),
          mcq('Install package:', ['pip install x', 'pip add x', 'pip get x', 'pip i x'], 0),
          mcq('Pin requirements:', ['pip freeze > req.txt', 'pip dump req.txt', 'pip list req.txt', 'pip save'], 0),
          mcq('Install from requirements:', ['pip install -r req.txt', 'pip read req.txt', 'pip use req.txt', 'pip apply req.txt'], 0),
          mcq('Editable install:', ['pip install -e .', 'pip install -d .', 'pip install --dev .', 'pip install src'], 0),
          fill('Modern build front-end is ___ (PEP 517).', ['build']),
          fill('pyproject.toml table for build is [build-___].', ['system']),
          mcq('uv / poetry / hatch are:', ['Dependency managers', 'Linters', 'Test runners', 'Profilers'], 0, 'medium'),
          mcq('Lock file ensures:', ['Reproducible installs', 'Faster install only', 'Type checking', 'Linting'], 0, 'medium'),
        ]),
        makeExercise('Standard Library Highlights', [
          mcq('Date & time:', ['datetime', 'time only', 'chrono', 'cal'], 0),
          mcq('Random numbers:', ['random', 'randint module', 'rand', 'std.random'], 0),
          mcq('Regex:', ['re', 'regex stdlib', 'pcre', 'patterns'], 0),
          mcq('JSON:', ['json', 'simplejson stdlib', 'jsons', 'pickle'], 0),
          mcq('CSV:', ['csv', 'tablib std', 'table', 'sheet'], 0),
          mcq('HTTP client:', ['urllib.request / http.client', 'requests stdlib', 'httpx stdlib', 'wget'], 0),
          fill('subprocess runs ___ commands.', ['external']),
          fill('logging module provides leveled ___.', ['logs']),
          mcq('collections.defaultdict avoids:', ['KeyError on missing keys', 'Hashing', 'Iteration', 'Sorting'], 0, 'medium'),
          mcq('heapq is a ___ heap.', ['Min', 'Max', 'Both', 'No'], 0, 'medium'),
        ]),
        makeExercise('Testing', [
          mcq('Built-in test framework:', ['pytest', 'unittest', 'nose', 'doctest only'], 1),
          mcq('Popular 3rd-party:', ['pytest', 'mocha', 'rspec', 'minitest'], 0),
          mcq('doctest checks:', ['Docstring examples', 'Coverage', 'Performance', 'Memory'], 0),
          mcq('assert in tests typically uses:', ['== / is / etc.', 'assertEquals only', 'assertSame', 'expect'], 0),
          mcq('Mocking is in:', ['unittest.mock', 'mockmod', 'mockify', 'pytest.mock built-in'], 0),
          mcq('Coverage measured by:', ['coverage.py', 'cprofile', 'timeit', 'mypy'], 0),
          fill('pytest discovers tests by ___ prefix.', ['test_']),
          fill('Fixtures in pytest decorate with ___.', ['@pytest.fixture']),
          mcq('Parametrising pytest tests uses:', ['@pytest.mark.parametrize', '@param', '@iter', '@for'], 0, 'medium'),
          mcq('Property-based testing library:', ['Hypothesis', 'pytest-cov', 'mock', 'tox'], 0, 'medium'),
        ]),
      ],
    },
  ],

  3: [
    {
      title: 'Decorators & Closures',
      description: 'Higher-order functions and metaprogramming.',
      exercises: [
        makeExercise('Decorators', [
          mcq('A decorator is a function that:', ['Returns a value', 'Wraps another callable', 'Imports modules', 'Reads files'], 1),
          mcq('Syntax @dec applies to:', ['Variable', 'Function below', 'Module', 'File'], 1),
          mcq('functools.wraps preserves:', ['Memory', 'Metadata of wrapped function', 'Speed', 'Threading'], 1),
          mcq('Closures capture variables by:', ['Value only', 'Reference', 'Copy', 'Pickle'], 1),
          mcq('Stacking decorators applies:', ['Bottom-up (innermost first)', 'Top-down', 'Random', 'Alphabetic'], 0),
          mcq('Decorator with arguments needs:', ['One nested level', 'Two nested levels', 'No nesting', 'Class only'], 1),
          fill('@property turns a method into an ___ attribute.', ['accessor']),
          fill('Closures rely on Python\u2019s ___ scoping rule.', ['LEGB']),
          mcq('@staticmethod vs @classmethod: classmethod receives:', ['nothing', 'self', 'cls', 'instance'], 2, 'medium'),
          mcq('Late-binding closures over loop var: i in lambda captures:', ['Value at definition', 'Final value of i', 'Initial 0', 'None'], 1, 'medium'),
        ]),
        makeExercise('Closures', [
          mcq('A closure is a function plus its:', ['Globals', 'Captured environment', 'Builtins', 'Arguments'], 1),
          mcq('Mutate enclosing var requires:', ['global', 'nonlocal', 'self', 'class'], 1),
          mcq('Closure cell stores:', ['Reference to free var', 'Copy', 'Pickle', 'Weakref'], 0),
          mcq('Closures often replace:', ['Modules', 'Tiny stateful classes', 'Threads', 'Files'], 1),
          mcq('Closures + recursion build:', ['Y combinator-like patterns', 'GIL', 'Profiles', 'Bytecode'], 0),
          mcq('Free variable resolution:', ['Late', 'Eager only', 'Random', 'Compile time'], 0),
          fill('A closure remembers vars from its ___ scope.', ['enclosing']),
          fill('Inspect cells via fn.___.', ['__closure__']),
          mcq('Bind loop var early via:', ['default arg trick', 'lambda no-arg', 'globals', 'class'], 0, 'medium'),
          mcq('Memoising via closure uses:', ['Dict in enclosing scope', 'Global only', 'Class only', 'Module only'], 0, 'medium'),
        ]),
        makeExercise('Decorators with Args', [
          mcq('Param decorator nests:', ['1 level', '2 levels', '3 levels', '0'], 1),
          mcq('Innermost wrapper signature usually:', ['(*a, **kw)', 'fixed', 'no args', 'self'], 0),
          mcq('Order of stacked params:', ['Top first applied', 'Bottom first applied', 'Random', 'Alpha'], 1),
          mcq('Use functools.wraps inside the:', ['Inner wrapper', 'Outer factory', 'Class', 'Module'], 0),
          mcq('Argument-less form: @dec vs @dec():', ['Same', 'Different (latter calls factory)', 'Both invalid', 'Both no-op'], 1),
          mcq('Class-based decorator implements:', ['__call__', '__add__', '__iter__', '__len__'], 0),
          fill('A decorator factory returns a ___.', ['decorator']),
          fill('Stacked decorators compose like ___ functions.', ['nested']),
          mcq('Optional-args decorator pattern often uses:', ['Single dispatch', 'functools.partial / sentinel', 'Threads', 'Async'], 1, 'medium'),
          mcq('Method decorator gets self via:', ['First positional in wrapper', 'Class arg', 'No args', 'global'], 0, 'medium'),
        ]),
        makeExercise('functools Tour', [
          mcq('functools.partial fixes:', ['Some args/kwargs', 'Globals', 'Modules', 'Loops'], 0),
          mcq('functools.cache differs from lru_cache:', ['Bounded', 'Unbounded', 'Async', 'Thread'], 1),
          mcq('functools.singledispatch dispatches on:', ['First arg type', 'Last arg', 'Module', 'Return'], 0),
          mcq('functools.reduce mirrors:', ['fold', 'map', 'filter', 'sort'], 0),
          mcq('functools.cached_property caches per:', ['Instance', 'Class', 'Module', 'Thread'], 0),
          mcq('functools.total_ordering needs:', ['__eq__ + one ordering', 'All ops', 'No ops', '__init__ only'], 0),
          fill('functools is part of the standard ___.', ['library']),
          fill('partialmethod is for ___ methods.', ['bound']),
          mcq('lru_cache(maxsize=None) means:', ['Cache off', 'Unbounded', 'Disabled', 'Async'], 1, 'medium'),
          mcq('cached_property requires the instance to have:', ['__hash__', '__dict__', '__slots__', 'class only'], 1, 'medium'),
        ]),
        makeExercise('Metaprogramming', [
          mcq('Default metaclass of class is:', ['object', 'type', 'class', 'meta'], 1),
          mcq('Define metaclass via:', ['class C(metaclass=M)', 'class C: meta=M', 'class C@M', 'meta C: M'], 0),
          mcq('__init_subclass__ runs on:', ['Subclass creation', 'Instance creation', 'Module load', 'Import'], 0),
          mcq('__set_name__ helps with:', ['Descriptors knowing attr name', 'Threads', 'Files', 'Async'], 0),
          mcq('Descriptors define:', ['__get__/__set__/__delete__', '__add__', '__call__ only', '__init__ only'], 0),
          mcq('Metaclasses are typically used for:', ['Frameworks (ORM, ABCs)', 'Print debug', 'Math', 'Logging'], 0),
          fill('Class itself is an instance of its ___.', ['metaclass']),
          fill('inspect module helps ___ live objects.', ['introspect']),
          mcq('ABCMeta enables:', ['Abstract methods enforcement', 'Threads', 'I/O', 'Async'], 0, 'medium'),
          mcq('Modifying class dict in metaclass __new__:', ['Allowed', 'Forbidden', 'Crashes', 'Silently ignored'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Async & Concurrency',
      description: 'asyncio, threading, multiprocessing.',
      exercises: [
        makeExercise('Async', [
          mcq('Coroutine defined with:', ['def', 'async def', 'fn', 'coroutine'], 1),
          mcq('Await pauses on:', ['Synchronous code', 'Awaitable', 'List', 'Print'], 1),
          mcq('asyncio.run starts:', ['Threads', 'Event loop', 'Subprocesses', 'GIL'], 1),
          mcq('GIL prevents:', ['Multiple processes', 'Parallel bytecode in threads', 'I/O', 'Async'], 1),
          mcq('CPU-bound parallelism uses:', ['threading', 'asyncio', 'multiprocessing', 'logging'], 2),
          mcq('I/O-bound parallelism best with:', ['multiprocessing', 'threading or asyncio', 'no concurrency', 'GIL'], 1),
          fill('asyncio.gather runs awaitables ___.', ['concurrently']),
          fill('Threading pools live in ___.', ['concurrent.futures']),
          mcq('Async function called without await returns:', ['Result', 'Coroutine object', 'None', 'Future immediately resolved'], 1, 'medium'),
          mcq('Cancellation in asyncio raises:', ['Exception()', 'CancelledError', 'TimeoutError', 'IOError'], 1, 'medium'),
        ]),
        makeExercise('asyncio Tasks', [
          mcq('Schedule coroutine on loop:', ['asyncio.create_task(c)', 'loop.run(c)', 'await spawn c', 'fork c'], 0),
          mcq('Wait for many tasks:', ['asyncio.gather(*tasks)', 'asyncio.all(tasks)', 'asyncio.join(tasks)', 'tasks.run()'], 0),
          mcq('Timeout helper (3.11+):', ['asyncio.timeout()', 'asyncio.deadline()', 'asyncio.expire()', 'asyncio.kill()'], 0),
          mcq('Convert blocking call to await:', ['loop.run_in_executor', 'asyncio.block', 'asyncio.thread', 'asyncio.wrap'], 0),
          mcq('asyncio.sleep(0) is used to:', ['Yield control', 'Crash', 'Cancel', 'Sleep ms'], 0),
          mcq('asyncio.Queue is:', ['Sync only', 'Coroutine-safe queue', 'Thread-only', 'Process-only'], 1),
          fill('Top-level await needs ___ context.', ['async']),
          fill('asyncio TaskGroup arrived in Python ___.', ['3.11']),
          mcq('Pending tasks at loop close cause:', ['Warnings/cancellation', 'Crash', 'Silent', 'Restart'], 0, 'medium'),
          mcq('Streams API uses:', ['StreamReader/Writer', 'Socket only', 'File only', 'Queue only'], 0, 'medium'),
        ]),
        makeExercise('Threading', [
          mcq('Spawn thread:', ['threading.Thread(target=fn).start()', 'thread.start(fn)', 'fork(fn)', 'spawn(fn)'], 0),
          mcq('Join waits until:', ['Thread completes', 'Loop ends', 'Process exits', 'GIL releases'], 0),
          mcq('Lock acquired with:', ['with lock:', 'lock.start()', 'lock.run()', 'lock.go()'], 0),
          mcq('Daemon thread:', ['Joins forever', 'Killed when main exits', 'Reentrant only', 'Async only'], 1),
          mcq('Thread pool:', ['ThreadPoolExecutor', 'Pool', 'ForkPool', 'WorkerSet'], 0),
          mcq('GIL releases on:', ['I/O calls', 'Pure CPU bytecode forever', 'Never', 'Sleep only'], 0),
          fill('queue.Queue is ___-safe.', ['thread']),
          fill('threading.Event acts as a ___ flag.', ['boolean']),
          mcq('RLock allows:', ['One acquire only', 'Reentrant acquire by same thread', 'Cross-process', 'Async only'], 1, 'medium'),
          mcq('Thread-local storage:', ['threading.local()', 'thread.tls', 'tls.local', 'local.thread'], 0, 'medium'),
        ]),
        makeExercise('multiprocessing', [
          mcq('Bypass GIL via:', ['multiprocessing', 'threading', 'asyncio', 'GIL.release'], 0),
          mcq('Process pool:', ['ProcessPoolExecutor', 'Pool', 'Both', 'Neither'], 2),
          mcq('IPC with Queue is:', ['Process-safe', 'Thread only', 'Async only', 'None'], 0),
          mcq('Shared memory (3.8+):', ['multiprocessing.shared_memory', 'mmap only', 'pickle', 'pipe'], 0),
          mcq('Default start method on Linux:', ['fork', 'spawn', 'forkserver', 'thread'], 0),
          mcq('Default on Windows:', ['fork', 'spawn', 'forkserver', 'thread'], 1),
          fill('multiprocessing.Pool.map blocks until ___.', ['done']),
          fill('Manager() supplies ___ shared objects.', ['proxy']),
          mcq('Sending Python objects across processes uses:', ['Pickle', 'JSON', 'Bytes only', 'Custom'], 0, 'medium'),
          mcq('os.fork() copies memory pages with:', ['COW', 'Eager copy', 'No copy', 'Random'], 0, 'medium'),
        ]),
        makeExercise('concurrent.futures', [
          mcq('Common base class:', ['Executor', 'Future', 'Worker', 'Pool'], 0),
          mcq('Submit returns:', ['Future', 'Result', 'None', 'Coro'], 0),
          mcq('Wait for any to finish:', ['as_completed', 'wait(FIRST_COMPLETED)', 'Both', 'Neither'], 2),
          mcq('Thread pool good for:', ['CPU-bound', 'I/O-bound', 'Both equally', 'Neither'], 1),
          mcq('Process pool good for:', ['CPU-bound', 'I/O-bound', 'Both equally', 'Neither'], 0),
          mcq('Cancel returns:', ['bool', 'None', 'Future', 'Result'], 0),
          fill('Map preserves the ___ of inputs.', ['order']),
          fill('Default ThreadPool max workers is min(32, cpu_count() + ___).', ['4']),
          mcq('Exception inside worker:', ['Re-raised on Future.result()', 'Lost', 'Logged only', 'Crashes pool'], 0, 'medium'),
          mcq('Calling shutdown(wait=False):', ['Returns immediately', 'Blocks', 'Crashes', 'No effect'], 0, 'medium'),
        ]),
      ],
    },
    {
      title: 'Typing & Performance',
      description: 'Type hints, dataclasses, profiling, optimisations.',
      exercises: [
        makeExercise('Typing', [
          mcq('Type hints are enforced at:', ['Runtime by default', 'Compile time only', 'Not enforced (hints only)', 'Linting only and never useful'], 2),
          mcq('Optional[X] equals:', ['X', 'X | None', 'List[X]', 'Set[X]'], 1),
          mcq('TypeVar is for:', ['Constants', 'Generic types', 'Classes only', 'Modules'], 1),
          mcq('@dataclass auto-generates:', ['__init__/__repr__/__eq__', 'Threading', 'I/O', 'Logging'], 0),
          mcq('mypy is a:', ['Profiler', 'Static type checker', 'Test runner', 'Debugger'], 1),
          mcq('Protocol enables:', ['Inheritance', 'Structural typing', 'Threading', 'Async'], 1),
          fill('From Python 3.9, list[int] works without ___.', ['List']),
          fill('Pydantic enforces types at ___ time.', ['runtime']),
          mcq('Frozen dataclass behaves:', ['Mutable', 'Immutable, hashable', 'Lazy', 'Threaded'], 1, 'medium'),
          mcq('Self type (PEP 673) refers to:', ['Module', 'Containing class', 'Function', 'Decorator'], 1, 'medium'),
        ]),
        makeExercise('Performance', [
          mcq('CPython compiles to:', ['Native code', 'Bytecode', 'JS', 'WASM only'], 1),
          mcq('Faster numerical work is best done with:', ['Pure Python', 'NumPy', 'JSON', 'pickle'], 1),
          mcq('PyPy is:', ['Profiler', 'JIT-compiled Python', 'Linter', 'Type checker'], 1),
          mcq('cProfile measures:', ['Memory', 'Time of function calls', 'Threads', 'Tests'], 1),
          mcq('timeit is for:', ['Long jobs', 'Small benchmarks', 'Memory', 'I/O'], 1),
          mcq('Avoid global lookups by:', ['Aliasing locally in hot loops', 'Using more imports', 'Using long names', 'None'], 0),
          fill('Cython compiles Python-like code to ___.', ['C']),
          fill('Memory profiling: install ___-profiler.', ['memory']),
          mcq('Calling a built-in (like sum) vs a hand loop is usually:', ['Slower', 'Faster (C-level)', 'Same', 'Random'], 1, 'medium'),
          mcq('Numpy vectorised ops avoid:', ['Python interpreter overhead per element', 'Memory entirely', 'GIL release', 'Imports'], 0, 'medium'),
        ]),
        makeExercise('Generics & Protocols', [
          mcq('Generic class:', ['class C(Generic[T])', 'class C<T>', 'class C[T] only', 'class C: T'], 0),
          mcq('PEP 695 (3.12) generic syntax:', ['class C[T]:', 'class C(T):', 'class C of T', 'class T C:'], 0),
          mcq('Bound TypeVar:', ['TypeVar("T", bound=Base)', 'TypeVar("T": Base)', 'TypeVar.bind(T, Base)', 'TypeVar(T<Base>)'], 0),
          mcq('Variadic generic introduced in:', ['3.10', '3.11', '3.12', '3.9'], 1),
          mcq('Protocol enables:', ['Structural typing (duck typed)', 'Inheritance only', 'Threads', 'Async'], 0),
          mcq('@runtime_checkable adds:', ['isinstance support', 'Decorators', 'Logging', 'Async'], 0),
          fill('TypeAlias keyword in 3.10+ is ___.', ['TypeAlias']),
          fill('PEP 612 introduced ParamSpec for ___.', ['callables']),
          mcq('Self type lives in:', ['typing', 'types', 'inspect', 'collections'], 0, 'medium'),
          mcq('Generic with default (3.13):', ['T = TypeVar("T", default=int)', 'TypeVar.default(int)', 'forbidden', 'TypeAlias'], 0, 'medium'),
        ]),
        makeExercise('Profiling Tools', [
          mcq('Time small snippets:', ['timeit', 'cProfile', 'memory_profiler', 'pyinstrument'], 0),
          mcq('Function-level profile:', ['timeit', 'cProfile', 'mprof', 'tracemalloc'], 1),
          mcq('Allocations tracker:', ['tracemalloc', 'cProfile', 'timeit', 'pyspy'], 0),
          mcq('Sampling profiler:', ['py-spy', 'cProfile', 'mprof', 'timeit'], 0),
          mcq('Visualise call graph:', ['snakeviz', 'mypy', 'flake8', 'black'], 0),
          mcq('Line-level timing:', ['line_profiler', 'cProfile', 'timeit', 'pdb'], 0),
          fill('cProfile output can be analysed with ___.', ['pstats']),
          fill('python -X importtime measures ___ time.', ['import']),
          mcq('GIL contention is best diagnosed with:', ['py-spy --gil', 'cProfile', 'timeit', 'mypy'], 0, 'medium'),
          mcq('Asyncio debug mode set via env var:', ['PYTHONASYNCIODEBUG=1', 'PYDEBUG=1', '-O flag', 'PYTHONHASH=0'], 0, 'medium'),
        ]),
        makeExercise('Native & Numerical Speedups', [
          mcq('Compile Python to C extension:', ['Cython', 'mypy', 'black', 'pip'], 0),
          mcq('JIT-compiled NumPy:', ['Numba', 'Cython', 'PyPy3', 'CPython'], 0),
          mcq('GPU arrays:', ['CuPy', 'Numba CUDA', 'Both', 'Neither'], 2),
          mcq('FFI to C:', ['ctypes', 'cffi', 'Both', 'Neither'], 2),
          mcq('Vectorised dataframes:', ['pandas/Polars', 'tkinter', 'asyncio', 'pickle'], 0),
          mcq('No-GIL build (3.13 experimental):', ['PEP 703', 'PEP 703 free-threaded', 'GIL stays', 'Off only'], 1),
          fill('mypyc compiles type-annotated Python to ___.', ['C']),
          fill('PyPy provides a tracing ___.', ['JIT']),
          mcq('Polars vs pandas advantage:', ['Lazy + multithreaded', 'Single-threaded', 'GIL bound only', 'No types'], 0, 'medium'),
          mcq('NumPy ufuncs are written in:', ['Pure Python', 'C', 'Java', 'Rust'], 1, 'medium'),
        ]),
      ],
    },
  ],
};
